### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by awilkins** [facebook/nuclide#1027]
1. Open the todo-show list
2. Close the editor in the pane on the right - todo occupies full editor area
3. Open a new editor via TODO list - it's in the same tab group as todo
4. Drag tab to left group (successful)

**Atom**: 1.15.0-beta3 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.207.0

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At /usr/share/atom-beta/resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (NaN, 0)
  at Function.module.exports.Point.assertValid (/app.asar/node_modules/text-buffer/lib/point.js:63:15)
  at DisplayLayer.translateScreenPosition (/app.asar/node_modules/text-buffer/lib/display-layer.js:326:11)
  at TextEditor.module.exports.TextEditor.bufferPositionForScreenPosition (/app.asar/src/text-editor.js:1662:32)
  at bufferPositionForMouseEvent (/packages/nuclide/pkg/commons-atom/mouse-to-position.js:24:18)
  at BreakpointDisplayController._getCurrentMouseEventLine (/packages/nuclide/pkg/nuclide-debugger/lib/BreakpointDisplayController.js:179:101)
  at BreakpointDisplayController._handleGutterMouseMove (/packages/nuclide/pkg/nuclide-debugger/lib/BreakpointDisplayController.js:184:26)

```

### Commands

```
     -2:56.6.0 command-palette:toggle (atom-pane.pane.active)
     -2:54.5.0 editor:consolidate-selections (input.hidden-input)
     -2:54.5.0 core:cancel (input.hidden-input)
     -2:53.1.0 settings-view:open (atom-pane.pane.active)
     -2:44.8.0 core:confirm (input.hidden-input)
     -2:06.2.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:04.7.0 core:confirm (input.hidden-input)
     -2:04.7.0 todo-show:find-in-project (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
autocomplete-modules 1.6.7 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.56 
cucumber-autocomplete 0.7.2 
cucumber-autocomplete 0.7.2 
cucumber-step 0.2.0 
docblockr 0.9.1 
editorconfig 2.2.1 
highlight-selected 0.12.0 
language-ansible 0.2.1 
language-babel 2.55.4 
language-gherkin 1.0.4 
language-groovy 0.6.0 
language-markdown 0.19.1 
linter 1.11.23 
linter-ansible-linting 1.2.2 
linter-coffeelint 1.2.1 
linter-eslint 8.1.2 
linter-jshint 3.0.2 
linter-sass-lint 1.7.4 
markdown-preview-plus 2.4.5 
minimap 4.26.8 
minimap-highlight-selected 4.5.0 
motepair 0.23.0 
nuclide 0.207.0 
pigments 0.39.0 
regex-railroad-diagram 0.16.0 
rest-client 1.3.1 
todo-show 1.11.0 
vim-mode-plus 0.82.3 
vim-mode-plus-ex-mode 0.8.1 
```

**Comment by jgebhardt** [comment]
Does this happen when the todo-show package is deactivated?

**Comment by mostafaeweda** [comment]
Also, plz upgrade to the latest Nucldie
