### ISSUE TITLE
Uncaught Error: Cannot find module './ConnectionState'

### ISSUE THREAD

**Issue by SirWindfield** [facebook/nuclide#1032]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0-beta3 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Education
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.207.0

### Stack Trace

Uncaught Error: Cannot find module './ConnectionState'

```
At C:\Users\Sven\AppData\Local\atom\app-1.15.0-beta3\resources\app.asar\src\module-cache.js:379

Error: Cannot find module './ConnectionState'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0-beta3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at _load_ConnectionState (/packages/nuclide/pkg/nuclide-remote-projects/lib/RemoteProjectsController.js:38:52)
    at RemoteProjectsController._updateConnectionStatus (/packages/nuclide/pkg/nuclide-remote-projects/lib/RemoteProjectsController.js:76:50)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at stoppedChangingActivePaneItemCallback (/app.asar/src/pane-container.js:352:36)
```

### Commands

```
     -1:21.8.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:19.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:33.9.0 command-palette:toggle (input.hidden-input)
  2x -0:31.7.0 core:move-down (input.hidden-input)
     -0:31.1.0 core:confirm (input.hidden-input)
     -0:31.1.0 settings-view:view-installed-packages (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
atom-beautify 0.29.17 
atom-clock 0.1.5 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
autocomplete-modules 1.6.7 
color-picker 2.2.5 
file-icons 2.0.16 
git-plus 7.3.3 
haskell-grammar 0.4.0 
highlight-selected 0.12.0 
language-babel 2.55.6 
language-graphql 0.8.0 
language-ini 1.18.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 1.11.23 
linter-sass-lint 1.7.4 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-find-and-replace 4.5.1 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
nuclide 0.207.0 
nuclide-format-js 0.0.36 
pigments 0.39.0 
rest-client 1.3.1 
set-syntax 0.3.2 
sort-lines 0.14.0 
sync-settings 0.8.1 
todo-show 1.11.0 
toggle-quotes 1.0.0 
tool-bar 1.0.1 
```

I just opened a project folder. Not sure what this is about, I am not complaining :D Just wanted to let you know that there is something wrong.

**Comment by galletabotin** [comment]
If u didn't who would noe?

**Comment by SirWindfield** [comment]
@galletabotin Not sure what this might have triggered. I added an empty project folder to the left sided tree and simultaneously pressed Ctrl+Alt+P to open the command palette. A second later the error popped up.

**Comment by nmote** [comment]
This looks like a corrupt install. Try removing and re-installing Nuclide.
