### ISSUE TITLE
Tests do not run on Windows

### ISSUE THREAD

**Issue by jrajav** [facebook/nuclide#1034]
Running the tests via `scripts/test` does not work using Python 2.7 on Windows. Python and Atom are both available on the PATH, but this error occurs:

```
$ python scripts/test
Traceback (most recent call last):
  File "scripts/test", line 119, in <module>
    check_dependencies(not options.no_atom)
  File "C:\dev\nuclide\scripts\lib\dependencies.py", line 45, in check_dependencies
    check_dependency(dependency['version-cmd'], dependency['version-output'])
  File "C:\dev\nuclide\scripts\lib\dependencies.py", line 34, in check_dependency
    raise Exception('Error while running %s: %s' % (' '.join(cmd), str(e)))
Exception: Error while running atom --version: [Error 2] The system cannot find the file specified
```

**Comment by johnislarry** [comment]
Hi @jrajav, unfortunately our Windows build isn't a high priority for the team, though we do have a few team members who have done some work on this (@ebluestein).  I wouldn't necessarily expect all of our tests to pass on Windows.  If you're interested in running a specific test, you can `cd` into the package directory and run the test manually.  E.g.

```
cd Nuclide/pkg/nuclide-flow
apm test
```

If running tests in a server package (e.g. `nuclide-debugger-php-rpc`) you need to use `npm test`

**Comment by ebluestein** [comment]
@jrajav, I just took a look at those tests and while the outer wrapper is Python, unfortunately it invokes some bash shell scripts as well, which won't work on Windows. As @johnislarry said, many of the individual tests likely work, but there are large parts of Nuclide that don't work on Windows at the moment.  I have been trying to slowly fix some of those Windows-specific issues as I encounter them, but as stated above, Windows is lower priority for the team compared to other work. 

If you have specific things you encounter that don't work on Windows, please let us know. I cannot promise we'll get to them immediately, but I will try to take a look!

**Comment by jrajav** [comment]
@johnislarry @ebluestein Thank you both for the response!
