### ISSUE TITLE
Uncaught Error: Invariant violation: "parentPane != null"

### ISSUE THREAD

**Issue by seshadribt24** [facebook/nuclide#1043]
[Enter steps to reproduce:]

1. Enabled Toggle Debugger
2. Clicked Toggle Smartlog

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.208.50982021

### Stack Trace

Uncaught Error: Invariant violation: "parentPane != null"

```
At C:\ProgramData\nuclide\0.208.50982021\nuclide\pkg\fb-interactive-smartlog\lib\ui\SmartlogComponent.js:68

Error: Invariant violation: "parentPane != null"
  at Immediate.setImmediate (C:/ProgramData/nuclide/0.208.50982021/nuclide/pkg/fb-interactive-smartlog/lib/ui/SmartlogComponent.js:68:15)
  at runCallback (timers.js:574:20)
  at tryOnImmediate (timers.js:554:5)
  at processImmediate [as _immediateCallback] (timers.js:533:5)

```

### Commands

```
  2x -1:56.7.0 core:backspace (input.hidden-input)
     -1:53.1.0 core:confirm (input.hidden-input)
  5x -1:53.1.0 nuclide-task-runner:toggle-toolbar-visibility (atom-pane.pane.active)
  2x -1:15.3.0 nuclide-diagnostics-ui:toggle-table (div.nuclide-file-tree.focusable-panel.tree-view)
  2x -1:12.2.0 nuclide-outline-view:toggle (div.nuclide-file-tree.focusable-panel.tree-view)
  2x -1:07.9.0 nuclide-context-view:toggle (div.nuclide-file-tree.focusable-panel.tree-view)
  2x -1:05.1.0 fb-biggrep:toggle (div.nuclide-file-tree.focusable-panel.tree-view)
  8x -1:01.9.0 nuclide-task-runner:toggle-toolbar-visibility (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:54.8.0 nuclide-debugger:toggle (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:42.7.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:42.7.0 nuclide-debugger:toggle-launch-attach (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:42.5.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:42.5.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:37.3.0 fb-slog:start (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -0:37.3.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:15.7.0 fb-interactive-smartlog:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-django 0.3.2 
haskell-grammar 0.4.0 
highlight-selected 0.12.0 
language-babel 2.55.6 
language-graphql 0.8.0 
language-ini 1.18.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
merge-conflicts 1.4.4 
nuclide 0.208.50982021 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.0.1 
tree-view-open-files 0.3.0 
```

**Comment by mostafaeweda** [comment]
That was fixed in a later Nuclide & Atom version -- plz upgrade to the latest.
