### ISSUE TITLE
no httplib under python3

### ISSUE THREAD

**Issue by LER0ever** [facebook/nuclide#1049]
### Issue and Steps to Reproduce
The command nuclide-start-server failed to start with an error message:
```
Traceback (most recent call last):
  File "scripts/nuclide_server_manager.py", line 24, in <module>
    from nuclide_server import LOG_FILE
  File "/usr/lib/node_modules/nuclide/pkg/nuclide-server/scripts/nuclide_server.py", line 19, in <module>
    import utils
  File "/usr/lib/node_modules/nuclide/pkg/nuclide-server/scripts/utils.py", line 9, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'
```
But it seems that httplib is replaced by http.client and is no longer available in python3? (And Arch just set their default interpreter to python3 ...)

### Versions
* Atom: 1.15.0
* Nuclide: 0.209.0
* Client OS: Linux (Manjaro 17.0 KDE edition)
* Server OS (optional): Linux (Manjaro 17.0 i3 edition)

**Comment by hansonw** [comment]
Dang, we should probably add `python2.7` to the shebang in `nuclide_server_manager.py`. Will take care of it
