### ISSUE TITLE
Uncaught Error: Invariant violation: "HOME != null"

### ISSUE THREAD

**Issue by XeniousSoftware** [facebook/nuclide#1065]
[Enter steps to reproduce:]

1. installed atom on windows 10
2. then after installing nuclide i get this error

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.211.0

### Stack Trace

Uncaught Error: Invariant violation: "HOME != null"

```
At C:\Users\yunus\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:58

Error: Invariant violation: "HOME != null"
    at Object.expandHomeDir (/packages/nuclide/pkg/commons-node/nuclideUri.js:432:11)
    at /packages/nuclide/pkg/nuclide-hg-rpc/lib/hg-utils.js:40:73
    at next (<anonymous>)
    at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:27:14
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12
    at getHgExecParams (/packages/nuclide/pkg/nuclide-hg-rpc/lib/hg-utils.js:71:18)
    at /packages/nuclide/pkg/nuclide-hg-rpc/lib/hg-utils.js:18:46
    at next (<anonymous>)
    at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:27:14
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12
    at hgAsyncExecute (/packages/nuclide/pkg/nuclide-hg-rpc/lib/hg-utils.js:28:17)
    at HgService._hgAsyncExecute (/packages/nuclide/pkg/nuclide-hg-rpc/lib/HgService.js:204:61)
    at /packages/nuclide/pkg/nuclide-hg-rpc/lib/HgService.js:501:31
    at next (<anonymous>)
    at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:27:14
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12
    at HgService.fetchBookmarks (/packages/nuclide/pkg/nuclide-hg-rpc/lib/HgService.js:508:7)
    at HgRepositoryClient.getBookmarks (/packages/nuclide/pkg/nuclide-hg-repository-client/lib/HgRepositoryClient.js:682:26)
    at /packages/nuclide/pkg/nuclide-bookshelf/lib/applyActionMiddleware.js:77:76)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:227:188)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:29:506)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:48:393)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:50:60)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:29:506)
    at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:14:276)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:53:373)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:29:506)
```

### Commands

```
  2x -2:18.3.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
nuclide 0.211.0 
```

**Comment by aadisriram** [comment]
Ah, I found the issue, this is only going to be a problem on windows. I have the fix ready and will be addressed in the next release.

**Comment by aadisriram** [comment]
This is fixed in the latest release!
