### ISSUE TITLE
Uncaught Error: Timeout after 60000 for id: 59, Calling remote method fetchBookmarks..

### ISSUE THREAD

**Issue by rshenoyq** [facebook/nuclide#1066]
[Enter steps to reproduce:]

Start up nuclide

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.211.53192568

### Stack Trace

Uncaught Error: Timeout after 60000 for id: 59, Calling remote method fetchBookmarks..

```
At /opt/facebook/nuclide/0.211.53192568/nuclide/node_modules/rxjs/bundles/Rx.min.js:58

Error: Timeout after 60000 for id: 59, Calling remote method fetchBookmarks..
  at Call._timeout (/opt/facebook/nuclide/0.211.53192568/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:142:20)
  at Call._timerId.setTimeout (/opt/facebook/nuclide/0.211.53192568/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:112:12)

```

### Commands

```
     -5:03.7.0 core:save (input.hidden-input)
  4x -5:03.7.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -3:12.6.0 core:backspace (input.hidden-input)
  2x -3:12.6.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -3:12.4.0 core:backspace (input.hidden-input)
  2x -3:12.4.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -3:12 core:move-down (input.hidden-input)
     -3:12 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -3:11.7.0 core:move-right (input.hidden-input)
     -3:11.7.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -3:11.2.0 core:backspace (input.hidden-input)
  2x -3:11.2.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -3:10.5.0 working-sets:select-active (input.hidden-input)
 24x -1:26.4.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -0:20.3.0 core:save (input.hidden-input)
  2x -0:20.3.0 fb-code-snippet-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.12.0 
language-babel 2.54.1 
language-graphql 0.8.0 
language-ini 1.17.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
merge-conflicts 1.4.4 
nuclide 0.211.53192568 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.0.1 
```

**Comment by aadisriram** [comment]
Ideally fetchBookmarks shouldn't timeout if it is able to access hg, is this a 100% repro? If not maybe the lock on hg was being held by some other command that was run.

**Comment by aadisriram** [comment]
Do you have a constant repro on this? Please reopen and also let me know if 'hg bookmarks' gives you results on the terminal.
