### ISSUE TITLE
Uncaught Error: Cannot find module './FileTreeSelectionRange'

### ISSUE THREAD

**Issue by fangyuxi** [facebook/nuclide#1070]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.211.0

### Stack Trace

Uncaught Error: Cannot find module './FileTreeSelectionRange'

```
At /Users/a58/.atom/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:52

Error: Cannot find module './FileTreeSelectionRange'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (/private/var/folders/bt/1y0vk3sj04qdnlsb0g2jmjt00000gn/T/AppTranslocation/1B6A0209-0103-4611-A5FF-C99268A3588A/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/app.asar/src/native-compile-cache.js:50:27)
  at _load_FileTreeSelectionRange (/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:105:36)
  at FileTreeStore._setSelectedNode (/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:1215:56)
  at FileTreeStore._onDispatch (/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:398:14)
  at FileTreeDispatcher._invokeCallback (/packages/nuclide/pkg/commons-node/Dispatcher.js:214:24)
  at FileTreeDispatcher.dispatch (/packages/nuclide/pkg/commons-node/Dispatcher.js:192:14)
  at FileTreeActions.setSelectedNode (/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeActions.js:426:22)
  at FileTreeEntryComponent._onMouseDown (/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeEntryComponent.js:326:20)
  at Object.invokeGuardedCallback (/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:26:12)
  at executeDispatch (/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:89:21)
  at Object.executeDispatchesInOrder (/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:112:5)
  at executeDispatchesAndRelease (/packages/nuclide/node_modules/react/lib/EventPluginHub.js:44:22)
  at executeDispatchesAndReleaseTopLevel (/packages/nuclide/node_modules/react/lib/EventPluginHub.js:55:10)
  at Array.forEach (native)
  at forEachAccumulated (/packages/nuclide/node_modules/react/lib/forEachAccumulated.js:25:9)
  at Object.processEventQueue (/packages/nuclide/node_modules/react/lib/EventPluginHub.js:231:7)
  at runEventQueueInBatch (/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at /packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
  at handleTopLevelImpl (/packages/nuclide/node_modules/react/lib/ReactEventListener.js:73:24)
  at ReactDefaultBatchingStrategyTransaction.perform (/packages/nuclide/node_modules/react/lib/Transaction.js:138:20)
  at Object.batchedUpdates (/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/packages/nuclide/node_modules/react/lib/ReactUpdates.js:98:20)
  at dispatchEvent (/packages/nuclide/node_modules/react/lib/ReactEventListener.js:150:20)

```

### Commands

```
     -5:39.6.0 core:paste (input.hidden-input)
  2x -0:26.9.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
nuclide 0.211.0 
```

**Comment by aadisriram** [comment]
Can you please provide steps to repro this?

**Comment by aadisriram** [comment]
This could be a case of lazy loading and you could have updated to a new version and not reloaded atom. If this issue persists please reopen the issue.
