### ISSUE TITLE
Uncaught Error: Remote Error: abort: No such file or directory: '/data/users/hieup/repo/.hg/store...

### ISSUE THREAD

**Issue by hicder** [facebook/nuclide#1072]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.211.53192568

### Stack Trace

Uncaught Error: Remote Error: abort: No such file or directory: '/data/users/hieup/repo/.hg/store/partialindex/60'
 processing message {"protocol":"service_framework3_rpc","type":"call-object","method":"fetchBookmarks","objectId":3,"id":66,"args":{}}
"Error: abort: No such file or directory: '/data/users/hieup/repo/.hg/store/partialindex/60'\n\n    at logAndThrowHgError (/usr/local/fbpkg/nuclide/nuclide-server/211/pkg/nuclide-hg-rpc/lib/hg-utils.js:184:11)\n    at /usr/local/fbpkg/nuclide/nuclide-server/211/pkg/nuclide-hg-rpc/lib/hg-utils.js:23:7\n    at next (native)\n    at step (/usr/local/fbpkg/nuclide/nuclide-server/211/node_modules/async-to-generator/async-to-generator.js:11:30)\n    at /usr/local/fbpkg/nuclide/nuclide-server/211/node_modules/async-to-generator/async-to-generator.js:21:13"

```
At /opt/facebook/nuclide/0.211.53192568/nuclide/node_modules/rxjs/bundles/Rx.min.js:58

Error: abort: No such file or directory: '/data/users/hieup/repo/.hg/store/partialindex/60'

    at logAndThrowHgError (/usr/local/fbpkg/nuclide/nuclide-server/211/pkg/nuclide-hg-rpc/lib/hg-utils.js:184:11)
    at /usr/local/fbpkg/nuclide/nuclide-server/211/pkg/nuclide-hg-rpc/lib/hg-utils.js:23:7
    at next (native)
    at step (/usr/local/fbpkg/nuclide/nuclide-server/211/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /usr/local/fbpkg/nuclide/nuclide-server/211/node_modules/async-to-generator/async-to-generator.js:21:13
```

### Commands

```
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.57.1 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
merge-conflicts 1.4.4 
nuclide 0.211.53192568 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
vim-mode-plus 0.85.1 
```

**Comment by tjfryan** [comment]
Do you have steps to reproduce?

**Comment by urzds** [comment]
For me it happens on every start of Atom 1.15.0 with Nuclide 0.214.0:

```
$HOME/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:58

Error
  at logAndThrowHgError ($HOME/.atom/packages/nuclide/pkg/nuclide-hg-rpc/lib/hg-utils.js:193:11)
  at $HOME/.atom/packages/nuclide/pkg/nuclide-hg-rpc/lib/hg-utils.js:23:7
  at undefined.next (<anonymous>:null:null)
  at step ($HOME/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
  at $HOME/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:21:13
  at process._tickCallback (internal/process/next_tick.js:103:7)
```

The error appeared as long as I did NOT have Mercurial installed. As soon as I installed it on the system, the error stopped appearing on Atom startup. Uninstalling Mercurial makes the error appear again.
