### ISSUE TITLE
Nuclide can't use watchman running on Raspbian

### ISSUE THREAD

**Issue by russoue** [facebook/nuclide#1075]
### Issue and Steps to Reproduce
I am using watchman to use nuclide and am repeatedly getting the following error message. I have used the `4.7.0` release of watchman, the nuclide plugin and server version is `0.211.0` and my OS is `Linux raspberrypi-2 4.4.50-v7+`. I have opened an issue with the watchman project too: https://github.com/facebook/watchman/issues/443.

I am seeing errors like the following:

```
Watchman Error:Remote Error: The client was ended processing message {"protocol":"service_framework3_rpc","type":"call","method":"FileWatcherService/watchDirectoryRecursive","id":11,"args":{"directoryPath":"/home/russoue/code"}} "Error: The client was ended\n at Client.cancelCommands (/usr/local/lib/node_modules/nuclide/node_modules/fb-watchman/index.js:52:15)\n at Client.end (/usr/local/lib/node_modules/nuclide/node_modules/fb-watchman/index.js:315:8)\n at Client. (/usr/local/lib/node_modules/nuclide/pkg/nuclide-watchman-helpers/lib/WatchmanClient.js:101:16)\n at emitOne (events.js:96:13)\n at Client.emit (events.js:191:7)\n at spawnError (/usr/local/lib/node_modules/nuclide/node_modules/fb-watchman/index.js:170:10)\n at ChildProcess. (/usr/local/lib/node_modules/nuclide/node_modules/fb-watchman/index.js:193:5)\n at emitOne (events.js:96:13)\n at ChildProcess.emit (events.js:191:7)\n at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)"
```

I have put more logs in the watchman issue. I am not sure on which side the problem is as watchman can be run successfully from the command line on the server side. Please help.

### Versions
* Atom: `1.15.0`
* Nuclide: `0.211.0`
* Client OS: `macOS Sierra, version 10.12.4`
* Server OS (optional): `Linux raspberrypi-2 4.4.50-v7+`

### Additional Details
* Installed packages (`apm ls --installed`):

```
# apm ls --installed
Community Packages (47) /Users/russoue/.atom/packages
├── ariake-dark-syntax@0.1.3
├── atom-beautify@0.29.17
├── atom-dark-fusion-syntax@2.2.0
├── atom-language-rust@0.12.1
├── atom-material-syntax@1.0.2
├── atom-material-ui@1.3.9
├── atom-monokai@0.10.9
├── autocomplete-clang@0.10.0
├── build-cargo@2.0.0
├── busy-signal@1.3.0
├── clang-format@1.28.0
├── dark-flat-ui@1.2.4
├── file-icons@2.1.1
├── fizzy@0.21.0
├── flatwhite-syntax@0.8.0
├── git-plus@7.3.3
├── github-atom-light-syntax@0.3.2
├── goodafternoon-ui@0.1.2
├── gpp-compiler@3.0.7
├── intentions@1.1.2
├── language-cpp14@0.6.2
├── language-rust@0.4.10
├── linter@2.1.2
├── linter-cpplint@2.0.1
├── linter-gcc@0.7.1
├── linter-rust@0.8.0
├── linter-ui-default@1.2.1
├── monokai@0.22.0
├── monokai-seti@0.7.0
├── nord-atom-syntax@0.6.0
├── nord-atom-ui@0.10.2
├── nuclide@0.211.0
├── oceanic-next@1.0.0
├── racer@0.20.0
├── relative-numbers@0.7.1
├── rust-api-docs-helper@0.5.1
├── rustfmt@0.1.3
├── seti-syntax@1.1.3
├── seti-ui@1.7.0
├── spacegray-atom-dark-syntax@1.3.2
├── spacegray-atom-dark-ui@1.0.1
├── spacegray-dark-syntax@0.2.0
├── spacegray-dark-ui@0.12.0
├── unity-ui@2.1.9
├── vim-mode-plus@0.85.1
├── vim-mode-plus-ex-mode@0.9.0
└── vim-modeline@0.5.2
```

**Comment by russoue** [comment]
It's now working great after I updated Nuclide to version `0.213.0`!
