### ISSUE TITLE
Nuclide workspace broken, cannot find module 'underscore-plus'

### ISSUE THREAD

**Issue by andryushka** [facebook/nuclide#1076]
### Issue and Steps to Reproduce
Enable Nuclide in settings.

### Expected Behavior
Nuclide works.

### Actual Behavior
Nuclide workspace broken (for example tree shown as common tab).

### Versions
* Atom: 1.15.0
* Nuclide: 0.213.0
* Client OS: Linux (Fedora 25)
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── MagicPython@1.0.9
├── Zen@0.16.4
├── advanced-open-file@0.16.6
├── atom-beautify@0.29.17
├── atom-django@0.3.2
├── atom-hg@2.0.14
├── atom-html-preview@0.1.22
├── atom-jinja2@0.6.0
├── atom-quoter@0.1.2
├── atom-ternjs@0.18.2
├── atom-typescript@11.0.1
├── auto-detect-indentation@1.3.0
├── autocomplete-html-entities@0.1.0
├── autocomplete-modules@1.6.8
├── autocomplete-paths@1.0.5
├── autocomplete-python@1.8.62
├── block-travel@1.0.5
├── busy-signal@1.3.0
├── color-picker@2.2.5
├── data-atom@0.25.0
├── docblockr@0.9.4
├── duplicate-line-or-selection@0.9.0
├── es6-javascript@1.0.0
├── expand-selection-to-quotes@0.11.0
├── file-icons@2.1.2
├── formatter-gofmt@1.0.1
├── go-debug@1.2.0
├── go-plus@5.4.0
├── go-signature-statusbar@1.2.0
├── hg-commit@0.4.0
├── highlight-line@0.12.0
├── highlight-selected@0.13.1
├── hyperclick@0.0.40
├── intentions@1.1.2
├── js-hyperclick@1.10.1
├── language-babel@2.57.1
├── language-docker@1.1.7
├── language-ini@1.19.0
├── language-nginx@0.7.0
├── language-protobuf@0.7.1
├── linter@2.1.2
├── linter-docker@0.1.5
├── linter-eslint@8.1.4
├── linter-flake8@2.1.5
├── linter-jsonlint@1.3.0
├── linter-shellcheck@1.4.4
├── linter-tidy@2.3.1
├── linter-ui-default@1.2.2
├── linter-write-good@0.8.0
├── markdown-preview-plus@2.4.9
├── merge-conflicts@1.4.4
├── minimap@4.26.8
├── minimap-bookmarks@0.4.2
├── minimap-find-and-replace@4.5.2
├── minimap-highlight-selected@4.5.0
├── minimap-linter@2.0.0
├── minimap-selection@4.4.0
├── multi-cursor@2.1.5
├── nuclide@0.213.0
├── nuclide-format-js@0.0.36
├── open-recent@5.0.0
├── package-cop@0.2.10
├── pandoc-convert@1.1.0
├── paste-repeater@0.1.1
├── pigments@0.39.1
├── project-manager@3.3.4
├── python-indent@1.0.2
├── python-isort@0.0.7
├── python-tools@0.6.9
├── react-es6-snippets@0.3.0
├── react-snippets@0.7.2
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── split-diff@1.3.0
├── sync-settings@0.8.1
├── tidy-tabs@0.4.0
├── todo-show@1.11.0
├── toggle-quotes@1.0.1
├── tree-view-autoresize@1.6.0
└── zentabs@0.8.8

```
npm list -G | grep underscore-plus 
└─┬ underscore-plus@1.6.6
```

Console message:
```
Cannot find module 'underscore-plus'
Error: Cannot find module 'underscore-plus'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (/usr/lib64/electron/1.3.13/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/usr/lib64/atom/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/usr/lib64/atom/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/home/ai/.atom/packages/nuclide/pkg/nuclide-ui/VendorLib/atom-tabs/lib/tab-bar-view.js:11:7)
  at Object.<anonymous> (/home/ai/.atom/packages/nuclide/pkg/nuclide-ui/VendorLib/atom-tabs/lib/tab-bar-view.js:843:4)
  at Module._compile (/usr/lib64/atom/src/native-compile-cache.js:109:30)
  at Object.value [as .js] (/usr/lib64/atom/src/compile-cache.js:216:21)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (module.js:483:17)
  at require (/usr/lib64/atom/src/native-compile-cache.js:50:27)
  at _load_tabBarView (/home/ai/.atom/packages/nuclide/pkg/nuclide-workspace-view-locations/lib/PanelLocation.js:35:47)
  at _disposables.default.paneContainer.observePanes.pane (/home/ai/.atom/packages/nuclide/pkg/nuclide-workspace-view-locations/lib/PanelLocation.js:133:46)
  at PaneContainer.module.exports.PaneContainer.observePanes (/usr/lib64/atom/src/pane-container.js:90:9)
  at PanelLocation.initialize (/home/ai/.atom/packages/nuclide/pkg/nuclide-workspace-view-locations/lib/PanelLocation.js:132:19)
  at Object.create (/home/ai/.atom/packages/nuclide/pkg/nuclide-workspace-view-locations/lib/main.js:90:18)
  at actions.ofType.map.action [as project] (/home/ai/.atom/packages/nuclide/pkg/nuclide-workspace-views/lib/redux/Epics.js:70:30)
  at a._next (/home/ai/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:95:123)
  at a.next (/home/ai/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:29:506)
  at a._next (/home/ai/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:159:18)
  at a.next (/home/ai/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:29:506)
  at a.next (/home/ai/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:37:345)
  at Object.action [as dispatch] (/home/ai/.atom/packages/nuclide/pkg/commons-node/redux-observable.js:66:15)
  at Object.registerLocation (/home/ai/.atom/packages/nuclide/pkg/nuclide-workspace-views/lib/main.js:127:25)
  at _disposables.add.default.map.id (/home/ai/.atom/packages/nuclide/pkg/nuclide-workspace-view-locations/lib/main.js:81:193)
  at Array.map (native)
  at Activation.consumeWorkspaceViewsService (/home/ai/.atom/packages/nuclide/pkg/nuclide-workspace-view-locations/lib/main.js:81:179)
  at Object.moduleExports.(anonymous function) [as consumeWorkspaceViewsService] (/home/ai/.atom/packages/nuclide/pkg/commons-atom/createPackage.js:51:34)
  at Provider.module.exports.Provider.provide (/usr/lib64/atom/node_modules/service-hub/lib/provider.js:34:52)
  at ServiceHub.module.exports.ServiceHub.provide (/usr/lib64/atom/node_modules/service-hub/lib/service-hub.js:30:20)
  at Package.module.exports.Package.activateServices (/usr/lib64/atom/src/package.js:396:71)
  at Package.module.exports.Package.activateNow (/usr/lib64/atom/src/package.js:221:16)
  at /usr/lib64/atom/src/package.js:190:32
  at Package.module.exports.Package.measure (/usr/lib64/atom/src/package.js:96:15)
  at /usr/lib64/atom/src/package.js:183:26
  at Package.module.exports.Package.activate (/usr/lib64/atom/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib64/atom/src/package-manager.js:542:34)
  at Object.keys.forEach.name (/home/ai/.atom/packages/nuclide/lib/main.js:286:21)
  at Array.forEach (native)
  at Object.activate (/home/ai/.atom/packages/nuclide/lib/main.js:283:25)
  at Package.module.exports.Package.activateNow (/usr/lib64/atom/src/package.js:218:19)
  at /usr/lib64/atom/src/package.js:190:32
  at Package.module.exports.Package.measure (/usr/lib64/atom/src/package.js:96:15)
  at /usr/lib64/atom/src/package.js:183:26
  at Package.module.exports.Package.activate (/usr/lib64/atom/src/package.js:180:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib64/atom/src/package-manager.js:542:34)
  at /usr/lib64/atom/src/package-manager.js:344:19
  at /usr/lib64/atom/src/config.js:635:20
  at Function.module.exports.Emitter.simpleDispatch (/usr/lib64/atom/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/usr/lib64/atom/node_modules/event-kit/lib/emitter.js:129:28)
  at Config.module.exports.Config.emitChangeEvent (/usr/lib64/atom/src/config.js:826:29)
  at Config.module.exports.Config.setRawValue (/usr/lib64/atom/src/config.js:612:19)
  at Config.module.exports.Config.set (/usr/lib64/atom/src/config.js:227:14)
  at Config.module.exports.Config.removeAtKeyPath (/usr/lib64/atom/src/config.js:377:12)
  at Package.module.exports.Package.enable (/usr/lib64/atom/src/package.js:81:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/usr/lib64/atom/src/package-manager.js:165:14)
  at HTMLButtonElement.<anonymous> (/usr/lib64/atom/node_modules/settings-view/lib/package-card.js:348:27)
  at HTMLButtonElement.dispatch (/usr/lib64/atom/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/usr/lib64/atom/node_modules/jquery/dist/jquery.js:4121:28)
```
![2017-03-30 13-17-06](https://cloud.githubusercontent.com/assets/6255465/24499706/37f98abe-154b-11e7-83cb-3d45240c78a9.png)

**Comment by andryushka** [comment]
Repeats also with a clean installation of an atom from http://atom.io after `rm -rf ~/.atom`

**Comment by andryushka** [comment]
Seems like problem w/ fedora package from copr repo. Gone away in atom 1.17.0.
