### ISSUE TITLE
Strange/Wrong Breakpoint Behavior & Cause error when press F9

### ISSUE THREAD

**Issue by hellolake** [facebook/nuclide#1082]
### Issue and Steps to Reproduce
![screen-shot-2017-04-02-at-04 42 44](https://cloud.githubusercontent.com/assets/15854353/24583702/d8260b70-1785-11e7-9165-f8b1c8eefaf9.jpg)

Toggle Breakpoint (F9) will cause an error and it happens when select Line Number after press F9.

### Expected Behavior
Click or select Line Number will only select lines at time.
Set breakpoint via click that blue dot on the left of Line Number.
Stable Toggle Breakpoint.

### Actual Behavior
Click or select Line Number will select lines and set Breakpoint at the same time.
Toggle Breakpoint (F9) will cause an error then happens when select lines.

### Toggle Breakpoint Stack Trace
TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1023:13)
    at MarkerLayer.module.exports.MarkerLayer.markPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:222:32)
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.markBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:109:52)
    at TextEditor.module.exports.TextEditor.markBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1784:38)
    at BreakpointDisplayController._createBreakpointMarkerAtLine (/Users/lakes/.atom/packages/nuclide/pkg/nuclide-debugger/lib/BreakpointDisplayController.js:269:33)
    at BreakpointDisplayController._update (/Users/lakes/.atom/packages/nuclide/pkg/nuclide-debugger/lib/BreakpointDisplayController.js:158:27)
    at new BreakpointDisplayController (/Users/lakes/.atom/packages/nuclide/pkg/nuclide-debugger/lib/BreakpointDisplayController.js:69:10)
    at BreakpointManager._handleTextEditor (/Users/lakes/.atom/packages/nuclide/pkg/nuclide-debugger/lib/BreakpointManager.js:55:26)
    at atom.workspace.observeTextEditors.editor (/Users/lakes/.atom/packages/nuclide/pkg/commons-atom/text-editor.js:179:7)
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:329:9)
    at observeTextEditors (/Users/lakes/.atom/packages/nuclide/pkg/commons-atom/text-editor.js:177:25)
    at new BreakpointManager (/Users/lakes/.atom/packages/nuclide/pkg/nuclide-debugger/lib/BreakpointManager.js:29:114)
    at new DebuggerModel (/Users/lakes/.atom/packages/nuclide/pkg/nuclide-debugger/lib/DebuggerModel.js:122:31)
    at new Activation (/Users/lakes/.atom/packages/nuclide/pkg/nuclide-debugger/lib/main.js:223:19)
    at Object.activate (/Users/lakes/.atom/packages/nuclide/pkg/nuclide-debugger/lib/main.js:538:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:96:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:550:34)
    at Object.keys.forEach.name (/Users/lakes/.atom/packages/nuclide/lib/main.js:286:21)
    at Array.forEach (native)
    at Object.activate (/Users/lakes/.atom/packages/nuclide/lib/main.js:283:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:218:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:96:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:180:34)

### Versions
* Atom: 1.15.0
* Nuclide: 0.213.0/0.214.0
* Client OS: Mac 10.12.1
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-react-native-autocomplete@0.0.27
├── busy-signal@1.3.0
├── emmet@2.4.3
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── intentions@1.1.2
├── language-babel@2.57.2
├── language-graphql@0.8.0
├── language-ini@1.19.0
├── language-javascript-jsx@0.3.7
├── language-lua@0.9.7
├── language-ocaml@1.1.3
├── language-swift@0.3.0
├── language-thrift@1.0.2
├── linter@2.0.0
├── linter-eslint@8.1.4
├── linter-ui-default@1.2.1
├── merge-conflicts@1.4.4
├── nuclide@0.213.0
├── nuclide-format-js@0.0.36
├── react-native-snippets@0.3.0
├── react-redux-atom-snippets@0.7.2
├── react-redux-snippets@0.1.6
├── set-syntax@0.3.2
├── sort-lines@0.14.0
└── tool-bar@1.1.0

**Comment by ebluestein** [comment]
This should be fixed in the latest Nuclide.
