### ISSUE TITLE
Uncaught Error: not implemented

### ISSUE THREAD

**Issue by tjkswaine** [facebook/nuclide#1107]
Steps to reproduce:

1. Open source control for a remote, hg driven repo.
2. try to create a new bookmark.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.218.55532894

### Stack Trace

Uncaught Error: not implemented

```
At /opt/facebook/nuclide/0.218.55532894/nuclide/pkg/nuclide-remote-connection/lib/RemoteDirectory.js:255

Error: not implemented
  at RemoteDirectory.getEntriesSync (/opt/facebook/nuclide/0.218.55532894/nuclide/pkg/nuclide-remote-connection/lib/RemoteDirectory.js:255:11)
  at dirHasCabalFile (/packages/haskell-ghc-mod/node_modules/atom-haskell-utils/lib/util.js:52:18)
  at findProjectRoot (/packages/haskell-ghc-mod/node_modules/atom-haskell-utils/lib/util.js:65:112)
  at Object.getRootDir (/packages/haskell-ghc-mod/node_modules/atom-haskell-utils/lib/util.js:83:21)
  at GhcModiProcess.module.exports.GhcModiProcess.getRootDir (/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process.coffee:27:16)
  at CompletionBackend.module.exports.CompletionBackend.getModuleMap (/packages/haskell-ghc-mod/lib/completion-backend/completion-backend.coffee:67:5)
  at CompletionBackend.getModuleMap (/packages/haskell-ghc-mod/lib/completion-backend/completion-backend.coffee:1:1)
  at /packages/haskell-ghc-mod/lib/completion-backend/completion-backend.coffee:146:31)
  at runCallback (timers.js:574:20)
  at tryOnImmediate (timers.js:554:5)
  at processImmediate [as _immediateCallback] (timers.js:533:5)

```

### Commands

```
     -3:23.8.0 core:move-up (button.btn)
     -1:23.9.0 editor:newline (input.hidden-input)
  4x -1:14 core:backspace (input.hidden-input)
  3x -0:58.6.0 editor:newline (input.hidden-input)
     -0:43.9.0 snippets:next-tab-stop (input.hidden-input)
     -0:43.9.0 snippets:expand (input.hidden-input)
     -0:43.9.0 editor:indent (input.hidden-input)
  2x -0:43.3.0 core:backspace (input.hidden-input)
     -0:41.5.0 find-and-replace:select-next (input.hidden-input)
     -0:40.3.0 snippets:next-tab-stop (input.hidden-input)
     -0:40.3.0 snippets:expand (input.hidden-input)
     -0:40.3.0 editor:indent (input.hidden-input)
     -0:39.7.0 core:backspace (input.hidden-input)
  3x -0:38.5.0 core:move-up (input.hidden-input)
  2x -0:36.8.0 core:select-down (input.hidden-input)
  2x -0:36.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-haskell 0.6.5 
autocomplete-python 1.8.4 
haskell-ghc-mod 1.16.0 
haskell-grammar 0.4.0 
haskell-hoogle 0.1.3 
highlight-selected 0.11.2 
ide-haskell 1.6.6 
language-babel 2.32.1 
language-graphql 0.7.0 
language-haskell 1.7.18 
language-ini 1.16.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.4.0 
language-thrift 1.0.2 
linter-python-pyflakes 0.1.0 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
nuclide 0.218.55532894 
nuclide-format-js 0.0.36 
python-autopep8 0.1.3 
python-isort 0.0.7 
python-jedi 0.3.7 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.0.0 
```

**Comment by hansonw** [comment]
Many packages, e.g. `atom-haskell-utils` are not compatible with Nuclide and its remote file system, as you can see in the error message. In this case it's impossible to implement `Directory.getEntriesSync` for remote directories. Sorry :(
