### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 164, Calling remote method fetchBookmarks..

### ISSUE THREAD

**Issue by tjkswaine** [facebook/nuclide#1108]
Steps to reproduce:

1. Show Smartlog
2. Cleanup (remove) uncommitted changes
3. arc pull

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.218.55532894

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 164, Calling remote method fetchBookmarks..

```
At /opt/facebook/nuclide/0.218.55532894/nuclide/node_modules/rxjs/bundles/Rx.min.js:58

RpcTimeoutError: Timeout after 60000 for id: 164, Calling remote method fetchBookmarks..
  at RpcTimeoutError (/opt/facebook/nuclide/0.218.55532894/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:126:20)
  at Call._timeout (/opt/facebook/nuclide/0.218.55532894/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:172:20)
  at Call._timerId.setTimeout (/opt/facebook/nuclide/0.218.55532894/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:142:12)

```

### Commands

```
     -9:12.8.0 core:paste (input.hidden-input)
  8x -9:12 core:move-left (input.hidden-input)
     -9:09.9.0 core:confirm (input.hidden-input)
     -8:38.2.0 core:move-up (input.hidden-input)
  4x -8:28.3.0 core:backspace (input.hidden-input)
     -8:24.1.0 core:paste (input.hidden-input)
     -8:23.8.0 core:confirm (input.hidden-input)
     -3:11.9.0 fb-interactive-smartlog:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:56.9.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-haskell 0.6.5 
autocomplete-python 1.8.4 
haskell-ghc-mod 1.16.0 
haskell-grammar 0.4.0 
haskell-hoogle 0.1.3 
highlight-selected 0.11.2 
ide-haskell 1.6.6 
language-babel 2.32.1 
language-graphql 0.7.0 
language-haskell 1.7.18 
language-ini 1.16.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.4.0 
language-thrift 1.0.2 
linter-python-pyflakes 0.1.0 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
nuclide 0.218.55532894 
nuclide-format-js 0.0.36 
python-autopep8 0.1.3 
python-isort 0.0.7 
python-jedi 0.3.7 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.0.0 
```

**Comment by hansonw** [comment]
Please keep internal bugs to Facebook tasks, thanks ;) Also this looks like a temporary error unless you can consistently repro this. (Also try removing the incompatible package, as seen in your last bug report).
