### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 4745, Calling remote method fetchBookmarks..

### ISSUE THREAD

**Issue by dutran** [facebook/nuclide#1110]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.218.55532894

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 4745, Calling remote method fetchBookmarks..

```
At /opt/facebook/nuclide/0.218.55532894/nuclide/node_modules/rxjs/bundles/Rx.min.js:58

RpcTimeoutError: Timeout after 60000 for id: 4745, Calling remote method fetchBookmarks..
  at RpcTimeoutError (/opt/facebook/nuclide/0.218.55532894/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:126:20)
  at Call._timeout (/opt/facebook/nuclide/0.218.55532894/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:172:20)
  at Call._timerId.setTimeout (/opt/facebook/nuclide/0.218.55532894/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:142:12)

```

### Commands

```
     -5:05.0 nuclide-file-tree:add-file (div.header.list-item)
  8x -4:44.8.0 core:move-left (input.hidden-input)
  5x -4:43.1.0 core:select-left (input.hidden-input)
  9x -4:41 core:move-right (input.hidden-input)
 15x -4:37.5.0 core:select-left (input.hidden-input)
     -4:18.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.57.3 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
nuclide 0.218.55532894 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by hansonw** [comment]
Please file tasks for the Facebook version internally using the bug nub in the toolbar. Thanks
