### ISSUE TITLE
Uncaught Error: Not connected

### ISSUE THREAD

**Issue by philippotto** [facebook/nuclide#1114]
[Enter steps to reproduce:]

1. Temporarily disconnect remote connection and try to let it automatically reconnect

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Windows 10 (local) and Ubuntu 16.04 (remote)
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.218.0

### Stack Trace

Uncaught Error: Not connected

```
At C:\Users\Philipp\.atom\packages\nuclide\pkg\nuclide-remote-connection\lib\SshHandshake.js:0

Error: Not connected
  at Client.forwardOut (/packages/nuclide/node_modules/ssh2/lib/client.js:983:11)
  at SshHandshake._forwardSocket (/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js:264:22)
  at /packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js:474:18)
  at emitOne (events.js:96:13)
  at Server.emit (events.js:188:7)
  at TCP.onconnection (net.js:1459:8)

```

### Commands

```
     -2:35.4.0 editor:toggle-line-comments (input.hidden-input)
     -2:35.1.0 core:save (input.hidden-input)
  4x -2:34.5.0 core:move-up (input.hidden-input)
     -2:32.5.0 editor:select-to-end-of-word (input.hidden-input)
     -2:32.3.0 core:copy (input.hidden-input)
     -1:27.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
  6x -1:27.4.0 editor:move-to-beginning-of-word (input.hidden-input)
     -1:25.5.0 editor:select-to-beginning-of-word (input.hidden-input)
  2x -1:17.6.0 editor:move-to-beginning-of-word (input.hidden-input)
     -1:17.1.0 editor:select-to-end-of-word (input.hidden-input)
     -1:15.9.0 core:save (input.hidden-input)
     -0:54.6.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:53.5.0 core:save (input.hidden-input)
     -0:52.8.0 editor:move-to-end-of-word (input.hidden-input)
     -0:52.6.0 core:move-right (input.hidden-input)
     -0:51.9.0 editor:select-to-end-of-word (input.hidden-input)
```

### Non-Core Packages

```
git-history 3.3.0 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.57.7 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.1.2 
linter-eslint 8.1.6 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
nuclide 0.218.0 
nuclide-format-js 0.0.36 
rulerz 0.4.3 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by hansonw** [comment]
This seems like you're using the insecure code path "nuclide-start-server -k". Is that the case / if so, does this work without that extra flag?

**Comment by philippotto** [comment]
@hansonw Yes, this is true. I'm using the -k flag since I can't establish the connection otherwise. If I omit the flag I get:

```
The server successfully started, but we were unable to connect.
Original error message:
 connect ECONNREFUSED 141.89.216.90:9091
```

However, SSHing into the machine works just fine.

**Comment by Ale-cc** [comment]
![14](https://user-images.githubusercontent.com/18302674/30735994-a37ead80-9fb3-11e7-81f6-8644f4fbf2ec.png)
Firstly ,check the information you login in.
After I reinstalling the Atom ,I find it hard to connect the server.
I fund it that update my .npmrc file for installing package(In China),
`registry=https://registry.npm.taobao.org/ `
Finally I can connect the server.

**Comment by abhijits1234** [comment]
I am facing the same issue

**Comment by JananiKSekar** [comment]
I am facing the same issue, but i am getting this error:
The server successfully started, but we were unable to connect.
Original error message:
 Timeout after 60000 for id: 4182, Calling function FileSystemService/resolveRealPath.

**Comment by francip** [comment]
Remote connection with insecure server (nuclide-start-server -k) used to work in v0.280, and stopped working again in v0.282.

[Enter steps to reproduce:]

1. Install nuclide server v0.282 on remote remote machine
(in my case: Raspberry Pi3 / Raspbian Stretch / Node.js v9.5.0)
2. Run Nuclide and attempt to connect to the remote server using 'nuclide-start-server -k' command

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.282.0


### Stack Trace

Uncaught Error: Not connected

```
At /Users/francip/.atompi/packages/nuclide/node_modules/ssh2/lib/client.js:983

Error: Not connected
    at Client.forwardOut (/packages/nuclide/node_modules/ssh2/lib/client.js:983:11)
    at SshHandshake._forwardSocket (/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js:275:22)
    at /packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js:467:18)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at TCP.onconnection (net.js:1454:8)
```

### Commands

```
     -1:36.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -1:27.9.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
file-icons 2.1.16 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
jsonlint 1.1.4 
language-babel 2.83.1 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
linter-jsonlint 1.3.0 
MagicPython 1.0.12 
merge-conflicts 1.4.5 
nuclide 0.282.0 
nuclide-format-js 0.0.44 
pretty-json 1.6.4 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.5 
```

**Comment by Lawris** [comment]
Same issue on v0.284 (Client and Server).

**Comment by p-t-u** [comment]
Same issue. Nuclide is broken on Ubuntu 18.04 Beta, presumably due to changes in the Python packages.

"nuclide-start-server -k" causes the bug described here.

"nuclide-start-server" causes this other bug: https://github.com/facebook/nuclide/issues/1341
