### ISSUE TITLE
Uncaught Error: Cannot find module '../../commons-node/string'

### ISSUE THREAD

**Issue by mikedotJS** [facebook/nuclide#1124]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.222.0

### Stack Trace

Uncaught Error: Cannot find module '../../commons-node/string'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:379

Error: Cannot find module '../../commons-node/string'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at _load_string (/packages/nuclide/pkg/nuclide-navigation-stack/lib/NavigationStackController.js:19:20)
    at NavigationStackController.updateScroll (/packages/nuclide/pkg/nuclide-navigation-stack/lib/NavigationStackController.js:140:54)
    at scrollSubscription.onDidChangeScrollTop.scrollTop (/packages/nuclide/pkg/nuclide-navigation-stack/lib/main.js:76:20)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/text-editor-element.js:105:46
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditorPresenter.module.exports.TextEditorPresenter.updateScrollTop (/app.asar/src/text-editor-presenter.js:944:29)
    at TextEditorPresenter.module.exports.TextEditorPresenter.restoreScrollTopIfNeeded (/app.asar/src/text-editor-presenter.js:1989:21)
    at TextEditorPresenter.module.exports.TextEditorPresenter.setLineHeight (/app.asar/src/text-editor-presenter.js:1275:14)
    at LinesComponent.module.exports.LinesComponent.measureLineHeightAndDefaultCharWidth (/app.asar/src/lines-component.js:132:22)
    at TextEditorComponent.module.exports.TextEditorComponent.measureLineHeightAndDefaultCharWidth (/app.asar/src/text-editor-component.js:1070:36)
    at TextEditorComponent.module.exports.TextEditorComponent.sampleFontStyling (/app.asar/src/text-editor-component.js:1051:14)
    at TextEditorComponent.sampleFontStyling (/app.asar/src/text-editor-component.js:3:59)
    at TextEditorComponent.module.exports.TextEditorComponent.becameVisible (/app.asar/src/text-editor-component.js:292:12)
    at TextEditorComponent.module.exports.TextEditorComponent.checkForVisibilityChange (/app.asar/src/text-editor-component.js:994:16)
    at /app.asar/src/text-editor-element.js:87:22)
    at /app.asar/src/pane-element.js:138:24)
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/app.asar/src/pane.js:435:19)
    at Pane.module.exports.Pane.activatePreviousItem (/app.asar/src/pane.js:400:21)
    at Pane.module.exports.Pane.removeItem (/app.asar/src/pane.js:585:16)
    at Pane.module.exports.Pane.destroyItem (/app.asar/src/pane.js:658:16)
    at TabBarView.module.exports.TabBarView.closeTab (/app.asar/node_modules/tabs/lib/tab-bar-view.js:333:26)
    at HTMLDivElement.TabView.didClickCloseIcon (/app.asar/node_modules/tabs/lib/tab-bar-view.js:222:19)
```

### Commands

```
  3x -1:14.3.0 core:backspace (input.hidden-input)
     -1:12.8.0 core:confirm (input.hidden-input)
  2x -0:27.4.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
busy-signal 1.4.1 
emmet 2.4.3 
fast-import-js 0.5.2 
file-icons 2.1.4 
goto-definition 1.3.3 
intentions 1.1.2 
language-javascript-jsx 0.3.7 
linter 2.1.4 
linter-eslint 8.1.7 
linter-ui-default 1.2.3 
merge-conflicts 1.4.4 
nuclide 0.222.0 
prettier-atom 0.30.0 
react-snippets 0.7.2 
redux-snippets 0.2.2 
```

**Comment by matthewwithanm** [comment]
Hey @mikedotJS! Does this happen every time you reload Atom? If so, it sounds like you have a bad Nuclide install and reinstalling Nuclide should fix it.

**Comment by abseomar** [comment]
نحن المراجعين سنقترح لكم حلولا شامله فتابعونا

**Comment by abseomar** [comment]
![13882507_10154375799983279_2682463787948468347_n](https://cloud.githubusercontent.com/assets/20147460/25726114/e5ecf92e-3122-11e7-9b78-ab119e01d604.png)

**Comment by mikedotJS** [comment]
Hey @matthewwithanm, yes, i did the brand new Nuclide update and it started to happen every time i reloaded Atom. Like you said, i just reinstalled it and it did fix it !

**Comment by matthewwithanm** [comment]
Great! (:

**Comment by abseomar** [comment]
QDKARMELINA          crispy wafers  with hazelnuts filling   65g/*Karmela                                 Wafer
25/01/2017    L21
25/01/2018   L21
importer for libya altaef foods/*made in                                     فلسطين

**Comment by abseomar** [comment]
last comnet by aditlibya in auditoco&auditusa;auditmosco;auditjapan

**Comment by abseomar** [comment]
agncyco crises
