### ISSUE TITLE
GraphQL support not working?

### ISSUE THREAD

**Issue by dpeek** [facebook/nuclide#1126]
### Issue and Steps to Reproduce
Create a project following the [nuclide](https://nuclide.io/docs/languages/graphql/) and [graphql language service](https://github.com/graphql/graphql-language-service#graphql-configuration-file-graphqlrc) instructions:

`./.graphqlrc`

```json
{
  "build-configs": {
    "product-name": {
      "input-dirs": [
        "./"
      ],
      "exclude-dirs": [
      ],
      "schema-path": "./schema.graphql"
    }
  }
}
```

(also tried with absolute paths)

`./schema.graphql`

```graphql
type Query {
  foo(bar: String): String
}
```

`./test.graphql`

```graphql
query {
  # crickets
}
```

### Expected Behavior
Awesome GraphQL support.

### Actual Behavior
Syntax highlighting but not much else, and this error in the console:

```
[2017-05-03T21:06:27.691Z] [ERROR] nuclide - Error getting Hyperclick suggestion: Source object: null is missing property queryRange.
Error marshalling value: 'null'
object
DefinitionQueryResult
named

Error: Source object: null is missing property queryRange.
Error marshalling value: 'null'
object
DefinitionQueryResult
named

  at type.fields.map.e (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:644:17)
  at Array.map (native)
  at _registerKind (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:622:58)
  at Object.e [as unmarshaller] (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:805:14)
  at TypeRegistry._unmarshal (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:311:27)
  at registerType (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:246:121)
  at Object.e [as unmarshaller] (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:816:14)
  at TypeRegistry._registerKind (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:188:30)
  at Object.e [as unmarshaller] (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:805:14)
  at TypeRegistry._unmarshal (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:311:27)
  at TypeRegistry.unmarshal (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:293:33)
  at RpcConnection.unmarshal (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:232:36)
  at _client.marshalArguments.then.then.value (/Users/dpeek/.atom/packages/nuclide/pkg/nuclide-graphql-rpc/lib/GraphQLServerServiceProxy.js:44:22)
  at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Versions
* Atom: 1.16.0
* Nuclide: 0.223.0
* Client OS: macOS

### Additional Details

Installed packages:

```
Community Packages (13) /Users/dpeek/.atom/packages
├── atom-typescript@11.0.3
├── highlight-selected@0.13.1
├── language-babel@2.58.0
├── language-graphql@0.8.0
├── language-swift@0.5.0
├── linter-eslint@8.1.7
├── merge-conflicts@1.4.4
├── nuclide@0.223.0
├── nuclide-format-js@0.0.36
├── prettier-atom@0.30.0
├── set-syntax@0.3.2
├── sort-lines@0.14.0
└── tool-bar@1.1.0
```

**Comment by asiandrummer** [comment]
aaaah sorry @dpeek! I updated a bunch of things in `graphql-language-service` and completely forgot to update the documentation, especially around `.graphqlrc` (even the name changed to `.graphqlconfig`). I'll go ahead and change them right now. Apologies for this.

In a nutshell, there's now a different format for the GraphQL configuration file:
```js
// `.graphqlconfig` file
{
  "projects": {
    "productName": {
      "includeDirs": [],
      "excludeDirs": [],
      "schemaPath": "schema.graphql"
    }
  }
}
```

**Comment by dpeek** [comment]
Thankyou, works perfectly!

**Comment by mgadda** [comment]
For posterity, it looks like the format has changed again since Jun 9 to adhere to the [graphcool/graphql-config specification](https://github.com/graphcool/graphql-config#simplest-use-case). 

@asiandrummer let me know if that's not actually the case. thanks! 

Incidentally, using either the above format or the graphql-config format, I am still not seeing nuclide pick up the config and start parsing queries.

**Comment by steida** [comment]
It still does not work for me. Does there any working repo example? I remember it worked, but not anymore.
