### ISSUE TITLE
Uncaught Error: adb is unavailable. Add it to your path and restart nuclide or make sure that 'ad...

### ISSUE THREAD

**Issue by kungfu321** [facebook/nuclide#1128]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.223.0

### Stack Trace

Uncaught Error: adb is unavailable. Add it to your path and restart nuclide or make sure that 'adb start-server' works.

```
At C:\Users\kienv\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:58

Error: adb is unavailable. Add it to your path and restart nuclide or make sure that 'adb start-server' works.
    at /packages/nuclide/pkg/nuclide-adb-sdb-rpc/lib/DebugBridgePathStore.js:32:13
    at next (<anonymous>)
    at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:21:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Commands

```
     -3:52.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:50.8.0 atom-beautify:beautify-editor (div.line)
     -0:45.5.0 core:undo (input.hidden-input)
     -0:13.9.0 nuclide-devices:toggle (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
autoclose-html 0.23.0 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.1.4 
highlight-selected 0.13.1 
language-mongodb 0.3.1 
laravel 0.7.1 
laravel-forms-bootstrap-snippets 1.2.0 
minimap 4.28.2 
minimap-cursorline 0.2.0 
nodejs-snippets 2.0.2 
nuclide 0.223.0 
pigments 0.39.1 
react-native-snippets 0.3.0 
seti-ui 1.7.0 
```

**Comment by a20012251** [comment]
Did you hit this after opening the device panel?

**Comment by matthewwithanm** [comment]
Thanks for the report @kungfu321! @a20012251 has fixed this so I'm going to close (:
