### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replaceWith' of undefined

### ISSUE THREAD

**Issue by theotix** [facebook/nuclide#1137]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.223.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replaceWith' of undefined

```
At /Users/theotix/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:15

TypeError: Cannot read property 'replaceWith' of undefined
  at linterMessageV2ToDiagnosticMessage (/packages/nuclide/pkg/nuclide-diagnostics-store/lib/LinterAdapter.js:111:17)
  at linterMessagesToDiagnosticUpdate (/packages/nuclide/pkg/nuclide-diagnostics-store/lib/LinterAdapter.js:148:56)
  at /packages/nuclide/pkg/nuclide-diagnostics-store/lib/LinterAdapter.js:218:22)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:227:188)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:29:506)
  at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:48:393)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:50:60)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:29:506)
  at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:14:470
  at process._tickCallback (internal/process/next_tick.js:103:7)

```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-css-comb 3.1.0 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
busy-signal 1.4.1 
color-picker 2.2.5 
compare-files 0.8.0 
file-types 0.5.5 
language-blade 0.30.0 
language-ocaml 1.8.0 
language-slim 0.5.0 
language-vue 0.21.2 
merge-conflicts 1.4.4 
nuclide 0.223.0 
ocaml-indent 0.6.0 
ocaml-merlin 0.14.3 
pigments 0.39.1 
seti-ui 1.8.0 
```

**Comment by acierto** [comment]
Steps to reproduce:
1. install apm install ocaml-merlin
2. open any OCaml .ml file
