### ISSUE TITLE
Uncaught TypeError: this._transport.registerNuclideNotificationHandler is not a function

### ISSUE THREAD

**Issue by aaronbdixon** [facebook/nuclide#1143]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.226.0

### Stack Trace

Uncaught TypeError: this._transport.registerNuclideNotificationHandler is not a function

```
At /Users/**/.atom/packages/nuclide/pkg/nuclide-debugger/lib/Protocol/NuclideProtocolParser.js:743

TypeError: this._transport.registerNuclideNotificationHandler is not a function
  at Object.InspectorBackendClass.StubConnection (/packages/nuclide/pkg/nuclide-debugger/lib/Protocol/NuclideProtocolParser.js:743:21)
  at /packages/nuclide/pkg/nuclide-debugger/lib/Protocol/NuclideProtocolParser.js:206:32
  at tryToString (fs.js:455:3)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

```

### Commands

```
     -0:13.7.0 command-palette:toggle (input.hidden-input)
  3x -0:11.3.0 core:backspace (input.hidden-input)
     -0:07.4.0 nuclide-react-native:start-debugging (input.hidden-input)
     -0:07.4.0 nuclide-debugger:stop-debugging (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-material-ui)
     -0:07.4.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-material-ui)
     -0:07.4.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-material-ui)
```

### Non-Core Packages

```
atom-autocomplete-php 0.22.2 
atom-less 0.1.10 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.3 
atom-writer 0.0.1 
build-gradle 0.6.0 
busy-signal 1.4.1 
duotone-dark-syntax 2.1.0 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-awk 0.1.12 
language-babel 2.61.0 
language-gradle 0.0.3 
language-graphql 0.9.0 
language-ini 1.19.0 
language-javascript-jsx 0.3.7 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-swift 0.5.0 
language-thrift 1.0.2 
language-vue 0.21.2 
linter 2.1.4 
linter-eslint 8.1.7 
linter-jshint 3.1.2 
linter-less 2.6.0 
linter-ui-default 1.4.0 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.226.0 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
wordpress-api 1.2.2 
```

**Comment by RoJoHub** [comment]
Also i have this error

**Comment by j-w-huang** [comment]
I think the react native  debugger  is deprecated..

**Comment by j-w-huang** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.228.0


### Stack Trace

Uncaught TypeError: this._transport.registerNuclideNotificationHandler is not a function

```
At /home/yuer/.atom/packages/nuclide/pkg/nuclide-debugger/lib/Protocol/NuclideProtocolParser.js:743

TypeError: this._transport.registerNuclideNotificationHandler is not a function
  at Object.InspectorBackendClass.StubConnection (/packages/nuclide/pkg/nuclide-debugger/lib/Protocol/NuclideProtocolParser.js:743:21)
  at /packages/nuclide/pkg/nuclide-debugger/lib/Protocol/NuclideProtocolParser.js:206:32
  at tryToString (fs.js:455:3)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

```

### Commands

```
     -0:14.6.0 nuclide-debugger:toggle (atom-pane.pane.active)
     -0:06.6.0 nuclide-react-native:start-packager (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui)
     -0:06.6.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui)
     -0:06.5.0 nuclide-react-native:start-debugging (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui)
     -0:06.5.0 nuclide-debugger:stop-debugging (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui)
     -0:06.5.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui)
     -0:06.5.0 nuclide-debugger:toggle-launch-attach (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui)
     -0:06.4.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui)
```

### Non-Core Packages

```
atom-material-ui 1.3.10 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.61.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.228.0 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
VisualStudio 0.1.3 
```

**Comment by vanvanj** [comment]
I have this issue too.....

**Comment by VisionBao** [comment]
I have this issue too

**Comment by mostafaeweda** [comment]
That should be fixed now with the debugger old channel removed and cleaned up.
