### ISSUE TITLE
Help me!!!

### ISSUE THREAD

**Issue by j-w-huang** [facebook/nuclide#1153]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom:
* Nuclide:
* Client OS:
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by ebluestein** [comment]
With what do you need help?

**Comment by j-w-huang** [comment]
@ebluestein sorry, I paste error:
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.228.0


### Stack Trace

Uncaught TypeError: this._transport.registerNuclideNotificationHandler is not a function

```
At /home/yuer/.atom/packages/nuclide/pkg/nuclide-debugger/lib/Protocol/NuclideProtocolParser.js:743

TypeError: this._transport.registerNuclideNotificationHandler is not a function
  at Object.InspectorBackendClass.StubConnection (/packages/nuclide/pkg/nuclide-debugger/lib/Protocol/NuclideProtocolParser.js:743:21)
  at /packages/nuclide/pkg/nuclide-debugger/lib/Protocol/NuclideProtocolParser.js:206:32
  at tryToString (fs.js:455:3)
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

```

### Commands

```
     -0:14.2.0 nuclide-debugger:toggle (atom-pane.pane.active)
     -0:06.1.0 nuclide-react-native:start-packager (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:06.1.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:06.0 nuclide-react-native:start-debugging (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:06.0 nuclide-debugger:stop-debugging (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:06.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:06.0 nuclide-debugger:toggle-launch-attach (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -0:05.9.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
```

### Non-Core Packages

```
file-icons 2.1.6 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.61.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
native-color-picker 0.2.5 
nucleon 1.0.4 
nuclide 0.228.0 
nuclide-format-js 0.0.36 
platformio-ide-terminal 2.5.0 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
VisualStudio 0.1.3 
```
