### ISSUE TITLE
Issue with hyperclick on atom master

### ISSUE THREAD

**Issue by joefitzgerald** [facebook/nuclide#1154]
[Enter steps to reproduce:]

1. install nuclide
1. build atom master
1. open atom
1. error

**Atom**: 1.19.0-dev-944b5c5b0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [hyperclick](https://github.com/facebook/nuclide) package 0.0.0

### Stack Trace

Failed to activate the hyperclick package

```
At Cannot read property 'getDomNode' of undefined

TypeError: Cannot read property 'getDomNode' of undefined
    at getLinesDomNode (/packages/nuclide/pkg/hyperclick/lib/HyperclickForTextEditor.js:104:38)
    at addMouseListeners (/packages/nuclide/pkg/hyperclick/lib/HyperclickForTextEditor.js:114:7)
    at HyperclickForTextEditor._setupMouseListeners (/packages/nuclide/pkg/hyperclick/lib/HyperclickForTextEditor.js:120:5)
    at /packages/nuclide/pkg/hyperclick/lib/HyperclickForTextEditor.js:74:10)
    at Hyperclick.observeTextEditor (/packages/nuclide/pkg/hyperclick/lib/Hyperclick.js:80:37)
    at atom.workspace.observeTextEditors.editor (/packages/nuclide/modules/nuclide-commons-atom/text-editor.js:180:7)
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:703:15)
    at observeTextEditors (/packages/nuclide/modules/nuclide-commons-atom/text-editor.js:178:25)
    at /packages/nuclide/pkg/hyperclick/lib/Hyperclick.js:76:95)
    at Object.activate (/packages/nuclide/pkg/hyperclick/lib/main.js:46:16)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at Object.keys.forEach.name (/packages/nuclide/lib/main.js:305:21)
    at Array.forEach (native)
    at Object.activate (/packages/nuclide/lib/main.js:302:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:842:34
```

### Non-Core Packages

```
activate-power-mode 1.4.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.3 
autocomplete-flow 1.6.0 
busy-signal 1.4.1 
concourse-vis 1.4.0 
file-icons 2.1.6 
go-debug 1.3.1 
go-plus 5.5.4 
go-signature-statusbar 1.2.0 
intentions 1.1.2 
language-javascript-jsx 0.3.7 
linter 2.1.4 
linter-eslint 8.1.7 
linter-flow 5.6.0 
linter-js-standard 3.9.1 
linter-jsonlint 1.3.0 
linter-ui-default 1.5.4 
markdown-scroll-sync 2.1.2 
nuclide 0.228.0 
nuclide-test-runner-jest 0.3.0 
platformio-ide-terminal 2.5.0 
react 0.16.2 
redux-snippets 0.2.2 
standard-formatter 2.8.0 
svg-preview 0.11.0 
text-manipulation 0.6.0 
```

**Comment by joefitzgerald** [comment]
<img width="1455" alt="screen shot 2017-05-20 at 10 48 26 am" src="https://cloud.githubusercontent.com/assets/744740/26277689/e8c1b274-3d49-11e7-8ba1-3c8b719ea1c4.png">

`component.linesComponent` is undefined in `HyperclickForTextEditor.js`

**Comment by hansonw** [comment]
Uh oh, looks like we're not compatible with the new text-editor implementation! :(
