### ISSUE TITLE
Failed to activate the nuclide-hg-repository package

### ISSUE THREAD

**Issue by Tikam02** [facebook/nuclide#1177]
**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [nuclide-hg-repository](https://github.com/facebook/nuclide) package 0.0.0

### Stack Trace

Failed to activate the nuclide-hg-repository package

```
At Cannot read property 'isDestroyed' of undefined

TypeError: Cannot read property 'isDestroyed' of undefined
    at ServiceHub.module.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.17.0/resources/app/node_modules/service-hub/lib/service-hub.js:29:1)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:446:1)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:256:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.0/resources/app/src/package-manager.js:642:1)
    at Object.keys.forEach.name (/packages/nuclide/lib/main.js:305:21)
    at Array.forEach (native)
    at Object.activate (/packages/nuclide/lib/main.js:302:25)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:253:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.0/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.0/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.17.0/resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.17.0/resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.17.0/resources/app/src/package-manager.js:600:1)
    at ~/AppData/Local/atom/app-1.17.0/resources/app/src/atom-environment.js:832:1
```

### Commands

```
  2x -0:10.2.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
astromac-ui 0.1.0 
astronomical-ui 0.22.5 
atom-html-preview 0.1.22 
atom-live-server 2.1.2 
atom-material-syntax 1.0.6 
atom-react-native-css 1.1.3 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
autoclose-html 0.23.0 
busy-signal 1.4.1 
color-picker 2.2.5 
css-comb 2.5.0 
css-snippets 1.1.0 
emmet 2.4.3 
glacier-darkula-syntax 1.1.7 
gpp-compiler 3.0.7 
hyperclick 0.0.40 
intentions 1.1.2 
language-html5-subtlegradient 0.1.0 
linter 2.1.4 
linter-ui-default 1.5.4 
livestyle-atom 0.2.9 
logo-file-icons 1.11.0 
minimap 4.28.2 
molecule-ubuntu 0.2.0 
native-color-picker 0.2.5 
nebula-ui 0.6.0 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
nuclide 0.228.0 
nuclide-format-js 0.0.36 
open-recent 5.0.0 
platformio-ide-terminal 2.5.0 
todo-show 1.11.0 
wordpress-api 1.2.2 
```

**Comment by wbinnssmith** [comment]
thanks for reporting @Tikam02. We have a fix for this coming in the next release of Nuclide :)
