### ISSUE TITLE
install nuclide 0.231.0 came up error info

### ISSUE THREAD

**Issue by RazerTang** [facebook/nuclide#1180]
### Issue and Steps to Reproduce
I just click install button, and it shows error info below:
gyp info using node-gyp@3.4.0
gyp info using node@6.9.5 | darwin | x64
gyp http GET https://atom.io/download/electron/v1.3.15/iojs-v1.3.15.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ECONNREFUSED 127.0.0.1:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1022:11)
gyp ERR! stack     at exports._exceptionWithHostPort (util.js:1045:20)
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=1.3.15" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/weiqingtang/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

### Versions
* Atom:1.17.2 x64
* Nuclide:0.231.0
* Mac OS:10.12.5
* Node:8.0.0
* node-gyp:3.6.2

![2017-06-06 6 15 25](https://cloud.githubusercontent.com/assets/5905640/26824474/231173a4-4ae4-11e7-8b5d-2e639b5f34b4.png)

**Comment by RazerTang** [comment]
[](https://nuclide.io/docs/advanced-topics/building-from-source/)

Run the following commands to build Nuclide from source.
# Clone the source
$ git clone https://github.com/facebook/nuclide.git
$ cd nuclide
# Install dependencies
$ npm install
# Link the 'nuclide' package to Atom's package directory
# You could also use apm link --dev ... see Development Mode below.
$ apm link
