### ISSUE TITLE
You just connected to a remote project without Watchman support, 

### ISSUE THREAD

**Issue by zakiaziz** [facebook/nuclide#1183]
### Issue and Steps to Reproduce
A warning message shows after connected to a remote server

### Expected Behavior
A warning should not be shown. Files should sync

### Actual Behavior
Warning message shown. Modifying files locally updates file remotely. Modifying files remotely doesn't update local file.
![screen shot 2017-06-07 at 4 44 13 pm](https://user-images.githubusercontent.com/940281/26902445-56cd448e-4ba7-11e7-83d7-984f594f77a6.png)

Content of warning message:
```
You just connected to a remote project /home/zaki/atlasx without Watchman support, which means that crucial features such as synced remote file editing, file search, and Mercurial-related updates will not work.

A possible workaround is to create an empty .watchmanconfig file in the remote folder, which will enable Watchman if you have it installed.

Watchman Error:Remote Error: A non-recoverable condition has triggered. Watchman needs your help! The triggering condition was at timestamp=1496868122: inotify-add-watch(/home/zaki/atlasx/node_modules/babel-core/node_modules/babel-runtime/core-js/symbol) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl All requests will continue to fail with this message until you resolve the underlying problem. You will find more information on fixing this at https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch processing message {"protocol":"service_framework3_rpc","type":"call","method":"FileWatcherService/watchDirectoryRecursive","id":8,"args":{"directoryPath":"/home/zaki/atlasx"}} "Error: A non-recoverable condition has triggered. Watchman needs your help!\nThe triggering condition was at timestamp=1496868122: inotify-add-watch(/home/zaki/atlasx/node_modules/babel-core/node_modules/babel-runtime/core-js/symbol) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl\nAll requests will continue to fail with this message until you resolve\nthe underlying problem. You will find more information on fixing this at\nhttps://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch\n\n at BunserBuf. (/home/zaki/.nvm/versions/node/v6.10.0/lib/node_modules/nuclide/node_modules/fb-watchman/index.js:95:23)\n at emitOne (events.js:96:13)\n at BunserBuf.emit (events.js:189:7)\n at BunserBuf.process (/home/zaki/.nvm/versions/node/v6.10.0/lib/node_modules/nuclide/node_modules/bser/index.js:292:10)\n at /home/zaki/.nvm/versions/node/v6.10.0/lib/node_modules/nuclide/node_modules/bser/index.js:247:12\n at _combinedTickCallback (internal/process/next_tick.js:67:7)\n at process._tickCallback (internal/process/next_tick.js:98:9)"
```

Another issue I'm having: Project files aren't indexing properly. I'm not sure if this is related but it seems like it would be. When hitting `cmd` + `p` I see:
![screen shot 2017-06-07 at 5 36 30 pm](https://user-images.githubusercontent.com/940281/26902702-445d85ce-4ba8-11e7-975e-7473ab185139.png)

### Versions
* Atom: 1.17.2
* Nuclide: nuclide@0.231.0
* Client OS: OSX 10.12.4
* Server OS (optional): Ubuntu 14.04

### Additional Details
* Installed packages (`apm ls --installed`):
```
$ apm ls --installed
Community Packages (4) /Users/zakiaziz/.atom/packages
├── Remote-FTP@0.10.7
├── atom-monokai-soda@3.0.1
├── gitlab@0.1.3-7
└── nuclide@0.231.0
```

**Comment by kylefritz** [comment]
I was having this problem until I recursively `chown` `/usr/local/var/run/watchman/<username>-state/`

**Comment by zietbukuel** [comment]
@kylefritz is this on the remote or local machine? In both cases I get this:

```
ls /usr/local/var/run/watchman/
ls: cannot access /usr/local/var/run/watchman/: No such file or directory
```

**Comment by kylefritz** [comment]
remote machine.

**Comment by zietbukuel** [comment]
I don't have that folder in my remote machine. After a year, I'm still having the same issue... Any other way to fix this?
