### ISSUE TITLE
Uncaught TypeError: this.isLevelEnabled is not a function

### ISSUE THREAD

**Issue by alzalabany** [facebook/nuclide#1192]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.232.0

### Stack Trace

Uncaught TypeError: this.isLevelEnabled is not a function

```
At /Users/madina/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43

TypeError: this.isLevelEnabled is not a function
  at /packages/nuclide/node_modules/log4js/lib/logger.js:83:34)
  at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43:337)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:42:227)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:106:294)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:170:388)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:48:322)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:48:322)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:240:110)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:61:263)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:60:68)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:61:263)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:81:365)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at process.nextTick (internal/child_process.js:744:12)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

### Commands

```
     -5:56.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -5:53.9.0 editor:consolidate-selections (input.hidden-input)
     -5:53.9.0 core:cancel (input.hidden-input)
     -5:52.2.0 command-palette:toggle (input.hidden-input)
     -5:44.2.0 core:move-down (input.hidden-input)
     -5:40.6.0 core:confirm (input.hidden-input)
     -5:40.5.0 nuclide-react-native:start-packager (input.hidden-input)
     -5:40.5.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:26.5.0 command-palette:toggle (input.hidden-input)
     -3:21.4.0 core:confirm (input.hidden-input)
     -3:21.3.0 nuclide-react-native:start-debugging (input.hidden-input)
     -3:21.3.0 nuclide-debugger:stop-debugging (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:21.3.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:20.5.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:19.2.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.65.1 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
linter-eslint 8.2.1 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.232.0 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by mostafaeweda** [comment]
Please update to the latest Nuclide and let us know if this is still an issue
