### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getRootScopeDescriptor' of undefined

### ISSUE THREAD

**Issue by susheelyarlagadda** [facebook/nuclide#1197]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.232.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getRootScopeDescriptor' of undefined

```
At /Users/susheelkumaryarlagadda/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43

TypeError: Cannot read property 'getRootScopeDescriptor' of undefined
  at Object.display_context (/packages/flow/lib/flow.js:210:27)
  at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (<embedded>:21492:25)
  at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (<embedded>:21450:39)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (<embedded>:21550:33)
  at /packages/nuclide/pkg/nuclide-file-tree/lib/main.js:156:22)
  at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43:337)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:42:227)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at a._complete (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:189:331)
  at a.complete (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:228)
  at a._complete (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:529)
  at a.complete (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:228)
  at a.complete (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:207:175)
  at requestAnimationFrame (/packages/nuclide/modules/nuclide-commons/observable.js:286:14)

```

### Commands

```
  2x -1:39.6.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -1:14.1.0 atom-terminal:open-project-root (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory-starred)
  2x -1:05.2.0 application:add-project-folder (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory-starred)
     -0:24.4.0 tabs:close-all-tabs (div.title)
```

### Non-Core Packages

```
atom-react-autocomplete 0.1.10 
atom-terminal 0.8.0 
emmet 2.4.3 
emmet-jsx-css-modules 1.0.0 
flow 0.5.3 
language-babel 2.65.1 
language-javascript-jsx 0.3.7 
language-jsx 0.1.1 
language-ocaml 1.9.5 
nuclide 0.232.0 
react 0.16.2 
react-native-snippets 0.3.0 
react-snippets 0.8.0 
sort-lines 0.14.0 
term3 0.22.1 
tool-bar 1.1.0 
```

**Comment by mostafaeweda** [comment]
This seems coming from the `flow` package, not Nuclide.
You shouldn't need that package as Nuclide already provides decent flow support
