### ISSUE TITLE
atom 1.9 beta 0

### ISSUE THREAD

**Issue by atomi** [facebook/nuclide#1199]
[Enter steps to reproduce:]

1. install go-plus package
2. install hyperclick
Note: This may be an issue with atom's new editor. 

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Linux Mint
**Thrown From**: [hyperclick](https://github.com/facebooknuclide/hyperclick) package 0.0.40

### Stack Trace

Failed to activate the hyperclick package

```
At Cannot read property 'getDomNode' of undefined

TypeError: Cannot read property 'getDomNode' of undefined
    at getLinesDomNode (/packages/hyperclick/lib/HyperclickForTextEditor.js:99:40)
    at addMouseListeners (/packages/hyperclick/lib/HyperclickForTextEditor.js:109:9)
    at HyperclickForTextEditor._setupMouseListeners (/packages/hyperclick/lib/HyperclickForTextEditor.js:115:7)
    at /packages/hyperclick/lib/HyperclickForTextEditor.js:60:10)
    at Hyperclick.observeTextEditor (/packages/hyperclick/lib/Hyperclick.js:85:37)
    at /packages/hyperclick/lib/Hyperclick.js:74:20
    at Workspace.observeTextEditors (/usr/share/atom-beta/resources/app/src/workspace.js:717:15)
    at /packages/hyperclick/lib/Hyperclick.js:62:51)
    at Object.activate (/packages/hyperclick/lib/main.js:55:16)
    at Package.module.exports.Package.activateNow (/usr/share/atom-beta/resources/app/src/package.js:253:25)
    at /usr/share/atom-beta/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom-beta/resources/app/src/package.js:99:21)
    at /usr/share/atom-beta/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom-beta/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom-beta/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/usr/share/atom-beta/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom-beta/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom-beta/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom-beta/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
```

### Non-Core Packages

```
git-plus 7.9.3 
go-debug 1.4.3 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
linter 2.1.4 
linter-ui-default 1.6.1 
```

**Comment by admmasters** [comment]
So I think they have moved hyperclick to an internal package - deleting hyperclick 0.0.40 from atom's packages was what worked for me.

**Comment by hansonw** [comment]
Yeah the `hyperclick` package isn't well supported. I may do a release later this week, though..
For a lighter-weight package that includes Hyperclick, try out https://atom.io/packages/atom-ide-ui :D
