### ISSUE TITLE
Error when connecting to remote server

### ISSUE THREAD

**Issue by friscoMad** [facebook/nuclide#1216]
### Issue and Steps to Reproduce
When I try to connect to a remote server it kinda works as it retrieves the list of files but raises an exception and closes right away.

### Expected Behavior
Just work

### Actual Behavior
Exception and tree view is unresponsive

### Versions
* Atom: 1.18.0 x64
* Nuclide: 0.232.0
* Client OS: Windows 7
* Server OS (optional): Centos 7
* Server Versions: Node 7.7.1 Watchman 4.9.0 Python 2.7.5

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.232.0

### Extended description

The exception is only the server closing but it is not traced why the server is closing. This stack trace only appears after restarting atom, after that if you try to connect again this exception do not appear.

There is another error that appear every time (the first one and others) that only reads:

> The server successfully started, but we were unable to connect.
> Original error message:
>  Cannot read property 'split' of undefined
> 

As it does retrieve the file list the connection must be stablished but still shows that error.
In the server side I am unable to show anything interesting in the logs:

```
2017-06-25 04:11:05,882 - root - INFO - Invoked nuclide_server_manager...
2017-06-25 04:11:05,882 - NuclideServerManager - INFO - NuclideServerManager was created with these options: {'certs_dir': None, 'json_output_file': '/tmp/nuclide-sshhandshake-0.44609647241983597', 'timeout': 60, 'dump_core': True, 'insecure': True, 'inspect': False, 'quiet': False, 'debug': False, 'command': 'start', 'workspace': '/home/pokemad/pokemon', 'common_name': 'neoseo.es', 'port': None, 'verbose': False}
2017-06-25 04:11:05,882 - NuclideServerManager - INFO - Starting to clean up old Nuclide processes/files.
2017-06-25 04:11:05,902 - NuclideServerManager - INFO - Cleaning up old certificate files...
2017-06-25 04:11:05,904 - NuclideServerManager - INFO - Finished cleaning up old Nuclide processes/files.
2017-06-25 04:11:05,904 - root - WARNING - Failed to clean up old core dumps ([Errno 2] No such file or directory: '/var/tmp/cores')
2017-06-25 04:11:05,905 - NuclideServerManager - INFO - Trying to determine the port to use for Nuclide server...
2017-06-25 04:11:05,929 - NuclideServerManager - INFO - Found existing Nuclide server on port: 9091
2017-06-25 04:11:05,930 - NuclideServerManager - INFO - Initialized NuclideServer.
2017-06-25 04:11:05,957 - NuclideServerManager - INFO - A Nuclide server is already running.                           Running version: 232. Desired version: 232.
2017-06-25 04:11:05,958 - NuclideServerManager - INFO - Restarting Nuclide server on port 9091
2017-06-25 04:11:05,962 - NuclideServer - INFO - Stopped old Nuclide server on port 9091.
2017-06-25 04:11:05,962 - NuclideServerManager - INFO - Starting NuclideServer...
2017-06-25 04:11:05,963 - NuclideServerManager - INFO - Using http.
2017-06-25 04:11:05,963 - NuclideServer - INFO - NuclideServer start/restarting with the following arguments:
              timeout: 60
              cert:    None
              key:     None
              ca:      None
              force:   False
              quiet:   False
              debug:   False
              inspect: False
              expiration_days: None
2017-06-25 04:11:05,983 - NuclideServer - INFO - Opening node server subprocess.
2017-06-25 04:11:05,986 - NuclideServer - INFO - Trying to ping the Nuclide server...
2017-06-25 04:11:06,618 - NuclideServer - INFO - Attempted 6 pings.
2017-06-25 04:11:06,619 - NuclideServer - INFO - Verified Nuclide started on port 9091.
```

Nohup files are empty 😭 

### Stack Trace

Uncaught Error: Remote Error: Connection Closed processing message {"protocol":"service_framework3_rpc","type":"call","method":"FileSystemService/findNearestAncestorNamed","id":9,"args":{"fileName":".hhconfig","pathToDirectory":"/home/pokemad/pokemon"}}
"Error: Connection Closed\n  at _calls.forEach.call (C:\\Users\\Frisco\\.atom\\packages\\nuclide\\pkg\\nuclide-rpc\\lib\\RpcConnection.js:693:19)\n  at Map.forEach (native)\n  at RpcConnection.dispose (C:\\Users\\Frisco\\.atom\\packages\\nuclide\\pkg\\nuclide-rpc\\lib\\RpcConnection.js:692:17)\n  at ServerConnection.close (C:\\Users\\Frisco\\.atom\\packages\\nuclide\\pkg\\nuclide-remote-connection\\lib\\ServerConnection.js:261:20)\n  at C:\\Users\\Frisco\\.atom\\packages\\nuclide\\pkg\\nuclide-remote-connection\\lib\\ServerConnection.js:350:16\n  at undefined.next (<anonymous>:null:null)\n  at step (C:\\Users\\Frisco\\.atom\\packages\\nuclide\\node_modules\\async-to-generator\\async-to-generator.js:11:30)\n  at C:\\Users\\Frisco\\.atom\\packages\\nuclide\\node_modules\\async-to-generator\\async-to-generator.js:21:13\n  at process._tickCallback (internal/process/next_tick.js:103:7)\n"

```
At C:\Users\Frisco\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:23

Error: Connection Closed
  at _calls.forEach.call (/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:693:19)
  at Map.forEach (native)
  at RpcConnection.dispose (/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:692:17)
  at ServerConnection.close (/packages/nuclide/pkg/nuclide-remote-connection/lib/ServerConnection.js:261:20)
  at /packages/nuclide/pkg/nuclide-remote-connection/lib/ServerConnection.js:350:16
  at undefined.next (<anonymous>:null:null)
  at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
  at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:21:13
  at process._tickCallback (internal/process/next_tick.js:103:7)

```

### Commands

```
  2x -3:05.8.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always)
     -2:35.5.0 nuclide-diagnostics-ui:show-table (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:31.4.0 nuclide-diagnostics-ui:toggle-table (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:17 nuclide-ssh-tunnels-panel:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:58.6.0 nuclide-remote-projects:connect (ul.list-inline.tab-bar.inset-panel)
     -1:31 core:delete (input.hidden-input)
     -1:21.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
autocomplete-python 1.9.1 
busy-signal 1.4.3 
file-icons 2.1.7 
highlight-selected 0.13.1 
hyperclick 0.0.40 
intentions 1.1.2 
kite 0.28.1 
linter 2.2.0 
linter-ui-default 1.6.2 
minimap 4.28.2 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-pigments 0.2.2 
nuclide 0.232.0 
open-recent 5.0.0 
pigments 0.39.1 
project-manager 3.3.5 
python-indent 1.0.3 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by friscoMad** [comment]
After some more findings it turned out that there is an incompatibility with Open Recent package and the exception shown on Console Dev is:

```
[2017-06-26T14:52:47.526Z] [ERROR] nuclide-remote-connection - SshHandshake failed: SERVER_CANNOT_CONNECT, Connection check failed Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
  at Minimatch.match (C:\Users\Frisco\AppData\Local\atom\app-1.18.0\resources\app\node_modules\settings-view\node_modules\minimatch\minimatch.js:702:10)
  at minimatch (C:\Users\Frisco\AppData\Local\atom\app-1.18.0\resources\app\node_modules\settings-view\node_modules\minimatch\minimatch.js:99:42)
  at C:\Users\Frisco\.atom\packages\open-recent\lib\main.coffee:173:18
  at Array.some (native)
  at OpenRecent.filterPath (C:\Users\Frisco\.atom\packages\open-recent\lib\main.coffee:172:41)
  at OpenRecent.insertCurrentPaths (C:\Users\Frisco\.atom\packages\open-recent\lib\main.coffee:188:20)
  at OpenRecent.onProjectPathChange (C:\Users\Frisco\.atom\packages\open-recent\lib\main.coffee:53:6)
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63096:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63212:34)
  at Project.module.exports.Project.addPath (<embedded>:22118:35)
  at addRemoteFolderToProject (C:\Users\Frisco\.atom\packages\nuclide\pkg\nuclide-remote-projects\lib\main.js:284:16)
  at subscriptions.add.RemoteConnection.onDidAddRemoteConnection.connection (C:\Users\Frisco\.atom\packages\nuclide\pkg\nuclide-remote-projects\lib\main.js:445:23)
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63096:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63212:34)
  at C:\Users\Frisco\.atom\packages\nuclide\pkg\nuclide-remote-connection\lib\RemoteConnection.js:193:35
  at undefined.next (<anonymous>:null:null)
  at step (C:\Users\Frisco\.atom\packages\nuclide\node_modules\async-to-generator\async-to-generator.js:11:30)
  at C:\Users\Frisco\.atom\packages\nuclide\node_modules\async-to-generator\async-to-generator.js:21:13
  at process._tickCallback (internal/process/next_tick.js:103:7)
```

Disabling Open Recent package was enough to get it working

**Comment by tjaklitsch** [comment]
@friscoMad thank you.

**Comment by jgebhardt** [comment]
`open-recent` likely does not understand remote URLs.
