### ISSUE TITLE
Uncaught Invariant Violation: Minified React error #119; visit http://facebook.github.io/react/do...

### ISSUE THREAD

**Issue by hmeerlo** [facebook/nuclide#1218]
[Enter steps to reproduce:]

1. Try to create a new Folder in existing folder using right mouse button New -> Folder
2. Dialog for Folder name appears but dooesn't accept any input, error already triggered

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.232.0

### Stack Trace

Uncaught Invariant Violation: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

```
At /Users/hermanmeerlo/.atom/packages/nuclide/node_modules/react/lib/reactProdInvariant.js:36

Invariant Violation: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
  at reactProdInvariant (/packages/nuclide/node_modules/react/lib/reactProdInvariant.js:32:15)
  at Object.addComponentAsRefTo (/packages/nuclide/node_modules/react/lib/ReactOwner.js:69:358)
  at attachRef (/packages/nuclide/node_modules/react/lib/ReactRef.js:23:16)
  at Object.ReactRef.attachRefs (/packages/nuclide/node_modules/react/lib/ReactRef.js:42:5)
  at ReactCompositeComponentWrapper.attachRefs (/packages/nuclide/node_modules/react/lib/ReactReconciler.js:24:12)
  at CallbackQueue.notifyAll (/packages/nuclide/node_modules/react/lib/CallbackQueue.js:67:22)
  at ReactReconcileTransaction.close (/packages/nuclide/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
  at ReactReconcileTransaction.closeAll (/packages/nuclide/node_modules/react/lib/Transaction.js:204:25)
  at ReactReconcileTransaction.perform (/packages/nuclide/node_modules/react/lib/Transaction.js:151:16)
  at batchedMountComponentIntoNode (/packages/nuclide/node_modules/react/lib/ReactMount.js:127:15)
  at ReactDefaultBatchingStrategyTransaction.perform (/packages/nuclide/node_modules/react/lib/Transaction.js:138:20)
  at Object.batchedUpdates (/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/packages/nuclide/node_modules/react/lib/ReactUpdates.js:98:20)
  at Object._renderNewRootComponent (/packages/nuclide/node_modules/react/lib/ReactMount.js:321:18)
  at Object._renderSubtreeIntoContainer (/packages/nuclide/node_modules/react/lib/ReactMount.js:402:32)
  at Object.render (/packages/nuclide/node_modules/react/lib/ReactMount.js:423:23)
  at FileSystemActions._openDialog (/packages/nuclide/pkg/nuclide-file-tree/lib/FileSystemActions.js:350:41)
  at FileSystemActions._openAddDialog (/packages/nuclide/pkg/nuclide-file-tree/lib/FileSystemActions.js:329:10)
  at FileSystemActions.openAddFolderDialog (/packages/nuclide/pkg/nuclide-file-tree/lib/FileSystemActions.js:79:10)
  at /packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeController.js:157:67)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (<embedded>:18901:35)
  at CommandRegistry.handleCommandEvent (<embedded>:18639:65)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (<embedded>:18802:25)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (<embedded>:1554:34)
  at EventEmitter.outerCallback (<embedded>:2012:31)
  at emitThree (events.js:116:13)
  at EventEmitter.emit (events.js:194:7)

```

### Commands

```
  2x -0:36.8.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:18.5.0 nuclide-file-tree:add-folder (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory)
     -0:16.9.0 nuclide-file-tree:clear-filter (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:14.9.0 fuzzy-finder:toggle-file-finder (atom-pane.pane)
     -0:14.2.0 editor:consolidate-selections (input.hidden-input)
     -0:14.2.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.8 
git-blame 1.1.1 
git-plus 7.9.3 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.66.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
local-history 4.3.0 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.232.0 
nuclide-format-js 0.0.36 
prettier-atom 0.34.0 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by mostafaeweda** [comment]
I see you're using an old nuclide version, please update to the latest and re-open if that's still the case

**Comment by hmeerlo** [comment]
For me 0.232.0 is the latest version, there is no update available.

**Comment by mostafaeweda** [comment]
I just released 0.236.0 today

**Comment by hmeerlo** [comment]
Ok, then there is a problem with the update mechanism on my side. I just checked the releases and I should also have seen 0.233.0 and 0.234.0 but Atom still says that there are no updates for me (0.232.0).
![screen shot 2017-06-29 at 08 22 45](https://user-images.githubusercontent.com/448150/27674079-6526efb8-5ca4-11e7-8600-ab2288bb7afc.png)

**Comment by mostafaeweda** [comment]
Ooops, I missed the `apm publish` piece of the release. It should now be available.

**Comment by hmeerlo** [comment]
Please re-open, this still occurs on 0.236.0

**Comment by shail** [comment]
```
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.236.0

Stack Trace

Uncaught Invariant Violation: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.


At /Users/shail/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43

Invariant Violation: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
  at reactProdInvariant (/packages/nuclide/node_modules/react/lib/reactProdInvariant.js:32:15)
  at Object.addComponentAsRefTo (/packages/nuclide/node_modules/react/lib/ReactOwner.js:69:358)
  at attachRef (/packages/nuclide/node_modules/react/lib/ReactRef.js:23:16)
  at Object.ReactRef.attachRefs (/packages/nuclide/node_modules/react/lib/ReactRef.js:42:5)
  at ReactDOMComponent.attachRefs (/packages/nuclide/node_modules/react/lib/ReactReconciler.js:24:12)
  at CallbackQueue.notifyAll (/packages/nuclide/node_modules/react/lib/CallbackQueue.js:67:22)
  at ReactReconcileTransaction.close (/packages/nuclide/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
  at ReactReconcileTransaction.closeAll (/packages/nuclide/node_modules/react/lib/Transaction.js:204:25)
  at ReactReconcileTransaction.perform (/packages/nuclide/node_modules/react/lib/Transaction.js:151:16)
  at ReactUpdatesFlushTransaction.perform (/packages/nuclide/node_modules/react/lib/Transaction.js:138:20)
  at ReactUpdatesFlushTransaction.perform (/packages/nuclide/node_modules/react/lib/ReactUpdates.js:90:38)
  at Object.flushBatchedUpdates (/packages/nuclide/node_modules/react/lib/ReactUpdates.js:173:19)
  at ReactDefaultBatchingStrategyTransaction.closeAll (/packages/nuclide/node_modules/react/lib/Transaction.js:204:25)
  at ReactDefaultBatchingStrategyTransaction.perform (/packages/nuclide/node_modules/react/lib/Transaction.js:151:16)
  at Object.batchedUpdates (/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.enqueueUpdate (/packages/nuclide/node_modules/react/lib/ReactUpdates.js:201:22)
  at enqueueUpdate (/packages/nuclide/node_modules/react/lib/ReactUpdateQueue.js:25:16)
  at Object.enqueueForceUpdate (/packages/nuclide/node_modules/react/lib/ReactUpdateQueue.js:158:5)
  at FileTreeSidebarComponent.ReactComponent.forceUpdate (/packages/nuclide/node_modules/react/lib/ReactComponent.js:85:16)
  at FileTreeSidebarComponent._processExternalUpdate (/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:450:12)
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63093:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63209:34)
  at /packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:583:21)
  at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43:337)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:42:227)
  at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
  at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
  at requestAnimationFrame (/packages/nuclide/modules/nuclide-commons/observable.js:296:14)

```

### Commands

```
  2x -1:25.2.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always)
     -0:44.2.0 application:open (ul.list-inline.tab-bar.inset-panel)
     -0:35.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-ternjs 0.18.3 
atom-typescript 11.0.3 
autoclose-html 0.23.0 
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
color-picker 2.2.5 
docblockr 0.10.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.6 
flow-ide 1.4.2 
git-blame 1.1.1 
git-history 3.3.0 
highlight-selected 0.13.1 
hyperclick 0.0.40 
javascript-snippets 1.2.1 
js-hyperclick 1.11.0 
language-babel 2.62.0 
language-docker 1.1.7 
language-postcss 1.3.1 
linter 2.1.4 
linter-eslint 8.2.1 
linter-jsonlint 1.3.0 
linter-shellcheck 1.4.4 
linter-stylelint 3.10.0 
nuclide 0.236.0 
open-in-browser 0.5.0 
open-recent 5.0.0 
pigments 0.39.1 
prettier-atom 0.31.1 
react 0.16.2 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
todo-show 1.11.0 
vim-mode-plus 0.92.1 
zentabs 0.8.8 
```

**Comment by macrozone** [comment]
Issue arised after updating to 0.250.0. i can't work anymore, need to downgrade

**Comment by PointedEars** [comment]
Same here, reproducible.

1. Context-click on folder in Nuclide “Folders” pane.
2. Select “New” → “File”.

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Debian GNU/Linux
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.250.0


### Stack Trace

Uncaught Invariant Violation: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

```
At /home/pelinux/.atom/packages/nuclide/node_modules/react/lib/reactProdInvariant.js:36

Invariant Violation: Minified React error #119; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=119 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (/packages/nuclide/node_modules/react/lib/reactProdInvariant.js:32:15)
    at Object.addComponentAsRefTo (/packages/nuclide/node_modules/react/lib/ReactOwner.js:69:358)
    at attachRef (/packages/nuclide/node_modules/react/lib/ReactRef.js:23:16)
    at Object.ReactRef.attachRefs (/packages/nuclide/node_modules/react/lib/ReactRef.js:42:5)
    at ReactCompositeComponentWrapper.attachRefs (/packages/nuclide/node_modules/react/lib/ReactReconciler.js:24:12)
    at CallbackQueue.notifyAll (/packages/nuclide/node_modules/react/lib/CallbackQueue.js:67:22)
    at ReactReconcileTransaction.close (/packages/nuclide/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.closeAll (/packages/nuclide/node_modules/react/lib/Transaction.js:204:25)
    at ReactReconcileTransaction.perform (/packages/nuclide/node_modules/react/lib/Transaction.js:151:16)
    at batchedMountComponentIntoNode (/packages/nuclide/node_modules/react/lib/ReactMount.js:127:15)
    at ReactDefaultBatchingStrategyTransaction.perform (/packages/nuclide/node_modules/react/lib/Transaction.js:138:20)
    at Object.batchedUpdates (/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (/packages/nuclide/node_modules/react/lib/ReactUpdates.js:98:20)
    at Object._renderNewRootComponent (/packages/nuclide/node_modules/react/lib/ReactMount.js:321:18)
    at Object._renderSubtreeIntoContainer (/packages/nuclide/node_modules/react/lib/ReactMount.js:402:32)
    at Object.render (/packages/nuclide/node_modules/react/lib/ReactMount.js:423:23)
    at FileSystemActions._openDialog (/packages/nuclide/pkg/nuclide-file-tree/lib/FileSystemActions.js:451:41)
    at FileSystemActions._openAddDialog (/packages/nuclide/pkg/nuclide-file-tree/lib/FileSystemActions.js:430:10)
    at FileSystemActions._openAddFileDialogImpl (/packages/nuclide/pkg/nuclide-file-tree/lib/FileSystemActions.js:144:10)
    at FileSystemActions.openAddFileDialog (/packages/nuclide/pkg/nuclide-file-tree/lib/FileSystemActions.js:117:17)
    at /packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeController.js:166:67)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:44.1.0 intentions:highlight (input.hidden-input)
  4x -4:38.5.0 click (span.syntax--variable.syntax--other.syntax--constant.syntax--js)
     -4:30.9.0 core:move-left (input.hidden-input)
     -4:30.5.0 core:move-right (input.hidden-input)
     -4:30.1.0 intentions:highlight (input.hidden-input)
  3x -4:19.4.0 click (div.title.icon.icon-tools)
     -4:14.6.0 core:select-all (input.hidden-input)
     -4:12.2.0 key-binding-resolver:toggle (input.hidden-input)
 10x -4:08.0 click (div.body)
     -3:17.7.0 core:select-all (input.hidden-input)
  9x -3:14.2.0 click (div.meta)
     -2:38.7.0 core:select-all (input.hidden-input)
  9x -2:28 click (h4.card-name)
     -1:22.1.0 nuclide-file-tree:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-compact.seti-icons.seti-animate.theme-lcars-syntax.theme-seti-ui)
     -1:04.5.0 nuclide-file-tree:add-file (div.header.list-item)
  8x -1:00.5.0 click (div.description.fatal-notification)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-css-unit-converter 1.1.1 
atom-mysql-snippets 0.3.1 
atom-php-navigation 0.6.0 
atom-ternjs 0.18.3 
atom-x 0.4.0 
atomatigit 1.5.5 
autoclose-html 0.23.0 
autocomplete-awk 0.1.2 
autocomplete-bibtex 0.7.0 
autocomplete-clang 0.11.3 
autocomplete-html-entities 0.1.0 
autocomplete-paths 2.11.0 
autocomplete-php 0.3.7 
autocomplete-python 1.10.2 
autocomplete-xml 0.9.4 
autoupdate-packages 1.3.1 
block-comment 0.4.3 
busy-signal 1.4.3 
character-table 0.4.3 
clipboard-plus 0.5.1 
color-picker 2.2.5 
column-select 0.2.0 
compare-files 0.8.1 
css-snippets 1.1.0 
ctrl-last-tab 0.3.0 
data-atom 0.25.2 
docblockr 0.11.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
es6-javascript 1.0.0 
ex-mode 0.18.0 
filesize 3.0.0 
fixmyjs 1.4.1 
fold-comments 0.6.0 
git-blame 1.2.2 
git-clone 0.2.0 
git-control 0.9.0 
git-diff-details 1.4.0 
git-difftool 0.2.7 
git-go 1.0.5 
git-hide 1.0.0 
git-history 3.3.0 
git-log 0.4.1 
git-plus 7.9.3 
git-rebase 0.1.1 
git-status 0.3.4 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
goto 1.8.3 
goto-definition 1.3.4 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
hyperclick-php 0.2.1 
indent-toggle-on-paste 0.1.3 
intentions 1.1.5 
iso8601-timestamp 0.1.1 
javascript-snippets 1.2.1 
js-hyperclick 1.11.0 
js-refactor 0.7.5 
language-apache 1.7.0 
language-awk 0.1.12 
language-babel 2.74.1 
language-diff 0.7.0 
language-gettext 0.6.1 
language-ini 1.19.0 
language-latex 1.1.1 
language-lua 0.9.11 
language-sql-mysql 0.3.1 
language-swift 0.5.0 
latex-autocomplete 1.0.0 
latex-completions 0.3.3 
latex-friend 0.0.11 
latex-hyperclick 0.2.0 
latexer 0.3.0 
latextools 0.8.5 
lcars-syntax 0.0.1 
less-autocompile 1.0.0 
less-than-slash 0.17.0 
line-count-status 0.0.3 
line-jumper 0.14.1 
linter 2.2.0 
linter-checkbashisms 0.1.5 
linter-chktex 1.3.1 
linter-csslint 2.0.0 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-less 2.6.0 
linter-mixed-indent 1.1.0 
linter-mypy 2.2.0 
linter-php 1.4.0 
linter-pylint 2.1.0 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.8 
linter-xmllint 1.4.3 
local-history 4.3.0 
MagicPython 1.0.12 
man 0.8.2 
merge-conflicts 1.4.5 
method-separator 0.2.0 
minimap 4.29.6 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
multi-cursor 2.1.5 
multi-cursor-plus 1.2.0 
multi-file-open 0.1.1 
multirow-tabs 0.3.3 
navigate 0.1.17 
navigate-indent 0.1.0 
next-occurrence 0.5.0 
nuclide 0.250.0 
nuclide-format-js 0.0.41 
open-git-modified-files 0.2.4 
open-recent 5.0.0 
open-this 0.4.0 
pdf-view 0.59.0 
php-debug 0.2.5 
php-extract-method 0.2.1 
php-getters-setters 0.5.5 
pigments 0.40.2 
platformio-ide-terminal 2.6.0 
preview 0.17.0 
preview-inline 1.4.7 
project-folder 1.5.0 
project-view 0.6.2 
promote-folder-to-project 2.0.1 
punchclock 0.6.5 
python-isort 0.0.7 
python-tools 0.6.9 
qolor 0.4.2 
quantum-shell 0.7.1 
quick-query 0.11.2 
recent-projects 0.13.1 
refactor 0.11.5 
regex-tester 0.2.0 
remember-file-positions 0.2.3 
remote-edit 1.9.0 
revert-buffer 0.5.0 
script 3.15.0 
set-syntax 0.3.2 
seti-ui 1.9.0 
show-origin 0.2.0 
sloc 1.1.0 
sort-lines 0.15.0 
split-diff 1.5.1 
switch-header-source 0.22.1 
symbols-tree-nav 0.15.5 
symbols-tree-view 0.14.0 
term 0.2.4 
text-manipulation 0.6.0 
todo-show 2.0.0 
tool-bar 1.1.0 
tree-view-git-status 1.4.0 
up2date 0.1.2 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 1.3.3 
w3c-validation 0.4.0 
wordcount 2.10.4 
xkcd-comics 0.3.0 
xml-tools 0.2.1 
Zen 0.18.0 
```

**Comment by PointedEars** [comment]
**Problem does not occur anymore** with Atom 1.20.0, Nuclide 0.252.0. Thanks :smile:
