### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by hypno2000** [facebook/nuclide#1219]
[Enter steps to reproduce:]

1. save any file or open any file

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.232.0

### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/range.js:33

TypeError: Cannot read property 'start' of undefined
  at Function.module.exports.Range.fromObject (<embedded>:71622:37)
  at linterMessageV2ToDiagnosticMessage (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/LinterAdapter.js:132:24)
  at linterMessagesToDiagnosticUpdate (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/LinterAdapter.js:148:56)
  at IndieLinterDelegate.setAllMessages (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/IndieLinterRegistry.js:70:103)
  at ErrorPusher.pushErrors.lodash_1.debounce (/packages/atom-typescript/dist/main/errorPusher.js:30:29)
  at invokeFunc (/packages/docker/node_modules/lodash/lodash.js:10350:23)
  at trailingEdge (/packages/docker/node_modules/lodash/lodash.js:10397:18)
  at timerExpired (/packages/docker/node_modules/lodash/lodash.js:10385:18)

```

### Commands

```
     -6:44.7.0 core:save (input.hidden-input)
  2x -6:40.7.0 core:backspace (input.hidden-input)
     -6:37.8.0 core:save (input.hidden-input)
     -5:53.8.0 editor:toggle-line-comments (input.hidden-input)
  4x -5:51.6.0 core:undo (input.hidden-input)
  2x -5:48.7.0 core:backspace (input.hidden-input)
     -5:43.7.0 core:save (input.hidden-input)
  2x -5:38.1.0 editor:newline (input.hidden-input)
  2x -5:26.7.0 core:backspace (input.hidden-input)
 16x -5:25.8.0 core:save (input.hidden-input)
     -2:14.3.0 settings-view:open (input.hidden-input)
  5x -1:59.5.0 core:close (div.panels-item)
     -1:49.8.0 core:save (input.hidden-input)
     -1:48.4.0 settings-view:open (input.hidden-input)
     -1:43.9.0 core:confirm (input.hidden-input)
     -1:34.9.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-typescript 11.0.4 
blame 0.12.0 
busy-signal 1.4.3 
docker 0.7.0 
editorconfig 2.2.2 
ex-mode 0.15.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.2 
language-docker 1.1.8 
language-elixir 0.19.0 
language-protobuf 0.7.1 
linter 2.2.0 
linter-tslint 1.6.0 
linter-ui-default 1.6.2 
minimap 4.28.2 
monokai-seti 0.9.0 
nuclide 0.232.0 
react 0.16.2 
seti-syntax 1.1.3 
seti-ui 1.9.0 
shebang-set-grammar 0.6.0 
vim-mode-plus 0.93.0 
```

**Comment by mostafaeweda** [comment]
I see you're using an older version of nuclide - please update and see if that's still the case.
If so, please re-open
