### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by hmeerlo** [facebook/nuclide#1220]
[Enter steps to reproduce:]

1. CMD-T to try and open a class file
2. nothing happened, instead this error came

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.232.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At /Users/hermanmeerlo/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:164

TypeError: Cannot read property 'getText' of undefined
  at process.nextTick (/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:164:43)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)

```

### Commands

```
     -2:28.7.0 core:delete (input.hidden-input)
     -2:28.2.0 core:move-down (input.hidden-input)
     -2:27.4.0 core:save (input.hidden-input)
     -0:29.5.0 nuclide-quick-open:find-anything-via-omni-search (input.hidden-input)
     -0:26 autocomplete-plus:cancel (input.hidden-input)
     -0:25.6.0 editor:consolidate-selections (input.hidden-input)
     -0:25.6.0 core:cancel (input.hidden-input)
     -0:25.4.0 editor:consolidate-selections (input.hidden-input)
     -0:25.4.0 core:cancel (input.hidden-input)
     -0:24.8.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:23.8.0 editor:consolidate-selections (input.hidden-input)
     -0:23.8.0 core:cancel (input.hidden-input)
     -0:22.8.0 nuclide-quick-open:find-anything-via-omni-search (input.hidden-input)
     -0:20.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:19.9.0 editor:consolidate-selections (input.hidden-input)
     -0:19.9.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.8 
git-blame 1.1.1 
git-plus 7.9.3 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.66.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
local-history 4.3.0 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.232.0 
nuclide-format-js 0.0.36 
prettier-atom 0.34.0 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by mostafaeweda** [comment]
You seem to be on an older version of nuclide - please update to the latest & re-open if that's still happening
