### ISSUE TITLE
Uncaught Invariant Violation: Minified React error #34; visit http://facebook.github.io/react/doc...

### ISSUE THREAD

**Issue by huogh** [facebook/nuclide#1232]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.236.0

### Stack Trace

Uncaught Invariant Violation: Minified React error #34; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=34 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

```
At /Users/huoguanghua/.atom/packages/nuclide/node_modules/react/lib/reactProdInvariant.js:36

Invariant Violation: Minified React error #34; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=34 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at reactProdInvariant (/packages/nuclide/node_modules/react/lib/reactProdInvariant.js:32:15)
    at Object.getNodeFromInstance (/packages/nuclide/node_modules/react/lib/ReactDOMComponentTree.js:166:144)
    at Object.extractEvents (/packages/nuclide/node_modules/react/lib/ChangeEventPlugin.js:288:57)
    at Object.extractEvents (/packages/nuclide/node_modules/react/lib/EventPluginHub.js:196:46)
    at /packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:28:33)
    at handleTopLevelImpl (/packages/nuclide/node_modules/react/lib/ReactEventListener.js:73:24)
    at ReactDefaultBatchingStrategyTransaction.perform (/packages/nuclide/node_modules/react/lib/Transaction.js:138:20)
    at Object.batchedUpdates (/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (/packages/nuclide/node_modules/react/lib/ReactUpdates.js:98:20)
    at dispatchEvent (/packages/nuclide/node_modules/react/lib/ReactEventListener.js:150:20)
```

### Commands

```
  5x -1:43.4.0 core:close (input.hidden-input)
     -0:51.1.0 editor:newline (input.hidden-input)
  3x -0:50.6.0 core:backspace (input.hidden-input)
  2x -0:49.4.0 editor:newline (input.hidden-input)
     -0:45.8.0 core:backspace (input.hidden-input)
     -0:42.9.0 autocomplete-plus:confirm (input.hidden-input)
     -0:42.9.0 snippets:expand (atom-text-editor.editor.is-focused)
  2x -0:42.1.0 core:undo (input.hidden-input)
     -0:40.9.0 core:backspace (input.hidden-input)
     -0:39.6.0 core:move-right (input.hidden-input)
     -0:37.8.0 editor:newline (input.hidden-input)
  2x -0:36.5.0 core:backspace (input.hidden-input)
     -0:32.4.0 core:move-right (input.hidden-input)
     -0:31.7.0 core:save (input.hidden-input)
     -0:26.7.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:25.2.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-runner 2.7.1 
atom-terminal-panel 4.4.4 
atom-ternjs 0.18.3 
autocomplete-webpack 0.8.0 
emmet 2.4.3 
node-debugger 1.10.1 
nuclide 0.236.0 
platformio-ide-terminal 2.5.3 
script 3.15.0 
```

**Comment by rightparen** [comment]
@huogh if this is something that you can reproduce consistently, could you provide repro steps?  The stack trace is just async React code so it's hard to tell where the problem might be.  From the "Commands" list it looks like you might have been opening the debugger at the time--is this correct?  If so, are there any more specifics you can provide?

**Comment by louismartin** [comment]
The steps to repro for me are:
1) Open the debugger
2) Restart the debugger clicking on the refresh button at the top left of the debugger.

```
Invariant Violation: Minified React error #34; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=34 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
  at reactProdInvariant (/opt/facebook/nuclide/0.236.63305782/nuclide/node_modules/react/lib/reactProdInvariant.js:32:15)
  at Object.getNodeFromInstance (/opt/facebook/nuclide/0.236.63305782/nuclide/node_modules/react/lib/ReactDOMComponentTree.js:166:144)
  at Object.extractEvents (/opt/facebook/nuclide/0.236.63305782/nuclide/node_modules/react/lib/ChangeEventPlugin.js:288:57)
  at Object.extractEvents (/opt/facebook/nuclide/0.236.63305782/nuclide/node_modules/react/lib/EventPluginHub.js:196:46)
  at Object.handleTopLevel [as _handleTopLevel] (/opt/facebook/nuclide/0.236.63305782/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:28:33)
  at handleTopLevelImpl (/opt/facebook/nuclide/0.236.63305782/nuclide/node_modules/react/lib/ReactEventListener.js:73:24)
  at ReactDefaultBatchingStrategyTransaction.perform (/opt/facebook/nuclide/0.236.63305782/nuclide/node_modules/react/lib/Transaction.js:138:20)
  at Object.batchedUpdates (/opt/facebook/nuclide/0.236.63305782/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/opt/facebook/nuclide/0.236.63305782/nuclide/node_modules/react/lib/ReactUpdates.js:98:20)
  at dispatchEvent (/opt/facebook/nuclide/0.236.63305782/nuclide/node_modules/react/lib/ReactEventListener.js:150:20)
```
