### ISSUE TITLE
Linux installation problem

### ISSUE THREAD

**Issue by Hakit** [facebook/nuclide#124]
Hello, I am on Ubuntu 15.04 and I have recently pulled the repo, the update has not worked. So I have removed the repo from my disk and "re-pulled" it (I have also delete all *nuclide-\** in .atom)

But now when I do `./scripts/dev/setup`

```
START INSTALL: 2015-07-03 10:34:26.794527
Installing dependencies for Node package nuclide-node-transpiler...
Installing dependencies for Node package nuclide-atom-interfaces...
Done installing dependencies for nuclide-atom-interfaces
Installing dependencies for Node package nuclide-keytar-wrapper...
Error running ['npm', 'install'] in /home/mark/bin/nuclide/pkg/nuclide/node-transpiler
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/dev/../lib/package_manager.py", line 314, in install_dependencies
    npm.install(src_path, local_packages=package_config['localDependencies'], include_dev_dependencies=package_config['includeDevDependencies'])
  File "./scripts/dev/../lib/npm.py", line 49, in install
    self._npm_install(package_root, include_dev_dependencies)
  File "./scripts/dev/../lib/npm.py", line 55, in _npm_install
    self._execute(npm_command, cwd=package_root)
  File "./scripts/dev/../lib/npm.py", line 85, in _execute
    output = fs.cross_platform_check_output(cmd_args, cwd=cwd, stderr=devnull)
  File "./scripts/dev/../lib/fs.py", line 89, in cross_platform_check_output
    raise subprocess.CalledProcessError(returncode, cmd_args, output=stdout)
CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 236
Traceback (most recent call last):
  File "./scripts/dev/setup", line 44, in <module>
    package_manager.install_dependencies(npm, include_packages_that_depend_on_atom=include_apm)
  File "./scripts/dev/../lib/package_manager.py", line 46, in install_dependencies
    installer.install()
  File "./scripts/dev/../lib/package_manager.py", line 151, in install
    self._do_multiprocess_install()
  File "./scripts/dev/../lib/package_manager.py", line 198, in _do_multiprocess_install
    (config['name'], exitcode))
Exception: Installing package nuclide-node-transpiler failed with exit code 1
Done installing dependencies for nuclide-keytar-wrapper
```

And when the verbose mode is activated:

```
START INSTALL: 2015-07-03 10:40:31.675318
Including package: nuclide-node-transpiler
Including package: nuclide-jasmine
Including package: nuclide-test-helpers
Including package: nuclide-commons
Including package: nuclide-atom-interfaces
Including package: nuclide-atom-npm
Including package: nuclide-ui-tabs
Including package: nuclide-logging
Including package: nuclide-ui-radiogroup
Including package: nuclide-version
Including package: nuclide-buck-base
Including package: nuclide-remote-uri
Including package: nuclide-flow-base
Including package: nuclide-watchman-helpers
Including package: nuclide-hg-repository-base
Including package: nuclide-debugger-hhvm-proxy
Including package: nuclide-service-transformer
Including package: nuclide-remote-search
Including package: nuclide-arcanist-base
Including package: nuclide-hack-common
Including package: nuclide-task
Including package: nuclide-path-search
Including package: nuclide-clang
Including package: nuclide-source-control-helpers
Including package: nuclide-server
Including package: nuclide-remote-connection
Including package: nuclide-atom-helpers
Including package: nuclide-client
Including package: nuclide-ui-atom-input
Including package: nuclide-ssh-dialog
Including package: nuclide-arcanist-client
Including package: nuclide-flow
Including package: nuclide-hg-repository-client
Including package: nuclide-hg-repository
Including package: nuclide-keytar-wrapper
Including package: nuclide-remote-projects
Including package: nuclide-ui-atom-combo-box
Including package: nuclide-service-hub-plus
Including package: nuclide-buck-toolbar
Including package: nuclide-ui-tree
Including package: nuclide-type-hint
Including package: nuclide-ui-checkbox
Including package: nuclide-hg-git-bridge
Including package: nuclide-installer-base
Including package: nuclide-installer
Including package: nuclide-panel
Including package: nuclide-phabricator-comments
Including package: nuclide-diff-view
Including package: nuclide-hack
Including package: nuclide-file-watcher
Including package: nuclide-code-format
Including package: nuclide-analytics
Including package: nuclide-language-hack
Including package: nuclide-quick-open
Including package: hyperclick
Including package: nuclide-file-tree
Installing dependencies for Node package nuclide-node-transpiler...
Installing dependencies for Node package nuclide-atom-interfaces...
npm WARN package.json nuclide-atom-interfaces@0.0.0 No license field.

Done installing dependencies for nuclide-atom-interfaces
Installing dependencies for Node package nuclide-keytar-wrapper...
npm WARN package.json nuclide-keytar-wrapper@0.0.0 No README data
npm WARN package.json nuclide-keytar-wrapper@0.0.0 No license field.

Done installing dependencies for nuclide-keytar-wrapper
Installing dependencies for Node package nuclide-service-hub-plus...
npm WARN package.json nuclide-service-hub-plus@0.0.0 No README data
npm WARN package.json nuclide-service-hub-plus@0.0.0 No license field.

Done installing dependencies for nuclide-service-hub-plus
Installing dependencies for Atom package nuclide-type-hint...
npm WARN package.json nuclide-type-hint@0.0.0 No README data
npm WARN package.json nuclide-type-hint@0.0.0 No license field.

Done installing dependencies for nuclide-type-hint
Running `apm link /home/mark/bin/nuclide/pkg/nuclide/type-hint`...
Done linking nuclide-type-hint
Installing dependencies for Atom package nuclide-language-hack...
npm WARN package.json nuclide-language-hack@0.0.0 No license field.

Done installing dependencies for nuclide-language-hack
Running `apm link /home/mark/bin/nuclide/pkg/nuclide/language-hack`...
Done linking nuclide-language-hack
Installing dependencies for Atom package hyperclick...
npm WARN package.json hyperclick@0.0.0 No license field.
react-for-atom@0.13.6 node_modules/react-for-atom
└── react@0.13.2 (envify@3.4.0)

Done installing dependencies for hyperclick
Running `apm link /home/mark/bin/nuclide/pkg/nuclide/hyperclick`...
Done linking hyperclick
Error running ['npm', 'install'] in /home/mark/bin/nuclide/pkg/nuclide/node-transpiler
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/dev/../lib/package_manager.py", line 314, in install_dependencies
    npm.install(src_path, local_packages=package_config['localDependencies'], include_dev_dependencies=package_config['includeDevDependencies'])
  File "./scripts/dev/../lib/npm.py", line 49, in install
    self._npm_install(package_root, include_dev_dependencies)
  File "./scripts/dev/../lib/npm.py", line 55, in _npm_install
    self._execute(npm_command, cwd=package_root)
  File "./scripts/dev/../lib/npm.py", line 81, in _execute
    output = fs.cross_platform_check_output(cmd_args, cwd=cwd, stderr=subprocess.STDOUT)
  File "./scripts/dev/../lib/fs.py", line 89, in cross_platform_check_output
    raise subprocess.CalledProcessError(returncode, cmd_args, output=stdout)
CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 236
Traceback (most recent call last):
  File "./scripts/dev/setup", line 44, in <module>
    package_manager.install_dependencies(npm, include_packages_that_depend_on_atom=include_apm)
  File "./scripts/dev/../lib/package_manager.py", line 46, in install_dependencies
    installer.install()
  File "./scripts/dev/../lib/package_manager.py", line 151, in install
    self._do_multiprocess_install()
  File "./scripts/dev/../lib/package_manager.py", line 198, in _do_multiprocess_install
    (config['name'], exitcode))
Exception: Installing package nuclide-node-transpiler failed with exit code 1
```

**Comment by bolinfest** [comment]
What happens if you run 'npm install' from the nuclide/node-transpiler package after running setup?

**Comment by Hakit** [comment]
Thanks @bolinfest It has worked, package installed, but I have had also another error (with another package).

```
Error running ['npm', 'install'] in /home/mark/bin/nuclide/pkg/nuclide/task
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/dev/../lib/package_manager.py", line 314, in install_dependencies
    npm.install(src_path, local_packages=package_config['localDependencies'], include_dev_dependencies=package_config['includeDevDependencies'])
  File "./scripts/dev/../lib/npm.py", line 49, in install
    self._npm_install(package_root, include_dev_dependencies)
  File "./scripts/dev/../lib/npm.py", line 55, in _npm_install
    self._execute(npm_command, cwd=package_root)
  File "./scripts/dev/../lib/npm.py", line 85, in _execute
    output = fs.cross_platform_check_output(cmd_args, cwd=cwd, stderr=devnull)
  File "./scripts/dev/../lib/fs.py", line 89, in cross_platform_check_output
    raise subprocess.CalledProcessError(returncode, cmd_args, output=stdout)
CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./scripts/dev/setup", line 44, in <module>
    package_manager.install_dependencies(npm, include_packages_that_depend_on_atom=include_apm)
  File "./scripts/dev/../lib/package_manager.py", line 46, in install_dependencies
    installer.install()
  File "./scripts/dev/../lib/package_manager.py", line 151, in install
    self._do_multiprocess_install()
  File "./scripts/dev/../lib/package_manager.py", line 198, in _do_multiprocess_install
    (config['name'], exitcode))
Exception: Installing package nuclide-task failed with exit code 1
Done installing dependencies for nuclide-service-transformer
```

So I have test the method (npm install in /pkg/nuclide/task) and..

```
module.js:336
    throw err;
          ^
Error: Cannot find module './sync.js'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/mark/.nvm/versions/io.js/v2.3.1/lib/node_modules/npm/node_modules/rimraf/node_modules/glob/glob.js:50:16)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
```
