### ISSUE TITLE
Failed to activate the nuclide-debugger package

### ISSUE THREAD

**Issue by levani** [facebook/nuclide#1242]
[Enter steps to reproduce:]

I disabled the nuclide plugin and re-enabled after several seconds.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [nuclide-debugger](https://github.com/facebook/nuclide) package 0.0.0

### Stack Trace

Failed to activate the nuclide-debugger package

```
At Output service used after deactivation

Error: Output service used after deactivation
  at Object.registerOutputProvider (/packages/nuclide/pkg/nuclide-console/lib/main.js:244:17)
  at registerConsoleLogging (/packages/nuclide/pkg/nuclide-debugger-base/lib/AtomServiceContainer.js:53:28)
  at /packages/nuclide/pkg/nuclide-debugger/lib/Bridge.js:76:107)
  at /packages/nuclide/pkg/nuclide-debugger/lib/DebuggerModel.js:124:20)
  at /packages/nuclide/pkg/nuclide-debugger/lib/main.js:237:19)
  at Object.activate (/packages/nuclide/pkg/nuclide-debugger/lib/main.js:751:18)
  at Package.module.exports.Package.activateNow (<embedded>:69116:25)
  at <embedded>:69088:38
  at Package.module.exports.Package.measure (<embedded>:68962:21)
  at <embedded>:69081:32
  at Package.module.exports.Package.activate (<embedded>:69078:40)
  at PackageManager.module.exports.PackageManager.activatePackage (<embedded>:20534:40)
  at _features.forEach.feature (/packages/nuclide/modules/nuclide-commons-atom/FeatureLoader.js:166:23)
  at Array.forEach (native)
  at FeatureLoader.activate (/packages/nuclide/modules/nuclide-commons-atom/FeatureLoader.js:164:20)
  at Object.activate (/packages/nuclide/lib/main.js:236:17)
  at Package.module.exports.Package.activateNow (<embedded>:69116:25)
  at <embedded>:69088:38
  at Package.module.exports.Package.measure (<embedded>:68962:21)
  at <embedded>:69081:32
  at Package.module.exports.Package.activate (<embedded>:69078:40)
  at PackageManager.module.exports.PackageManager.activatePackage (<embedded>:20534:40)
  at <embedded>:20266:25
  at <embedded>:17903:26
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63093:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63209:34)
  at Config.module.exports.Config.emitChangeEvent (<embedded>:18094:35)
  at Config.module.exports.Config.setRawValue (<embedded>:17880:25)
  at Config.module.exports.Config.set (<embedded>:17495:20)
  at Config.module.exports.Config.removeAtKeyPath (<embedded>:17645:18)
  at Package.module.exports.Package.enable (<embedded>:68947:32)
  at PackageManager.module.exports.PackageManager.enablePackage (<embedded>:20077:20)
  at HTMLButtonElement.enablementButtonClickHandler (<embedded>:180768:31)

```

### Commands

```
  2x -8:34.9.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -8:25.9.0 command-palette:toggle (input.hidden-input)
     -8:22.6.0 core:move-down (input.hidden-input)
     -8:22.4.0 core:confirm (input.hidden-input)
     -8:22.3.0 nuclide-react-native:start-packager (input.hidden-input)
     -8:22.3.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-cobalt2-syntax.theme-one-dark-ui)
     -2:43.1.0 command-palette:toggle (input.hidden-input)
  3x -2:40.9.0 core:backspace (input.hidden-input)
     -2:38 core:move-down (input.hidden-input)
     -2:36.7.0 core:confirm (input.hidden-input)
     -2:36.7.0 nuclide-react-native:start-packager (input.hidden-input)
     -2:36.7.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-cobalt2-syntax.theme-one-dark-ui)
     -2:29.7.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-close.has-description)
     -1:20 window:toggle-dev-tools (atom-notification.error.icon.icon-flame.native-key-bindings.has-close.has-description)
     -0:37.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-cobalt2-syntax.theme-one-dark-ui)
  2x -0:30.3.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-cobalt2-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
atom-typescript 11.0.6 
busy-signal 1.4.3 
cobalt2-syntax 0.5.1 
emmet 2.4.3 
file-icons 2.1.9 
highlight-selected 0.13.1 
intentions 1.1.2 
language-blade 0.34.0 
language-nginx 0.8.0 
linter 2.2.0 
linter-eslint 8.2.1 
linter-php 1.3.2 
linter-ui-default 1.6.3 
minimap 4.29.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
nuclide 0.241.0 
pretty-json 1.6.3 
```

**Comment by mostafaeweda** [comment]
That's now fixed
