### ISSUE TITLE
Cannot find module 'babel-plugin-idx'

### ISSUE THREAD

**Issue by TheSavior** [facebook/nuclide#1243]
[Enter steps to reproduce:]

1. Load Atom
2. Cry

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.241.0

### Stack Trace

Failed to load the nuclide package

```
At Cannot find module 'babel-plugin-idx'

Error: Cannot find module 'babel-plugin-idx'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Function.require.resolve (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:69:35)
    at Object.<anonymous> (/Users/eliwhite/fbsource/fbobjc/Tools/Nuclide/pkg/nuclide-node-transpiler/lib/NodeTranspiler.js:43:14)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/eliwhite/fbsource/fbobjc/Tools/Nuclide/pkg/nuclide-node-transpiler/lib/require-hook.js:24:24)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/eliwhite/fbsource/fbobjc/Tools/Nuclide/pkg/nuclide-node-transpiler/lib/main.js:27:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/opt/facebook/nuclide/0.233.61365329/nuclide/lib/main-entry.js:17:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
```

### Commands

```
     -0:04.3.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
copy-path 0.4.1 
dash 1.7.1 
file-icons 2.1.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
javascript-snippets 1.2.1 
language-babel 2.61.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.8.0 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.241.0 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
tool-bar 1.1.0 
```

**Comment by TheSavior** [comment]
I was apparently on the internal built from source version. I reinstalled atom and nuclide and it went away. (y)
