### ISSUE TITLE
Uncaught TypeError: Cannot read property 'NaN' of undefined

### ISSUE THREAD

**Issue by srinivt** [facebook/nuclide#1250]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.242.66273750

### Stack Trace

Uncaught TypeError: Cannot read property 'NaN' of undefined

```
At /opt/facebook/nuclide/0.242.66273750/nuclide/node_modules/xterm/lib/SelectionManager.js:247

TypeError: Cannot read property 'NaN' of undefined
    at SelectionManager._onSingleClick (/opt/facebook/nuclide/0.242.66273750/nuclide/node_modules/xterm/lib/SelectionManager.js:247:71)
    at SelectionManager._onMouseDown (/opt/facebook/nuclide/0.242.66273750/nuclide/node_modules/xterm/lib/SelectionManager.js:211:22)
    at HTMLDivElement._mouseDownListener (/opt/facebook/nuclide/0.242.66273750/nuclide/node_modules/xterm/lib/SelectionManager.js:52:67)
```

### Commands

```
     -0:09.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
file-icons 2.1.9 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.65.1 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.10 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.242.66273750 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
Sublime-Style-Column-Selection 1.7.4 
tool-bar 1.1.0 
```

**Comment by shushz** [comment]
This is actually thrown by the `xterm` module that we use.
Perhaps it's better to be open on their GitHub page: https://github.com/sourcelair/xterm.js

**Comment by rightparen** [comment]
I have heard reports that updating to xterm 3.0.1 appears to have fixed this.
