### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scopeName' of undefined

### ISSUE THREAD

**Issue by idevelop** [facebook/nuclide#1270]
[Enter steps to reproduce:]

1. Launch Atom

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.245.68217134

### Stack Trace

Uncaught TypeError: Cannot read property 'scopeName' of undefined

```
At /opt/facebook/nuclide/0.245.68217134/nuclide/node_modules/rxjs/bundles/Rx.min.js:43

TypeError: Cannot read property 'scopeName' of undefined
    at fromItem (/opt/facebook/nuclide/0.245.68217134/nuclide/pkg/fb-analytics-client/lib/observePanelFocus.js:99:50)
    at a._rxjsBundlesRxMinJs.Observable.fromEvent.map.e [as project] (/opt/facebook/nuclide/0.245.68217134/nuclide/pkg/fb-analytics-client/lib/observePanelFocus.js:54:14)
    at a._next (/opt/facebook/nuclide/0.245.68217134/nuclide/node_modules/rxjs/bundles/Rx.min.js:106:201)
    at a.next (/opt/facebook/nuclide/0.245.68217134/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at HTMLDocument.<anonymous> (/opt/facebook/nuclide/0.245.68217134/nuclide/node_modules/rxjs/bundles/Rx.min.js:81:365)
    at HTMLElement.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:158:25)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:337:28)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:492:27)
    at Immediate.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:702:30)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -0:33.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  7x -0:17.6.0 core:close (input.hidden-input)
  4x -0:05.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
file-icons 2.1.11 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
howdoi 0.1.1 
language-babel 2.71.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
merge-conflicts 1.4.5 
nuclide 0.245.68217134 
nuclide-format-js 0.0.41 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
windows-carriage-return-remover 0.1.3 
```

**Comment by matthewwithanm** [comment]
@idevelop Thanks for the report!

@wbinnssmith I'm surprised that this can be null (there's a `NullGrammar`) but `¯\_(ツ)_/¯`

**Comment by wbinnssmith** [comment]
@idevelop we fixed this with this week's release. You should receive it in a day or two! Please reopen if not resolve :D
