### ISSUE TITLE
Uncaught TypeError: atom.workspace.toggle is not a function

### ISSUE THREAD

**Issue by santhosh2sai** [facebook/nuclide#1276]
[Before submitting, please enter steps to reproduce:]

1. ...
2. ...

**Learn IDE Package**: 2.5.3
**Learn IDE Core**: 2.5.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.247.0

### Stack Trace

Uncaught TypeError: atom.workspace.toggle is not a function

```
At /Users/saisanthoshsamudrala/.atom/packages/nuclide/pkg/nuclide-health/lib/main.js:164

TypeError: atom.workspace.toggle is not a function
    at /packages/nuclide/pkg/nuclide-health/lib/main.js:164:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  3x -3:59.3.0 learn-ide:toggle-popout (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-atom-dark-ui)
  3x -0:40.7.0 core:backspace (input.hidden-input)
     -0:14.6.0 command-palette:toggle (input.hidden-input)
     -0:06.7.0 nuclide-health:toggle (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
autocomplete-html-entities 0.1.0 
html-shorcuts-react 1.1.1 
npm-install 4.0.4 
nuclide 0.247.0 
platformio-ide-terminal 2.5.5 
react-es6-snippets 0.3.0 
react-es7-snippets 0.3.13 
react-native-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
react-snippets 0.9.0 
```

**Comment by matthewwithanm** [comment]
Hey @santhosh2sai! Is Learn IDE a fork of Atom? What version of Atom are you using? Seems like it's a pretty old one as `atom.workspace.toggle()` has been around since 1.17.

**Comment by matthewwithanm** [comment]
This has been hanging a while so I'm going to close it. lmk if this is still an issue 😊
