### ISSUE TITLE
Uncaught Error: Cannot find module 'nuclide-commons-atom/text-editor'

### ISSUE THREAD

**Issue by h2asoft** [facebook/nuclide#1279]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.4 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.249.0

### Stack Trace

Uncaught Error: Cannot find module 'nuclide-commons-atom/text-editor'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1

Error: Cannot find module 'nuclide-commons-atom/text-editor'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_textEditor (/packages/nuclide/pkg/nuclide-remote-projects/lib/RemoteProjectsController.js:28:24)
    at RemoteProjectsController._updateConnectionStatus (/packages/nuclide/pkg/nuclide-remote-projects/lib/RemoteProjectsController.js:67:30)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:551:30
```

### Commands

```
     -2:25.4.0 core:confirm (input.hidden-input)
     -0:54.3.0 core:paste (input.hidden-input)
     -0:53.7.0 core:confirm (input.hidden-input)
     -0:27.6.0 nuclide-file-tree:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
nuclide 0.249.0 
nuclide-format-js 0.0.41 
tool-bar 1.1.0 
```

**Comment by hansonw** [comment]
This should be fixed as soon as you reload Atom. Please let me know if that doesn't do it.
