### ISSUE TITLE
Error on opening Atom 1.19.5, workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by kmiyashiro** [facebook/nuclide#1284]
### Issue and Steps to Reproduce
Update to Atom 1.19.5
Open Atom
### Expected Behavior
Atom displays anything
### Actual Behavior
Atom is blank

### Versions
* Atom: 1.19.5
* Nuclide: 0.250
* Client OS: OS X 10.12.6
* Server OS (optional):

### Additional Details
Error in console
```

<embedded>:71614 Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/Applications/Atom.app/Contents/Resources/app/src/item-registry.js:11:21)
    at PaneContainer.didAddPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:269:29)
    at PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:242:18)
    at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app/src/pane.js:162:32)
    at PaneAxis.module.exports.PaneAxis.setContainer (/Applications/Atom.app/Contents/Resources/app/src/pane-axis.js:97:36)
    at PaneContainer.setRoot (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:137:21)
    at PaneContainer.deserialize (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:58:16)
    at WorkspaceCenter.deserialize (/Applications/Atom.app/Contents/Resources/app/src/workspace-center.js:31:30)
    at Workspace.deserialize (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:416:42)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1263:35
```

* Installed packages (`apm ls --installed`):
 
Community Packages (40) /Users/kelly/.atom/packages
├── atom-beautify@0.30.5
├── busy-signal@1.4.3
├── color-picker@2.2.5
├── dash@1.7.1
├── docblockr@0.11.0
├── file-icons@2.1.11
├── git-plus@7.9.3
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── intentions@1.1.5
├── language-babel@2.73.0
├── language-ember-htmlbars@0.4.0
├── language-graphql@0.9.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-pug@0.0.21
├── language-racket@0.4.0
├── language-rust@0.4.12
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-eslint@8.2.1
├── linter-jshint@3.1.5
├── linter-jsonlint@1.3.0
├── linter-markdown@5.2.0
├── linter-pug@1.3.1
├── linter-rubocop@2.1.1
├── linter-ruby@1.2.6
├── linter-stylelint@4.0.2
├── linter-ui-default@1.6.8 (disabled)
├── linter-xo@0.23.1
├── merge-conflicts@1.4.5
├── nuclide@0.250.0
├── nuclide-format-js@0.0.41
├── set-syntax@0.3.2
├── sort-lines@0.15.0
├── source-preview@0.5.2
├── source-preview-pug@0.2.0
├── sync-settings@0.8.3
└── tool-bar@1.1.0

**Comment by kmiyashiro** [comment]
Oops, I don't think this is caused by nuclide, I just saw the stacktrace was coming from nuclide log appender.

**Comment by ccqgithub** [comment]
+1 when i `atom --clear-window-state`, it become ok.

but when i  close the window, and reopen then folder, it is appear agian ...
