### ISSUE TITLE
Uncaught Error: Cannot find module 'nuclide-commons-atom/range'

### ISSUE THREAD

**Issue by mban** [facebook/nuclide#1288]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.250.0

### Stack Trace

Uncaught Error: Cannot find module 'nuclide-commons-atom/range'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1

Error: Cannot find module 'nuclide-commons-atom/range'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_range (/packages/nuclide/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:20:19)
    at HyperclickForTextEditor._onMouseMove (/packages/nuclide/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:198:34)
```

### Commands

```
     -5:41 nuclide-file-tree:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-react-native-style 0.1.5 
badass-react-snippets 1.1.0 
fancy-react 0.6.2 
git-plus 7.9.3 
git-time-machine 1.5.9 
nativebase-snippets-atom 2.0.2 
nuclide 0.250.0 
nuclide-format-js 0.0.41 
react 0.16.2 
react-native-components 0.1.1 
react-native-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
react-redux-react-native-snippets 0.2.4 
react-snippets 0.9.0 
react-snippets-for-atom 0.2.0 
react-storybook-snippets 0.3.0 
```

**Comment by wbinnssmith** [comment]
Hi @mban, can you try upgrading Nuclide to the latest version (0.252.0 as of now) and see if this issue persists? Thanks!
