### ISSUE TITLE
Remote server failing to start 

### ISSUE THREAD

**Issue by tylersax** [facebook/nuclide#130]
I successfully installed nuclide server on a Raspberry Pi running Debian 7.8 (+ Raspbian). However, when I try to run `nuclide-start-server`, I get:

```sh
pi@raspberrypi:~$ nuclide-start-server
Cleaning up old files...
Starting Nuclide server...
Nuclide server failed to respond to version check on port 9090.
The log file can be found at ~/nuclide.nohup.out.
```

...and the log file is empty. Any ideas?

**Comment by Dr-Jerm** [comment]
I am also unable to get the nuclide-server-start command to run without the
```Nuclide server failed to respond to version check on port 9090```
message. I have tried (through nvm) node versions 0.12.4 and 0.12.6 with no luck. Also attempted on both debian and ubuntu.

**Comment by meshelluh** [comment]
I'm having issues with `nuclide-start-server` as well. my installation seems to run successfully with no warning or errors. 

    Traceback (most recent call last):
     File "scripts/nuclide_server_manager.py", line 25, in <module>
        from nuclide_server import LOG_FILE
      File "/usr/local/lib/node_modules/nuclide-server/scripts/nuclide_server.py", line 18, in <module>
    import utils File "/usr/local/lib/node_modules/nuclide server/scripts/utils.py", line 16, in <module> from     pkg_resources import resource_string

I posted about it here as well: http://stackoverflow.com/questions/31304593/remote-server-setup-nuclide-start-server-command-doesnt-work

**Comment by kristoftorfs** [comment]
A workaround I just found is to run the server in insecure mode: 

```bash
nuclide-start-server -k
```

**Comment by Dr-Jerm** [comment]
@kristoftorfs thanks, that worked.

**Comment by cbosuna** [comment]
According to http://stackoverflow.com/questions/31304593/remote-server-setup-nuclide-start-server-command-doesnt-work it sounds like setuptools might be broken?  Are you interested in trying their solution or are you satisfied with the workaround?

**Comment by arsenx** [comment]
I am getting the same issue.
I am running a Debian 8 virtual environment.
The output to the file seems to show that the server starts correctly.

[2015-07-28T14:10:30.488Z] [INFO] nuclide - Registered service /home/<USER>/.npm_packages/lib/node_modules/nuclide-server/lib/services/NuclideFsService.js without ServiceFramework.
[2015-07-28T14:10:30.491Z] [INFO] nuclide - Registered service /home/<USER>/.npm_packages/lib/node_modules/nuclide-server/lib/services/NuclideSearchService.js without ServiceFramework.
[2015-07-28T14:10:30.492Z] [INFO] nuclide - Registered service /home/<USER>/.npm_packages/lib/node_modules/nuclide-server/lib/services/NuclideWatcherService.js without ServiceFramework.
[2015-07-28T14:10:30.492Z] [INFO] nuclide - Registered service /home/<USER>/.npm_packages/lib/node_modules/nuclide-server/lib/services/NuclideHackService.js without ServiceFramework.
[2015-07-28T14:10:30.493Z] [INFO] nuclide - Registered service /home/<USER>/.npm_packages/lib/node_modules/nuclide-server/lib/services/SourceControlService.js without ServiceFramework.
[2015-07-28T14:10:30.494Z] [INFO] nuclide - Registered service FlowService with ServiceFramework.
[2015-07-28T14:10:30.496Z] [INFO] nuclide - Registered service HgService with ServiceFramework.
[2015-07-28T14:10:30.497Z] [INFO] nuclide - Registered service ClangService with ServiceFramework.
[2015-07-28T14:10:30.497Z] [INFO] nuclide - Registered service ArcanistBaseService with ServiceFramework.
[2015-07-28T14:10:30.498Z] [INFO] nuclide - Registered service BuckUtils with ServiceFramework.
[2015-07-28T14:10:30.499Z] [INFO] nuclide - Registered service BuckProject with ServiceFramework.
[2015-07-28T14:10:30.499Z] [INFO] nuclide - Registered service HhvmDebuggerProxyService with ServiceFramework.
[2015-07-28T14:10:30.500Z] [INFO] nuclide - Registered service FindInProjectService with ServiceFramework.
[2015-07-28T14:10:30.501Z] [INFO] nuclide - NuclideServer started on port 9090.

**Comment by cbosuna** [comment]
@arsenx Does restarting atom and trying to connect again fix the problem?  Is port 9090 accessible on your VM from your host?

**Comment by arsenx** [comment]
Hi @cbosuna i've restarted atom numerous times over the course of testing.
I believe that this issue might be related to #132 since I am able to connect successfully via `http` but not `https`

The problem does not come from atom itself since the output of the error when trying to start the `nuclide-server` is `Nuclide server failed to respond to version check on port 9090.`

It is not urgent for me as it's okay for me to connect via `http` since I am working with a local vm but might be a problem to those who try using this tool as a means to connect to a remote server over the web.

**Comment by webda2l** [comment]
Same problem for me. :/

CASE: Connect by ssh to an Ubuntu Server 15.04 (HyperV) with password, and "nuclide-start-server -k"

**Atom Version**: 1.0.9
**System**: Microsoft Windows 10 Pro
**Thrown From**: [nuclide-remote-projects](https://github.com/facebooknuclideapm/nuclide-remote-projects) package, v0.0.30


### Stack Trace

Uncaught AssertionError: undefined == true

```
At assert.js:87

AssertionError: undefined == true
  at SshHandshake._updateServerInfo (C:\Users\david\.atom\packages\nuclide-remote-projects\node_modules\nuclide-remote-connection\lib\SshHandshake.js:169:7)
  at Channel.<anonymous> (C:\Users\david\.atom\packages\nuclide-remote-projects\node_modules\nuclide-remote-connection\lib\SshHandshake.js:237:22)
  at emitOne (events.js:77:13)
  at Channel.emit (events.js:166:7)
  at SSH2Stream.<anonymous> (C:\Users\david\.atom\packages\nuclide-remote-projects\node_modules\nuclide-remote-connection\node_modules\ssh2\lib\Channel.js:125:14)
  at SSH2Stream.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at SSH2Stream.emit (events.js:163:7)
  at parsePacket (C:\Users\david\.atom\packages\nuclide-remote-projects\node_modules\nuclide-remote-connection\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:3437:10)
  at SSH2Stream._transform (C:\Users\david\.atom\packages\nuclide-remote-projects\node_modules\nuclide-remote-connection\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:555:13)
  at SSH2Stream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SSH2Stream._read (C:\Users\david\.atom\packages\nuclide-remote-projects\node_modules\nuclide-remote-connection\node_modules\ssh2\node_modules\ssh2-streams\lib\ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at SSH2Stream.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```

### Commands

```
     -0:14.8.0 nuclide-remote-projects:connect (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.30
linter, v1.4.3
nuclide-arcanist, v0.0.30
nuclide-code-format, v0.0.30
nuclide-diagnostics-store, v0.0.30
nuclide-diagnostics-ui, v0.0.30
nuclide-diff-view, v0.0.30
nuclide-file-tree, v0.0.30
nuclide-file-watcher, v0.0.30
nuclide-find-references, v0.0.30
nuclide-flow, v0.0.30
nuclide-hack, v0.0.30
nuclide-hg-repository, v0.0.30
nuclide-installer, v0.0.30
nuclide-language-hack, v0.0.30
nuclide-ocaml, v0.0.30
nuclide-quick-open, v0.0.30
nuclide-remote-projects, v0.0.30
nuclide-type-hint, v0.0.30
php-debug, v0.1.3

# Dev
No dev packages
```

**Comment by kentor** [comment]
I get this in the logs:
```
❯ cat ~/nuclide.nohup.out                                                                         
nohup: can't detach from console: No such file or directory
```

what does this mean?

**Comment by mostafaeweda** [comment]
We probably fixed that in the recent server improvements and the latest UP release: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/

**Comment by simar7** [comment]
@mostafaeweda I'm running into the same problem again. Here's the output:

```
[simar@TuxCore ~ ]$ nuclide-start-server -k -v -t 30
2016-05-25 03:29:56,569 - root - WARNING - Failed to clean up old core dumps ()
2016-05-25 03:29:56,571 - NuclideServerManager - INFO - Trying to determine the port to use for Nuclide server...
2016-05-25 03:29:56,591 - NuclideServerManager - INFO - Found an open port: 9090.
2016-05-25 03:29:56,593 - NuclideServerManager - INFO - Initialized NuclideServer.
2016-05-25 03:29:56,609 - NuclideServerManager - INFO - Starting NuclideServer...
2016-05-25 03:29:56,611 - NuclideServerManager - INFO - Using http.
2016-05-25 03:29:56,612 - NuclideServer - INFO - NuclideServer start/restarting with the following arguments:
                           timeout: 30
                           cert:    None
                           key:     None
                           ca:      None
                           force:   False
                           quiet:   False
                           debug:   False
2016-05-25 03:29:56,630 - NuclideServer - INFO - Opening node server subprocess.
2016-05-25 03:29:56,634 - NuclideServer - INFO - Trying to ping the Nuclide server...
2016-05-25 03:30:28,166 - NuclideServer - ERROR - Attempted to start Nuclide server on port 9090, but timed out after 30 seconds.
{"succes": false, "logs": ["2016-05-25 03:29:56,569 - root - WARNING - Failed to clean up old core dumps ()", "2016-05-25 03:29:56,571 - NuclideServerManager - INFO - Trying to determine the port to use for Nuclide server...", "2016-05-25 03:29:56,591 - NuclideServerManager - INFO - Found an open port: 9090.", "2016-05-25 03:29:56,593 - NuclideServerManager - INFO - Initialized NuclideServer.", "2016-05-25 03:29:56,609 - NuclideServerManager - INFO - Starting NuclideServer...", "2016-05-25 03:29:56,611 - NuclideServerManager - INFO - Using http.", "2016-05-25 03:29:56,612 - NuclideServer - INFO - NuclideServer start/restarting with the following arguments:\n                           timeout: 30\n                           cert:    None\n                           key:     None\n                           ca:      None\n                           force:   False\n                           quiet:   False\n                           debug:   False", "2016-05-25 03:29:56,630 - NuclideServer - INFO - Opening node server subprocess.", "2016-05-25 03:29:56,634 - NuclideServer - INFO - Trying to ping the Nuclide server...", "2016-05-25 03:30:28,166 - NuclideServer - ERROR - Attempted to start Nuclide server on port 9090, but timed out after 30 seconds."]}
The log file can be found at /tmp/nuclide-simar-logs/server-start/nuclide-2016-05-25T03:29:56.nohup.out.
```


The log is empty and I have made sure I have the required ports open.

**Comment by mostafaeweda** [comment]
cc @hansonw

**Comment by underscorefunk** [comment]
I'm having the same problem, though when I dig in, the log reveals this...

`/usr/local/lib/node_modules/nuclide/pkg/nuclide-server/lib/nuclide-main.js:17
const {__DEV__} = require('../../nuclide-node-transpiler/lib/env');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
`
