### ISSUE TITLE
Uncaught Error: Cannot find module './getModifierKeys'

### ISSUE THREAD

**Issue by jinjorge** [facebook/nuclide#1310]
[Enter steps to reproduce:]

1. Update to `0.256.0`
2. On re-launch viewing a previously open file prior to updating the app, displays an `Uncaught Error`

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.256.0

### Stack Trace

Uncaught Error: Cannot find module './getModifierKeys'

```
At /Users/jeremiah/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43

Error: Cannot find module './getModifierKeys'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_getModifierKeys (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:131:29)
    at /packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:303:49)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43:337)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:42:227)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:81:365)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
nuclide 0.256.0 
```

**Comment by jgebhardt** [comment]
@jinjorge did this resolve after reloading Nuclide/Atom?

**Comment by jinjorge** [comment]
@jgebhardt yes, it resolved after a subsequent app launch
