### ISSUE TITLE
Uncaught Error: Couldn't convert text to a String

### ISSUE THREAD

**Issue by dirid51** [facebook/nuclide#1313]
[Enter steps to reproduce:]

1. This error was reoccurring every ten seconds or so, without me doing anything. It started after telling Atom to update everything.

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Education
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.257.0

### Stack Trace

Uncaught Error: Couldn't convert text to a String

```
At C:\Users\randallbooth\AppData\Local\atom\app-1.20.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:532

Error: Couldn't convert text to a String
    at TextBuffer.module.exports.TextBuffer.getText (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:532:94)
    at new ForwardsMultiLine (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/text-buffer/lib/match-iterator.js:254:37)
    at TextBuffer.module.exports.TextBuffer.scanInRange (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1028:28)
    at wordAtPositionFromBuffer (/packages/nuclide/modules/nuclide-commons/range.js:26:10)
    at wordAtPosition (/packages/nuclide/modules/nuclide-commons-atom/range.js:57:65)
    at HyperclickForTextEditor._onMouseMove (/packages/nuclide/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:185:64)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
autocomplete-modules 1.7.1 
busy-signal 1.4.3 
intentions 1.1.5 
language-babel 2.74.4 
linter 2.2.0 
linter-eslint 8.3.2 
linter-flow 5.6.1 
linter-jshint 3.1.6 
linter-ui-default 1.6.10 
nuclide 0.257.0 
```

**Comment by jgebhardt** [comment]
Did the error resolve after you finished updating all packages?

**Comment by dirid51** [comment]
No, I was constantly getting the error notice, so I disabled nuclide, then uninstalled it. The error message was no longer showing up every few seconds, so I assumed that the error really had been the result of nuclide, somehow or other. After everything was updated, and rebuilt if necessary, I reinstalled nuclide fresh. I have not experienced the error since the reinstallation.

**Comment by jgebhardt** [comment]
Seems like potentially a bug in Atom's TextBuffer on Windows.
