### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by cwdick** [facebook/nuclide#1320]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.258.0

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/cwdick/fbsource/fbobjc/Tools/Nuclide/node_modules/vscode-jsonrpc/lib/messageReader.js:191

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/Users/cwdick/fbsource/fbobjc/Tools/Nuclide/node_modules/vscode-jsonrpc/lib/messageReader.js:191:27)
    at Socket.<anonymous> (/Users/cwdick/fbsource/fbobjc/Tools/Nuclide/node_modules/vscode-jsonrpc/lib/messageReader.js:176:19)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -1:47.2.0 editor:consolidate-selections (input.hidden-input)
     -1:47.2.0 core:cancel (input.hidden-input)
     -1:44.4.0 core:save (input.hidden-input)
  3x -1:26.1.0 core:move-down (input.hidden-input)
     -0:10.8.0 core:move-left (input.hidden-input)
     -0:10.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:09.8.0 editor:select-to-end-of-line (input.hidden-input)
     -0:05.0 core:backspace (input.hidden-input)
     -0:03.8.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -0:03.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.12 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.75.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
merge-conflicts 1.4.5 
nuclide 0.258.0 
nuclide-format-js 0.0.41 
set-syntax 0.4.0 
sort-lines 0.15.0 
tool-bar 1.1.0 
```

**Comment by hansonw** [comment]
I see you're at FB, could you use the internal bug reporting mechanism? Thanks!
