### ISSUE TITLE
Failed to activate the atom-ide-definitions package

### ISSUE THREAD

**Issue by rr-kalbeck** [facebook/nuclide#1340]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [atom-ide-definitions](https://github.com/facebook/nuclide) package 0.0.0

### Stack Trace

Failed to activate the atom-ide-definitions package

```
At Package not initialized

Error: Package not initialized
    at /packages/atom-ide-ui/modules/nuclide-commons-atom/createPackage.js:48:15)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at _features.forEach.feature (/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:188:23)
    at Array.forEach (native)
    at FeatureLoader.activate (/packages/atom-ide-ui/modules/nuclide-commons-atom/FeatureLoader.js:186:20)
    at Object.activate (/packages/atom-ide-ui/index.js:102:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -5:35 settings-view:open (input.hidden-input)
     -5:02.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-ide-ui 0.5.1 
atom-typescript 11.0.10 
busy-signal 1.4.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-templates 0.2.0 
git-blame 1.3.1 
intentions 1.1.5 
language-babel 2.75.1 
language-graphql 0.9.0 
language-pug 0.0.21 
linter 2.2.0 
linter-eslint 8.3.2 
linter-tslint 1.8.1 
linter-ui-default 1.6.10 
react-snippets 1.0.0 
```

**Comment by hansonw** [comment]
Looks related to https://github.com/facebook-atom/atom-ide-ui/issues/85. Could you try the remediation there (and follow up on that issue if it doesn't work?)

**Comment by Mullazman** [comment]
Why was this closed without resolve, or have I missed something? I'm getting this as well, only just installed atom-ide-ui

**Comment by hansonw** [comment]
Please follow up in the linked issue (it's a dupe)
