### ISSUE TITLE
Uncaught TypeError: node.repo.isStatusUntracked is not a function

### ISSUE THREAD

**Issue by GGrudanov** [facebook/nuclide#1348]
1. In the terminal cd to a directory which has .hg folder
2. Start atom in current directory by typing (atom .) in terminal
3. You will see a toast saying Nuclide Bookshelf broke, please report a bug... etc
4. Right click any file in the right hand side folders view

I cannot reproduce it when starting from a folder which doesn't contain a .hg folder.
Nor can I reproduce it when starting Atom and then selecting the same folder as I did in step 1 by using 'Add Project Folder' (When prompted Previous automatically-saved project state detected press Add to this window and discard state, else it will fail like in step 3), however I do get the toast warning: Mercurial: failed to subscribe to watchman!.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: KDE neon
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.262.0

### Stack Trace

Uncaught TypeError: node.repo.isStatusUntracked is not a function

```
At /home/ggrudanov/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43

TypeError: node.repo.isStatusUntracked is not a function
    at nodes.every.node (/packages/nuclide/pkg/nuclide-hg-repository/lib/main.js:109:24)
    at /packages/nuclide/node_modules/immutable/dist/immutable.js:4340:24
    at List.__iterate (/packages/nuclide/node_modules/immutable/dist/immutable.js:2194:13)
    at List.every (/packages/nuclide/node_modules/immutable/dist/immutable.js:4339:12)
    at shouldDisplayActionTreeItem (/packages/nuclide/pkg/nuclide-hg-repository/lib/main.js:105:18)
    at Object.shouldDisplay (/packages/nuclide/pkg/nuclide-hg-repository/lib/main.js:222:14)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/usr/share/atom/resources/app/src/context-menu-manager.js:167:25)
    at /usr/share/atom/resources/app/src/context-menu-manager.js:177:32
    at Array.map (native)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/usr/share/atom/resources/app/src/context-menu-manager.js:175:43)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/usr/share/atom/resources/app/src/context-menu-manager.js:100:39)
    at /packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:414:45)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:238:504)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:81:365)
```

### Commands

```
```

### Non-Core Packages

```
atom-hg 2.0.14 
atom-isort 2.5.2 
atom-material-ui 2.0.6 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
file-icons 2.1.13 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
Hydrogen 2.0.1 
intentions 1.1.5 
language-babel 2.75.2 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-python 3.1.2 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
MagicPython 1.0.12 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
nuclide 0.262.0 
nuclide-format-js 0.0.41 
python-tools 0.6.9 
set-syntax 0.4.0 
sort-lines 0.18.0 
symbols-tree-view 0.14.0 
tool-bar 1.1.0 
windows-carriage-return-remover 0.1.3 
```

**Comment by GGrudanov** [comment]
Cannot reproduce anymore..
