### ISSUE TITLE
Failed to activate the nuclide-debugger package

### ISSUE THREAD

**Issue by stoufa06** [facebook/nuclide#1352]
### Issue and Steps to Reproduce
just updated nuclide and restarted atom

### Versions
* Nuclide:0.260.0 
**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Linux Mint
**Thrown From**: [nuclide-debugger](https://github.com/facebook/nuclide) package 0.0.0

### Stack Trace

Failed to activate the nuclide-debugger package

```
At dock.dock.isVisible is not a function

TypeError: dock.dock.isVisible is not a function
    at _getWorkspaceDocks.forEach.dock (/packages/nuclide/pkg/nuclide-debugger/lib/DebuggerLayoutManager.js:322:21)
    at Array.forEach (native)
    at DebuggerLayoutManager._updateDebuggerVisibility (/packages/nuclide/pkg/nuclide-debugger/lib/DebuggerLayoutManager.js:321:31)
    at DebuggerLayoutManager._reshowDebuggerPanes (/packages/nuclide/pkg/nuclide-debugger/lib/DebuggerLayoutManager.js:313:12)
    at /packages/nuclide/pkg/nuclide-debugger/lib/DebuggerLayoutManager.js:126:10)
    at /packages/nuclide/pkg/nuclide-debugger/lib/main.js:233:27)
    at Object.activate (/packages/nuclide/pkg/nuclide-debugger/lib/main.js:862:18)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:690:42)
    at _features.forEach.feature (/packages/nuclide/modules/nuclide-commons-atom/FeatureLoader.js:188:23)
    at Array.forEach (native)
    at FeatureLoader.activate (/packages/nuclide/modules/nuclide-commons-atom/FeatureLoader.js:186:20)
    at /packages/nuclide/lib/main.js:249:17)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:253:25)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:690:42)
    at config.transactAsync (/usr/share/atom/resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:646:50)
    at /usr/share/atom/resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
nuclide 0.260.0 
```

**Comment by mostafaeweda** [comment]
That was fixed in a later Atom / Nuclide version -- please update to the latest.
