### ISSUE TITLE
Omnisearch does not work if you include the path to your files on your search string

### ISSUE THREAD

**Issue by guicamillo** [facebook/nuclide#1371]
### Issue and Steps to Reproduce
While using omnisearch, if you add the path to the search string you get no results.
If you search for the filename only, it works just fine.

EDIT: This happens on both remotely connected directories AND on local files.

Consider the following files and dirs as an example:
```
.
└── path
    ├── file-on-root.pm
    └── to
        └── my
            ├── file-1.png
            ├── file-2.svg
            └── index.html
```

### Expected Behavior
While searching with the file path as part of the search, you should get the results.
<img width="456" alt="screen shot 2017-11-07 at 12 29 03 pm" src="https://user-images.githubusercontent.com/5016970/32489164-b76c5cf2-c3b7-11e7-9f24-00814dd95c90.png">

### Actual Behavior
Nothing is found.

<img width="566" alt="screen shot 2017-11-07 at 12 29 12 pm" src="https://user-images.githubusercontent.com/5016970/32489182-c9f413e2-c3b7-11e7-9a7c-64914f47dbf7.png">

### Versions
* Atom: 1.21.2
* Nuclide: 0.264.0
* Client OS: OSX Sierra - 10.12.6
* Server OS (optional): CentOS 7.4.1708

### Additional Details
* Installed packages (`apm ls --installed`):
```
gcamillo@C02VJ0Z0HV2T ~> apm ls --installed
├── expose@0.15.0
├── file-icons@2.1.13
├── fonts@3.0.3
├── highlight-selected@0.13.1
├── minimap@4.29.7
├── minimap-cursorline@0.2.0
├── minimap-highlight-selected@4.6.1
├── minimap-pigments@0.2.2
├── minimap-selection@4.5.0
├── nuclide@0.264.0
└── pigments@0.40.2
````

**Comment by hansonw** [comment]
Odd, somehow the native file search module is not loading for you (you're seeing the crappy fallback version). Can you reload Atom and see if something related to "fuzzy-native" comes up? And paste the error here if there is one?

**Comment by guicamillo** [comment]
@hansonw there's nothing on the console :/

**Comment by hansonw** [comment]
@guicamillo anything related to 'fuzzy-native' inside of `$TMPDIR/nuclide-$USER-logs/nuclide.log`?

**Comment by guicamillo** [comment]
@hansonw Didn't find anything `fuzzy` related there, but I've found this: `Caught unhandled rejection ENOENT: no such file or directory, lstat '/nuclide:`, and there's one issue open for it https://github.com/atom/fuzzy-finder/issues/233.

Does anything come to your mind?

**Comment by ryan953** [comment]
I'm getting the same issue too: Nothing appears when i use the full path in the search box.

I went looking to see if "Failed to load native fuzzy matching. Falling back to JS implementation" was in the Developer Tools console, but no luck. I did see this though: 

![screen shot 2018-01-17 at 11 39 23 am](https://user-images.githubusercontent.com/187460/35063319-9e6850ca-fb7b-11e7-8a03-7778624d8317.png)

```
[ERROR] installErrorReporter - Caught unhandled rejection Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at then.result (/Users/ryan/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:377:41)
```

Atom: 1.23.3
Nuclide: 0.275.0
Client OS: OSX Sierra - 10.13.2

**Comment by guicamillo** [comment]
I do see the same error.

**Comment by ryan953** [comment]
@hansonw I went diving back into this, and in the server logs I did find that fuzzy-native reference:

```
cat /tmp/nuclide-ryanalbrecht-logs/server-start/nuclide-2018-02-07T08:23:08.nohup.out
TASK(91795): [2018-02-07 08:23:12.950] [ERROR] nuclide-fuzzy-native - Failed to load native fuzzy matching. Falling back to JS implementation { Error: Cannot find module '/usr/local/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/fuzzy-native/build/fuzzy-native-v0.6.6-node-v59-linux-x64/fuzzy-native.node'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/fuzzy-native/lib/main.js:6:18)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nuclide/pkg/nuclide-fuzzy-native/lib/main.js:26:20)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at _load_nuclideFuzzyNative (/usr/local/lib/node_modules/nuclide/pkg/nuclide-fuzzy-file-search-rpc/lib/process/PathSet.js:25:32)
    at new PathSet (/usr/local/lib/node_modules/nuclide/pkg/nuclide-fuzzy-file-search-rpc/lib/process/PathSet.js:38:49)
    at /usr/local/lib/node_modules/nuclide/pkg/nuclide-fuzzy-file-search-rpc/lib/process/FileSearch.js:21:21
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at _next (/usr/local/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:24:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }
```

Lookts like it's expecting `fuzzy-native-v0.6.6-node-v59-linux-x64/fuzzy-native.node` but I have `fuzzy-native-v0.6.6-node-v51-linux-x64/fuzzy-native.node` on the filesystem.

Doing a `node -v` shows `v9.2.0` as my user or root.

I went into that `nuclide/node_modules/nuclide-prebuilt-libs/fuzzy-native` folder and tried `npm rebuild`, and along the way installed `node-pre-gyp` and `nan` which each revealed different error messages. I'm a bit out of my element as to how this packaging works and what's picking up this old ABI version.

**Comment by hansonw** [comment]
Ah.. if possible it would be best to stick to Node v7 for the Nuclide
server. (It may be helpful to set the PATH in the server command In general
the Nuclide server is only fully tested with the node version bundled with
Atom - we should note that somewhere)

**Comment by ryan953** [comment]
Awesome!

I used nvm and did some janky `nvm use 7` in my `.bashrc` file, and then `nvm use 9` in `.bash_profile` to keep my shell using the version I want for yarn and stuff and it's working great!

This was so confusing, better docs on the server-supported node version would be really great, and looking back I don't think guicamillo or myself thought you were asking for fuzzy-native logs from the server. We were so oblivious to where the problems could be.

(yarn complains about node v7, ugh!)

**Comment by guicamillo** [comment]
Yeah, I never noticed that @hansonw's request for logs was server-related either. My bad.
I'll try to proceed with @ryan953's solution and see what happens here :)

**Comment by ryan953** [comment]
@guicamillo I switched from messing with bashrc files and instead prepended the Remote Server Command field with `nvm use 7`. Seems to be working better this way when I login or connect in different ways to my server.

It looks like this:

![screen shot 2018-03-12 at 9 49 15 am](https://user-images.githubusercontent.com/187460/37297343-a823ddc6-25da-11e8-9041-9436c647987e.png)

**Comment by guicamillo** [comment]
@ryan953 This solves the issue! thanks a lot!

**Comment by pedroseac** [comment]
It didn't work for me 😞 

Besides the conf in nuclide, did you do anything else in the server?

**Comment by carsondarling** [comment]
For what it's worth, I was seeing this issue earlier today (Nuclide was trying to load v51 of `nuclide-fuzzy-native`, but I only had v54 (not sure what caused the version mismatch). Updating all packages seems to have fixed it.

**Comment by pedroseac** [comment]
Just updated everything, and nuclide is now on `0.299`, and still, it doesn't work.
