### ISSUE TITLE
Uncaught Error: Nuclide URI must be either local file names or URLs starting with nuclide://

### ISSUE THREAD

**Issue by eecolella** [facebook/nuclide#1381]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.268.0

### Stack Trace

Uncaught Error: Nuclide URI must be either local file names or URLs starting with nuclide://

```
At /Users/eecolella/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:23

Error: Nuclide URI must be either local file names or URLs starting with nuclide://
    at Object.parse (/packages/nuclide/modules/nuclide-commons/nuclideUri.js:135:11)
    at Function.getForUri (/packages/nuclide/pkg/nuclide-remote-connection/lib/ServerConnection.js:430:70)
    at createBufferForUri (/packages/nuclide/pkg/nuclide-remote-connection/lib/remote-text-buffer.js:117:89)
    at bufferForUri (/packages/nuclide/pkg/nuclide-remote-connection/lib/remote-text-buffer.js:103:10)
    at DefinitionPreviewView.componentWillReceiveProps (/packages/nuclide/pkg/nuclide-definition-preview/lib/DefinitionPreviewView.js:121:112)
    at updateClassInstance (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:142:377)
    at beginWork (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:150:331)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:182:356)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:183:362)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:184:367)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:188:412)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:187:423)
    at Object.updateContainer (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:248:43)
    at ck (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:254:82)
    at Object.render (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:255:105)
    at ContextViewManager._renderProviders (/packages/nuclide/pkg/nuclide-context-view/lib/ContextViewManager.js:327:23)
    at ContextViewManager._render (/packages/nuclide/pkg/nuclide-context-view/lib/ContextViewManager.js:340:12)
    at ContextViewManager.updateCurrentDefinition (/packages/nuclide/pkg/nuclide-context-view/lib/ContextViewManager.js:293:10)
    at /packages/nuclide/pkg/nuclide-context-view/lib/ContextViewManager.js:246:32)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43:337)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:42:227)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:106:294)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:240:110)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:61:263)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:23:256
```

### Commands

```
     -5:52 core:move-right (input.hidden-input)
     -5:50.1.0 core:confirm (input.hidden-input)
     -5:15.5.0 core:select-all (input.hidden-input)
     -5:14.1.0 core:confirm (input.hidden-input)
     -5:03.4.0 command-palette:toggle (input.hidden-input)
     -4:58.7.0 core:move-down (input.hidden-input)
     -4:58.2.0 core:confirm (input.hidden-input)
     -4:58.2.0 settings-view:change-themes (input.hidden-input)
     -4:27.8.0 window:increase-font-size (input.hidden-input)
  2x -4:26.8.0 window:decrease-font-size (input.hidden-input)
     -4:24.5.0 window:increase-font-size (input.hidden-input)
     -2:33.8.0 core:select-all (input.hidden-input)
     -2:33.4.0 core:backspace (input.hidden-input)
  2x -2:33.2.0 core:confirm (input.hidden-input)
     -1:40.7.0 core:select-all (input.hidden-input)
     -1:38.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ayu 0.1.0 
ide-css 0.2.0 
ide-html 0.4.1 
ide-json 0.1.0 
ide-typescript 0.7.0 
nuclide 0.268.0 
```

**Comment by hansonw** [comment]
I am guessing that one of ide-css/html is returning invalid URIs :( Unfortunately these are not likely to be compatible with our context view. Sorry!
