### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by shiny** [facebook/nuclide#1385]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.268.0

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2388

TypeError: Cannot match against 'undefined' or 'null'.
    at TextEditorComponent.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:2388:65)
    at TextEditorComponent.screenPositionForMouseEvent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1953:23)
    at HyperclickForTextEditor._getMousePositionAsBufferPosition (/packages/nuclide/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:322:38)
    at HyperclickForTextEditor._onMouseMove (/packages/nuclide/modules/atom-ide-ui/pkg/hyperclick/lib/HyperclickForTextEditor.js:186:88)
```

### Commands

```
  2x -1:37.9.0 core:backspace (input.hidden-input)
     -1:36.6.0 core:move-left (input.hidden-input)
  4x -1:20.6.0 core:move-right (input.hidden-input)
     -1:16.4.0 core:move-down (input.hidden-input)
     -1:16 autocomplete-plus:cancel (input.hidden-input)
     -1:15.8.0 core:move-down (input.hidden-input)
  4x -1:15.5.0 core:move-right (input.hidden-input)
     -1:02.2.0 core:cut (input.hidden-input)
     -0:49.9.0 core:paste (input.hidden-input)
     -0:48.4.0 core:move-right (input.hidden-input)
 38x -0:31 core:undo (input.hidden-input)
  3x -0:25.3.0 core:redo (input.hidden-input)
 28x -0:23.8.0 core:undo (input.hidden-input)
  3x -0:12.5.0 core:redo (input.hidden-input)
  5x -0:10.8.0 core:undo (input.hidden-input)
  3x -0:07.7.0 core:redo (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-ide-ui 0.5.4 
dash 1.7.1 
ide-php 0.6.10 
ide-typescript 0.7.0 
language-nginx 0.8.0 
language-vue 0.23.1 
language-vue-component 0.5.0 
nuclide 0.268.0 
nuclide-format-js 0.0.41 
```

**Comment by hansonw** [comment]
Seems like an issue with the core Atom API `screenPositionForMouseEvent`. Please track 
 https://github.com/atom/atom/issues/15682 instead
