### ISSUE TITLE
Uncaught Invariant Violation: Minified React error #149

### ISSUE THREAD

**Issue by awilkins** [facebook/nuclide#1386]
1. Clicked the button to add a new working set
2. Error fires
3. Entire content of Nuclide file tree disappears

**Atom**: 1.23.0-beta1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.268.0

### Stack Trace

Uncaught Invariant Violation: Minified React error #149; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=149&args[]=input for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

```
At /home/awilkins/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43

Invariant Violation: Minified React error #149; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=149&args[]=input for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:12:224)
    at Me (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:124:445)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:129:479)
    at Ca (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:132:473)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:137:206
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:147:110)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:147:42)
    at beginWork (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:151:403)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:182:356)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:183:362)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:184:367)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:188:412)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:187:423)
    at Object.enqueueSetState (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:140:182)
    at VirtualizedFileTree.v.setState (/packages/nuclide/node_modules/react/cjs/react.production.min.js:12:357)
    at VirtualizedFileTree._processStoreUpdate (/packages/nuclide/pkg/nuclide-file-tree/components/VirtualizedFileTree.js:283:10)
    at _disposables.add._store.subscribe (/packages/nuclide/pkg/nuclide-file-tree/components/VirtualizedFileTree.js:192:60)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:605:21)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:43:337)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:42:227)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at requestAnimationFrame (/packages/atom-ide-ui/modules/nuclide-commons/observable.js:372:14)
```

### Commands

```
     -5:53.3.0 core:confirm (input.hidden-input)
  7x -5:53.3.0 blur (input.hidden-input)
     -5:49.3.0 vim-mode-plus:activate-insert-mode (input.hidden-input)
  6x -5:48.1.0 core:backspace (input.hidden-input)
     -5:43.9.0 intentions:highlight (input.hidden-input)
     -5:43.9.0 core:save (input.hidden-input)
  5x -5:42.8.0 blur (input.hidden-input)
     -3:47.6.0 nuclide-file-tree:remove (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory)
 13x -3:45.6.0 blur (div.list-tree.has-collapsable-children.file-tree-scroller.nuclide-file-tree.focusable-panel.tree-view)
     -0:57.7.0 command-palette:toggle (atom-pane.pane)
  2x -0:57.6.0 blur (atom-pane.pane)
 19x -0:54.5.0 core:backspace (input.hidden-input)
     -0:52.8.0 settings-view:open (input.hidden-input)
  8x -0:52.6.0 blur (input.hidden-input)
     -0:48.2.0 core:confirm (input.hidden-input)
  9x -0:44.1.0 blur (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-ide-ui 0.6.0 
atom-jinja2 0.6.0 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
autocomplete-python 1.10.3 
busy-signal 1.4.3 
cucumber-autocomplete 0.7.2 
editorconfig 2.2.2 
ex-mode 0.18.0 
file-icons 2.1.14 
file-types 0.5.5 
floobits 0.32.12 
flow-ide 1.9.0 
go-debug 1.5.2 
go-plus 5.6.0 
go-signature-statusbar 1.2.3 
graphviz-preview-plus 1.5.2 
highlight-selected 0.13.1 
ide-css 0.2.0 
ide-flowtype 0.17.4 
ide-go 0.4.0 
ide-html 0.4.1 
ide-python 0.3.0 
ide-typescript 0.7.0 
ide-yaml 0.4.1 
intentions 1.1.5 
language-ansible 0.2.1 
language-babel 2.79.0 
language-docker 1.1.8 
language-dot 1.7.0 
language-gherkin 1.0.4 
language-groovy 0.7.0 
language-markdown 0.25.1 
language-nginx 0.8.0 
language-nunjucks 4.1.0 
language-puppet 0.23.0 
language-terraform 0.8.1 
linter 2.2.0 
linter-ansible-linting 1.3.1 
linter-docker 0.2.1 
linter-eslint 8.4.0 
linter-sass-lint 1.8.3 
linter-shellcheck 1.4.6 
linter-terraform-semantics 0.2.0 
linter-terraform-syntax 1.2.1 
linter-ui-default 1.6.10 
markdown-preview-plus 2.4.16 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
narrow 0.53.2 
nuclide 0.268.0 
regex-railroad-diagram 0.19.4 
teletype 0.1.4 
vim-mode-plus 1.20.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
wordcount 2.10.4 
```

**Comment by shushz** [comment]
At this moment I suspect an interop problem with one of the other packages. Mainly because you'd expect this error to be consistent, yet I can't repo it (on Atom 1.23-beta1)
