### ISSUE TITLE
Uncaught InterngraphError: InterngraphError: 

### ISSUE THREAD

**Issue by jyotiblack** [facebook/nuclide#1396]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.270.81972311

### Stack Trace

Uncaught InterngraphError: InterngraphError: 

```
At /opt/facebook/nuclide/0.257.73181069/nuclide/node_modules/rxjs/bundles/Rx.min.js:69

InterngraphError: InterngraphError: 
    at /opt/facebook/nuclide/0.270.81972311/nuclide/pkg/commons-node/fb-interngraph.js:33:13
    at Generator.next (<anonymous>)
    at step (/opt/facebook/nuclide/0.257.73181069/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at _next (/opt/facebook/nuclide/0.257.73181069/nuclide/node_modules/async-to-generator/async-to-generator.js:24:9)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.14 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.80.1 
language-graphql 0.9.0 
language-haskell 1.14.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.270.81972311 
nuclide-format-js 0.0.41 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.0 
```

**Comment by pelmers** [comment]
Please keep internal bugs to internal tasks :)
Thanks!
