### ISSUE TITLE
Uncaught Error: Ensure Node was launched with --inspect. Cannot connect to runtime process, timeo...

### ISSUE THREAD

**Issue by kmwarter** [facebook/nuclide#1398]
[Enter steps to reproduce:]

1. ...Fire up app on localhost port
2. ...Try to use that port to run debugger

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.270.0

### Stack Trace

Uncaught Error: Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).

```
At /Users/crux/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:23

Error: Ensure Node was launched with --inspect. Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).
    at send.then.errorResponse (/packages/nuclide/pkg/nuclide-debugger-common/lib/VsDebugSession.js:166:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Commands

```
     -9:33.3.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -7:58.8.0 nuclide-debugger:show-attach-dialog (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -7:39.5.0 core:confirm (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
  3x -7:39.5.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
     -1:14.6.0 nuclide-debugger:show-attach-dialog (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:02.1.0 core:confirm (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:02.1.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
color-picker 2.2.5 
editorconfig 2.2.2 
file-icons 2.1.13 
language-babel 2.75.1 
language-pug 0.0.21 
nuclide 0.270.0 
pigments 0.40.2 
```

**Comment by spacecat7** [comment]
Running into the same issue when trying to connect to 8081
