### ISSUE TITLE
Uncaught Error: Cannot launch program '{path}' because corresponding JavaScript cannot be found.

### ISSUE THREAD

**Issue by PrinceP** [facebook/nuclide#1403]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.270.0

### Stack Trace

Uncaught Error: Cannot launch program '{path}' because corresponding JavaScript cannot be found.

```
At C:\Users\Prince\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:23

Error: Cannot launch program '{path}' because corresponding JavaScript cannot be found.
    at send.then.errorResponse (/packages/nuclide/pkg/nuclide-debugger-common/lib/VsDebugSession.js:166:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Commands

```
     -2:30.1.0 file:copy-full-path (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-text)
     -2:26.8.0 nuclide-terminal:new-terminal (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-text)
  2x -0:48.4.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:43.3.0 nuclide-debugger:show-launch-dialog (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 10x -0:29.5.0 core:backspace (input.hidden-input)
     -0:17.3.0 core:confirm (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:16.9.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
autocomplete-modules 1.8.0 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.0 
linter-flow 5.6.1 
linter-ui-default 1.6.10 
nuclide 0.270.0 
```

**Comment by mostafaeweda** [comment]
Your installed node version is probably old -- it should be `>= v7.4.0`
