### ISSUE TITLE
Uncaught Error: Please save all open files before trying to refactor a Hack file.

### ISSUE THREAD

**Issue by zacharylayne** [facebook/nuclide#1404]
[Enter steps to reproduce:]

1. Open Nuclide.
2. Wait.

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.270.81972311

### Stack Trace

Uncaught Error: Please save all open files before trying to refactor a Hack file.

```
At C:\ProgramData\nuclide\0.252.70996414\nuclide\node_modules\rxjs\bundles\Rx.min.js:69

Error: Please save all open files before trying to refactor a Hack file.
    at checkWorkspaceModified (C:/ProgramData/nuclide/0.270.81972311/nuclide/pkg/fb-hackast-refactorizer/lib/main.js:51:13)
    at Object.refactoringsAtPoint (C:/ProgramData/nuclide/0.270.81972311/nuclide/pkg/fb-hackast-refactorizer/lib/main.js:65:9)
    at C:/ProgramData/nuclide/0.270.81972311/nuclide/pkg/nuclide-refactorizer/lib/main.js:164:44
    at Generator.next (<anonymous>)
    at step (C:/ProgramData/nuclide/0.252.70996414/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at _next (C:/ProgramData/nuclide/0.252.70996414/nuclide/node_modules/async-to-generator/async-to-generator.js:24:9)
```

### Commands

```
     -2:09.8.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui)
     -2:01.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-atom-light-ui)
     -1:54.5.0 nuclide-file-tree:reveal-active-file (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-text.default-icon)
     -1:33.3.0 outline-view:toggle (div.list-tree.has-collapsable-children.file-tree-scroller.nuclide-file-tree.focusable-panel.tree-view)
  4x -0:14.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
file-icons 2.1.11 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.74.2 
language-graphql 0.9.0 
language-haskell 1.14.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-ui-default 1.6.10 
MagicPython 1.0.12 
nuclide 0.270.81972311 
nuclide-format-js 0.0.41 
omnisharp-atom 0.31.2 
set-syntax 0.4.0 
sort-lines 0.15.0 
tool-bar 1.1.0 
```

**Comment by pelmers** [comment]
hi, please report facebook internal (e.g. hack refactor) issues with the bug icon at the bottom left
