### ISSUE TITLE
Uncaught Error: Invariant violation: "unpublishedWorkData != null"

### ISSUE THREAD

**Issue by ramonfritsch** [facebook/nuclide#1405]
[Enter steps to reproduce:]

1. Click on 'Toggle On Demand' on Nuclide's sidebar
2. On the modal, filter by 'Archived'

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.270.81972311

### Stack Trace

Uncaught Error: Invariant violation: "unpublishedWorkData != null"

```
At /opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:185

Error: Invariant violation: "unpublishedWorkData != null"
    at SavedWorkView._applyRepoFilterToWorkDataByCategory (/opt/facebook/nuclide/0.270.81972311/nuclide/pkg/fb-on-demand/lib/ui/SavedWorkView.js:177:15)
    at SavedWorkView._getFilteredWorkDataByCategory (/opt/facebook/nuclide/0.270.81972311/nuclide/pkg/fb-on-demand/lib/ui/SavedWorkView.js:150:17)
    at SavedWorkView.render (/opt/facebook/nuclide/0.270.81972311/nuclide/pkg/fb-on-demand/lib/ui/SavedWorkView.js:228:45)
    at k (/opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:147:346)
    at beginWork (/opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:150:341)
    at e (/opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:182:356)
    at k (/opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:183:362)
    at p (/opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:184:367)
    at batchedUpdates (/opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:190:267)
    at qb (/opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:41:344)
    at ob (/opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:41:278)
    at Object.batchedUpdates (/opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:42:85)
    at dispatchEvent (/opt/facebook/nuclide/0.270.81972311/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:45:162)
```

### Commands

```
     -1:28.8.0 nuclide-file-tree:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:27.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:21.8.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:17.1.0 core:close (button.pull-right.nuclide-home-tryit.btn.btn-sm)
     -1:15 nuclide-console:toggle (input.hidden-input)
     -1:03.8.0 core:cancel (div.)
     -0:49.9.0 fb-biggrep:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:45.5.0 core:close (atom-pane.pane.active)
     -0:41.3.0 fb-on-demand:saved-work (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.14 
highlight-selected 0.13.1 
language-babel 2.80.3 
language-graphql 0.9.0 
language-haskell 1.14.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.270.81972311 
nuclide-format-js 0.0.41 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.0 
```

**Comment by pelmers** [comment]
this is a facebook-internal issue, please open a task/file bug through the bug icon at the bottom left
