### ISSUE TITLE
Uncaught Error: Cannot find module '../../commons-node/fb-node-run.sh'

### ISSUE THREAD

**Issue by ben-z** [facebook/nuclide#1412]
### Steps to reproduce

1. Open settings for the Nuclide package under Atom settings - packages.
2. Check "Use RPC for local services."
3. Restart Atom.

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.271.0

### Stack Trace

Uncaught Error: Cannot find module '../../commons-node/fb-node-run.sh'

```
At /Users/ben/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:69

Error: Cannot find module '../../commons-node/fb-node-run.sh'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Function.require.resolve (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:69:35)
    at createLocalRpcClient (/packages/nuclide/pkg/nuclide-remote-connection/lib/service-manager.js:108:29)
    at getlocalService (/packages/nuclide/pkg/nuclide-remote-connection/lib/service-manager.js:132:24)
    at getServiceByConnection (/packages/nuclide/pkg/nuclide-remote-connection/lib/service-manager.js:177:12)
    at /packages/nuclide/pkg/nuclide-flow/lib/main.js:43:114)
    at Generator.next (<anonymous>)
    at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:29:7
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12)
    at /packages/nuclide/pkg/nuclide-flow/lib/main.js:64:18)
    at ConnectionCache.get (/packages/nuclide/modules/nuclide-commons/cache.js:26:29)
    at ConnectionCache (/packages/nuclide/pkg/nuclide-remote-connection/lib/ConnectionCache.js:54:12)
    at /packages/nuclide/pkg/nuclide-flow/lib/main.js:13:25)
    at Generator.next (<anonymous>)
    at step (/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:29:7
    at /packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12)
    at Object.activate (/packages/nuclide/pkg/nuclide-flow/lib/main.js:37:17)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:255:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:1068:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:717:40)
    at Promise.all.then (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:650:18)
```

### Commands

```
     -0:11.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-keyboard-macros-vim 0.1.6 
editorconfig 2.2.2 
ex-mode 0.18.0 
file-icons 2.1.15 
fonts 3.0.3 
highlight-selected 0.13.1 
language-babel 2.81.0 
language-graphql 0.9.0 
language-haskell 1.16.2 
language-ini 1.19.0 
language-lua 0.9.11 
language-mips 0.3.0 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
linter-eslint 8.4.0 
MagicPython 1.0.12 
nuclide 0.271.0 
nuclide-format-js 0.0.43 
prettier-atom 0.43.1 
relative-numbers 0.8.0 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.0 
vim-mode-plus 1.24.3 
```

**Comment by ben-z** [comment]
This issue seems to go away when I disable `nuclide-flow`.

**Comment by bitcrumb** [comment]
I'm seeing the same error. Unchecking "Use RPC for local services" indeed makes the error go away.

**Comment by Jpunt** [comment]
Is there a way to get around this issue, and actually use flow?

**Comment by ben-z** [comment]
@Jpunt This issue appeared for me when I enabled `Use RPC for local services` as an attempt to make Atom less laggy. As @bitcrumb said, disabling it allows me to use `nuclide-flow` normally.

**Comment by Jpunt** [comment]
Ah great, thanks 👍

**Comment by derwaldgeist** [comment]
I'm getting this error without having the `nuclide-flow` package installed. Disabling `Use RPC for local services` solved the problem, though. Thanks for the hint.

**Comment by chmac** [comment]
Where is the `Use RCP for local services` option? I don't see it anywhere in nuclide settings (filtering for `rpc`), nor in Atom's settings screen.

**Comment by Jpunt** [comment]
@chmac it's underneath the collapsable sections in the Nuclide-settings: 

![screen shot 2017-12-20 at 12 58 24](https://user-images.githubusercontent.com/190501/34206143-8a221b34-e585-11e7-9512-cc044f74ea99.png)

(I've been looking for while as well)

**Comment by kevinsimper** [comment]
I did not do anything but install Nuclide and could not find the option to disable `Use RPC for local services`

**Comment by squirmsound** [comment]
I was able to fix this issue by installing `flow-ide` and uninstalling `atom-ide-ui`.

**Comment by MihaiDamian** [comment]
How can I disable nuclide-flow? I don't see an explicit setting for this.

**Comment by sunjay** [comment]
Seems to be fixed (at least for me) by updating to the latest nuclide v0.273.0

**Comment by a7madgamal** [comment]
yep its fixed

**Comment by ben-z** [comment]
Can confirm! I'm going to close this issue 😄
