### ISSUE TITLE
nuclide server won't start so atom can't connect

### ISSUE THREAD

**Issue by solomonkinard** [facebook/nuclide#1416]
### Issue and Steps to Reproduce
$ /usr/local/lib/node_modules/nuclide/pkg/nuclide-server/nuclide-start-server -k -v

### Expected Behavior
No errors

### Actual Behavior
2017-12-20 20:57:22,776 - root - INFO - Invoked nuclide_server_manager...
2017-12-20 20:57:22,776 - NuclideServerManager - INFO - NuclideServerManager was created with these options: {'certs_dir': None, 'json_output_file': None, 'timeout': 10, 'dump_core': True, 'insecure': True, 'inspect': False, 'quiet': False, 'debug': False, 'version': None, 'command': 'start', 'workspace': None, 'common_name': None, 'port': None, 'verbose': True}
2017-12-20 20:57:22,777 - NuclideServerManager - INFO - Starting to clean up old Nuclide processes/files.
2017-12-20 20:57:22,786 - NuclideServerManager - INFO - Cleaning up old certificate files...
2017-12-20 20:57:22,787 - NuclideServerManager - INFO - Finished cleaning up old Nuclide processes/files.
2017-12-20 20:57:22,787 - root - WARNING - Failed to clean up old core dumps ([Errno 2] No such file or directory: '/var/tmp/cores')
2017-12-20 20:57:22,787 - NuclideServerManager - INFO - Trying to determine the port to use for Nuclide server...
2017-12-20 20:57:22,796 - NuclideServerManager - INFO - Found an open port: 9090.
2017-12-20 20:57:22,797 - NuclideServerManager - INFO - Initialized NuclideServer.
2017-12-20 20:57:22,802 - NuclideServerManager - INFO - Starting NuclideServer...
2017-12-20 20:57:22,803 - NuclideServerManager - INFO - Using http.
2017-12-20 20:57:22,803 - NuclideServer - INFO - NuclideServer start/restarting with the following arguments:
              timeout: 10
              cert:    None
              key:     None
              ca:      None
              force:   False
              quiet:   False
              debug:   False
              inspect: False
              expiration_days: None
2017-12-20 20:57:22,814 - NuclideServer - INFO - Opening node server subprocess.
2017-12-20 20:57:22,816 - NuclideServer - INFO - Trying to ping the Nuclide server...
2017-12-20 20:57:33,079 - NuclideServer - ERROR - Attempted to start Nuclide server on port 9090, but timed out after 10 seconds.
{"logs": ["2017-12-20 20:57:22,776 - root - INFO - Invoked nuclide_server_manager...", "2017-12-20 20:57:22,776 - NuclideServerManager - INFO - NuclideServerManager was created with these options: {'certs_dir': None, 'json_output_file': None, 'timeout': 10, 'dump_core': True, 'insecure': True, 'inspect': False, 'quiet': False, 'debug': False, 'version': None, 'command': 'start', 'workspace': None, 'common_name': None, 'port': None, 'verbose': True}", "2017-12-20 20:57:22,777 - NuclideServerManager - INFO - Starting to clean up old Nuclide processes/files.", "2017-12-20 20:57:22,786 - NuclideServerManager - INFO - Cleaning up old certificate files...", "2017-12-20 20:57:22,787 - NuclideServerManager - INFO - Finished cleaning up old Nuclide processes/files.", "2017-12-20 20:57:22,787 - root - WARNING - Failed to clean up old core dumps ([Errno 2] No such file or directory: '/var/tmp/cores')", "2017-12-20 20:57:22,787 - NuclideServerManager - INFO - Trying to determine the port to use for Nuclide server...", "2017-12-20 20:57:22,796 - NuclideServerManager - INFO - Found an open port: 9090.", "2017-12-20 20:57:22,797 - NuclideServerManager - INFO - Initialized NuclideServer.", "2017-12-20 20:57:22,802 - NuclideServerManager - INFO - Starting NuclideServer...", "2017-12-20 20:57:22,803 - NuclideServerManager - INFO - Using http.", "2017-12-20 20:57:22,803 - NuclideServer - INFO - NuclideServer start/restarting with the following arguments:\n              timeout: 10\n              cert:    None\n              key:     None\n              ca:      None\n              force:   False\n              quiet:   False\n              debug:   False\n              inspect: False\n              expiration_days: None", "2017-12-20 20:57:22,814 - NuclideServer - INFO - Opening node server subprocess.", "2017-12-20 20:57:22,816 - NuclideServer - INFO - Trying to ping the Nuclide server...", "2017-12-20 20:57:33,079 - NuclideServer - ERROR - Attempted to start Nuclide server on port 9090, but timed out after 10 seconds."], "success": false}
The log file can be found at /tmp/nuclide-s-logs/server-start/nuclide-2017-12-20T20:57:22.nohup.out.

$ cat /tmp/nuclide-s-logs/server-start/nuclide-2017-12-20T20:57:22.nohup.out
/usr/local/lib/node_modules/nuclide/pkg/commons-node/load-transpiler.js:18
const {__DEV__} = require('../../modules/nuclide-node-transpiler/lib/env');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nuclide/pkg/nuclide-server/lib/nuclide-main.js:24:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

### Versions
* Atom:
* Nuclide: 0.272.0 (doesn't connect to nuclide server)
node: v4.2.6
npm: 3.5.2
* Client OS: Mac Sierra
* Server OS (optional): Ubuntu 16.05

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by aradabir007** [comment]
same error here

**Comment by swiftcoder** [comment]
Your version of node appears to be too old, and it's rejecting the modern require syntax as a result. Try upgrading to a recent (7.x or newer) nodejs.

**Comment by JianCao92** [comment]
I'm experiencing the same error here too. Any help will be appreciated!
