### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by siremurray** [facebook/nuclide#1422]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0-beta1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.273.0

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:160

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:294:12)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Channel.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Channel.Readable.push (_stream_readable.js:134:10)
    at /packages/nuclide/node_modules/ssh2/lib/Channel.js:166:15)
    at emitOne (events.js:96:13)
    at SSH2Stream.emit (events.js:188:7)
    at parsePacket (/packages/nuclide/node_modules/ssh2-streams/lib/ssh.js:3444:10)
    at SSH2Stream._transform (/packages/nuclide/node_modules/ssh2-streams/lib/ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/packages/nuclide/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at SSH2Stream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.15 
highlight-selected 0.13.1 
language-babel 2.81.1 
language-graphql 0.9.0 
language-haskell 1.16.2 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
minimap 4.29.7 
nuclide 0.273.0 
nuclide-format-js 0.0.43 
one-sharp-syntax 3.0.0 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.0 
```

**Comment by siremurray** [comment]
I get disconnected repeatedly at random times. I have to restart atom before I can remotely connect again. The remote connection is to a VM.
