### ISSUE TITLE
Uncaught Error: Remote Error: Expected a string argumentError marshalling value: '6'stringFiel...

### ISSUE THREAD

**Issue by xuemao** [facebook/nuclide#1427]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.273.85332531

### Stack Trace

Uncaught Error: Remote Error: Expected a string argument
Error marshalling value: '6'
string
Field: projectId
object
ArcProjectInfo
named
nullable
 processing message {"protocol":"service_framework3_rpc","type":"call","method":"ArcanistService/findArcProjectIdAndDirectory","id":13,"args":{"fileName":"/Users/mao/code/Titan"}}
"AssertionError: Expected a string argument\n    at stringTransformer (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:322:27)\n    at Object.marshaller (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:805:14)\n    at TypeRegistry._marshal (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:263:27)\n    at type.fields.map.prop (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:595:28)\n    at Array.map (native)\n    at _registerKind (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:580:58)\n    at Object.marshaller (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:805:14)\n    at TypeRegistry._marshal (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:263:27)\n    at registerType (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:245:64)\n    at Object.marshaller (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:816:14)"

```
At /opt/facebook/nuclide/0.273.85332531/nuclide/node_modules/rxjs/bundles/Rx.min.js:34

AssertionError: Expected a string argument
    at stringTransformer (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:322:27)
    at Object.marshaller (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:805:14)
    at TypeRegistry._marshal (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:263:27)
    at type.fields.map.prop (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:595:28)
    at Array.map (native)
    at _registerKind (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:580:58)
    at Object.marshaller (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:805:14)
    at TypeRegistry._marshal (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:263:27)
    at registerType (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:245:64)
    at Object.marshaller (/opt/facebook/nuclide/0.273.85332531/nuclide/pkg/nuclide-rpc/lib/TypeRegistry.js:816:14)
```

### Commands

```
     -0:05.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-ide-ui 0.7.0 
file-icons 2.1.15 
goto-definition 1.3.4 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.81.0 
language-graphql 0.9.0 
language-haskell 1.16.2 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.273.85332531 
nuclide-format-js 0.0.43 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.0 
vim-mode-plus 1.24.3 
vim-mode-plus-ex-mode 0.11.0 
```

**Comment by pelmers** [comment]
Since this is a facebook-specific error, please file a bug with the internal task tool, thanks! (there is bug icon at the bottom left of the window)
