### ISSUE TITLE
Remote Terminal shows cannot find module, but can edit the file system.

### ISSUE THREAD

**Issue by VinayakBagaria** [facebook/nuclide#1431]
### Issue and Steps to Reproduce
I am not able to open terminal when connected to a remote server via Nuclide. Although, I can edit the files and those changes do reflect in the remote file.

Try connecting to a remote directory.
Select 'Open Terminal Here' from the Context Menu. It shows :
![screenshot from 2018-01-04 21-38-02](https://user-images.githubusercontent.com/17192467/34572645-e5b9ba4c-f197-11e7-9978-cdc0623b7174.png)

### Expected Behavior
Terminal should open, which allows remote command line interfacing.

### Actual Behavior
See response in the image above.

### Versions
* Atom: 1.23.2
* Nuclide: 0.273.0
* Client OS: Ubuntu 17.10
* Server OS : Ubuntu 16.04.3 LTS

### Additional Details
* Installed packages (`apm ls --installed`):
├── MagicPython@1.0.12
├── ask-stack@2.2.0
├── autocomplete-clang@0.11.4
├── build@0.70.0
├── busy-signal@1.4.3
├── css-snippets@1.1.0
├── d3-snippets@1.2.1
├── emmet@2.4.3
├── es6-snippets@0.3.0
├── file-icons@2.1.15
├── flow-ide@1.9.0
├── highlight-selected@0.13.1
├── hyperclick@0.1.5
├── intentions@1.1.5
├── javascript-snippets@1.2.1
├── language-babel@2.81.1
├── language-graphql@0.9.0
├── language-haskell@1.17.2
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-ui-default@1.6.10
├── minimap@4.29.7
├── nuclide@0.273.0
├── nuclide-format-js@0.0.43
├── platformio-ide-terminal@2.8.0
├── prettier-atom@0.45.0
├── pretty-json@1.6.4
├── react-native-snippets@0.3.0
├── react-snippets@1.0.1
├── scss-snippets@0.6.0
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── teletype@0.5.0
├── todo-show@2.1.0
├── tool-bar@1.1.0
├── vue-atom-snippets@1.0.0
└── vue-snippets@0.6.0

**Comment by DanielKristofKiss** [comment]
I got the same:
- Atom 1.23.2
- Nuclide 0.275.0
- Client Os: MacOs 10.13.2
- Server Os: Ubuntu 16.04.3

**Comment by TheBirdie** [comment]
Same with;
- Atom 1.23.3
- Nuclide 0.275.0
- Client Os: Ubuntu 16.04
- Server Os: Ubuntu 16.04

**Comment by TheBirdie** [comment]
I've got a workaround if anyone is interested:
1. Clone pty repo (https://github.com/chjj/pty.js)
2. `cd pty && npm install`
3. Create the folder missing from your error message (`.../nuclide/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.0.2-node-v59-linux-x64` for me)
4. Copy inside the binary generated in step (2) `pty.js/build/Release/pty.node`

.. or use an old NodeJS version corresponding to the ABI version 51 (see here https://nodejs.org/en/download/releases/)

**Comment by tim-soft** [comment]
I'm also hitting this wall! It looks like the **remote** terminal function relies on an unmaintained lib that doesn't support newer node versions. Maybe Nuclide could use this fork of the project as an alternative?

https://github.com/Tyriar/node-pty

- Atom 1.24.0
- Nuclide 0.286.0
- Node 9.6.1 

```
Error starting process:
    Error: Remote Error: Cannot find module '/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.2-node-v59-linux-x64/pty.node'
processing message {
    "protocol": "service_framework3_rpc",
    "type": "call",
    "method": "PtyService/spawn",
    "id": 26,
    "args": {
        "info": {
            "terminalType": "xterm-256color",
            "environment": [],
            "cwd": "/srv/node/wildsports-portal"
        },
        "client": -6
    }
}
```

```
Error: Cannot find module '/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.2-node-v59-linux-x64/pty.node'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/pty/lib/unixTerminal.js:17:11)
    at Module._compile (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/pty/lib/index.js:9:16)
    at Module._compile (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at _load_pty (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/pkg/nuclide-pty-rpc/lib/PtyService.js:170:41)
    at new PtyImplementation (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/pkg/nuclide-pty-rpc/lib/PtyService.js:236:38)
    at RpcConnection.<anonymous> (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/pkg/nuclide-pty-rpc/lib/PtyService.js:23:12)
    at Generator.next (<anonymous>)
    at step (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at _next (/root/.nvm/versions/node/v9.6.1/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:24:9)
    at <anonymous>
```

**Comment by paulchill** [comment]
is this fixed?

**Comment by rwatts3** [comment]
having the same issue, and it's been this way for at least a month, just curious if there is a solution.

**Comment by shrey150** [comment]
I ran "Application: Install Update" from Atom and this error started occurring and I'm having problems with doing the workaround, is there a definitive solution to this?

**Comment by lagurohit** [comment]
same here. Node version is 6.9.1 and atom 1.28

**Comment by dotku** [comment]
I manually download the pty version from here https://github.com/daviwil/node-pty-prebuilt

then I got error with function: 
```
Error starting process:
Error: Remote Error: Usage: pty.fork(file, args, env, cwd, cols, rows, uid, gid, utf8, onexit) processing message {"protocol":"service_framework3_rpc","type":"call","method":"PtyService/spawn","id":27,"args":{"info":{"terminalType":"xterm-256color","environment":[],"cwd":"/usr/share/nginx/react-es/"},"client":-4}}
"Error: Usage: pty.fork(file, args, env, cwd, cols, rows, uid, gid, utf8, onexit)\n    at new UnixTerminal (/home/ec2-user/.nvm/versions/node/v10.11.0/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/pty/lib/unixTerminal.js:53:24)\n    at Object.spawn (/home/ec2-user/.nvm/versions/node/v10.11.0/lib/node_modules/nuclide/node_modules/nuclide-prebuilt-libs/pty/lib/index.js:12:12)\n    at new PtyImplementation (/home/ec2-user/.nvm/versions/node/v10.11.0/lib/node_modules/nuclide/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/pty-service/PtyService.js:247:42)\n    at RpcConnection.spawn (/home/ec2-user/.nvm/versions/node/v10.11.0/lib/node_modules/nuclide/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/pty-service/PtyService.js:120:10)"
```
