### ISSUE TITLE
Failed to load the nuclide package. Problem reading log4js config

### ISSUE THREAD

**Issue by tomchambers2** [facebook/nuclide#1439]
### Issue and Steps to Reproduce
Installed through atom package manager UI. Restarted atom, got this error.

### Expected Behavior
Throws error and doesn't load

### Actual Behavior
Should load without error

### Additional Details
**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.277.0

### Stack Trace

Failed to load the nuclide package

```
At Problem reading log4js config { appenders: 
   [ { type: '/Users/tomchambers/.atom/packages/nuclide/pkg/nuclide-logging/VendorLib/fileAppender.js',
       filename: '/var/folders/7r/stkk_66d0gj686vq7h0fw2tr0000gn/T/nuclide-tomchambers-logs/nuclide.log',
       maxLogSize: 1048576,
       backups: 10,
       layout: [Object] },
     { type: 'logLevelFilter', level: 'WARN', appender: [Object] },
     { type: 'logLevelFilter', level: 'ALL', appender: [Object] } ] }. Error was "Cannot find module './internal/streams/stream'" (Error: Cannot find module './internal/streams/stream'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/tomchambers/.atom/packages/nuclide/node_modules/readable-stream/lib/_stream_readable.js:50:14)
    at Object.<anonymous> (/Users/tomchambers/.atom/packages/nuclide/node_modules/readable-stream/lib/_stream_readable.js:1008:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/tomchambers/.atom/packages/autocomplete-json/node_modules/readable-stream/readable.js:12:30)
    at Object.<anonymous> (/Users/tomchambers/.atom/packages/autocomplete-json/node_modules/readable-stream/readable.js:21:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/tomchambers/.atom/packages/nuclide/node_modules/streamroller/lib/BaseRollingFileStream.js:8:12)
    at Object.<anonymous> (/Users/tomchambers/.atom/packages/nuclide/node_modules/streamroller/lib/BaseRollingFileStream.js:129:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3))

Error: Problem reading log4js config { appenders: 
   [ { type: '/Users/tomchambers/.atom/packages/nuclide/pkg/nuclide-logging/VendorLib/fileAppender.js',
       filename: '/var/folders/7r/stkk_66d0gj686vq7h0fw2tr0000gn/T/nuclide-tomchambers-logs/nuclide.log',
       maxLogSize: 1048576,
       backups: 10,
       layout: [Object] },
     { type: 'logLevelFilter', level: 'WARN', appender: [Object] },
     { type: 'logLevelFilter', level: 'ALL', appender: [Object] } ] }. Error was "Cannot find module './internal/streams/stream'" (Error: Cannot find module './internal/streams/stream'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/nuclide/node_modules/readable-stream/lib/_stream_readable.js:50:14)
    at /packages/nuclide/node_modules/readable-stream/lib/_stream_readable.js:1008:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/autocomplete-json/node_modules/readable-stream/readable.js:12:30)
    at /packages/autocomplete-json/node_modules/readable-stream/readable.js:21:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/nuclide/node_modules/streamroller/lib/BaseRollingFileStream.js:8:12)
    at /packages/nuclide/node_modules/streamroller/lib/BaseRollingFileStream.js:129:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3))
    at configureOnceOff (/packages/nuclide/node_modules/log4js/lib/log4js.js:321:13)
    at Object.configure (/packages/nuclide/node_modules/log4js/lib/log4js.js:376:3)
    at exports.initializeLogging (/packages/nuclide/pkg/nuclide-logging/lib/main.js:63:39)
    at /packages/nuclide/pkg/commons-node/once.js:27:21
    at /packages/nuclide/lib/main.js:114:67)
    at /packages/nuclide/lib/main.js:399:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/nuclide/lib/main-entry.js:33:18)
    at /packages/nuclide/lib/main-entry.js:35:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at config.transact (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:531:20)
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:342:22)
```

### Commands

```
     -0:06.3.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
busy-signal 1.4.3 
console-log 1.10.0 
emmet 2.4.3 
file-icons 2.1.16 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.81.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
nuclide 0.277.0 
nuclide-format-js 0.0.43 
prettier-atom 0.48.0 
set-syntax 0.4.0 
Sublime-Style-Column-Selection 1.7.4 
```

**Comment by zaguini** [comment]
Got it on 0.279.0

**Comment by ViktorAksionov** [comment]
Any fix? I got this error after updating nuclide to version 0.284.0

**Comment by ViktorAksionov** [comment]
Uninstalling nuclide and installing it again fixed this issue.

**Comment by mnapoleon** [comment]
For me this happened after 0.285.0 update appeared to freeze and I shut Atom down.  Removed nuclide and reinstalled fixed it

**Comment by toblerpwn** [comment]
Seeing this 0.300.0

**Comment by wellyshen** [comment]
Me too and reinstall won't fix this issue.

**Comment by irrigator** [comment]
In 0.300.0 the error message is
>(_collection || _load_collection(...)).DefaultMap is not a constructor

**Comment by jacktator** [comment]
Same issue, started throwing in 0.300.0 

OSX: 10.13.4
Atom: 1.26.0 x64

**Comment by russoue** [comment]
I am having the same problem with 0.300.0 on OS X 10.13.4 and Atom 1.26.  I tried to uninstall and re-install but that did not help.

**Comment by kockok** [comment]
Sad to downgrade to nuclide@0.299.0....

**Comment by zzyhdu** [comment]
apm uninstall nuclide && apm install nuclide@0.299.0 fixed this issue

**Comment by ferpalma21** [comment]
Have this problem (_collection || _load_collection(...)).DefaultMap is not a constructor

**Comment by KitsGithub** [comment]
apm install nuclide@0.299.0 can fix this problem

**Comment by FabioFelizzi** [comment]
Has there been any updates yet? I know using 299.0 is a viable solution for now but I can't be the only one who finds that "1 update" notification annoying :P

**Comment by ferpalma21** [comment]
The only way I found to fix it is going back to the version 0.299.0; if you want to go back you can do it like:

```
 apm install <nameOfThePackage>@<version>
 apm install nuclide@0.299.0
```
@FabioFelizzi So annoying!!!

**Comment by MoOx** [comment]
Hey, please stop doing +1 or repeating what have been told.

# Workaround

```shell
apm uninstall nuclide && apm install nuclide@0.299.0
```

If you have something like "Auto-Update-Packages", remember to disable it.

# Fix

Will be around when this issue is handled by someone. No need to ask "is there any news"? or "+1".
Use github reaction on the initial post to tell maintainers that you want this to be fixed. Useless comments won't help or give motivations.

**Comment by SalahAdDin** [comment]
@chmac, thank you!

**Comment by jgebhardt** [comment]
Does this still repro with a more current Nuclide version such as 0.321?

**Comment by kamronbatman** [comment]
I just got this problem while updating to the newest version.

**Comment by gnagyusa** [comment]
I got this problem when starting Atom from the command line. Starting it from the desktop UI works fine, though.

**Comment by jgebhardt** [comment]
Ah, thanks. Sorry about that! Check out https://github.com/facebook/nuclide/issues/1512#issuecomment-385614316 for a likely workaround.

**Comment by andrewdyates** [comment]
I'm still getting this exception.

[Enter steps to reproduce:]

1. Install Nuclide from Atom Install menu
2. This error appears

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.360.0


### Stack Trace

Failed to load the nuclide package

```
At installErrorReporter was called multiple times.

Error: installErrorReporter was called multiple times.
    at installErrorReporter (/packages/nuclide/lib/installErrorReporter.js:44:11)
    at /packages/nuclide/lib/main.js:248:67)
    at /packages/nuclide/lib/main.js:585:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/nuclide/lib/main-entry.js:35:18)
    at /packages/nuclide/lib/main-entry.js:37:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:88:25)
    at Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:619:16)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:552:25)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:23)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
```

### Commands

```
     -0:20.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
nuclide 0.360.0 
```

**Comment by anandkumarpathak** [comment]
I got the exception nuclide v 0.360.0 on windows. v0.357.0 worked for me.

**Comment by solomon71** [comment]
Same on macOS Mojave, exception thrown on 0.360.0, installing 0.357.0 worked.

**Comment by melkishengue** [comment]
I am trying to install version 0.299.0, as stated as workaround in previous comments, but:

`apm install nuclide@0.299.0`

`Package version: 0.299.0 not found`

**Comment by tbleckert** [comment]
Installing 0.357.0 worked for me, as suggested by @solomon71

**Comment by cjboco** [comment]
> I am trying to install version 0.299.0, as stated as workaround in previous comments, but:
> 
> `apm install nuclide@0.299.0`
> 
> `Package version: 0.299.0 not found`

Use `app install nuclide@0.357.0`

**Comment by kamronbatman** [comment]
@melkishengue, any particular reason to install 0.299? It was obviously faulty and should not be used. And generally (sorry for the broken record) you should use the newest version.

**Comment by ermik** [comment]
Just blew up on update to latest.

**Comment by darkmanAmazigh** [comment]
i goting this message every time i open ATOM IDE,
After installing nuclide 0.360.0

**Comment by CaptainMorgans** [comment]
<h3>I also get this</h3>

<strong>Cannot find module '../../fb-appsession-observer'</strong>

Hide Stack Trace
Error: Cannot find module '../../fb-appsession-observer'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:11:154663)
    at Module.require (file:///C:/Users/Stephen/AppData/Local/atom/app-1.33.0-beta0/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:11:145970)
    at _fbAppsessionObserver (C:\Users\Stephen\.atom\packages\nuclide\pkg\nuclide-logging\lib\main.js:60:16)
    at setupLoggingService (C:\Users\Stephen\.atom\packages\nuclide\pkg\nuclide-logging\lib\main.js:132:71)
    at initializeLogging (C:\Users\Stephen\.atom\packages\nuclide\pkg\nuclide-logging\lib\main.js:125:3)
    at C:\Users\Stephen\.atom\packages\nuclide\modules\nuclide-commons\once.js:28:21
    at Object.<anonymous> (C:\Users\Stephen\.atom\packages\nuclide\lib\main.js:250:41)
    at Object.<anonymous> (C:\Users\Stephen\.atom\packages\nuclide\lib\main.js:585:3)
    at Module.get_Module._compile (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:11:146680)
    at Object.value [as .js] (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:11:150227)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Stephen/AppData/Local/atom/app-1.33.0-beta0/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:11:145970)
    at Object.<anonymous> (C:\Users\Stephen\.atom\packages\nuclide\lib\main-entry.js:35:18)
    at Object.<anonymous> (C:\Users\Stephen\.atom\packages\nuclide\lib\main-entry.js:37:3)
    at Module.get_Module._compile (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:11:146680)
    at Object.value [as .js] (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:11:150227)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Stephen/AppData/Local/atom/app-1.33.0-beta0/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:1:626126)
    at Package.requireMainModule (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:11:3035887)
    at measure (C:\Users\Stephen\AppData\Local\atom\app-1.33.0-beta0\resources\app\static\<embedded>:11:3022598)

**Comment by rickmrobin** [comment]
Got the same error. And unable to view the project tree view.

facing the problem after updating nuclide to latest

**Comment by ahmadalfy** [comment]
@rickmrobin Accidentally restarted atom and the latest update was installed. Now I am facing the same issue

**Comment by spyshower** [comment]
@rickmrobin Hey man got the same issue, I fixed it by enabling the 'tree-view' package inside Atom!

**Comment by jgebhardt** [comment]
Try updating the nuclide package - we just pushed v0.362.0, which should fix the `fb-appsession-observer` issue.

**Comment by spyshower** [comment]
> Try updating the nuclide package - we just pushed v0.362.0, which should fix the `fb-appsession-observer` issue.

Which just says it's incompatible with nuclide, and you need to disable nuclide...
