### ISSUE TITLE
Uncaught Error: Invariant violation: "input != null"

### ISSUE THREAD

**Issue by QiquWong** [facebook/nuclide#1440]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.277.0

### Stack Trace

Uncaught Error: Invariant violation: "input != null"

```
At C:\Users\Charlie\.atom\packages\nuclide\modules\nuclide-commons-ui\SettingsInput.js:57

Error: Invariant violation: "input != null"
    at /packages/nuclide/modules/nuclide-commons-ui/SettingsInput.js:57:15)
    at AtomInput._onEditorBlur.blurEvent (/packages/nuclide/modules/nuclide-commons-ui/AtomInput.js:76:41)
    at later (/packages/nuclide/modules/nuclide-commons/debounce.js:27:23)
```

### Commands

```
     -7:38.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -3:24.1.0 nuclide-settings:toggle (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.16 
highlight-selected 0.13.1 
language-babel 2.81.1 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.277.0 
nuclide-format-js 0.0.43 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.4 
```

**Comment by pelmers** [comment]
fixed in 639a755545f800284781208e5dbf079ade1fbfa9
