### ISSUE TITLE
Uncaught Error: Failed to edit comment

### ISSUE THREAD

**Issue by dhuber23b** [facebook/nuclide#1446]
[Enter steps to reproduce:]

1. I am not sure how to reproduce.  I was just editing the code and marking comments as resolved when this error message popped up.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.278.88952316

### Stack Trace

Uncaught Error: Failed to edit comment

```
At /opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:93

Error: Failed to edit comment
    at a.performMutation.switchMap.response [as project] (/opt/facebook/nuclide/0.278.88952316/nuclide/pkg/fb-phabricator-common/lib/main.js:300:51)
    at a._next (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:261:315)
    at a.next (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:262:433)
    at a._next (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /opt/facebook/nuclide/0.272.84970322/nuclide/node_modules/rxjs/bundles/Rx.min.js:93:343
```

### Commands

```
     -2:34.9.0 core:backspace (input.hidden-input)
     -2:10.2.0 nuclide-move-item-to-available-pane:left (atom-text-editor.editor)
     -1:43.5.0 find-and-replace:show (input.hidden-input)
  3x -1:41.5.0 core:backspace (input.hidden-input)
     -1:40.3.0 core:confirm (input.hidden-input)
     -1:32.4.0 autocomplete-plus:cancel (input.hidden-input)
     -1:31.7.0 find-and-replace:find-next (input.hidden-input)
     -1:16.2.0 autocomplete-plus:cancel (input.hidden-input)
     -1:14 find-and-replace:find-next (input.hidden-input)
     -1:05.3.0 autocomplete-plus:cancel (input.hidden-input)
     -1:04.3.0 find-and-replace:find-next (input.hidden-input)
  9x -0:46.5.0 core:undo (input.hidden-input)
     -0:40.8.0 find-and-replace:show (input.hidden-input)
     -0:39.2.0 core:confirm (input.hidden-input)
  3x -0:37.1.0 find-and-replace:find-next (input.hidden-input)
  3x -0:28.8.0 editor:consolidate-selections (div.native-key-bindings)
```

### Non-Core Packages

```
file-icons 2.1.16 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.81.1 
language-cython 0.3.0 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
merge-conflicts 1.4.5 
nuclide 0.278.88952316 
nuclide-format-js 0.0.43 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.4 
xml-formatter 0.11.0 
```

**Comment by pelmers** [comment]
internal issue, please file a bug with bug nub at the bottom-left of the window!
