### ISSUE TITLE
Couldn't initialize jsimports server

### ISSUE THREAD

**Issue by FDiskas** [facebook/nuclide#1448]
### Issue and Steps to Reproduce
Fresh install of atom, and nuclide, allowed all dependencies to be installed in the settings.
Open an big js project

### Expected Behavior
It should not frow an error

### Actual Behavior
I got error
```
Couldn't initialize jsimports server - Request initialize failed with message: Cannot convert undefined or null to object
```
![nuclide](https://i.imgur.com/ZT4hMVH.png)

### Versions
* Atom: 1.23.3 x64
* Nuclide: 0.280.0
* Client OS: Zorinos (ubuntu based)

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── MagicPython@1.0.12
├── atom-ide-ui@0.7.2 (disabled)
├── atom-typescript@12.1.1
├── file-icons@2.1.16
├── highlight-selected@0.13.1
├── js-refactor@0.7.5 (disabled)
├── language-babel@2.83.1
├── language-graphql@0.9.0
├── language-haskell@1.17.3
├── language-ini@1.19.0
├── language-javascript-jsx@0.3.7
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── metro-ui@2.2.2
├── nuclide@0.280.0
├── nuclide-format-js@0.0.44
├── refactor@0.11.5 (disabled)
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.4
```

**Comment by hansonw** [comment]
Could you paste the contents `/tmp/nuclide-$USER-logs/nuclide.log` somewhere so I can see the full error trace? Also, if the JS project is public a link to the repo would be super helpful to repro :)

**Comment by FDiskas** [comment]
<details>
<summary>nuclide.log :pencil2:</summary>

```
2018-02-01 11:03:27.240 DEBUG (pid:7542) nuclide-language-service - Starting observing diagnostics local, jsimports.observe-diagnostics
2018-02-01 11:03:29.292 DEBUG (pid:7542) nuclide-hack - Starting observing diagnostics local, hack.observe-diagnostics
2018-02-01 11:03:29.980 INFO (pid:8060) LocalRpcServer - Started local RPC server.
2018-02-01 11:03:30.136 INFO (pid:8060) nuclide-commons/process - 21ms: stat -f -L -c %T /mnt/SSD/Projects/moebel.de/admin-interface
2018-02-01 11:03:30.138 INFO (pid:8060) nuclide-commons/process - 45ms: stat -f -L -c %T /mnt/SSD/Projects/moebel.de/admin-interface
2018-02-01 11:03:30.139 INFO (pid:8060) nuclide-commons/process - 87ms: which ag
2018-02-01 11:03:30.176 INFO (pid:8060) nuclide-commons/process - 14ms: which rg
2018-02-01 11:03:30.191 INFO (pid:8060) nuclide-commons/process - 5ms: which ack
2018-02-01 11:03:30.204 INFO (pid:8060) nuclide-commons/process - 3ms: which grep
2018-02-01 11:03:30.510 INFO (pid:8060) nuclide-commons/process - 26ms: which hh_client
2018-02-01 11:03:30.524 INFO (pid:8060) nuclide-commons/process - 192ms: which /usr/share/atom-beta/atom
2018-02-01 11:03:30.557 INFO (pid:8060) jsimports - MultiProjectLanguageService ensureProcesses. 
2018-02-01 11:03:30.568 DEBUG (pid:7542) nuclide-hack - Observing diagnostics local, hack.observe-diagnostics
2018-02-01 11:03:30.581 INFO (pid:8060) jsimports - observing connections
2018-02-01 11:03:30.611 INFO (pid:8060) jsimports - MultiProjectLanguageService ensureProcesses. /mnt/SSD/Projects/moebel.de/admin-interface
2018-02-01 11:03:30.572 DEBUG (pid:7542) nuclide-hack - Clearing errors after stream closed
2018-02-01 11:03:30.574 DEBUG (pid:7542) nuclide-language-service - Observing diagnostics local, jsimports.observe-diagnostics
2018-02-01 11:03:30.680 INFO (pid:8060) jsimports - Spawn: /usr/share/atom-beta/atom /home/vytenis/.atom/packages/nuclide/pkg/nuclide-js-imports-server/src/index-entry.js
2018-02-01 11:03:30.718 INFO (pid:8060) jsimports - Establishing JsonRPC connection...
2018-02-01 11:03:31.312 INFO (pid:7542) nuclide-flow - Checking the Flow persistent connection gk...
2018-02-01 11:03:31.366 INFO (pid:8060) Flow - MultiProjectLanguageService ensureProcesses. 
2018-02-01 11:03:31.373 INFO (pid:8060) Flow - MultiProjectLanguageService ensureProcesses. /mnt/SSD/Projects/moebel.de/admin-interface
2018-02-01 11:03:31.391 INFO (pid:8060) nuclide-flow-rpc - [unknown]: Flow server in /mnt/SSD/Projects/moebel.de/admin-interface
2018-02-01 11:03:31.326 INFO (pid:7542) nuclide-flow - Got Flow persistent connection gk: false
2018-02-01 11:03:31.327 INFO (pid:7542) nuclide-flow - Enabling Flow persistent connection: false
2018-02-01 11:03:31.327 INFO (pid:7542) nuclide-flow - Checking the nuclide_flow_lazy_mode_ide gk...
2018-02-01 11:03:31.348 INFO (pid:7542) nuclide-flow - ideLazyMode: false
2018-02-01 11:03:31.621 INFO (pid:8060) Flow - observing connections
2018-02-01 11:03:31.625 INFO (pid:8060) Flow - observing connections
2018-02-01 11:03:31.690 INFO (pid:8060) jsimports - Lsp.telemetry: [2018-02-01 11:03:31.661] [DEBUG] nuclide-js-imports-server - Server initialized.
2018-02-01 11:03:31.693 INFO (pid:8060) nuclide-commons/process - 25ms: which /mnt/SSD/Projects/moebel.de/admin-interface/node_modules/.bin/flow
2018-02-01 11:03:31.779 ERROR (pid:8060) jsimports - Request initialize failed with message: Cannot convert undefined or null to object
STATE=Starting
  EXCEPTION STACK:
Error: Request initialize failed with message: Cannot convert undefined or null to object
    at new ResponseError (/home/vytenis/.atom/packages/nuclide/node_modules/vscode-jsonrpc/lib/messages.js:46:28)
    at handleResponse (/home/vytenis/.atom/packages/nuclide/node_modules/vscode-jsonrpc/lib/main.js:407:48)
    at processMessageQueue (/home/vytenis/.atom/packages/nuclide/node_modules/vscode-jsonrpc/lib/main.js:235:17)
    at Immediate.<anonymous> (/home/vytenis/.atom/packages/nuclide/node_modules/vscode-jsonrpc/lib/main.js:219:13)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
  CALL STACK:
Error
    at LspLanguageService._logLspException (/home/vytenis/.atom/packages/nuclide/pkg/nuclide-vscode-language-service-rpc/lib/LspLanguageService.js:831:23)
    at /home/vytenis/.atom/packages/nuclide/pkg/nuclide-vscode-language-service-rpc/lib/LspLanguageService.js:586:19
    at Generator.throw (<anonymous>)
    at step (/home/vytenis/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at _throw (/home/vytenis/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:27:9)
2018-02-01 11:03:31.855 INFO (pid:8060) nuclide-commons/process - 42ms: ps -A -o ppid,pid,comm
2018-02-01 11:03:31.896 INFO (pid:8060) nuclide-commons/process - 1193ms: /usr/share/atom-beta/atom /home/vytenis/.atom/packages/nuclide/pkg/nuclide-js-imports-server/src/index-entry.js
2018-02-01 11:03:31.981 INFO (pid:8060) nuclide-commons/process - 267ms: /mnt/SSD/Projects/moebel.de/admin-interface/node_modules/.bin/flow version --json
2018-02-01 11:03:32.113 INFO (pid:8060) nuclide-commons/process - 74ms: /mnt/SSD/Projects/moebel.de/admin-interface/node_modules/flow-bin/flow-linux64-v0.64.0/flow force-recheck /mnt/SSD/Projects/moebel.de/admin-interface/src/containers/product/item/helper/ProductFacetsHelper.js --retry-if-init false --retries 0 --no-auto-start --from nuclide
2018-02-01 11:03:32.117 INFO (pid:8060) nuclide-flow-rpc - [not running]: Flow server in /mnt/SSD/Projects/moebel.de/admin-interface
2018-02-01 11:03:32.147 INFO (pid:8060) nuclide-commons/process - 131ms: /mnt/SSD/Projects/moebel.de/admin-interface/node_modules/flow-bin/flow-linux64-v0.64.0/flow coverage --json /mnt/SSD/Projects/moebel.de/admin-interface/src/containers/product/item/helper/ProductFacetsHelper.js --retry-if-init false --retries 0 --no-auto-start --from nuclide
2018-02-01 11:03:32.155 INFO (pid:8060) nuclide-commons/process - 53ms: /mnt/SSD/Projects/moebel.de/admin-interface/node_modules/flow-bin/flow-linux64-v0.64.0/flow force-recheck /mnt/SSD/Projects/moebel.de/admin-interface/src/containers/product/item/helper/ProductFacetsHelper.js --retry-if-init false --retries 0 --no-auto-start --from nuclide
2018-02-01 11:03:32.157 INFO (pid:8060) nuclide-commons/process - 14ms: which /mnt/SSD/Projects/moebel.de/admin-interface/node_modules/.bin/flow
2018-02-01 11:03:32.329 INFO (pid:8060) nuclide-commons/process - 153ms: /mnt/SSD/Projects/moebel.de/admin-interface/node_modules/.bin/flow version --json
2018-02-01 11:03:32.414 INFO (pid:8060) nuclide-commons/process - 50ms: /mnt/SSD/Projects/moebel.de/admin-interface/node_modules/flow-bin/flow-linux64-v0.64.0/flow status --retry-if-init false --retries 0 --no-auto-start --from nuclide
2018-02-01 11:03:32.416 INFO (pid:8060) nuclide-commons/process - 68ms: which nice
2018-02-01 11:03:32.448 INFO (pid:8060) nuclide-commons/process - 38ms: /mnt/SSD/Projects/moebel.de/admin-interface/node_modules/flow-bin/flow-linux64-v0.64.0/flow status --json /mnt/SSD/Projects/moebel.de/admin-interface/src/containers/product/item/helper/ProductFacetsHelper.js --retry-if-init false --retries 0 --no-auto-start --from nuclide
2018-02-01 11:03:32.452 INFO (pid:8060) nuclide-commons/process - 61ms: /mnt/SSD/Projects/moebel.de/admin-interface/node_modules/flow-bin/flow-linux64-v0.64.0/flow status --json /mnt/SSD/Projects/moebel.de/admin-interface/src/containers/product/item/helper/ProductFacetsHelper.js --retry-if-init false --retries 0 --no-auto-start --from nuclide
2018-02-01 11:03:32.454 INFO (pid:8060) nuclide-commons/process - 11ms: which ionice
2018-02-01 11:03:32.484 DEBUG (pid:8060) nuclide-flow-rpc - flow server (8146): Feb  1 11:03:32.481 [info] argv=/mnt/SSD/Projects/moebel.de/admin-interface/node_modules/flow-bin/flow-linux64-v0.64.0/flow server --from nuclide --max-workers 2 /mnt/SSD/Projects/moebel.de/admin-interface

2018-02-01 11:03:32.485 DEBUG (pid:8060) nuclide-flow-rpc - flow server (8146): Feb  1 11:03:32.481 [info] Creating a new Flow server
```
</details>

**Comment by FDiskas** [comment]
Still happening: v0.284.0

**Comment by zaguini** [comment]
+1

**Comment by FDiskas** [comment]
Still happening: v0.287.0 :godmode:
