### ISSUE TITLE
Uncaught Error: Cannot find module './types'

### ISSUE THREAD

**Issue by ghobashy** [facebook/nuclide#1454]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.280.0

### Stack Trace

Uncaught Error: Cannot find module './types'

```
At /Users/Ghobashy2/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71

Error: Cannot find module './types'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/private/var/folders/cg/_9709qn955n74nk3ydnyy83w0000gn/T/AppTranslocation/717EE3F5-4F90-41C2-8908-D33EB5F6E05F/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/cg/_9709qn955n74nk3ydnyy83w0000gn/T/AppTranslocation/717EE3F5-4F90-41C2-8908-D33EB5F6E05F/d/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/private/var/folders/cg/_9709qn955n74nk3ydnyy83w0000gn/T/AppTranslocation/717EE3F5-4F90-41C2-8908-D33EB5F6E05F/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_types (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/getModifierKeys.js:12:19)
    at /packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/getModifierKeys.js:28:20)
    at /packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/getModifierKeys.js:55:3)
    at Module.get_Module._compile (/private/var/folders/cg/_9709qn955n74nk3ydnyy83w0000gn/T/AppTranslocation/717EE3F5-4F90-41C2-8908-D33EB5F6E05F/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/private/var/folders/cg/_9709qn955n74nk3ydnyy83w0000gn/T/AppTranslocation/717EE3F5-4F90-41C2-8908-D33EB5F6E05F/d/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/private/var/folders/cg/_9709qn955n74nk3ydnyy83w0000gn/T/AppTranslocation/717EE3F5-4F90-41C2-8908-D33EB5F6E05F/d/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_getModifierKeys (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:131:29)
    at /packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-datatip/lib/DatatipManager.js:312:49)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:111:270)
```

### Commands

```
```

### Non-Core Packages

```
nuclide 0.280.0 
nuclide-format-js 0.0.44 
```

**Comment by drmathochist** [comment]
Is this still happening after the usual restarting and clearing caches? There's very little information in here to help diagnose what's going on.
