### ISSUE TITLE
Uncaught ProcessExitError: "ps" failed with exit code 1ps -eo pid,ppid,pcpu,time,rss,vsz,comm

### ISSUE THREAD

**Issue by aaronbeall** [facebook/nuclide#1455]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.280.0

### Stack Trace

Uncaught ProcessExitError: "ps" failed with exit code 1

ps -eo pid,ppid,pcpu,time,rss,vsz,comm

```
At /Users/abeall/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71

ProcessExitError: "ps" failed with exit code 1



ps -eo pid,ppid,pcpu,time,rss,vsz,comm
    at /packages/nuclide/modules/nuclide-commons/process.js:389:15)
    at a._tryNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:216:66)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:215:461)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:88:375)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:240)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:166:129)
    at a.notifyError (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:88:439)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:160)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at a.notifyError (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:88:439)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:160)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:274)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at /packages/nuclide/modules/nuclide-commons/observable.js:257:14)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70:250)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:274)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at a.notifyError (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:88:439)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:160)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:77:309)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:274)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:226:379)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:136:175)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:293:281)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:266:51)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:194:28)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:111:240)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-typescript 12.1.1 
editorconfig 2.2.2 
linter 2.2.0 
nuclide 0.280.0 
react 0.17.0 
toggle-quotes 1.1.0 
```

**Comment by Goom11** [comment]
@aaronbeall, were you doing something in particular that triggered this or did this error pop up unrelated to what you were working on?

**Comment by aaronbeall** [comment]
This error popped up while I was away (laptop probably went to sleep) or immediately when I came back. I had a .txt in the active editor, some js files in other tabs.

**Comment by rightparen** [comment]
Thanks for reporting! This should be fixed by the commit referenced above.
