### ISSUE TITLE
Uncaught Error: Invariant violation: "this._disposables != null"

### ISSUE THREAD

**Issue by Kotpes** [facebook/nuclide#1457]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0-beta3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.282.0

### Stack Trace

Uncaught Error: Invariant violation: "this._disposables != null"

```
At /Users/sergeydubovik/.atom/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:168

Error: Invariant violation: "this._disposables != null"
    at DiagnosticsTable.componentWillUnmount (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/ui/DiagnosticsTable.js:132:13)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:143:273)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:143:411)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:144:465)
    at commitDeletion (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:148:97)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:158:23)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:165:441)
    at Object.updateContainer (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:175:31)
    at Pg (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:225:81)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:228:69
    at Object.unbatchedUpdates (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:171:453)
    at Object.unmountComponentAtNode (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:228:41)
    at HTMLElement.detachedCallback (/packages/nuclide/modules/nuclide-commons-ui/ReactMountRootElement.js:35:23)
    at HTMLElement.PaneElement.itemRemoved (/app.asar/src/pane-element.js:199:29)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Pane.removeItem (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:698:24)
    at Pane.destroyItem (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:775:16)
```

### Commands

```
     -0:41.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:23.6.0 tabs:close-all-tabs (div.title.icon.jsx-icon.medium-blue)
     -0:13.3.0 nuclide-file-tree:remove-project-folder-selection (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory-starred)
     -0:09.9.0 application:open (div.list-tree.has-collapsable-children.file-tree-scroller.nuclide-file-tree.focusable-panel.tree-view)
```

### Non-Core Packages

```
atom-ide-ui 0.8.1 
atom-import-cost 1.2.0 
atom-react-native-autocomplete 0.0.27 
autocomplete-html-entities 0.2.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
file-icons 2.1.16 
flow 0.5.3 
intentions 1.1.5 
language-javascript-jsx 0.3.7 
language-postcss 1.3.1 
linter 2.2.0 
linter-flow 5.6.1 
linter-ui-default 1.6.10 
nuclide 0.282.0 
pigments 0.40.2 
prettier-atom 0.49.2 
react 0.17.0 
react-es6-snippets 0.3.0 
react-snippets 1.0.1 
teletype 0.7.0 
tidy-tabs 0.4.0 
```

**Comment by Goom11** [comment]
@Kotpes, could you give us some repro steps? 
cc: @matthewwithanm

**Comment by ayc92** [comment]
@Goom11 I was able to repro this by dragging my "Linter" tab to another pane.

![screen shot 2018-02-14 at 10 06 18 am](https://user-images.githubusercontent.com/1166548/36220242-c00cd0b2-116e-11e8-962d-b2e3c8e0e4b2.png)

**Comment by matthewwithanm** [comment]
sorry about this! fix on the way!
