### ISSUE TITLE
Omnisearch Just Spinning on NOn-Project Directory

### ISSUE THREAD

**Issue by theGhostJW** [facebook/nuclide#1471]
### Issue and Steps to Reproduce
> Unzip the attached file (it ahs 2 small text files in it)
> open the Demo1 dir in atom
> Omni-search start typing : an

### Expected Behavior
=> search results returned

### Actual Behavior
=> Loading icon just keeps spinning

### Versions
* Atom: 1.24.0 x64
* Nuclide: 0.284.0
* Client OS: Windows 10

### Error Log
```
C:\Users\myUserName\.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:52 [2018-02-23T23:01:06.035Z] [ERROR] installErrorReporter - Caught unhandled rejection Failed to populate FileSearch for C:\ManualTestTemp\Demo1
Error: Failed to populate FileSearch for C:\ManualTestTemp\Demo1
    at getFilesFromHg.catch.catch.catch.catch (C:\Users\myUserName\.atom\packages\nuclide\pkg\nuclide-fuzzy-file-search-rpc\lib\process\PathSetFactory.js:218:11)
internal/process/next_tick.js:129 Uncaught (in promise) Error: Failed to populate FileSearch for C:\ManualTestTemp\Demo1
    at getFilesFromHg.catch.catch.catch.catch (C:\Users\myUserName\.atom\packages\nuclide\pkg\nuclide-fuzzy-file-search-rpc\lib\process\PathSetFactory.js:218:11)
_emitter.once.response @ C:\Users\myUserName\.atom\packages\nuclide\pkg\nuclide-task\lib\bootloader.js:134
onceWrapper @ events.js:290
emitOne @ events.js:96
emit @ events.js:188
child.on.response @ C:\Users\myUserName\.atom\packages\nuclide\pkg\nuclide-task\lib\bootloader.js:59
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickDomainCallback @ internal/process/next_tick.js:122
[Demo1.zip](https://github.com/facebook/nuclide/files/1753424/Demo1.zip)

```

may be relate to: #794

**Comment by hansonw** [comment]
Ah, we haven't added a good catch-all for non-Git repos on Windows. An easy workaround is to `git init` an empty Git repository in your directory (if you don't mind that). We might add the ability for Omnisearch to pick up `rg --files` if you have ripgrep installed, as it's quite popular these days.

**Comment by theGhostJW** [comment]
Thanks git init works.

Would it be possible to put some kind notification in the omnisearch panel when a search cannot be performed rather than just spinner?

e.g. No git root in directory - run git init [or install ripgrep] to enable omnisearch
