### ISSUE TITLE
nuclide-remote-projects fails to load  at error: "main.js: Unexpected token" 

### ISSUE THREAD

**Issue by pgnd** [facebook/nuclide#148]
Running
```
atom --version
	1.0.3-bb1fa7f
apm list --installed --bare | grep nuclide
	nuclide-file-tree@0.0.24
	nuclide-quick-open@0.0.24
	nuclide-remote-projects@0.0.24
iojs -v
	v2.4.0
node -v
	v2.4.0
npm -v
	2.13.0
node-gyp -v
	v2.0.2
```

On atom launch, error:

```
Failed to load the nuclide-remote-projects package

The error was thrown from the nuclide-remote-projects package. You can help by creating an issue. Please explain what actions triggered this error.

/home/pgnd/.atom/packages/nuclide-remote-projects/node_modules/nuclide-logging/lib/main.js: Unexpected token (44:38)
Hide Stack Trace
SyntaxError: /home/pgnd/.atom/packages/nuclide-remote-projects/node_modules/nuclide-logging/lib/main.js: Unexpected token (44:38)
  42 | 
  43 |   LOGGER_LEVELS.forEach((level) => {
> 44 |     lazyLogger[level] = async (...args: Array<any>) => {
     |                                       ^
  45 |       if (global[LOG4JS_INSTANCE_KEY] === undefined) {
  46 |         var defaultConfig = await require('./config').getDefaultConfig();
  47 |         configLog4jsLogger(defaultConfig, {});
  at Parser.pp.raise (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/location.js:73:13)
  at Parser.pp.unexpected (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/parseutil.js:87:8)
  at Parser.pp.expect (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/parseutil.js:81:33)
  at Parser.pp.parseExprList (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:764:12)
  at Parser.pp.parseSubscripts (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:258:29)
  at Parser.pp.parseExprSubscripts (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:227:17)
  at Parser.pp.parseMaybeUnary (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:204:19)
  at Parser.pp.parseExprOps (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:154:19)
  at Parser.pp.parseMaybeConditional (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:136:19)
  at Parser.pp.parseMaybeAssign (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:103:19)
  at Parser.pp.parseMaybeAssign (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:123:23)
  at Parser.pp.parseExpression (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:73:19)
  at Parser.pp.parseStatement (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/statement.js:122:23)
  at Parser.parseStatement (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:617:22)
  at Parser.pp.parseBlock (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/statement.js:424:21)
  at Parser.pp.parseFunctionBody (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:731:22)
  at Parser.parseFunctionBody (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:605:20)
  at Parser.pp.parseArrowExpression (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:710:8)
  at Parser.pp.parseParenArrowList (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:503:15)
  at Parser.parseParenArrowList (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:720:20)
  at Parser.pp.parseParenAndDistinguishExpression (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:476:17)
  at Parser.parseParenAndDistinguishExpression (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:864:26)
  at Parser.pp.parseExprAtom (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:363:19)
  at Parser.parseExprAtom (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/plugins/jsx/index.js:401:189)
  at Parser.pp.parseExprSubscripts (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:223:19)
  at Parser.pp.parseMaybeUnary (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:204:19)
  at Parser.pp.parseExprOps (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:154:19)
  at Parser.pp.parseMaybeConditional (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:136:19)
  at Parser.pp.parseMaybeAssign (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:103:19)
  at Parser.pp.parseExprList (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:774:18)
  at Parser.pp.parseSubscripts (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:258:29)
  at Parser.pp.parseExprSubscripts (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:227:17)
  at Parser.pp.parseMaybeUnary (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:204:19)
  at Parser.pp.parseExprOps (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:154:19)
  at Parser.pp.parseMaybeConditional (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:136:19)
  at Parser.pp.parseMaybeAssign (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:103:19)
  at Parser.pp.parseExpression (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:73:19)
  at Parser.pp.parseStatement (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/statement.js:122:23)
  at Parser.parseStatement (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:617:22)
  at Parser.pp.parseBlock (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/statement.js:424:21)
  at Parser.pp.parseFunctionBody (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:731:22)
  at Parser.parseFunctionBody (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:605:20)
  at Parser.pp.parseFunction (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/statement.js:506:8)
  at Parser.pp.parseFunctionStatement (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/statement.js:247:15)
  at Parser.pp.parseStatement (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/statement.js:67:19)
  at Parser.parseStatement (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/plugins/flow.js:617:22)
  at Parser.pp.parseTopLevel (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/statement.js:22:21)
  at Parser.parse (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/state.js:93:15)
  at Object.parse (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/index.js:77:65)
  at Object.exports.default (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/lib/helpers/parse.js:79:21)
  at File.parse (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/lib/transformation/file/index.js:549:40)
  at File.parseCode (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/lib/transformation/file/index.js:658:20)
  at /usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/lib/transformation/pipeline.js:167:12
  at File.wrap (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/lib/transformation/file/index.js:614:16)
  at Pipeline.transform (/usr/local/atom/share/atom/resources/app.asar/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
  at transpile (/usr/local/atom/share/atom/resources/app.asar/src/babel.js:128:16)
  at Object.loadFile [as .js] (/usr/local/atom/share/atom/resources/app.asar/src/babel.js:165:67)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/pgnd/.atom/packages/nuclide-remote-projects/node_modules/nuclide-client/lib/service-manager.js:5:14)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/local/atom/share/atom/resources/app.asar/src/babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/pgnd/.atom/packages/nuclide-remote-projects/node_modules/nuclide-client/lib/main.js:3:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/local/atom/share/atom/resources/app.asar/src/babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/pgnd/.atom/packages/nuclide-remote-projects/lib/main.js:78:17)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/local/atom/share/atom/resources/app.asar/src/babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/local/atom/share/atom/resources/app.asar/src/package.js:715:34)
  at /usr/local/atom/share/atom/resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/usr/local/atom/share/atom/resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/usr/local/atom/share/atom/resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/local/atom/share/atom/resources/app.asar/src/package-manager.js:373:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/local/atom/share/atom/resources/app.asar/src/package-manager.js:452:30)
  at /usr/local/atom/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:370:29
  at exit (/usr/local/atom/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/usr/local/atom/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/local/atom/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/local/atom/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)
```

**Comment by pgnd** [comment]
upgrade to 
```
atom --version
  1.0.3-405a255
```
fixes

**Comment by pgnd** [comment]
spoke too soon ... issue remains, on complete close of atom, and restart

**Comment by trungda** [comment]
I have the same issue with nuclide-flow package.

...
Failed to activate the nuclide-flow package
/Users/dinhanhtrung/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-logging/lib/main.js: Unexpected token (44:38)
Hide Stack Trace
SyntaxError: /Users/dinhanhtrung/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-logging/lib/main.js: Unexpected token (44:38)
  42 | 
  43 |   LOGGER_LEVELS.forEach((level) => {
> 44 |     lazyLogger[level] = async (...args: Array<any>) => {
     |                                       ^
  45 |       if (global[LOG4JS_INSTANCE_KEY] === undefined) {
  46 |         var defaultConfig = await require('./config').getDefaultConfig();
  47 |         configLog4jsLogger(defaultConfig, {});
    at Parser.pp.raise (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/location.js:73:13)
    at Parser.pp.unexpected (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/parseutil.js:87:8)
    at Parser.pp.expect (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/parseutil.js:81:33)
    at Parser.pp.parseExprList (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:764:12)
    at Parser.pp.parseSubscripts (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:258:29)
    at Parser.pp.parseExprSubscripts (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:227:17)
    at Parser.pp.parseMaybeUnary (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:204:19)
    at Parser.pp.parseExprOps (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:154:19)
    at Parser.pp.parseMaybeConditional (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:136:19)
    at Parser.pp.parseMaybeAssign (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/babylon/lib/expression.js:103:19)
...

**Comment by bolinfest** [comment]
I believe this should be fixed by https://github.com/atom/atom/pull/7996 because we need to use a newer version of Babel to get a bug fix.

**Comment by bolinfest** [comment]
Atom v1.0.3 is out. Please upgrade and reopen if that does not fix the issue.
