### ISSUE TITLE
SSL Failed to generate certs.

### ISSUE THREAD

**Issue by arhurMARNI** [facebook/nuclide#1481]
Hi, i got that issue when trying to start my Nuclide Server : 

### Actual Behavior
When executing `nuclide-start-server --verbose`, i got an ssl error for generating certs as : 

> 2018-03-15 16:10:51,601 - NuclideServerManager - INFO - Starting to clean up old Nuclide processes/files.
2018-03-15 16:10:51,621 - NuclideServerManager - INFO - Cleaning up old certificate files...
2018-03-15 16:10:51,625 - NuclideServerManager - INFO - Finished cleaning up old Nuclide processes/files.
2018-03-15 16:10:51,625 - NuclideServerManager - INFO - Trying to determine the port to use for Nuclide server...
2018-03-15 16:10:51,698 - NuclideServerManager - INFO - Found an open port: 9090.
2018-03-15 16:10:51,698 - NuclideServerManager - INFO - Initialized NuclideServer.
2018-03-15 16:10:51,720 - NuclideServerManager - INFO - Starting NuclideServer...
2018-03-15 16:10:51,721 - NuclideServerManager - INFO - Using https.
2018-03-15 16:10:51,721 - NuclideServerManager - INFO - Checking if certificate dir /Users/arthur/.certs exists.
2018-03-15 16:10:51,782 - NuclideCertificatesGenerator - ERROR - openssl failed: problems making Certificate Request
140735834579848:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/asn1/a_mbstr.c:159:maxsize=2
Traceback (most recent call last):
  File "scripts/nuclide_server_manager.py", line 428, in <module>
    server_start_result = manager.start_nuclide()
  File "scripts/nuclide_server_manager.py", line 251, in start_nuclide
    return {'exit_code': self.start_server(server), 'server': server}
  File "scripts/nuclide_server_manager.py", line 287, in start_server
    ca, server_cert, server_key = self._generate_certificates()
  File "scripts/nuclide_server_manager.py", line 221, in _generate_certificates
    expiration_days=CERTS_EXPIRATION_DAYS)
  File "/Users/arthur/lib/node_modules/nuclide/pkg/nuclide-server/scripts/nuclide_certificates_generator.py", line 86, in __init__
    self.generate()
  File "/Users/arthur/lib/node_modules/nuclide/pkg/nuclide-server/scripts/nuclide_certificates_generator.py", line 104, in generate
    raise RuntimeError('Failed to generate certs.')
RuntimeError: Failed to generate certs.

I tried to modify my nuclide openssl.cnf file adding 
`[ req_distinguished_name ]
countryName     = FR
countryName_default   = FR
countryName_min     = 64
countryName_max     = 64`

### Versions
* Atom: 1.24.1
* Nuclide Pkg: 0.288 
* Nuclide Server: 0.288 
* Client OS: MacOs HS

### Additional Details
* Installed packages :

```
 ├── Hydrogen@2.3.0
 ├── MagicPython@1.0.12
 ├── atom-ide-ui@0.9.4
 ├── atom-jquery@1.2.0
 ├── browser-plus@0.0.98
 ├── busy-signal@1.4.3
 ├── editorconfig@2.2.2
 ├── file-icons@2.1.17
 ├── highlight-selected@0.13.1
 ├── hyperclick@0.1.5
 ├── ide-php@0.7.11
 ├── intentions@1.1.5
 ├── jQuery@1.2.6
 ├── language-babel@2.84.0
 ├── language-graphql@0.9.0
 ├── language-haskell@1.17.3
 ├── language-ini@1.19.0
 ├── language-lua@0.9.11
 ├── language-ocaml@1.9.5
 ├── language-rust@0.4.12
 ├── language-scala@1.1.9
 ├── language-swift@0.5.0
 ├── language-thrift@1.0.2
 ├── linter@2.2.0
 ├── linter-php@1.5.1
 ├── linter-ui-default@1.7.1
 ├── monokai@0.24.0
 ├── nuclide@0.288.0
 ├── nuclide-format-js@0.0.44
 ├── php-analyser@0.2.0
 ├── php-debug@0.2.6
 ├── php-hyperclick@1.2.1
 ├── php-integrator-annotations@1.2.0
 ├── php-integrator-autocomplete-plus@1.6.2 (disabled)
 ├── php-integrator-base@3.2.1
 ├── php-integrator-call-tips-legacy-php56@1.2.3
 ├── php-integrator-linter-legacy-php56@1.3.1
 ├── php-integrator-navigation-legacy-php56@1.0.1
 ├── php-integrator-refactoring@1.4.1
 ├── php-integrator-refactoring-legacy-php56@1.0.1
 ├── php-integrator-tooltips-legacy-php56@1.1.6
 ├── platformio-ide-terminal@2.8.0
 ├── project-manager@3.3.5
 ├── set-syntax@0.4.0
 ├── sort-lines@0.18.0
 ├── styri-syntax@0.2.0
 └── tool-bar@1.1.6

```

**Comment by pelmers** [comment]
the error message here says that the name is too long, I believe that this relates to the 'commonName' field. What is the value of that in openssl.cnf?

**Comment by arhurMARNI** [comment]
Thanks Pelmers !

In /System/Library/OpenSSL/openssl.cnf : 

> #For the CA policy : 
> commonName = supplied
> #For the CA policy : 
> commonName = supplied

**Comment by arhurMARNI** [comment]
> #For the CA policy : 
> commonName = supplied
> #For the CA policy : 
> commonName = supplied

**Comment by arhurMARNI** [comment]
Thanks Pelmers !

In /System/Library/OpenSSL/openssl.cnf :

```
#For the CA policy :
commonName = supplied

# For the 'anything' policy
commonName = supplied

#organizationalUnitName_default	=
commonName			= Common Name (e.g. server FQDN or YOUR name)
commonName_max			= 64
```

**Comment by pelmers** [comment]
@arhurMARNI  I think the certificates generator prefixes the common name with 'username.Nuclide' which might be making it go over the limit. I suggest taking a look at https://github.com/facebook/nuclide/issues/1120 and picking a shorter name

**Comment by arhurMARNI** [comment]
I already saw that post but I get 28 when running 
` echo "tryggvi.nuclide.<host_name>"|wc -c    ` 

Where am I supposed to run `getconf HOST_NAME_MAX 64` ? 
Thx @pelmers

**Comment by pelmers** [comment]
@arhurMARNI have you tried again recently? f1c438f57abd47e7c57b336927a9ca8db5f1236a may have fixed a related parsing bug

**Comment by Blake1985** [comment]
No sire I’m at work I will at four when I get off
