### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 8910, Calling function FileSystemService/re...

### ISSUE THREAD

**Issue by brianjo** [facebook/nuclide#1482]
[Enter steps to reproduce:]

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.288.96987626

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 8910, Calling function FileSystemService/readFile.

```
At /opt/facebook/nuclide/0.288.96987626/nuclide/node_modules/rxjs/bundles/Rx.min.js:34

RpcTimeoutError: Timeout after 60000 for id: 8910, Calling function FileSystemService/readFile.
    at Call._timeout (/opt/facebook/nuclide/0.288.96987626/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/opt/facebook/nuclide/0.288.96987626/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
```

### Commands

```
     -3:20.4.0 nuclide-breadcrumbs:toggle-connect-menu (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:13.9.0 nuclide-file-tree:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atominfo 0.0.0 
file-icons 2.1.17 
highlight-selected 0.13.1 
language-babel 2.84.0 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.288.96987626 
nuclide-format-js 0.0.44 
set-syntax 0.4.0 
sort-lines 0.18.0 
split-diff 1.5.2 
tool-bar 1.1.6 
```

**Comment by pelmers** [comment]
please file facebook-internal issues with the bug nub at the bottom left of the window! (also steps to reproduce will be helpful!)
