### ISSUE TITLE
Uncaught Error: Cannot make an authenticated request without being logged in

### ISSUE THREAD

**Issue by kenny11lee** [facebook/nuclide#1484]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.290.98502521

### Stack Trace

Uncaught Error: Cannot make an authenticated request without being logged in

```
At /opt/facebook/nuclide/0.290.98502521/nuclide/node_modules/rxjs/bundles/Rx.min.js:34

Error: Cannot make an authenticated request without being logged in
    at /opt/facebook/nuclide/0.290.98502521/nuclide/pkg/commons-node/fb-interngraph-user.js:15:13
    at Generator.next (<anonymous>)
    at step (/opt/facebook/nuclide/0.290.98502521/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at _next (/opt/facebook/nuclide/0.290.98502521/nuclide/node_modules/async-to-generator/async-to-generator.js:24:9)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
file-icons 2.1.17 
highlight-selected 0.13.1 
language-babel 2.84.0 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.290.98502521 
nuclide-format-js 0.0.45 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```

**Comment by pelmers** [comment]
since this is facebook-specific, please file a task internally with the bug button at the bottom left of the Nuclide window!
