### ISSUE TITLE
Uncaught Error: Got unexpected null or undefined

### ISSUE THREAD

**Issue by ribhupathria** [facebook/nuclide#1485]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.288.0

### Stack Trace

Uncaught Error: Got unexpected null or undefined

```
At /Users/ribhu/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71

Error: Got unexpected null or undefined
    at nullthrows (/packages/nuclide/node_modules/nullthrows/nullthrows.js:9:9)
    at getFileSystemServiceByNuclideUri (/packages/nuclide/pkg/nuclide-remote-connection/lib/main.js:177:58)
    at /packages/nuclide/pkg/nuclide-file-family-projectionist/lib/ProjectionistFileFamilyProvider.js:52:126)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:261:315)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:262:433)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/nuclide/pkg/nuclide-current-working-directory/lib/CwdApi.js:58:7)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:183:159)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:136:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:136:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:105:241)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:213:362)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Project.addPath (/Applications/Atom.app/Contents/Resources/app/src/project.js:384:26)
    at confirm.response (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1175:32)
    at CallbacksRegistry.apply (/Applications/Atom.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:48:25)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:299:21)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.9.4 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
ex-mode 0.18.0 
file-icons 2.1.17 
goto-definition 1.3.4 
highlight-selected 0.13.1 
ide-python 0.8.2 
intentions 1.1.5 
language-babel 2.84.0 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-gcc 0.7.1 
linter-python-pep8 0.2.0 
linter-ui-default 1.7.1 
MagicPython 1.0.12 
nuclide 0.288.0 
nuclide-format-js 0.0.45 
platformio-ide-terminal 2.8.1 
python-indent 1.1.4 
python-tools 0.6.9 
remote-sync-pro 5.1.1 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
vim-mode-plus 1.31.1 
```

**Comment by viktor-equinix** [comment]
Just got the same exception in Nuclide version 0.299.0

**Comment by JoshLWScott** [comment]
Just got exactly the same using v0.346.0 on MacOS.

My device popped up on the list, but got the error thrown when attempting to click on the device name.

**Comment by Jujenji** [comment]
@JoshLWScott got the same error while clicking on the Device in Ubuntu using 0.349.0
@ribhupathria As you closed the ticket, did you manage to fix this?

**Comment by effexts** [comment]
I got this too while clicking device trying to debug my app.
Using nuclide 0.349.0 and macOS Sierra 10.12.6

**Comment by broken-bytes** [comment]
Same for me @effexts
