### ISSUE TITLE
Uncaught RpcTimeoutError: Timeout after 60000 for id: 129, Calling function FileSystemService/fin...

### ISSUE THREAD

**Issue by BogartHu** [facebook/nuclide#1494]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.291.99692496

### Stack Trace

Uncaught RpcTimeoutError: Timeout after 60000 for id: 129, Calling function FileSystemService/findNearestAncestorNamed.

```
At /opt/facebook/nuclide/0.291.99692496/nuclide/node_modules/rxjs/bundles/Rx.min.js:34

RpcTimeoutError: Timeout after 60000 for id: 129, Calling function FileSystemService/findNearestAncestorNamed.
    at Call._timeout (/opt/facebook/nuclide/0.291.99692496/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:182:20)
    at Call._timerId.setTimeout (/opt/facebook/nuclide/0.291.99692496/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:144:14)
```

### Commands

```
     -2:15.9.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-close.has-buttons)
```

### Non-Core Packages

```
file-icons 2.1.17 
highlight-selected 0.13.1 
language-babel 2.84.0 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.291.99692496 
nuclide-format-js 0.0.44 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.6 
```

**Comment by wanderley** [comment]
This issue doesn't have enough data to repro or debug it.
