### ISSUE TITLE
Uncaught Error: Cannot find module './ChangedFilesList'

### ISSUE THREAD

**Issue by pintalubaf** [facebook/nuclide#1496]
[Enter steps to reproduce:]

1. Happens just after installing Nuclide in a just installed Atom instance. No reset yet.

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.293.0

### Stack Trace

Uncaught Error: Cannot find module './ChangedFilesList'

```
At /Users/x/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71

Error: Cannot find module './ChangedFilesList'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _load_ChangedFilesList (/packages/nuclide/pkg/nuclide-ui/MultiRootChangedFilesView.js:49:53)
    at _react.createElement.Array.from.map (/packages/nuclide/pkg/nuclide-ui/MultiRootChangedFilesView.js:281:54)
    at Array.map (native)
    at MultiRootChangedFilesView.render (/packages/nuclide/pkg/nuclide-ui/MultiRootChangedFilesView.js:277:48)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:130:280)
    at beginWork (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:133:485)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:161:93)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:161:417)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:162:149)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:169:173)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:165:441)
    at Object.enqueueSetState (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:108:299)
    at FileTreeSidebarComponent.A.setState (/packages/nuclide/node_modules/react/cjs/react.production.min.js:12:357)
    at FileTreeSidebarComponent._processExternalUpdate (/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:242:12)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:623:21)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at requestAnimationFrame (/packages/nuclide/node_modules/nuclide-commons/observable.js:372:14)
```

### Commands

```
     -4:30.8.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
 14x -3:28.6.0 core:backspace (input.hidden-input)
     -3:13.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
nuclide 0.293.0 
```

**Comment by wanderley** [comment]
Can you restart Atom and check if the issue persist?

**Comment by wanderley** [comment]
We need more info in order to debug this issue.
