### ISSUE TITLE
Uncaught Error: Path operation invoked on Atom URI atom://debug-sources/28871040-3337-4583-8948-5374f4b38c6a/2144/index.js

### ISSUE THREAD

**Issue by Bastorx** [facebook/nuclide#1498]
### Issue and Steps to Reproduce
Atom crash during debugging

### Expected Behavior
Atom should not crash

### Actual Behavior
Atom Crash during debugging

### Versions
* Atom: 0.25.0 (Edit: tested with 0.25.1 too, same problem)
* Nuclide: 0.296.0
* Client OS: Mac OS Sierra
* Server OS (optional): Docker - alpine-3.7

### Additional Details
STACK TRACE
/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70
Error: Path operation invoked on Atom URI atom://debug-sources/28871040-3337-4583-8948-5374f4b38c6a/2144/index.js
    at _testForIllegalUri (/Users/Bastien/.atom/packages/nuclide/modules/nuclide-commons/nuclideUri.js:711:13)
    at Object.basename (/Users/Bastien/.atom/packages/nuclide/modules/nuclide-commons/nuclideUri.js:246:3)
    at a._rxjsBundlesRxMinJs.Observable.concat.switchMap.editor [as project] (/Users/Bastien/.atom/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/LinterAdapter.js:247:98)
    at a._next (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:261:315)
    at a.next (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:105:241)
    at a._next (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.next (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:77:124)
    at a._group (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:203:241)
    at a._next (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:202:258)
    at a.next (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:88:375)
    at a._next (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/Users/Bastien/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at debounced (/Users/Bastien/.atom/packages/nuclide/modules/nuclide-commons/debounce.js:44:21)
    at TextEventDispatcher._dispatchEvents (/Users/Bastien/.atom/packages/nuclide/modules/nuclide-commons-atom/text-event.js:272:9)
    at Immediate.setImmediate (/Users/Bastien/.atom/packages/nuclide/modules/nuclide-commons-atom/text-event.js:256:31)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by mostafaeweda** [comment]
I'm unable to reproduce at the latest - with some fixes around this, could you update to the latest and re-open with reproduce steps & environment details (installed packages, open files, debugger type) to help us fix it.
