### ISSUE TITLE
Nuclide stopped working after latest update

### ISSUE THREAD

**Issue by xenobarbital** [facebook/nuclide#1508]
### Issue and Steps to Reproduce
Nuclide stopped working after update 0.299 -> 0.300

### Expected Behavior
Editor should start as usual

### Actual Behavior
At startup editor throws an error and continues with disabled nuclide package.

### Versions
**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Linux Mint-18.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.300.0

### Stack Trace

Failed to load the nuclide package

```
At (_collection || _load_collection(...)).DefaultMap is not a constructor

TypeError: (_collection || _load_collection(...)).DefaultMap is not a constructor
    at /packages/nuclide/modules/nuclide-commons-atom/ExperimentalMessageRouter.js:73:15)
    at activateExperimentalPackages (/packages/nuclide/modules/nuclide-commons-atom/experimental-packages.js:104:564)
    at FeatureLoader.load (/packages/nuclide/modules/nuclide-commons-atom/FeatureLoader.js:118:94)
    at /packages/nuclide/lib/main.js:165:17)
    at /packages/nuclide/lib/main.js:448:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/nuclide/lib/main-entry.js:33:18)
    at /packages/nuclide/lib/main-entry.js:35:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:782:33)
    at measure (/usr/share/atom/resources/app/src/package.js:143:22)
    at Package.measure (/usr/share/atom/resources/app/src/package.js:88:25)
    at Package.load (/usr/share/atom/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (/usr/share/atom/resources/app/src/package-manager.js:618:16)
    at config.transact (/usr/share/atom/resources/app/src/package-manager.js:531:20)
    at Config.transact (/usr/share/atom/resources/app/src/config.js:819:20)
    at PackageManager.loadPackages (/usr/share/atom/resources/app/src/package-manager.js:529:23)
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-easy-jsdoc 4.12.5 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
autocomplete-paths 2.12.2 
better-git-blame 0.4.5 
file-icons 2.1.19 
git-plus 7.10.2 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.84.0 
language-gradle 0.0.5 
linter-eslint 8.4.1 
minimap 4.29.8 
nuclide 0.300.0 
nuclide-format-js 0.0.45 
pigments 0.40.2 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```

**Comment by xenobarbital** [comment]
As temporal solution downgraded to nuclide-0.299

**Comment by jonkwheeler** [comment]
**Atom**: 1.27.0-beta0
**OS**: OSX 10.13.4

Same thing. Thanks @xenobarbital - Downgraded nicely with `apm uninstall nuclide && apm install nuclide@0.299.0`

**Comment by collinarnett** [comment]
I am on Windows Pro 1709 and my update has failed as well. Downgraded

**Atom**: 1.26.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro for Workstations
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.300.0


### Stack Trace

Failed to load the nuclide package

```
At installErrorReporter was called multiple times.

Error: installErrorReporter was called multiple times.
    at installErrorReporter (/packages/nuclide/lib/installErrorReporter.js:26:436)
    at /packages/nuclide/lib/main.js:68:99)
    at /packages/nuclide/lib/main.js:448:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.26.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.26.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.26.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/nuclide/lib/main-entry.js:33:18)
    at /packages/nuclide/lib/main-entry.js:35:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.26.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.26.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.26.0/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:782:33)
    at measure (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:143:22)
    at Package.measure (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:88:25)
    at Package.load (~/AppData/Local/atom/app-1.26.0/resources/app/src/package.js:129:16)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.26.0/resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.26.0/resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.26.0/resources/app/src/package-manager.js:689:23)
    at ~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (~/AppData/Local/atom/app-1.26.0/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.26.0/resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (~/AppData/Local/atom/app-1.26.0/resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.2 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
ide-java 0.8.3 
nuclide 0.300.0 
script 3.17.3 
```

**Comment by steida** [comment]
3.0.1 still broken

**Comment by adliska** [comment]
See https://github.com/facebook/nuclide/issues/1512#issuecomment-385614316 for details why this is happening and how to solve it.

**Comment by hansonw** [comment]
Closing due to duplication
