### ISSUE TITLE
Uncaught TypeError: (_collection || _load_collection(...)).DefaultMap is not a constructor

### ISSUE THREAD

**Issue by thomas81528262** [facebook/nuclide#1512]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.301.0

### Stack Trace

Uncaught TypeError: (_collection || _load_collection(...)).DefaultMap is not a constructor

```
At /Users/thomas/.atom/packages/nuclide/modules/nuclide-commons-atom/ExperimentalMessageRouter.js:73

TypeError: (_collection || _load_collection(...)).DefaultMap is not a constructor
    at /packages/nuclide/modules/nuclide-commons-atom/ExperimentalMessageRouter.js:73:15)
    at activateExperimentalPackages (/packages/nuclide/modules/nuclide-commons-atom/experimental-packages.js:104:564)
    at _loadDisposable.add.whenPackageLoaded (/packages/nuclide/modules/nuclide-commons-atom/FeatureLoader.js:139:103)
    at atom.packages.onDidLoadPackage.pack (/packages/nuclide/modules/nuclide-commons-atom/FeatureLoader.js:518:21)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:620:24)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:689:23)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:491:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:267:15)
    at ChildProcess.process.on (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:297:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -4:00.0 core:paste (input.hidden-input)
  9x -3:48.2.0 core:backspace (input.hidden-input)
     -3:29.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
nuclide 0.301.0 
```

**Comment by chmac** [comment]
For some reason atom linked me to #1439 instead of this issue.

Having looked into this a bit, it seems like I have `nuclide-commons` version 0.5.1 (which is 2 months old, 0.7.1 is the latest) in `~/.atom/packages/nuclide/node_modules/nuclide-commons/`. Version 0.5.1 does not have DefaultMap, which is where this error arises. I also have version 0.7.1 at `~/.atom/packages/nuclide/modules/nuclide-commons/`, but that's not what's being returned from `require()`.

I tried removing the `node_modules` version and nuclide appears to be working fine.

    rm -rf ~/.atom/packages/nuclide/node_modules/nuclide-commons/

**Comment by steida** [comment]
Also `rm -rf ~/.atom/.apm/nuclide`

**Comment by steida** [comment]
No, still errors. With Nuclide 3.0.1

![screen shot 2018-05-01 at 20 54 46](https://user-images.githubusercontent.com/66249/39488245-e806680e-4d81-11e8-90c3-3790e2cc9f2e.png)

**Comment by steida** [comment]
OK, trying complete reinstall https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/34

**Comment by hansonw** [comment]
Do you happen to have a `node_modules` in your home directory? Or are you setting a custom `$NODE_PATH`? Try to see if there's an older version of `nuclide-commons` somewhere else on the filesystem.

**Comment by steida** [comment]
```
find . -name nuclide-commons  -type d
./.atom/.apm/nuclide-commons
./.atom/.apm/registry.npmjs.org/nuclide-commons
./.Trash/nuclide-commons
./.vscode/extensions/flowtype.flow-for-vscode-0.8.1/node_modules/nuclide-commons
rm -rf ~/.atom/.apm/nuclide-commons
rm -rf ~/.atom/.apm/registry.npmjs.org/nuclide-commons
```

Still the same error.

**Comment by matthewwithanm** [comment]
sorry about this everybody! i unpublished the affected versions and we should have a real fix (and new version) out tomorrow. thanks for the patience and the detective work! ❤️

**Comment by wbinnssmith** [comment]
Just released a new version of Nuclide with a fix. Thanks for your patience everyone!
