### ISSUE TITLE
Uncaught TypeError: repo.getProjectDirectory is not a function

### ISSUE THREAD

**Issue by bretttjohnson1** [facebook/nuclide#1528]
[Enter steps to reproduce:]

1. Add a working set to nuclide

**Atom**: 1.27.0-beta1 x64
**Electron**: 1.7.11
**OS**: Ubuntu Bionic
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.302.0

### Stack Trace

Uncaught TypeError: repo.getProjectDirectory is not a function

```
At /home/brett/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsStore.js:170

TypeError: repo.getProjectDirectory is not a function
    at repos.map.repo (/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsStore.js:170:24)
    at Array.map (native)
    at WorkingSetsStore._saveDefinition (/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsStore.js:165:5)
    at WorkingSetsStore.saveWorkingSet (/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsStore.js:95:10)
    at /packages/nuclide/pkg/nuclide-file-tree/components/FileTreeToolbarComponent.js:209:24)
    at /packages/nuclide/pkg/nuclide-file-tree/components/WorkingSetNameAndSaveComponent.js:93:20)
    at /packages/nuclide/modules/nuclide-commons-ui/AtomInput.js:263:343)
    at CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom-beta/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom-beta/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom-beta/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
  6x -3:57.2.0 intentions:highlight (input.hidden-input)
     -3:25.7.0 settings-view:open (div.nuclide-file-tree-toolbar-container)
     -3:24.2.0 window:decrease-font-size (div.panels-item)
     -3:20.8.0 window:increase-font-size (div.panels-item)
     -3:19.3.0 window:decrease-font-size (div.panels-item)
  2x -3:18.6.0 window:increase-font-size (div.panels-item)
     -0:53.5.0 tree-view:remove-project-folder-selection (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-directory.name.nuclide-file-tree-path.icon-nuclicon-file-directory)
     -0:41.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.9.3 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-updater-linux 1.1.2 
busy-signal 1.4.3 
hidpi 0.14.0 
ide-python 0.8.1 
intentions 1.1.5 
language-haskell 1.17.3 
language-scheme 1.4.0 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
nuclide 0.302.0 
```

**Comment by thibaudalt** [comment]
Same here on macOS High Sierra with Atom 1.26.1

**Comment by awilkins** [comment]
Also running into this

* Project root folder is inside a git repository that is
  * Not the project root
  * Not present as a root in Atom

**Comment by awilkins** [comment]
Aha. Looks like `.getProjectDirectory()` is available when the repo is a Mercurial repository.

Workaround / Patch :

Open `pkg/nuclide-working-sets/lib/orkingSetsStore.js` and replace `getProjectDirectory()` on line 177 with `getWorkingDirectory()`.

Might break Mercurial support (seriously, who outside Facebook uses that....)  and might not have exactly the right effect when your checkout root isn't your project root but it's a quick edit and it seems to be OK for now.

**Comment by mkg20001** [comment]
Same here on Ubuntu 16.04 with Atom 1.28.0

**Comment by bsussman** [comment]
Same with 1.29.0-beta1.  

Code has changed - line 177 does not contain a reference to `getProjectDirectory()` but line 284 does.  Is this now the line to be altered as a temp workaround?

**Comment by aaronrr** [comment]
Same with Atom 1.26.1 on MacOS High Sierra (10.13.6)

For me the code was on line 170 changing to getWorkingDirectory() did the trick.

For anyone having trouble finding the file like me on it's in a hidden folder under your home directory on MacOS:
~/.atom/packages/nuclide/pkg/nuclide-working-sets/lib/WorkingSetsStore.js
