### ISSUE TITLE
Error: Not connected (Infinity Loop)

### ISSUE THREAD

**Issue by ezsper** [facebook/nuclide#153]
On Windows, it keeps popping up this message, even when my connection is established, the remote project works until this message, after this message pops, it keeps popping up until I close Atom, and reconnect to the remote folder.

My Atom version is 1.0.2,
My NodeJS version is 0.12.7
Windows 8.1

C:\Users\ezsper\.atom\packages\nuclide-remote-projects\node_modules\nuclide-remote-connection\lib\SshHandshake.js:318

Error: Not connected
  at Client.forwardOut (C:\Users\ezsper\.atom\packages\nuclide-remote-projects\node_modules\nuclide-remote-connection\node_modules\ssh2\lib\client.js:782:11)
  at SshHandshake._forwardSocket (C:\Users\ezsper\.atom\packages\nuclide-remote-projects\node_modules\nuclide-remote-connection\lib\SshHandshake.js:146:24)
  at Server.<anonymous> (C:\Users\ezsper\.atom\packages\nuclide-remote-projects\node_modules\nuclide-remote-connection\lib\SshHandshake.js:275:18)
  at emitOne (events.js:77:13)
  at Server.emit (events.js:166:7)
  at TCP.onconnection (net.js:1354:8

**Comment by ezsper** [comment]
I fixed by increasing the timeout of the `nuclide-start-server` from 10seconds to 60 seconds. But if I do a simple test of disconnecting my network and connecting again in 15 seconds, the message keeps popping up even when I'm online again.

**Comment by bolinfest** [comment]
Can you try the newest version of Nuclide (both server and client), v0.0.26? We've made some startup fixes.

**Comment by mostafaeweda** [comment]
Could you try now with the latest UP package release and feel free to open if that's still an issue: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
