### ISSUE TITLE
Language server 'jsimports' has crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by arizonahanson** [facebook/nuclide#1533]
### Issue and Steps to Reproduce
I repeatedly get a notification from Atom that reads:
 "Language server 'jsimports' has crashed 5 times in the last 3 minutes."

did a full reset - uninstalled atom, apm; removed ~/.atom, ~/.config/Atom;
reinstalled atom, nuclide - did a nuclide rebuild for atom version; set package-deps to install
error occurs when opening any .js file.

### Versions
* Atom: 1.26.1
* Nuclide: 0.302.0
* Client OS: Arch Linux

### Additional Details
Community Packages (25) /home/{snip}/.atom/packages
├── atom-material-ui@2.1.3
├── autocomplete-flow@1.6.0
├── autocomplete-modules@2.0.0
├── editorconfig@2.2.2
├── file-icons@2.1.20
├── go-plus@5.8.3
├── highlight-selected@0.13.1
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haskell@1.17.7
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-protobuf@0.7.1
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── nuclide@0.302.0
├── nuclide-format-js@0.0.45
├── one-dark-material-syntax@1.0.3
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.7

(node:31596) ExperimentalWarning: The fs.promises API is experimental

EDIT: found some info in the console:
[2018-05-14 11:38:41.859] [ERROR] nuclide-fuzzy-native - Failed to load native fuzzy matching. Falling back to JS implementation { Error: Cannot find module '/home/{snip}/.atom/packages/nuclide/node_modules/nuclide-prebuilt-libs/fuzzy-native/build/fuzzy-native-v0.7.2-node-v57-linux-x64/fuzzy-native.node'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/{snip}/.atom/packages/nuclide/node_modules/nuclide-prebuilt-libs/fuzzy-native/lib/main.js:6:18)
    at Object.<anonymous> (/home/{snip}/.atom/packages/nuclide/node_modules/nuclide-prebuilt-libs/fuzzy-native/lib/main.js:8:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12) code: 'MODULE_NOT_FOUND' }
[2018-05-14 11:38:46.169] [ERROR] js-imports-server - uncaughtException TypeError: Cannot read property 'toLowerCase' of undefined
    at new QueryItem (/home/{snip}/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/lib/QueryItem.js:120:39)
    at candidates.forEach.candidate (/home/{snip}/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/lib/FallbackMatcher.js:47:39)
    at Array.forEach (<anonymous>)
    at Matcher.addCandidates (/home/{snip}/.atom/packages/nuclide/pkg/nuclide-fuzzy-native/lib/FallbackMatcher.js:46:16)
    at ExportMatcher._performBatch (/home/{snip}/.atom/packages/nuclide/pkg/nuclide-js-imports-server/src/lib/ExportMatcher.js:64:21)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by hansonw** [comment]
Hey, did you install Atom from `pacman`? We've received reports of an issue where `pacman` incorrectly installs the wrong Electron version for Atom, leading to a similar error for Nuclide's terminal: https://github.com/facebook-atom/atom-ide-ui/issues/241#issuecomment-388630859

You can install Atom from the tarball in https://atom.io/releases as a workaround.

**Comment by hansonw** [comment]
Atom 1.26.1 is using Electron 1.7.11. (Electron 2.0.0 has landed in Atom master and will likely be released in 1.28, though.)

**Comment by craigbeck** [comment]
👍 same here. 

OSX 10.13.6
Atom 1.30.0-beta2

<img width="482" alt="screen shot 2018-08-17 at 12 28 09 pm" src="https://user-images.githubusercontent.com/1620605/44285141-0a91a780-a219-11e8-9285-0bee8452e1c6.png">
