### ISSUE TITLE
Cannot upgrade to latest version

### ISSUE THREAD

**Issue by Pozix** [facebook/nuclide#1542]
### Issue and Steps to Reproduce
apm update

### Expected Behavior
Updating to 0.307.0

### Actual Behavior
node-gyp error.
```
λ apm update
Package Updates Available (1)
└── nuclide 0.305.0 -> 0.307.0

Would you like to install these updates? (yes)

Installing nuclide@0.307.0 to C:\Users\User\.atom\packages failed

> runas@3.1.1 install C:\Users\User\AppData\Local\Temp\apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr\node_modules\nuclide\node_modules\runas
> node-gyp rebuild


C:\Users\User\AppData\Local\Temp\apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr\node_modules\nuclide\node_modules\runas>if not defined npm_config_node_gyp (node "C:\User\User\AppData\Local\atom\app-1.27.1\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\User\AppData\Local\atom\app-1.27.1\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.Cpp.Platform.targets(64,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...". [C:\Users\User\AppData\Local\Temp\apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr\node_modules\nuclide\node_modules\runas\build\runas.vcxproj]
C:\Users\User\AppData\Local\Temp\apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr
`-- (empty)


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\User\AppData\Local\atom\app-1.27.1\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\User\\AppData\\Local\\atom\\app-1.27.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\User\\AppData\\Local\\atom\\app-1.27.1\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\User\AppData\Local\Temp\apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr\node_modules\nuclide\node_modules\runas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.3 (node_modules\nuclide\node_modules\sane\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\User\AppData\Local\Temp\apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr\package.json'
npm WARN graphql-language-service-utils@1.1.0 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN graphql-language-service@1.1.2 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN relay-runtime@1.6.0 requires a peer of relay-compiler@1.6.0 but none was installed.
npm WARN graphql-language-service-server@1.1.2 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN graphql-language-service-interface@1.1.0 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN graphql-language-service-types@1.1.0 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr No description
npm WARN apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr No repository field.
npm WARN apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr No README data
npm WARN apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr No license field.
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\User\\AppData\\Local\\atom\\app-1.27.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\User\\AppData\\Local\\atom\\app-1.27.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\User\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\User\\.atom\\.apmrc" "install" "C:\\Users\\User\\AppData\\Local\\Temp\\d-118430-9276-17b6dp7.iej7n6zuxr\\package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\AppData\Local\Temp\apm-install-dir-118430-9276-1kdumj0.8zfb5r8uxr\npm-debug.log
npm ERR! code 1

```

### Versions
`apm --version`
```
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.1
python 2.7
git 2.17.0.windows.1
visual studio 2015
```
* Nuclide: 0.305.0
* Client OS: Win10

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── atom-beautify@0.32.5
├── atom-ide-ui@0.12.0 (disabled)
├── atom-live-server@2.2.0
├── atom-material-syntax@1.0.8
├── atom-material-syntax-dark@1.0.0
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@2.1.3
├── atom-python-run@0.9.6 (disabled)
├── atom-react-autocomplete@0.1.10
├── atom-typescript@12.5.1
├── auto-detect-indentation@1.3.0
├── autoclose-html@0.23.0
├── autocomplete-php@0.3.7
├── autocomplete-python@1.10.5
├── browser-plus@0.0.98
├── busy-signal@1.4.3
├── city-lights-syntax@1.1.8
├── city-lights-ui@1.3.3
├── color-picker@2.3.0
├── emmet@2.4.3
├── es6-javascript@1.0.0
├── file-icons@2.1.21
├── flow-ide@1.11.0
├── highlight-selected@0.13.1
├── Hydrogen@2.5.0
├── hyperclick@0.1.5
├── ide-css@0.3.0
├── ide-html@0.4.2
├── ide-json@0.2.1
├── ide-php@0.7.14
├── ide-python@0.9.2
├── ide-typescript@0.7.6
├── ide-vue@0.1.8
├── intentions@1.1.5
├── javascript-snippets@1.2.1
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haskell@1.17.7
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-csslint@2.0.1
├── linter-htmlhint@1.4.0
├── linter-jshint@3.1.8
├── linter-php@1.5.1
├── linter-sass-lint@1.8.3
├── linter-twig@0.4.2
├── linter-ui-default@1.7.1
├── local-history@4.3.1
├── markdown-writer@2.7.3
├── minimap@4.29.8
├── minimap-codeglance@0.4.7
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-highlight-selected@4.6.1
├── minimap-linter@2.1.3
├── minimap-pigments@0.2.2
├── minimap-selection@4.5.0
├── minimap-split-diff@0.3.7
├── monokai-seti@0.9.0
├── nuclide@0.305.0
├── nuclide-format-js@0.0.45
├── open-recent@5.0.0 (disabled)
├── pigments@0.40.2
├── project-manager@3.3.6
├── rest-client@1.3.1
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── todo-show@2.3.0
├── toggle-quotes@1.1.0
└── tool-bar@1.1.7
```

**Comment by Pozix** [comment]
I first had this issue as well:
https://github.com/facebook/nuclide/issues/1541
I switched to python 2.7 and got this one next.

**Comment by hansonw** [comment]
Yeah I think the workaround is to rollback to v0.301.0 for now. (I don't know how to resolve the underlying 'msbuild' issue here, but we'll probably remove "jest" from the dependencies for the next release.)
