### ISSUE TITLE
Server Error on nuclide-start-server in version 0.307.0

### ISSUE THREAD

**Issue by CreateWebNZ** [facebook/nuclide#1543]
### Issue and Steps to Reproduce
Since the update to 0.307.0, when I try to connect to the server, it attempts to connect for approx. 1 minute and then throws an error message. 

* Update nuclide from 0.303.0 to 0.307.0
* Connect to a remote server via ssh

### Expected Behavior
Nuclide server starts and the editor establishes a connection

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom: 1.27.1
* Nuclide: 0.307.0
* Client OS: Ubuntu 17.10 / Ubuntu 18.04 / Mac osx 10.13.4
* Server OS: Ubuntu 16.04

### Additional Details
The nuclide log reveals the following:

```
/usr/lib/node_modules/nuclide/pkg/nuclide-server/lib/main.js:64
async function getServerCredentials(args) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at NativeCompileCache._moduleCompile (/usr/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (/usr/lib/node_modules/nuclide/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/nuclide/pkg/nuclide-server/lib/nuclide-main.js:27:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3

```

**Comment by bbbbbrie** [comment]
**+1**

I can confirm that I can reproduce this behavior with Nuclide versions 0.307.0 and 0.311.0.

Atom: `1.27.2`
Nuclide: `0.307.0`
Client OS: `Ubuntu 16.04` (multiple clients)
Server OS: `CentOS 7.4` (multiple servers)

The entries observed in the corresponding log for Nuclide match what OP wrote. I'm happy to share more upon request.

Thank you!

--
Brie

**Comment by Empornium** [comment]
Your version of nodejs is too old, for async functions you need 7.6 or higher.

**Comment by semmypurewal** [comment]
Yeah, @Empornium is correct. We stopped compiling away async/await in Node once it landed in Node 8. So updating to Node 8+ should resolve this issue.
