### ISSUE TITLE
Cannot install NUCLIDE package in ATOM ide.

### ISSUE THREAD

**Issue by sparkeplug** [facebook/nuclide#1546]
### Issue and Steps to Reproduce

1. Open Atom.
2. Choose Atom | Preferences (Edit | Preferences on Linux and File | Settings on Windows) to bring up the Settings tab.
3. In the Settings tab, select Install from the list at the left.
4. In the search box, type “Nuclide” and press the Enter key.
5. Click the Install button for the nuclide package.

### Expected Behavior
Obviously , it should install.

### Actual Behavior
I'm getting the following console errors:

```
> runas@3.1.1 install C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11856-10488-1ls4rfu.6kfn7b9\node_modules\nuclide\node_modules\runas
> node-gyp rebuild


C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11856-10488-1ls4rfu.6kfn7b9\node_modules\nuclide\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\prabhuramkumarb\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\prabhuramkumarb\AppData\Local\atom\app-1.27.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11856-10488-1ls4rfu.6kfn7b9
`-- (empty)


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "C:\Users\prabhuramkumarb\AppData\Local\Programs\Python\Python36-32\python.EXE" is v3.6.5, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\prabhuramkumarb\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Users\prabhuramkumarb\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\prabhuramkumarb\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\prabhuramkumarb\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11856-10488-1ls4rfu.6kfn7b9\node_modules\nuclide\node_modules\runas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11856-10488-1ls4rfu.6kfn7b9\package.json'
npm WARN graphql-language-service@1.1.2 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN graphql-language-service-utils@1.1.0 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN relay-runtime@1.6.0 requires a peer of relay-compiler@1.6.0 but none was installed.
npm WARN graphql-language-service-types@1.2.1 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN apm-install-dir-11856-10488-1ls4rfu.6kfn7b9 No description
npm WARN apm-install-dir-11856-10488-1ls4rfu.6kfn7b9 No repository field.
npm WARN apm-install-dir-11856-10488-1ls4rfu.6kfn7b9 No README data
npm WARN apm-install-dir-11856-10488-1ls4rfu.6kfn7b9 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\prabhuramkumarb\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\prabhuramkumarb\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\prabhuramkumarb\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\prabhuramkumarb\\.atom\\.apmrc" "install" "C:\\Users\\PRABHU~1\\AppData\\Local\\Temp\\d-11856-10488-1s84hp1.mvi5c7syvi\\package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11856-10488-1ls4rfu.6kfn7b9\npm-debug.log
npm ERR! code 1
```

### Versions
* Atom: 1.27.2
* Nuclide: 0.310.0
* Client OS: Windows 10
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

`
Community Packages (79) C:\Users\prabhuramkumarb\.atom\packages

- ├── activate-power-mode@2.7.0
- ├── api-docs@0.0.6
- ├── atom-beautify@0.32.5
- ├── atom-css-class-checker@0.4.3
- ├── atom-css-comb@3.3.1
- ├── atom-css-unit-converter@1.1.1
- ├── atom-ide-ui@0.12.0
- ├── atom-import-sort@4.2.0
- ├── atom-jasmine@0.9.1
- ├── atom-karma-test-runner@1.1.1
- ├── atom-live-server@2.2.0
- ├── atom-material-syntax@1.0.8
- ├── atom-material-syntax-dark@1.0.0
- ├── atom-material-syntax-light@0.4.6
- ├── atom-material-ui@2.1.3
- ├── atom-terminal@0.8.0
- ├── atom-typescript@12.5.1
- ├── atom-wrap-in-tag@0.6.0
- ├── auto-detect-indentation@1.3.0
- ├── autoclose-html@0.23.0
- ├── autocomplete@0.47.0
- ├── autocomplete-js-import@1.4.0
- ├── autocomplete-math@0.1.1
- ├── avocode@0.0.9
- ├── behave-theme@1.7.0
- ├── bottom-dock@0.4.4
- ├── build-grunt@0.4.0 (disabled)
- ├── busy-signal@1.4.3
- ├── code-peek@1.4.21
- ├── color-picker@2.3.0
- ├── css-comb@2.5.0 (disabled)
- ├── emmet@2.4.3
- ├── file-icons@2.1.21
- ├── git-blame@1.6.0
- ├── git-control@0.9.0
- ├── git-controlhub@0.4.0
- ├── git-diff-details@1.4.0
- ├── git-log@0.4.1
- ├── git-plus@7.10.2
- ├── grunt-manager@0.1.16 (disabled)
- ├── grunt-runner@0.14.0 (disabled)
- ├── hydra-syntax-theme@4.0.1
- ├── hyper-alien-ui-theme@0.4.0
- ├── hyperclick@0.1.5
- ├── ide-typescript@0.7.6 (disabled)
- ├── intentions@1.1.5
- ├── isotope-ui@2.8.5
- ├── language-vue@0.23.1
- ├── linter@2.2.0 (disabled)
- ├── linter-csslint@2.0.1 (disabled)
- ├── linter-eslint@8.4.1
- ├── linter-jshint@3.1.8 (disabled)
- ├── linter-sass-lint@1.8.3 (disabled)
- ├── linter-scss-lint@3.1.1
- ├── linter-stylelint@4.3.0 (disabled)
- ├── linter-tidy@2.3.1
- ├── linter-tslint@1.9.1 (disabled)
- ├── linter-ui-default@1.7.1
- ├── livereload@0.4.4
- ├── material@2.2.0
- ├── material-ui@1.0.10
- ├── minimap@4.29.8
- ├── minimap-linter@2.1.3
- ├── minimap-pigments@0.2.2
- ├── mocha-ui@0.1.8 (disabled)
- ├── pigments@0.40.2
- ├── platformio-ide-terminal@2.8.1
- ├── prettier-atom@0.54.0
- ├── save-autorun@0.3.3
- ├── styri-syntax@0.2.0
- ├── svg-preview@0.12.1
- ├── sync-settings@0.8.6
- ├── teletype@0.13.3
- ├── theme-alien-syntax@0.6.0
- ├── todo-show@2.3.0
- ├── tree-view-git-status@1.5.0
- ├── unicode-input@0.5.1
- ├── vue2-autocomplete@0.1.0-alpha.4
- └── zalton-syntax@1.3.0

`

**Comment by drmathochist** [comment]
At the top, I'm seeing this error:
```
gyp ERR! stack Error: Python executable "C:\Users\prabhuramkumarb\AppData\Local\Programs\Python\Python36-32\python.EXE" is v3.6.5, which is not supported by gyp.
```

Can you try a different python version?

**Comment by sparkeplug** [comment]
Hi again,

Ive installed Python V.2.7.15

and got the following new error message.

```
> runas@3.1.1 install C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11857-2732-129como.1wvf2mx6r\node_modules\nuclide\node_modules\runas
> node-gyp rebuild


C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11857-2732-129como.1wvf2mx6r\node_modules\nuclide\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\prabhuramkumarb\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\prabhuramkumarb\AppData\Local\atom\app-1.27.2\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11857-2732-129como.1wvf2mx6r\node_modules\nuclide\node_modules\runas\build\binding.sln]
C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11857-2732-129como.1wvf2mx6r
`-- (empty)


npm WARN excluding symbolic link pkg\nuclide-fs-atom\__mocks__\fixtures -> ../../nuclide-fs/spec/fixtures
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\Directory\LinkDotDotSlashTextFile.txt -> ../TextFile.txt
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkDirectory -> Directory
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkDirectorySlashTextFile.txt -> Directory/TextFile.txt
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkLinkDirectory -> LinkDirectory
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkLinkDirectorySlashTextFile.txt -> LinkDirectorySlashTextFile.txt
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN excluding symbolic link pkg\nuclide-fs-atom\__mocks__\fixtures -> ../../nuclide-fs/spec/fixtures
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\Directory\LinkDotDotSlashTextFile.txt -> ../TextFile.txt
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkDirectory -> Directory
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkDirectorySlashTextFile.txt -> Directory/TextFile.txt
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkLinkDirectory -> LinkDirectory
npm WARN excluding symbolic link pkg\nuclide-fs\__mocks__\fixtures\dir\LinkLinkDirectorySlashTextFile.txt -> LinkDirectorySlashTextFile.txt
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\prabhuramkumarb\AppData\Local\atom\app-1.27.2\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\prabhuramkumarb\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\prabhuramkumarb\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11857-2732-129como.1wvf2mx6r\node_modules\nuclide\node_modules\runas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11857-2732-129como.1wvf2mx6r\package.json'
npm WARN relay-runtime@1.6.0 requires a peer of relay-compiler@1.6.0 but none was installed.
npm WARN graphql-language-service-utils@1.1.0 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN graphql-language-service@1.1.2 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN graphql-language-service-types@1.2.1 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN apm-install-dir-11857-2732-129como.1wvf2mx6r No description
npm WARN apm-install-dir-11857-2732-129como.1wvf2mx6r No repository field.
npm WARN apm-install-dir-11857-2732-129como.1wvf2mx6r No README data
npm WARN apm-install-dir-11857-2732-129como.1wvf2mx6r No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\prabhuramkumarb\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\prabhuramkumarb\\AppData\\Local\\atom\\app-1.27.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\prabhuramkumarb\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\prabhuramkumarb\\.atom\\.apmrc" "install" "C:\\Users\\PRABHU~1\\AppData\\Local\\Temp\\d-11857-2732-10cxokp.yjeeb9ms4i\\package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PRABHU~1\AppData\Local\Temp\apm-install-dir-11857-2732-129como.1wvf2mx6r\npm-debug.log
npm ERR! code 1
```

Are most of the users facing this kinda issue ?

**Comment by drmathochist** [comment]
cc @tjfryan

**Comment by DrFlavour** [comment]
I am currently facing the same issue. 

Is it possible to get instructions on how to install an earlier version using apm? I have tried, apm install nuclide@v0.310.0 and apm install nuclide@0.310.0. It states that package version is not found.

**Comment by sparkeplug** [comment]
Can install the package now. Closing the defect.
