### ISSUE TITLE
Uncaught TypeError: Cannot read property 'tunnelBehavior' of null

### ISSUE THREAD

**Issue by wenchao93** [facebook/nuclide#1553]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.315.0

### Stack Trace

Uncaught TypeError: Cannot read property 'tunnelBehavior' of null

```
At /Users/wenchaoleong/.atom/packages/nuclide/pkg/nuclide-metro/lib/main.js:36

TypeError: Cannot read property 'tunnelBehavior' of null
    at /packages/nuclide/pkg/nuclide-metro/lib/main.js:36:44)
    at CommandRegistry.handleCommandEvent (/Users/wenchaoleong/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at Object.didConfirmSelection (/Users/wenchaoleong/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:152:35)
    at SelectListView.confirmSelection (/Users/wenchaoleong/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (/Users/wenchaoleong/Applications/Atom.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (/Users/wenchaoleong/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/wenchaoleong/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/wenchaoleong/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Users/wenchaoleong/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -0:13.4.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:10 command-palette:toggle (div.package-detail.panels-item)
  3x -0:07.9.0 core:move-down (input.hidden-input)
     -0:07.2.0 core:confirm (input.hidden-input)
     -0:07.2.0 nuclide-metro:start (div.package-detail.panels-item)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.5 
language-babel 2.85.0 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
nuclide 0.315.0 
```

**Comment by LorienOlive** [comment]
Happening for me too.  Nuclide is suddenly unusable after an update.

**Comment by OrbitalStudios** [comment]
Entire team is getting this. It's a gating issue and requires a full downgrade to get back up and running.

**Comment by tucison** [comment]
看不懂怎么办，这特么太尴尬了

**Comment by yancouto** [comment]
Fix is on the way. Sorry for that.

**Comment by wellyshen** [comment]
This issue has been fixed.
