### ISSUE TITLE
Failed to start nuclide-server with custom `--port` set.

### ISSUE THREAD

**Issue by ryan953** [facebook/nuclide#1558]
### Issue and Steps to Reproduce
`nuclide-start-server` fails to start with the `--port 8080` param included in the Remote Server Command string.

I use a wrapper bash script around nuclide-start-server to ensure that nvm is started and using node v7... at the end of that script I run the statement:
`nuclide-start-server "$@" --port 8080` which fails to start nuclide. It returns the error:
```
SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at parseArgsAndRunMain (/home/ryanalbrecht/.nvm/versions/node/v7.10.1/lib/node_modules/nuclide/modules/big-dig/src/server/cli.js:74:23)
    at Object.<anonymous> (/home/ryanalbrecht/.nvm/versions/node/v7.10.1/lib/node_modules/nuclide/pkg/nuclide-server2/lib/main.js:29:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
```

If I flip the argument order around to be `nuclide-start-server --port 8080 "$@"` it still fails with a new error:
```
Usage: nuclide_server_manager.py [options]

nuclide_server_manager.py: error: no such option: --big-dig
```

When I remove the `--port` flag and connect over the default port 9093 everything works great.

### Expected Behavior
Should be able to set `--port`

### Versions
* Atom: 1.27.2
* Nuclide: 0.315.0 (experienced error in 0.311.0 too)
* Client OS: OSX
* Server OS (optional): Ubuntu Trusty 14.04

### Additional Details
* Installed packages (`apm ls --installed`):

The --big-dig check in [nuclide-start-server](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-server/nuclide-start-server#L15) looks too strict as it's only checking for that flag inside `$1`. Failing that check [node_server_manager.py#L308](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-server/scripts/nuclide_server_manager.py#L308) doesn't like the --big-dig flag because the options parser doesn't know about it.
There might be more that makes this related to #1555

**Comment by hansonw** [comment]
Ah yeah we switched to passing the port option in as part of a JSON blob.
You can still use the `--port=8080` flag but it has to be through the Nuclide UI:

![screen shot 2018-06-19 at 1 45 33 pm](https://user-images.githubusercontent.com/577378/41624718-57bbb73e-73cb-11e8-9764-5bdc4cef1c56.png)

We'll silently parse that flag out and put it into the JSON blob for you.

**Comment by ryan953** [comment]
ah right on. 
I like pointing people in my org to the script though because it glosses over this type config. Especially setting nvm, that's been a great win to let us use v7 for nuclide and versions for whatever scripts people have running outside of docker.

Can I make it a feature request to put that port flag parsing back into nuclide-start-server?

I have other work arounds...  but I suspect the UI doing this type of munging is non-obvious to other ppl too.

**Comment by hansonw** [comment]
cc @semmypurewal - people are already using Nuclide with Docker :)

**Comment by semmypurewal** [comment]
Oh cool! Hey @ryan953 it'd be awesome to sync up some time and hear how you and your team are using Nuclide with Docker! Feel free to reach out to me at my first name (semmy) at fb.com!

**Comment by ryan953** [comment]
@semmypurewal, i'm not running nuclide inside docker... but someone should play with that. It'd be great to simplify the install requirements, I wonder if watchman would be happy inside a container...

I mentioned docker in relation to node versions. nuclide requires node7 afaik but I've got some other js scripts that we want to run under node 8 and 9. So I use nvm to make sure the correct node version is running.

**Comment by semmypurewal** [comment]
Ah, gotcha! Yeah, that's been something we've been thinking about. I was able to create a VM with the dependencies (including watchman) which was pretty straightforward, so a Docker container shouldn't be too much different. If we could do this, then I think we could more easily distribute development environments. It's something that I'm hoping we look into next half.
