### ISSUE TITLE
Uncaught TypeError: p.getTabName is not a function

### ISSUE THREAD

**Issue by tailor4927** [facebook/nuclide#1559]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.317.0

### Stack Trace

Uncaught TypeError: p.getTabName is not a function

```
At /home/bijal/.atom/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:182

TypeError: p.getTabName is not a function
    at selectedProvider.find.p (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/ui/DebuggerLaunchAttachUI.js:127:81)
    at Array.find (native)
    at DebuggerLaunchAttachUI.componentWillMount (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/ui/DebuggerLaunchAttachUI.js:127:69)
    at mountClassInstance (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:112:147)
    at beginWork (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:138:175)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:176:105)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:176:379)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:182:329)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:181:378)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:181:221)
    at interactiveUpdates (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:188:482)
    at Xd (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:84:203)
```

### Commands

```
     -0:15.9.0 debugger:show-attach-dialog (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
```

### Non-Core Packages

```
atom-ide-debugger-native-gdb 0.7.2 
atom-ide-debugger-react-native 0.7.1 
atom-react 0.4.0 
atom-react-autocomplete 0.1.10 
atom-react-instyle 0.2.8 
atom-react-native-style 0.2.0 
atom-react-snippets 0.2.2 
nuclide 0.317.0 
react-native-components 0.1.1 
react-native-snippets 0.3.0 
react-redux-atom-snippets 0.7.2 
react-snippets-for-atom 0.2.0 
```

**Comment by brianramirez** [comment]
Any update/status with this? I am experiencing the exact same issue.
