### ISSUE TITLE
Uncaught TypeError: Cannot read property 'beginFrame' of undefined

### ISSUE THREAD

**Issue by GULERTOLGA** [facebook/nuclide#1563]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.317.0

### Stack Trace

Uncaught TypeError: Cannot read property 'beginFrame' of undefined

```
At /Users/tolgaguler/.atom/packages/nuclide/node_modules/xterm/lib/renderer/TextRenderLayer.js:143

TypeError: Cannot read property 'beginFrame' of undefined
    at TextRenderLayer.onGridChanged (/packages/nuclide/node_modules/xterm/lib/renderer/TextRenderLayer.js:143:25)
    at /packages/nuclide/node_modules/xterm/lib/renderer/Renderer.js:154:60
    at Array.forEach (<anonymous>)
    at Renderer._renderRows (/packages/nuclide/node_modules/xterm/lib/renderer/Renderer.js:154:28)
    at RenderDebouncer._innerRefresh (/packages/nuclide/node_modules/xterm/lib/utils/RenderDebouncer.js:29:14)
    at /packages/nuclide/node_modules/xterm/lib/utils/RenderDebouncer.js:24:88
```

### Commands

```
     -4:44.4.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:26.9.0 atom-ide-terminal:new-terminal (input.hidden-input)
```

### Non-Core Packages

```
nuclide 0.317.0 
nuclide-format-js 0.0.46 
react 0.18.0 
```

**Comment by pelmers** [comment]
fixed in latest release
