### ISSUE TITLE
Uncaught TypeError: Cannot read property 'params' of undefined

### ISSUE THREAD

**Issue by sidazhang** [facebook/nuclide#1564]
### Issue and Steps to Reproduce
Try to create a remote folder profile

### Expected Behavior
The profile should be created

### Actual Behavior
Uncaught TypeError

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Ubuntu 14.04.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.319.0

### Stack Trace

Uncaught TypeError: Cannot read property 'params' of undefined

```
At /home/sidney/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71

TypeError: Cannot read property 'params' of undefined
    at ConnectionDetailsPrompt.getPrefilledConnectionParams (/packages/nuclide/pkg/nuclide-remote-projects/lib/ConnectionDetailsPrompt.js:168:30)
    at ConnectionDetailsPrompt.render (/packages/nuclide/pkg/nuclide-remote-projects/lib/ConnectionDetailsPrompt.js:190:44)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:131:338)
    at beginWork (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:138:287)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:176:105)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:176:379)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:182:329)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:181:378)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:181:221)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:180:117)
    at /packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:179:51)
    at Object.enqueueSetState (/packages/nuclide/node_modules/react-dom/cjs/react-dom.production.min.js:110:32)
    at Object.E.setState (/packages/nuclide/node_modules/react/cjs/react.production.min.js:12:224)
    at /packages/nuclide/modules/nuclide-commons-ui/bindObservableAsProps.js:47:14)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:88:375)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:136:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:183:159)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:77:124)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:231:67)
    at Model.setState (/packages/nuclide/modules/nuclide-commons/Model.js:62:18)
    at updateState (/packages/nuclide/pkg/nuclide-remote-projects/lib/open-connection.js:176:11)
    at /packages/nuclide/pkg/nuclide-remote-projects/lib/open-connection.js:201:5)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:136:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at default.onDidChange.event (/packages/nuclide/pkg/nuclide-remote-projects/lib/connection-profile-utils.js:153:5)
    at emitter.on (/usr/share/atom/resources/app/src/config.js:1067:22)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:1226:62)
    at Config.setRawValue (/usr/share/atom/resources/app/src/config.js:1052:23)
    at Config.set (/usr/share/atom/resources/app/src/config.js:715:18)
    at SettingsPanel.set (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:238:34)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-panel.js:333:36
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1817:26)
    at later (/usr/share/atom/resources/app/node_modules/text-buffer/lib/helpers.js:28:13)
```

### Commands

```
     -1:10.5.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:57.1.0 core:backspace (input.hidden-input)
  2x -0:35.8.0 core:cancel (atom-pane.pane.active)
     -0:33.8.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:21.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-python 1.10.5 
file-icons 2.1.21 
highlight-selected 0.13.1 
language-babel 2.85.0 
language-graphql 0.10.1 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
nuclide 0.319.0 
nuclide-format-js 0.0.46 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
```

**Comment by sidazhang** [comment]
Seems like I needed to update node version on my machine. This resolved the problem

**Comment by Dayjo** [comment]
Just a FYI; I got this error on a machine that did not have `atom` or `apm` cli tools installed.

**Comment by dotku** [comment]
Can the password be empty?
