### ISSUE TITLE
Installing “nuclide@0.332.0” failed.

### ISSUE THREAD

**Issue by krrevilla** [facebook/nuclide#1586]
### Issue and Steps to Reproduce
1. Download latest atom.
2. Install Nuclide, via packages or apm install

### Expected Behavior
Success installation

### Actual Behavior
Failure to install.
/usr/share/atom/resources/app/apm/lib/install.js:313
          if (body.releases.latest) {
                           ^
TypeError: Cannot read property 'latest' of undefined
    at /usr/share/atom/resources/app/apm/lib/install.js:313:28
    at Request._callback (/usr/share/atom/resources/app/apm/lib/request.js:56:22)
    at Request.self.callback (/usr/share/atom/resources/app/apm/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)

### Versions
* Atom: 1.29
* Nuclide: 0.332.0
* Client OS: Ubuntu 18.04
* Server OS (optional):

**Comment by evangrayk** [comment]
I can't seem to reproduce this. The error snippet you have looks to be an error inside of apm, you may want to file an issue in their repo (https://github.com/atom/apm).

**Comment by krrevilla** [comment]
@evangrayk got it. will close it now. thanks
