### ISSUE TITLE
Uncaught TypeError: Parameter "url" must be a string, not undefined

### ISSUE THREAD

**Issue by NhatPhuong** [facebook/nuclide#1594]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.337.0

### Stack Trace

Uncaught TypeError: Parameter "url" must be a string, not undefined

```
At /Users/admin/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:119

TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:103:11)
    at Object.urlParse [as parse] (url.js:97:13)
    at TerminalView._statistics (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/terminal-view.js:424:22)
    at /packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/terminal-view.js:395:124)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.dispatch (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:121:78)
    at a._execute (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:118:206)
    at a.execute (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:118:27)
    at a.flush (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:119:368)
```

### Commands

```
```

### Non-Core Packages

```
aligner-css 1.2.1 
atom-css-comb 3.3.1 
atom-react-native-style 0.2.0 
Atom-Syntax-highlighting-for-Sass 0.5.0 
autocomplete-modules 2.1.0 
busy-signal 1.4.3 
change-case 0.6.5 
color-picker 2.3.0 
config-import-export 0.3.1 
copy-path 0.5.1 
css-declaration-sorter 1.2.2 
css-snippets 1.1.0 
duplicate-line-or-selection 0.9.0 
emmet 2.4.3 
file-icons 2.1.24 
flexbox-snippets 0.3.0 
fonts 3.1.0 
git-history 3.3.0 
highlight-selected 0.14.0 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.13.3 
language-babel 2.85.0 
language-graphql 0.10.1 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-eslint 8.4.1 
linter-stylelint 4.3.2 
linter-ui-default 1.7.1 
local-history 4.3.1 
nuclide 0.337.0 
nuclide-format-js 0.0.47 
pigments 0.40.2 
prettier-atom 0.54.0 
react-native-components 0.1.1 
react-native-snippets-horse 2.0.0 
save-workspace 0.5.0 
set-syntax 0.4.0 
sort-lines 0.18.0 
svg-preview 0.12.1 
toggle-quotes 1.1.1 
tool-bar 1.1.7 
```

**Comment by pelmers** [comment]
Hi, sorry about this issue. It is safe to ignore and will be fixed in this week's release
