### ISSUE TITLE
Uncaught Error: Cannot find module './atlas/Types'

### ISSUE THREAD

**Issue by nikmedoed** [facebook/nuclide#1603]
[Enter steps to reproduce:]

1. update packadges
2. reopen atom
3. open cmd (shift+alt+T)

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Windows 10 Pro 10.0.15063
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.341.0

### Stack Trace

Uncaught Error: Cannot find module './atlas/Types'

```
At C:\Users\NikitaAM\.atom\packages\nuclide\node_modules\rxjs\bundles\Rx.min.js:310

Error: Cannot find module './atlas/Types'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.30.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.30.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/nuclide/node_modules/xterm/lib/renderer/TextRenderLayer.js:14:15)
    at /packages/nuclide/node_modules/xterm/lib/renderer/TextRenderLayer.js:189:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/nuclide/node_modules/xterm/lib/renderer/Renderer.js:13:25)
    at /packages/nuclide/node_modules/xterm/lib/renderer/Renderer.js:193:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/nuclide/node_modules/xterm/lib/Terminal.js:21:18)
    at /packages/nuclide/node_modules/xterm/lib/Terminal.js:1265:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
```

### Commands

```
     -2:46.6.0 core:backspace (input.hidden-input)
     -2:12.3.0 core:paste (input.hidden-input)
     -1:57.2.0 core:delete (input.hidden-input)
     -0:08.9.0 atom-ide-terminal:new-terminal (input#nuclide.atom-ide-signature-help.enable.input-checkbox)
```

### Non-Core Packages

```
atom-import-js 0.15.0 
atom-js-console 1.2.2 
file-icons 2.1.24 
highlight-selected 0.14.0 
hyperclick 0.1.5 
language-babel 2.85.0 
language-graphql 0.10.1 
language-haskell 1.17.8 
language-ini 1.20.0 
language-javascript-jsx 0.3.7 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
nuclide 0.341.0 
nuclide-format-js 0.0.47 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.8 
```

**Comment by pelmers** [comment]
Seems like a file is missing/corrupted, can you try uninstall + re-install nuclide?

**Comment by nikmedoed** [comment]
This helped
