### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by initialxy** [facebook/nuclide#161]
[Enter steps to reproduce below:]

I'm really not sure how to reproduce this consistently. One thing I noticed is that my SSH session seem to have timed out at just the right time. I'm connected to a remote project through SSH. I suddenly started getting this error when I press command + option + t. Since then this error appears every time I press command + option + t. I restarted Nuclide and reconnected SSH, then this error is gone.

**Atom Version**: 1.0.13332683
**System**: Mac OS X 10.10.4
**Thrown From**: [nuclide-quick-open](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'map' of undefined

```
At /Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-quick-open/lib/QuickSelectionComponent.js:533

TypeError: Cannot read property 'map' of undefined
  at QuickSelectionComponent._renderTabs (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-quick-open/lib/QuickSelectionComponent.js:533:33)
  at QuickSelectionComponent.render (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-quick-open/lib/QuickSelectionComponent.js:708:14)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:775:34)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:801:14)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:235:30)
  at Object.ReactReconciler.mountComponent (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/ReactReconciler.js:38:35)
  at mountComponentIntoNode (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/ReactMount.js:248:32)
  at ReactReconcileTransaction.Mixin.perform (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/Transaction.js:134:20)
  at batchedMountComponentIntoNode (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/ReactMount.js:269:15)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/Transaction.js:134:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.batchedUpdates (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/ReactUpdates.js:110:20)
  at Object.ReactMount._renderNewRootComponent (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/ReactMount.js:404:18)
  at Object.ReactMount.render (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-buck-toolbar/node_modules/react-for-atom/node_modules/react/lib/ReactMount.js:493:32)
  at Activation._render (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-quick-open/lib/main.js:168:20)
  at new Activation (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-quick-open/lib/main.js:101:34)
  at activateSearchUI (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-quick-open/lib/main.js:250:18)
  at atom-workspace.nuclideQuickOpenToggleQuickOpen (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-quick-open/lib/main.js:297:9)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Nuclide.app/Contents/Resources/app/src/command-registry.js:241:29)
  at /Applications/Nuclide.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Nuclide.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Nuclide.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Nuclide.app/Contents/Resources/app/src/window-event-handler.js:177:20)

```

### Commands

```
  2x -2:17.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -2:17.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:16.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:35.1.0 core:copy (atom-text-editor.editor.is-focused)
     -1:30 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:28.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -1:28.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
  5x -1:16 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:09.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:08.0 core:copy (atom-text-editor.editor.is-focused.hyperclick)
  6x -1:03.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:40.4.0 core:save (atom-text-editor.editor.is-focused.hyperclick-loading)
     -0:39.5.0 find-and-replace:show (atom-text-editor.editor.is-focused.hyperclick-loading)
     -0:39.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:39.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:01.0 nuclide-quick-open:toggle-quick-open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "tree-view"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
fb-nuclide-installer, v0.1.4

# Dev
No dev packages
```

**Comment by bolinfest** [comment]
This is a Facebook-specific issue. Please report internally.
