### ISSUE TITLE
Uncaught Error: Cannot find module '../services/LinterAdapter'

### ISSUE THREAD

**Issue by LukaSikic** [facebook/nuclide#1610]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Linux Mint
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.345.0

### Stack Trace

Uncaught Error: Cannot find module '../services/LinterAdapter'

```
At /home/luka/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71

Error: Cannot find module '../services/LinterAdapter'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at _LinterAdapter (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/IndieLinterRegistry.js:21:16)
    at IndieLinterDelegate.setAllMessages (/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-diagnostics/lib/services/IndieLinterRegistry.js:97:28)
    at /packages/nuclide/pkg/nuclide-python/lib/main.js:212:137)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:183:159)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:262:433)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:240)
    at a._innerSub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:262:1)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:261:375)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:194:28)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:136:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.x (/packages/nuclide/modules/nuclide-commons/observable.js:412:66)
    at later (/packages/nuclide/modules/nuclide-commons/debounce.js:40:23)
```

### Commands

```
  4x -4:34.5.0 core:backspace (input.hidden-input)
  2x -4:24.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
nuclide 0.345.0 
```

**Comment by pelmers** [comment]
maybe fixed by a199693ac048545a02843bbb7537da841636ae52, though I wasn't able to reproduce the problem.

Please re-open if it happens in Nuclide version > 349.
