### ISSUE TITLE
Uncaught ProcessExitError: "ps" failed with exit code 1ps -eo pid,ppid,pcpu,time,rss,vsz,command

### ISSUE THREAD

**Issue by ermik** [facebook/nuclide#1623]
[Enter steps to reproduce:]
Happened in the background

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.353.0

### Stack Trace

Uncaught ProcessExitError: "ps" failed with exit code 1

ps -eo pid,ppid,pcpu,time,rss,vsz,command

```
At /Users/ermik/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71

ProcessExitError: "ps" failed with exit code 1



ps -eo pid,ppid,pcpu,time,rss,vsz,command
    at /packages/nuclide/modules/nuclide-commons/process.js:315:15)
    at a._tryNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:216:66)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:215:461)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.notifyNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:88:375)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:52)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at /packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:240)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:166:129)
    at a.notifyError (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:88:439)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:160)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at a.notifyError (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:88:439)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:160)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:274)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at /packages/nuclide/modules/nuclide-commons/observable.js:302:14)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70:250)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:274)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at a.notifyError (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:88:439)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:90:160)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:77:309)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:274)
    at a._error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:226:379)
    at a.error (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:486)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:136:175)
```

### Commands

```
```

### Non-Core Packages

```
atom-ternjs 0.18.3 
atom-typescript 12.6.3 
docker 0.8.0 
file-icons 2.1.25 
go-debug 1.6.2 
go-plus 5.8.6 
gotests 0.4.0 
highlight-selected 0.14.0 
ide-csharp 0.6.2 
ide-flowtype 0.23.1 
ide-json 0.2.1 
ide-typescript 0.7.6 
ide-yaml 0.4.4 
language-babel 2.85.0 
language-graphql 0.11.0 
language-haskell 1.17.8 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-logstash 0.1.7 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-protobuf 0.7.1 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
linter-eslint 8.4.1 
linter-js-yaml 1.3.0 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-ruby 1.2.6 
linter-sass-lint 1.8.3 
linter-tslint 1.9.1 
no-title-bar 1.11.4 
nuclide 0.353.0 
nuclide-format-js 0.0.47 
oceanic-next 1.0.0 
prettier-atom 0.55.2 
set-syntax 0.4.0 
sort-lines 0.18.0 
todo-show 2.3.2 
tool-bar 1.1.10 
```

**Comment by velocityboy** [comment]
This is really weird. ps should never fail. If you enter the command from
the shell prompt, does it succeed? Is your system extremely resource
constrained right now?

**Comment by ermik** [comment]
ps starts http server on port 4000 from the shell / terminal; I don't even know what it is though
system is not constrained
