### ISSUE TITLE
Uncaught Error: Cannot find module 'react-for-atom'

### ISSUE THREAD

**Issue by bdubaut** [facebook/nuclide#163]
After updating Nuclide I now get this error when I am launching Atom: `module.js:330`

Stack trace:
```
Error: Cannot find module 'react-for-atom'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/bertrand.dubaut/.atom/packages/nuclide-diagnostics-ui/lib/gutter.js:20:13)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

**Comment by bolinfest** [comment]
My bad: I broke this with https://github.com/facebook/nuclide/commit/45463ccc3ae19635e06e27c817584afe6ffb6980. `react-for-atom` should have been listed in `dependencies` rather than `devDependencies`.

**Comment by bolinfest** [comment]
Fixed in https://github.com/facebook/nuclide/commit/cbe63210b541130790d695d313e7dd104c047e68. Pushing a release now.
