### ISSUE TITLE
Cannot find module '../../fb-appsession-observer'

### ISSUE THREAD

**Issue by uri-canva** [facebook/nuclide#1639]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

Error on atom launch:

Full stack trace:

```
Error: Cannot find module '../../fb-appsession-observer'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _fbAppsessionObserver (/Users/uri/.atom/packages/nuclide/pkg/nuclide-logging/lib/main.js:60:16)
    at setupLoggingService (/Users/uri/.atom/packages/nuclide/pkg/nuclide-logging/lib/main.js:132:71)
    at initializeLogging (/Users/uri/.atom/packages/nuclide/pkg/nuclide-logging/lib/main.js:125:3)
    at /Users/uri/.atom/packages/nuclide/modules/nuclide-commons/once.js:28:21
    at Object.<anonymous> (/Users/uri/.atom/packages/nuclide/lib/main.js:250:41)
    at Object.<anonymous> (/Users/uri/.atom/packages/nuclide/lib/main.js:585:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/uri/.atom/packages/nuclide/lib/main-entry.js:35:18)
    at Object.<anonymous> (/Users/uri/.atom/packages/nuclide/lib/main-entry.js:37:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
```

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom: 1.31.2 x64
* Nuclide: 0.360.0
* Client OS: macOS 10.14 (18A391)
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

```
Community Packages (32) /Users/uri/.atom/packages
├── Hydrogen@2.6.0
├── atom-beautify@0.33.4
├── autocomplete-ruby@0.2.8
├── busy-signal@1.4.3 (disabled)
├── change-case@0.6.5
├── go-debug@1.6.2
├── go-plus@5.8.6
├── intentions@1.1.5
├── ipython-exec@1.2.0
├── language-bazel@0.3.4
├── language-diff@0.7.0
├── language-digdag@0.0.2
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-terraform@0.8.1
├── linter@2.2.0 (disabled)
├── linter-flake8@2.3.0
├── linter-pydocstyle@0.4.7
├── linter-pylint@2.1.1
├── linter-rubocop@2.2.3
├── linter-ruby@1.2.6
├── linter-rust@0.9.0
├── linter-ui-default@1.7.1
├── markdown-pdf@2.2.0
├── multi-cursor@2.1.5
├── narrow@0.65.1
├── nix@2.1.0
├── nuclide@0.360.0
├── python-yapf@0.14.0
├── rustfmt@0.1.3
├── sort-lines@0.18.0
└── split-diff@1.5.3
```

**Comment by CoolCyberBrain** [comment]
Same here

**Comment by hb2708** [comment]
#1640
#1639
Both are same i am also facing it

```
macOS Mojave 10.14 (18A391)
Atom 1.31.2 x64
nuclide 0.360.0
```
```
Cannot find module '../../fb-appsession-observer'
Hide Stack Trace
Error: Cannot find module '../../fb-appsession-observer'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at _fbAppsessionObserver (/Users/harshalbhavsar/.atom/packages/nuclide/pkg/nuclide-logging/lib/main.js:60:16)
    at setupLoggingService (/Users/harshalbhavsar/.atom/packages/nuclide/pkg/nuclide-logging/lib/main.js:132:71)
    at initializeLogging (/Users/harshalbhavsar/.atom/packages/nuclide/pkg/nuclide-logging/lib/main.js:125:3)
    at /Users/harshalbhavsar/.atom/packages/nuclide/modules/nuclide-commons/once.js:28:21
    at Object.<anonymous> (/Users/harshalbhavsar/.atom/packages/nuclide/lib/main.js:250:41)
    at Object.<anonymous> (/Users/harshalbhavsar/.atom/packages/nuclide/lib/main.js:585:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/harshalbhavsar/.atom/packages/nuclide/lib/main-entry.js:35:18)
    at Object.<anonymous> (/Users/harshalbhavsar/.atom/packages/nuclide/lib/main-entry.js:37:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:782:33)
    at measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:143:22)
```

**Comment by dsetzer** [comment]
I'm getting this error too with a fresh atom install on linux.

**Comment by zedtux** [comment]
`apm uninstall nuclide && apm install nuclide@0.357.0`

**Comment by harrypunk** [comment]
Getting this error on Ubuntu 18 with Atom 1.28.2 and nuclide 0.36.0. Solved by uninstalling nuclide and reintsallling 0.357.0.

**Comment by MagicMirouff** [comment]
Same here

**Comment by lukaszgoworko** [comment]
temporary using the previous version: 
apm uninstall nuclide && apm install nuclide@0.357.0

**Comment by mattijsf** [comment]
Same here on macOS, had to downgrade to 0.357.0. Even happens on a clean install.

**Comment by caaespin** [comment]
Getting the same error.

**Comment by ThomasGHenry** [comment]
same. 

atom 1.31.2
macos 10.13.6
nuclide 0.360.0

**Comment by roopesh90** [comment]
Atom: 1.31.2
OS: Ubuntu 16.04.5 LTS
Nuclide: 0.360.0

have downgraded till this is fixed:

> `apm uninstall nuclide && apm install nuclide@0.357.0`

**Comment by IanVS** [comment]
This seems to be the commit which broke nuclide for non-facebook users:

https://github.com/facebook/nuclide/commit/22eea032f97ba3f724a8f98b62431c6d398286df

@velocityboy, do you think you could take a look at this issue to see if my guess is correct?

**Comment by velocityboy** [comment]
Yes, and this should already be fixed for This week’s release.

**Comment by IanVS** [comment]
Oh I see, the commit I linked to is the fix.  Thanks a ton!

**Comment by uri-canva** [comment]
Same for me.
