### ISSUE TITLE
Nuclide 0.360.0 update doesn't work 

### ISSUE THREAD

**Issue by harriebird** [facebook/nuclide#1644]
### Issue and Steps to Reproduce
1.  Update nuclide to version 0.360.0
2. Wait for the update to finish
3. Restart atom
4. Atom will notify that there is a failure in loading a nuclide package

### Expected Behavior
After restarting atom from the successful update, nuclide should work fine.

### Actual Behavior
It crashes due to a failure in loading a nuclide package. Screenshow is shown below:
```Cannot find module '../../fb-appsession-observer'```

![screen shot 2018-10-24 at 10 57 50 am](https://user-images.githubusercontent.com/20557045/47404079-7e52b200-d77e-11e8-961a-2ed42a8a8301.png)

And here is the stack trace:
```
At Cannot find module '../../fb-appsession-observer'

Error: Cannot find module '../../fb-appsession-observer'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154364)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145671)
    at _fbAppsessionObserver (/packages/nuclide/pkg/nuclide-logging/lib/main.js:60:16)
    at setupLoggingService (/packages/nuclide/pkg/nuclide-logging/lib/main.js:132:71)
    at initializeLogging (/packages/nuclide/pkg/nuclide-logging/lib/main.js:125:3)
    at /packages/nuclide/modules/nuclide-commons/once.js:28:21
    at /packages/nuclide/lib/main.js:250:41)
    at /packages/nuclide/lib/main.js:585:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145671)
    at /packages/nuclide/lib/main-entry.js:35:18)
    at /packages/nuclide/lib/main-entry.js:37:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146381)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149928)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:620607)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2964186)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:2950897)
```

### Versions
* Atom: 1.32.0
* Nuclide: 0.360.0
* Client OS: Mac OS X 10.13
* Server OS (optional):

### Additional Details
```
atom-ide-ui 0.13.0 
atom-typescript 12.6.3 
ide-typescript 0.7.9 
nuclide 0.360.0 
```

**Comment by awilkins** [comment]
Workaround 

```
apm install nuclide@0.357.0
```

**Comment by harriebird** [comment]
> Workaround
> 
> ```
> apm install nuclide@0.357.0
> ```

Yeah, this is what I've done a while ago. I reverted nuclide to version 0.357.0.

**Comment by jmezzacappa** [comment]
Many people are experiencing this problem.
Duplicates: #1641 #1640 #1639

**Comment by steida** [comment]
Solved in Nuclide 0.362.0
