### ISSUE TITLE
nuclide-language-hack snippets not working in Hack files

### ISSUE THREAD

**Issue by YouCantTriforce** [facebook/nuclide#165]
When I select "Hack" (or it is automatically detected) snippets are not working (e.g. "<<< + TAB" does nothing). However, when I switch to "PHP" mode, all snippets are working.

**Comment by mostafaeweda** [comment]
Oh, thanks for finding this - coming a fix.

**Comment by davidpetro88** [comment]
I had the same problem with hack package.

my error console :
Uncaught (in promise) TypeError: stderr.contains is not a function
  at /home/david/.atom/packages/nuclide-hack/node_modules/nuclide-client/node_modules/nuclide-server/lib/services/NuclideHackService.js:34:16
  at GeneratorFunctionPrototype.next (native)
  at step (/home/david/.atom/packages/nuclide-hack/node_modules/nuclide-client/node_modules/nuclide-server/lib/services/NuclideHackService.js:215:273) 

thk!

**Comment by mbacon40** [comment]
I am having this same issue as well. Was a fix for this ever found?
