### ISSUE TITLE
Uncaught Error: Cannot find module 'ctype' after fresh installation via nuclide-installer

### ISSUE THREAD

**Issue by kubapet** [facebook/nuclide#169]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.6
**System**: "openSUSE 20150811
**Thrown From**: [nuclide-quick-open](https://github.com/facebooknuclideapm/nuclide-quick-open) package, v0.0.30

### Stack Trace

Uncaught Error: Cannot find module 'ctype'

```
At module.js:330

Error: Cannot find module 'ctype'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/kubapet/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/request/node_modules/http-signature/lib/util.js:7:13)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/kubapet/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/request/node_modules/http-signature/lib/index.js:6:12)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/kubapet/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/request/request.js:15:21)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/kubapet/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/request/index.js:174:19)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/kubapet/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-server/lib/utils.js:11:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/kubapet/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-server/lib/NuclideRemoteEventbus.js:26:17)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/kubapet/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-remote-connection/lib/RemoteConnection.js:31:29)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/kubapet/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-remote-connection/lib/main.js:9:24)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/kubapet/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/lib/service-manager.js:22:17)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/kubapet/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/lib/main.js:10:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/usr/share/atom/resources/app.asar/src/babel.js:163:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at initSearch (/home/kubapet/.atom/packages/nuclide-quick-open/lib/main.js:275:19)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.setPaths (/usr/share/atom/resources/app.asar/src/project.js:237:27)
  at /usr/share/atom/resources/app.asar/src/project.js:71:26
  at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
  at process._tickCallback (node.js:357:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.30
nuclide-arcanist, v0.0.30
nuclide-code-format, v0.0.30
nuclide-diagnostics-store, v0.0.30
nuclide-diagnostics-ui, v0.0.30
nuclide-diff-view, v0.0.30
nuclide-file-tree, v0.0.30
nuclide-file-watcher, v0.0.30
nuclide-find-references, v0.0.30
nuclide-flow, v0.0.30
nuclide-hack, v0.0.30
nuclide-hg-repository, v0.0.30
nuclide-installer, v0.0.30
nuclide-language-hack, v0.0.30
nuclide-ocaml, v0.0.30
nuclide-quick-open, v0.0.30
nuclide-remote-projects, v0.0.30
nuclide-type-hint, v0.0.30

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
This predates the [consolidation of Nuclide](https://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/) into a single package. Please install the ['nuclide' Atom package](https://atom.io/packages/nuclide).
