### ISSUE TITLE
nuclide-remote-projects: Uncaught AssertionError: undefined == true

### ISSUE THREAD

**Issue by wmertens** [facebook/nuclide#170]
1. Connect to remote host with  -k flag (doesn't start without it)
2. Crash

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [nuclide-remote-projects](https://github.com/facebooknuclideapm/nuclide-remote-projects) package, v0.0.30

### Stack Trace

Uncaught AssertionError: undefined == true

```
At assert.js:87

AssertionError: undefined == true
  at SshHandshake._updateServerInfo (/Users/wmertens/.atom/packages/nuclide-remote-projects/node_modules/nuclide-remote-connection/lib/SshHandshake.js:169:7)
  at Channel.<anonymous> (/Users/wmertens/.atom/packages/nuclide-remote-projects/node_modules/nuclide-remote-connection/lib/SshHandshake.js:237:22)
  at emitOne (events.js:77:13)
  at Channel.emit (events.js:166:7)
  at SSH2Stream.<anonymous> (/Users/wmertens/.atom/packages/nuclide-remote-projects/node_modules/nuclide-remote-connection/node_modules/ssh2/lib/Channel.js:125:14)
  at SSH2Stream.g (events.js:257:16)
  at emitNone (events.js:67:13)
  at SSH2Stream.emit (events.js:163:7)
  at parsePacket (/Users/wmertens/.atom/packages/nuclide-remote-projects/node_modules/nuclide-remote-connection/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3437:10)
  at SSH2Stream._transform (/Users/wmertens/.atom/packages/nuclide-remote-projects/node_modules/nuclide-remote-connection/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
  at SSH2Stream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SSH2Stream._read (/Users/wmertens/.atom/packages/nuclide-remote-projects/node_modules/nuclide-remote-connection/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at SSH2Stream.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (_stream_readable.js:524:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```

### Commands

```
     -9:04.9.0 window:toggle-dev-tools (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-light-ui)
  2x -2:21.4.0 nuclide-remote-projects:connect (div.settings-view.pane-item)
     -0:42 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "my-package",
      "preview-tabs",
      "atom-terminal-panel",
      "language-coffee-script-angular",
      "minimap-find-and-replace",
      "pepper-autocomplete",
      "linter-tidy",
      "linter-python-pyflakes",
      "web-browser",
      "open-last-project",
      "livereload",
      "Coffeefilter",
      "coffee-refactor",
      "jshint",
      "tree-view"
    ],
    "projectHome": "~/Documents/Projects",
    "themes": [
      "one-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.2
atom-ternjs, v0.7.1
autocomplete-clang, v0.8.7
autocomplete-modules, v1.0.0
autocomplete-plus-python-jedi, v0.3.6
browser-plus, v0.0.30
coffee-navigator, v0.0.16
js-refactor, v0.4.2
language-jade, v0.6.2
language-javascript-jsx, v0.3.7
language-javascript-semantic, v0.2.1
last-cursor-position, v0.9.0
linter, v1.2.4
linter-coffeelint, v1.0.1
linter-eslint, v3.0.2
minimap, v4.12.1
minimap-git-diff, v4.1.7
minimap-selection, v4.3.0
nix, v2.1.0
nuclide-diff-view, v0.0.30
nuclide-file-tree, v0.0.30
nuclide-quick-open, v0.0.30
nuclide-remote-projects, v0.0.30
preview-plus, v1.2.5
project-manager, v1.15.11
refactor, v0.5.1
remote-edit, v1.8.15
remote-sync, v3.1.2
word-jumper, v0.3.0

# Dev
No dev packages
```

**Comment by fbourigault** [comment]
Same here with Windows 7 x64 as Host, Atom 1.0.7 and nuclide-remote-projects v0.0.30

**Comment by aewing** [comment]
I'm having this issue as well, windows 10 x64, Atom 1.0.8 and 1.0.9 -- connecting without -k I get "Failed to connect to Nuclide server on ....: undefined is not a function"

**Comment by aewing** [comment]
I'm not able to test this theory at the moment, but I suspect that the issue may be related to the handshake timeout -- similar to https://github.com/mscdex/ssh2/issues/142

**Comment by brainstorm** [comment]
Same issue here while trying nuclide out with @guillermo-carrasco. Without -k it connects successfully to the remote machine, showing the login messages and prompt, but then fails to connect to port 9090 on the remote `nuclide-server`.

**Comment by mostafaeweda** [comment]
Refer to #321 for general Nuclide windows support,
For the `-k`, /cc @peterhal @zertosh
