### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by joshruesch** [facebook/nuclide#175]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.14108370
**System**: Mac OS X 10.10.5
**Thrown From**: [nuclide-test-runner](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-test-runner/lib/TestSuiteModel.js:35

TypeError: Cannot read property 'id' of undefined
  at TestSuiteModel.addTestRun (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-test-runner/lib/TestSuiteModel.js:35:42)
  at EventEmitter.<anonymous> (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-test-runner/lib/TestRunnerController.js:223:33)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)
  at NuclideRemoteEventbus._handleSocketMessage (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/lib/NuclideRemoteEventbus.js:81:48)
  at NuclideSocket.<anonymous> (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/lib/NuclideRemoteEventbus.js:56:20)
  at emitOne (events.js:77:13)
  at NuclideSocket.emit (events.js:166:7)
  at WebSocket.onSocketMessage (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/lib/NuclideSocket.js:155:16)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:169:7)
  at Receiver.ontext (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/node_modules/ws/lib/WebSocket.js:798:10)
  at /Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/node_modules/ws/lib/Receiver.js:473:18
  at /Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/node_modules/ws/lib/Receiver.js:357:7
  at /Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-server/node_modules/ws/lib/PerMessageDeflate.js:217:5
  at afterWrite (_stream_writable.js:355:3)
  at onwrite (_stream_writable.js:346:7)
  at WritableState.onwrite (_stream_writable.js:88:5)
  at afterTransform (_stream_transform.js:79:5)
  at TransformState.afterTransform (_stream_transform.js:54:12)
  at Zlib.callback (zlib.js:590:5)

```

### Commands

```
     -0:47 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:47 snippets:expand (atom-text-editor.editor.is-focused)
     -0:47 editor:indent (atom-text-editor.editor.is-focused)
     -0:43.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:42.7.0 linter:lint (atom-text-editor.editor.is-focused)
  2x -0:38.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:37.5.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:17.8.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:17.4.0 core:save (atom-text-editor.editor.is-focused)
  4x -0:16.3.0 linter:lint (atom-text-editor.editor)
     -0:13.6.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:13.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:11.9.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:11.6.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:11.3.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:10.2.0 linter:lint (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view",
      "deprecation-cop",
      "fuzzy-finder",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
Thanks for the report. I will take a look at this.

**Comment by ssorallen** [comment]
Closing this task because this is specific to Nuclide.app.

**Comment by joshruesch** [comment]
Where should I report this bug then? I just clicked the button it told me to.

**Comment by vjeux** [comment]
I'm having the same issue 

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.3
**Thrown From**: [nuclide-test-runner](https://github.com/facebook/nuclide) package, v0.0.0-15449823


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Users/vjeux/.nuclide/15449823/Tools/Nuclide/pkg/nuclide/test-runner/lib/TestSuiteModel.js:34

TypeError: Cannot read property 'id' of undefined
  at TestSuiteModel.addTestRun (/Users/vjeux/.nuclide/15449823/Tools/Nuclide/pkg/nuclide/test-runner/lib/TestSuiteModel.js:34:42)
  at EventEmitter.<anonymous> (/Users/vjeux/.nuclide/15449823/Tools/Nuclide/pkg/nuclide/test-runner/lib/TestRunnerController.js:256:34)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)
  at NuclideRemoteEventbus._handleSocketMessage (/Users/vjeux/.nuclide/15449823/Tools/Nuclide/pkg/nuclide/server/lib/NuclideRemoteEventbus.js:98:48)
  at NuclideSocket.<anonymous> (/Users/vjeux/.nuclide/15449823/Tools/Nuclide/pkg/nuclide/server/lib/NuclideRemoteEventbus.js:68:20)
  at emitOne (events.js:77:13)
  at NuclideSocket.emit (events.js:169:7)
  at WebSocket.onSocketMessage (/Users/vjeux/.nuclide/15449823/Tools/Nuclide/pkg/nuclide/server/lib/NuclideSocket.js:155:16)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:172:7)
  at Receiver.ontext (/Users/vjeux/.nuclide/15449823/Tools/Nuclide/pkg/nuclide/server/node_modules/ws/lib/WebSocket.js:798:10)
  at /Users/vjeux/.nuclide/15449823/Tools/Nuclide/pkg/nuclide/server/node_modules/ws/lib/Receiver.js:473:18
  at /Users/vjeux/.nuclide/15449823/Tools/Nuclide/pkg/nuclide/server/node_modules/ws/lib/Receiver.js:357:7
  at /Users/vjeux/.nuclide/15449823/Tools/Nuclide/pkg/nuclide/server/node_modules/ws/lib/PerMessageDeflate.js:217:5
  at afterWrite (_stream_writable.js:345:3)
  at onwrite (_stream_writable.js:336:7)
  at WritableState.onwrite (_stream_writable.js:88:5)
  at afterTransform (_stream_transform.js:79:5)
  at TransformState.afterTransform (_stream_transform.js:54:12)
  at Zlib.callback (zlib.js:614:5)

```

### Commands

```
     -0:46.9.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-oceanic-next.theme-one-dark-ui)
     -0:42.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:29.6.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-oceanic-next.theme-one-dark-ui)
     -0:27.8.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  3x -0:27.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "fuzzy-finder",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "nuclide-toolbar",
      "language-javascript-jsx",
      "tree-view"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  }
}
```

### Installed Packages

```coffee
# User
fb-analytics-client, v0.0.0-15449823
fb-analytics-reporter-settings, v0.0.0-15449823
fb-biggrep-provider, v0.0.0-15449823
fb-codegraph-providers, v0.0.0-15449823
fb-diffs-and-tasks, v0.0.0-15449823
fb-error-reporting, v0.0.0-15449823
fb-file-a-bug, v0.0.0-15449823
fb-graphql, v0.0.0-15449823
fb-handle-url, v0.0.0-15449823
fb-hg-smartlog, v0.0.0-15449823
fb-logging-helper, v0.0.0-15449823
fb-nuclide-installer, v0.1.8
fb-package-manager, v0.0.0-15449823
fb-phabricator-comments-client, v0.0.0-15449823
fb-rating, v0.0.0-15449823
fb-slog-viewer, v0.0.0-15449823
fb-snippets, v0.0.0-15449823
fb-test-runner-t-client, v0.0.0-15449823
haskell-grammar, v0.4.0
highlight-selected, v0.10.1
hyperclick, v0.0.0-15449823
language-babel, v0.15.4
language-ini, v1.12.0
language-ocaml, v1.1.2
language-thrift, v1.0.1
nuclide-arcanist, v0.0.0-15449823
nuclide-blame, v0.0.0-15449823
nuclide-blame-provider-hg, v0.0.0-15449823
nuclide-blame-ui, v0.0.0-15449823
nuclide-buck-files, v0.0.0-15449823
nuclide-clang-atom, v0.0.0-15449823
nuclide-code-format, v0.0.0-15449823
nuclide-debugger-atom, v0.0.0-15449823
nuclide-debugger-hhvm, v0.0.0-15449823
nuclide-debugger-lldb, v0.0.0-15449823
nuclide-diagnostics-store, v0.0.0-15449823
nuclide-diagnostics-ui, v0.0.0-15449823
nuclide-diff-view, v0.0.0-15449823
nuclide-file-creation, v0.0.0-15449823
nuclide-file-creation-ios, v0.0.0-15449823
nuclide-file-tree-deux, v0.0.0-15449823
nuclide-file-watcher, v0.0.0-15449823
nuclide-find-references, v0.0.0-15449823
nuclide-flow, v0.0.0-15449823
nuclide-fuzzy-filename-provider, v0.0.0-15449823
nuclide-hack, v0.0.0-15449823
nuclide-hack-symbol-provider, v0.0.0-15449823
nuclide-health, v0.0.0-15449823
nuclide-hg-repository, v0.0.0-15449823
nuclide-home, v0.0.0-15449823
nuclide-language-hack, v0.0.0-15449823
nuclide-objc, v0.0.0-15449823
nuclide-ocaml, v0.0.0-15449823
nuclide-open-filenames-provider, v0.0.0-15449823
nuclide-quick-open, v0.0.0-15449823
nuclide-recent-files-service, v0.0.0-15449823
nuclide-remote-projects, v0.0.0-15449823
nuclide-test-runner, v0.0.0-15449823
nuclide-type-hint, v0.0.0-15449823
oceanic-next, v0.1.2
react, v0.12.10

# Dev
No dev packages
```

**Comment by vjeux** [comment]
This happens when a PHP file I'm testing has a syntax error

**Comment by vjeux** [comment]
Once it happens, I need to restart Nuclide to re-run the tests :(

**Comment by jaens** [comment]
This needs to be reopened, it happens on Atom.app as well!

**Comment by jaens** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.18
**System**: Mac OS X 10.11
**Thrown From**: [nuclide-test-runner](https://github.com/facebook/nuclide) package, v1337.0.0-16158877


### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Users/jaen/.nuclide/16158877/Tools/Nuclide/pkg/nuclide/test-runner/lib/TestSuiteModel.js:34

TypeError: Cannot read property 'id' of undefined
  at TestSuiteModel.addTestRun (/Users/jaen/.nuclide/16158877/Tools/Nuclide/pkg/nuclide/test-runner/lib/TestSuiteModel.js:34:42)
  at EventEmitter.<anonymous> (/Users/jaen/.nuclide/16158877/Tools/Nuclide/pkg/nuclide/test-runner/lib/TestRunnerController.js:261:34)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:169:7)
  at NuclideRemoteEventbus._handleSocketMessage (/Users/jaen/.nuclide/16158877/Tools/Nuclide/pkg/nuclide/server/lib/NuclideRemoteEventbus.js:98:48)
  at NuclideSocket.<anonymous> (/Users/jaen/.nuclide/16158877/Tools/Nuclide/pkg/nuclide/server/lib/NuclideRemoteEventbus.js:68:20)
  at emitOne (events.js:77:13)
  at NuclideSocket.emit (events.js:169:7)
  at WebSocket.onSocketMessage (/Users/jaen/.nuclide/16158877/Tools/Nuclide/pkg/nuclide/server/lib/NuclideSocket.js:154:16)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:172:7)
  at Receiver.ontext (/Users/jaen/.nuclide/16158877/Tools/Nuclide/pkg/nuclide/server/node_modules/ws/lib/WebSocket.js:798:10)
  at /Users/jaen/.nuclide/16158877/Tools/Nuclide/pkg/nuclide/server/node_modules/ws/lib/Receiver.js:473:18
  at /Users/jaen/.nuclide/16158877/Tools/Nuclide/pkg/nuclide/server/node_modules/ws/lib/Receiver.js:357:7
  at /Users/jaen/.nuclide/16158877/Tools/Nuclide/pkg/nuclide/server/node_modules/ws/lib/PerMessageDeflate.js:217:5
  at afterWrite (_stream_writable.js:345:3)
  at onwrite (_stream_writable.js:336:7)
  at WritableState.onwrite (_stream_writable.js:88:5)
  at afterTransform (_stream_transform.js:79:5)
  at TransformState.afterTransform (_stream_transform.js:54:12)
  at Zlib.callback (zlib.js:614:5)

```

### Commands

```
     -3:38.6.0 core:copy (atom-text-editor.editor.enable-nuclide-find-references.is-focused.hyperclick)
     -3:37.3.0 core:paste (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -3:28 core:copy (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -3:25.9.0 core:paste (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
  7x -3:19.7.0 core:backspace (atom-text-editor.editor.enable-nuclide-find-references.is-focused.autocomplete-active)
     -2:59.3.0 nuclide-code-format:format-code (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -2:57 core:save (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -2:36.2.0 core:cut (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -2:23.4.0 core:paste (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -2:21 nuclide-code-format:format-code (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -2:18.2.0 editor:newline (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -2:14.6.0 find-and-replace:select-next (atom-text-editor.editor.enable-nuclide-find-references.is-focused.hyperclick)
     -2:06.9.0 core:save (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -1:21.9.0 core:paste (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -1:06.4.0 nuclide-code-format:format-code (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -1:04.5.0 core:save (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "deprecation-cop",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "fuzzy-finder",
      "tree-view",
      "file-icons"
    ],
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
...
figlet, v0.5.2
haskell-grammar, v0.4.0
highlight-selected, v0.10.1
hyperclick, v1337.0.0-16158877
language-babel, v0.15.7
language-ini, v1.13.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
minimap, v4.15.0
minimap-find-and-replace, v4.3.1
nuclide-arcanist, v1337.0.0-16158877
nuclide-blame, v1337.0.0-16158877
nuclide-blame-provider-hg, v1337.0.0-16158877
nuclide-blame-ui, v1337.0.0-16158877
nuclide-buck-files, v1337.0.0-16158877
nuclide-clang-atom, v1337.0.0-16158877
nuclide-code-format, v1337.0.0-16158877
nuclide-debugger-atom, v1337.0.0-16158877
nuclide-debugger-hhvm, v1337.0.0-16158877
nuclide-debugger-lldb, v1337.0.0-16158877
nuclide-diagnostics-store, v1337.0.0-16158877
nuclide-diagnostics-ui, v1337.0.0-16158877
nuclide-diff-view, v1337.0.0-16158877
nuclide-file-tree, v1337.0.0-16158877
nuclide-file-watcher, v1337.0.0-16158877
nuclide-find-references, v1337.0.0-16158877
nuclide-flow, v1337.0.0-16158877
nuclide-fuzzy-filename-provider, v1337.0.0-16158877
nuclide-hack, v1337.0.0-16158877
nuclide-hack-symbol-provider, v1337.0.0-16158877
nuclide-health, v1337.0.0-16158877
nuclide-hg-repository, v1337.0.0-16158877
nuclide-home, v1337.0.0-16158877
nuclide-language-hack, v1337.0.0-16158877
nuclide-objc, v1337.0.0-16158877
nuclide-ocaml, v1337.0.0-16158877
nuclide-open-filenames-provider, v1337.0.0-16158877
nuclide-quick-open, v1337.0.0-16158877
nuclide-recent-files-service, v1337.0.0-16158877
nuclide-remote-projects, v1337.0.0-16158877
nuclide-test-runner, v1337.0.0-16158877
nuclide-toolbar, v1337.0.0-16158877
nuclide-type-hint, v1337.0.0-16158877
tool-bar, v0.1.9

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
@jaens The fix is in master but not yet in a public release. If you build from source this issue will be fixed, but I realize I closed this early. I'll keep it open until the next public release.

**Comment by IanVS** [comment]
This can probably be closed now, ya?
