### ISSUE TITLE
Cannot install install nuclide-server, seems to fail installing npm fb-phabricator-comments-base

### ISSUE THREAD

**Issue by chrislovsund** [facebook/nuclide#176]
Environment:
Fedora 22 and RHEL 7
nodejs 0.12.7

When running:
```
./scripts/dev/setup --no-atom --verbose
```

I get this:

```
Installing dependencies for Node package nuclide-server...
Error running ['npm', 'install'] in /users/chrlov/work/nuclide/pkg/nuclide/server
Process Process-27:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/dev/../lib/topological_installer.py", line 148, in install_dependencies
    npm.install(src_path, local_packages=package_config['localDependencies'], include_dev_dependencies=True)
  File "./scripts/dev/../lib/npm.py", line 63, in install
    self._npm_install(package_root, include_dev_dependencies)
  File "./scripts/dev/../lib/npm.py", line 80, in _npm_install
    self._execute(npm_command, cwd=package_root)
  File "./scripts/dev/../lib/npm.py", line 119, in _execute
    output = fs.cross_platform_check_output(cmd_args, cwd=cwd, stderr=subprocess.STDOUT)
  File "./scripts/dev/../lib/fs.py", line 89, in cross_platform_check_output
    raise subprocess.CalledProcessError(returncode, cmd_args, output=stdout)
CalledProcessError: Command '['npm', 'install']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./scripts/dev/setup", line 48, in <module>
    package_manager.install_dependencies(npm, include_packages_that_depend_on_atom=include_apm)
  File "./scripts/dev/../lib/package_manager.py", line 31, in install_dependencies
    installer.install()
  File "./scripts/dev/../lib/topological_installer.py", line 52, in install
    self._do_multiprocess_install()
  File "./scripts/dev/../lib/topological_installer.py", line 99, in _do_multiprocess_install
    (config['name'], exitcode))
Exception: Installing package nuclide-server failed with exit code 1
```

I then try to manually install server:
```
cd pkg/nuclide/server/
npm install
```

```
npm WARN package.json nuclide-server@0.0.0 No license field.
npm ERR! Linux 3.10.0-229.1.2.el7.x86_64
npm ERR! argv "/users/chrlov/bin/node-v0.12.7-linux-x64/bin/node" "/users/chrlov/bin/node-v0.12.7-linux-x64/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/fb-phabricator-comments-base
npm ERR! 404
npm ERR! 404 'fb-phabricator-comments-base' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'nuclide-server'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by jgebhardt** [comment]
Thanks for reporting! This should be fixed in 6461dad0cd9b9b186f798cbb2e5f132a5861df57.
