### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by yotamN** [facebook/nuclide#181]
[Enter steps to reproduce below:]

1. Install Nuclide
2. Run atom

**Atom Version**: 1.0.11
**System**: Ubuntu 15.04
**Thrown From**: [nuclide-diagnostics-store](https://github.com/facebooknuclideapm/nuclide-diagnostics-store) package, v0.0.30

### Stack Trace

Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

```
At /home/yotam/.atom/packages/nuclide-diagnostics-store/lib/TextEventDispatcher.js:103

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
  at TextCallbackContainer.addCallback (/home/yotam/.atom/packages/nuclide-diagnostics-store/lib/TextEventDispatcher.js:103:34)
  at TextEventDispatcher._onEvents (/home/yotam/.atom/packages/nuclide-diagnostics-store/lib/TextEventDispatcher.js:181:31)
  at TextEventDispatcher.onFileSave (/home/yotam/.atom/packages/nuclide-diagnostics-store/lib/TextEventDispatcher.js:203:19)
  at LinterAdapter._subscribeToEvent (/home/yotam/.atom/packages/nuclide-diagnostics-store/lib/LinterAdapter.js:148:37)
  at new LinterAdapter (/home/yotam/.atom/packages/nuclide-diagnostics-store/lib/LinterAdapter.js:118:10)
  at Object.consumeLinterProvider (/home/yotam/.atom/packages/nuclide-diagnostics-store/lib/main.js:105:19)
  at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
  at process._tickDomainCallback (node.js:384:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "autoHideMenuBar": true,
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "advanced-new-file",
      "atom-yeoman",
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-ternjs, v0.7.2
atom-tsd, v0.9.0
atom-typescript, v6.0.2
autoclose-html, v0.18.0
color-picker, v2.0.11
hyperclick, v0.0.30
json-schema, v0.1.13
linter, v1.5.0
linter-jshint, v1.1.5
minimap, v4.13.2
minimap-linter, v1.0.0
minimap-pigments, v0.1.6
node-debugger, v1.1.8
nucleus-dark-ui, v0.2.7
nuclide-arcanist, v0.0.30
nuclide-code-format, v0.0.30
nuclide-diagnostics-store, v0.0.30
nuclide-diagnostics-ui, v0.0.30
nuclide-diff-view, v0.0.30
nuclide-file-tree, v0.0.30
nuclide-file-watcher, v0.0.30
nuclide-find-references, v0.0.30
nuclide-installer, v0.0.30
pigments, v0.13.2

# Dev
No dev packages
```

**Comment by nmote** [comment]
Should be fixed by a922cd3142254d2bc52acf17206f2cc819c71ff3
