### ISSUE TITLE
Failed to connect to Nuclide server on xy: undefined is not a function

### ISSUE THREAD

**Issue by nrze** [facebook/nuclide#182]
Hi, I just installed nuclide-server via npm on my ubuntu server.

When I try to access the remove server from Atom, I get the error message **"Failed to connect to Nuclide server on xy: undefined is not a function"**

There is a ssh session opening on my server and nuclide-server is started. The client seems even to be connected, at least I get a disconnection error if I kill the process.

nuclide.nohup.out
==============
[2015-09-06T19:07:51.466Z] [INFO] nuclide - Registered service /usr/local/lib/node_modules/nuclide-server/lib/services/NuclideFsService.js without ServiceFramework.
[2015-09-06T19:07:51.472Z] [INFO] nuclide - Registered service /usr/local/lib/node_modules/nuclide-server/lib/services/NuclideSearchService.js without ServiceFramework.
[2015-09-06T19:07:51.473Z] [INFO] nuclide - Registered service /usr/local/lib/node_modules/nuclide-server/lib/services/NuclideWatcherService.js without ServiceFramework.
[2015-09-06T19:07:51.474Z] [INFO] nuclide - Registered service /usr/local/lib/node_modules/nuclide-server/lib/services/NuclideHackService.js without ServiceFramework.
[2015-09-06T19:07:51.475Z] [INFO] nuclide - Registered service /usr/local/lib/node_modules/nuclide-server/lib/services/SourceControlService.js without ServiceFramework.
[2015-09-06T19:07:51.476Z] [INFO] nuclide - Registered service FlowService with ServiceFramework.
[2015-09-06T19:07:51.478Z] [INFO] nuclide - Registered service MerlinService with ServiceFramework.
[2015-09-06T19:07:51.479Z] [INFO] nuclide - Registered service HgService with ServiceFramework.
[2015-09-06T19:07:51.480Z] [INFO] nuclide - Registered service ClangService with ServiceFramework.
[2015-09-06T19:07:51.483Z] [INFO] nuclide - Registered service ArcanistBaseService with ServiceFramework.
[2015-09-06T19:07:51.484Z] [INFO] nuclide - Registered service BuckUtils with ServiceFramework.
[2015-09-06T19:07:51.485Z] [INFO] nuclide - Registered service BuckProject with ServiceFramework.
[2015-09-06T19:07:51.486Z] [INFO] nuclide - Registered service HhvmDebuggerProxyService with ServiceFramework.
[2015-09-06T19:07:51.487Z] [INFO] nuclide - Registered service FindInProjectService with ServiceFramework.
[2015-09-06T19:07:51.547Z] [INFO] nuclide - NuclideServer started on port 9090.
[2015-09-06T19:07:51.548Z] [INFO] nuclide - NuclideServer event loop blocked for 70ms
[2015-09-06T19:07:52.194Z] [INFO] nuclide - WebSocket connecting
[2015-09-06T19:07:52.266Z] [INFO] nuclide - Client #006644d6-f6bc-440f-b219-292beb7a8b77 connecting with a new socket!

System Details (Server)
===================

node -v
v0.12.7

cat /etc/debian_version
jessie/sid

uname -a
Linux 3.13.0-042stab103.6 #1 SMP Wed Jan 21 13:07:39 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

python --version
Python 2.7.6

watchman -v
3.7.0

System Details (Client)
===================
win7 x64
Atom 1.011
nuclide plugins are all up to date

**Comment by codehotter** [comment]
I tested a bunch of versions.
Get the same error as nrze since Atom 1.0.8.
It works fine on [1.0.7](https://github.com/atom/atom/releases/tag/v1.0.7)

**Comment by markmiro** [comment]
I'm seeing this the same exact error message with Atom 1.0.11 on OSX Yosemite

**Comment by ssorallen** [comment]
Can you open Developer Tools in Atom and paste the stack trace that shows this exception? Thanks for reporting this.

**Comment by markmiro** [comment]
```
"Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/Users/mmiro/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/invariant.js:35:15)
  at Object.findDOMNode (/Users/mmiro/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/findDOMNode.js:60:7)
  at [object Object].close (/Users/mmiro/.atom/packages/nuclide-remote-projects/node_modules/nuclide-ssh-dialog/lib/ConnectionDialog.js:473:25)
  at Object.onConnect (/Users/mmiro/.atom/packages/nuclide-remote-projects/node_modules/nuclide-ssh-dialog/lib/ConnectionDialog.js:370:16)
  at /Users/mmiro/.atom/packages/nuclide-remote-projects/node_modules/nuclide-remote-connection/lib/SshHandshake.js:280:26
  at GeneratorFunctionPrototype.throw (native)
  at step (/Users/mmiro/.atom/packages/nuclide-remote-projects/node_modules/nuclide-remote-connection/lib/SshHandshake.js:12:273)
  at process._tickCallback (node.js:367:9)
"
```

After a minute or so a warning message comes up: "Watcher failed to start - watcher features disabled!
DETAILS: socket hang up" with the stack trace below

```
"Error: socket hang up
  at createHangUpError (_http_client.js:198:15)
  at TLSSocket.socketOnEnd (_http_client.js:283:23)
  at emitNone (events.js:72:20)
  at TLSSocket.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)
"
```

**Comment by nrze** [comment]
I can confirm, that it works with v 1.0.7.

With v1.011 I get following debug output (stacktrace):
[..]
(anonymous function) index.js:13
emitTwo                       events.js:87
emit                             events.js:169
emitPendingUnhandledRejections node.js:422
_tickCallbacl               node.js:368
[..]

**Comment by SidBala** [comment]
Hitting this with v1.0.11

**Comment by pwillcode** [comment]
I started getting this error when I updated from Atom v1.0.7 to v1.0.11 on Ubuntu 14.04

When I downgraded to Atom v1.0.7 the error went away. (I've been building Atom from source)

**Comment by markmiro** [comment]
Atom v1.0.15 with all nuclide the latest packages installed on client and server fixes this problem.

```
➜  ~  apm upgrade
Package Updates Available (18)
├── hyperclick 0.0.30 -> 0.0.32
├── nuclide-arcanist 0.0.30 -> 0.0.32
├── nuclide-code-format 0.0.30 -> 0.0.32
├── nuclide-diagnostics-store 0.0.30 -> 0.0.32
├── nuclide-diagnostics-ui 0.0.30 -> 0.0.32
├── nuclide-diff-view 0.0.30 -> 0.0.32
├── nuclide-file-tree 0.0.30 -> 0.0.32
├── nuclide-file-watcher 0.0.30 -> 0.0.32
├── nuclide-find-references 0.0.30 -> 0.0.32
├── nuclide-flow 0.0.30 -> 0.0.32
├── nuclide-hack 0.0.30 -> 0.0.32
├── nuclide-hg-repository 0.0.30 -> 0.0.32
├── nuclide-installer 0.0.30 -> 0.0.32
├── nuclide-language-hack 0.0.30 -> 0.0.32
├── nuclide-ocaml 0.0.30 -> 0.0.32
├── nuclide-quick-open 0.0.30 -> 0.0.32
├── nuclide-remote-projects 0.0.30 -> 0.0.32
└── nuclide-type-hint 0.0.30 -> 0.0.32
```

And on the server running this to get the latest
```
npm install -g nuclide-server
```

**Comment by mostafaeweda** [comment]
All those issues should now be gone with our latest UP release: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
