### ISSUE TITLE
Uncaught TypeError: Cannot read property 'row' of undefined while splitting panes

### ISSUE THREAD

**Issue by alvaromb** [facebook/nuclide#183]
[Enter steps to reproduce below:]

1. Open a JavaScript file.
2. Select ``Split Left`` right-clicking in the file tab.

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [nuclide-diagnostics-ui](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'row' of undefined

```
At /Users/alvaro/apsl/tools/atom/nuclide/pkg/nuclide/diagnostics/ui/lib/gutter.js:81

TypeError: Cannot read property 'row' of undefined
  at applyUpdateToEditor (/Users/alvaro/apsl/tools/atom/nuclide/pkg/nuclide/diagnostics/ui/lib/gutter.js:94:44)
  at DiagnosticStore.onFileMessagesDidUpdate (/Users/alvaro/apsl/tools/atom/nuclide/pkg/nuclide/diagnostics/base/lib/DiagnosticStore.js:188:9)
  at /Users/alvaro/apsl/tools/atom/nuclide/pkg/nuclide/diagnostics/ui/lib/main.js:82:42
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:281:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:342:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:334:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:96:16
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didAddPane (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:288:27)
  at Pane.module.exports.Pane.setContainer (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:100:26)
  at PaneAxis.module.exports.PaneAxis.addChild (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:142:13)
  at PaneAxis.module.exports.PaneAxis.insertChildBefore (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-axis.js:208:19)
  at Pane.module.exports.Pane.split (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:717:23)
  at Pane.module.exports.Pane.splitLeft (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:682:19)
  at TabBarView.module.exports.TabBarView.splitTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:427:31)
  at Object.addElementCommands.tabs:split-left (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:130:26)
  at space-pen-ul.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:86:36)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  3x -0:39.3.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:34.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ],
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
chester-atom-syntax, v0.1.1
hyperclick, v0.0.0
linter, v1.5.0
linter-eslint, v3.0.2
linter-jsxhint, v0.1.2
nuclide-arcanist, v0.0.0
nuclide-blame, v0.0.0
nuclide-blame-provider-hg, v0.0.0
nuclide-blame-ui, v0.0.0
nuclide-code-format, v0.0.0
nuclide-diagnostics-store, v0.0.0
nuclide-diagnostics-ui, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-file-tree, v0.0.0
nuclide-file-watcher, v0.0.0
nuclide-find-references, v0.0.0
nuclide-flow, v0.0.0
nuclide-format-js, v0.0.0
nuclide-hack, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-installer, v0.0.0
nuclide-language-hack, v0.0.0
nuclide-ocaml, v0.0.0
nuclide-quick-open, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-type-hint, v0.0.0
react, v0.12.6

# Dev
No dev packages
```

Also I try to update the package as suggested in the picture below, but Atom says that everything is up to date.

<img width="406" alt="screen shot 2015-09-07 at 16 48 55" src="https://cloud.githubusercontent.com/assets/289640/9718945/5e24198e-5580-11e5-960d-5929d055519c.png">

**Comment by bdubaut** [comment]
I get the same error, different stack trace though and with Ruby files open.

**Comment by nmote** [comment]
I will look into this.

**Comment by mostafaeweda** [comment]
this is working fine now, must have been fixed but not followed up here.
