### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by iostalk** [facebook/nuclide#185]
```
TypeError: undefined is not a function
  at ClickToSymbol.findClickableRangesAndCallback [as _findClickableRangesAndCallback] (/Users/xhowhy/.atom/packages/nuclide-click-to-symbol/lib/main.js:27:10)
  at ClickToSymbol.findClickableRangesAndCallback (/Users/xhowhy/.atom/packages/nuclide-click-to-symbol/lib/ClickToSymbol.js:54:51)
  at ClickToSymbol.onMouseMove (/Users/xhowhy/.atom/packages/nuclide-click-to-symbol/lib/ClickToSymbol.js:90:12)
```

**Comment by iostalk** [comment]
My atom is newest version, and just install nulide with apm successfully in the termial. I caught the error in the right red notification window.
How to solve this error?

**Comment by iostalk** [comment]
By the way, when I press CMD+P to open a file, press in the textfield, atom seems very slow.
And when I open a project javascript file, the editor seems very slow.

**Comment by iostalk** [comment]
I saw this: The error was thrown from the nuclide-click-to-symbol package. nuclide-click-to-symbol is out of date: 0.0.21 installed; 0.0.22 latest. Upgrading to the latest version may fix this issue

**Comment by iostalk** [comment]
TypeError: undefined is not a function
  at ClickToSymbol.findClickableRangesAndCallback [as _findClickableRangesAndCallback] (/Users/xhowhy/.atom/packages/nuclide-click-to-symbol/lib/main.js:27:10)
  at ClickToSymbol.findClickableRangesAndCallback (/Users/xhowhy/.atom/packages/nuclide-click-to-symbol/lib/ClickToSymbol.js:54:51)
  at ClickToSymbol.onMouseMove (/Users/xhowhy/.atom/packages/nuclide-click-to-symbol/lib/ClickToSymbol.js:90:12)

**Comment by iostalk** [comment]
How to upgrade nuclide-click-to-symbol?

**Comment by jssln** [comment]
@iostalk, we've removed the `nuclide-click-to-symbol` package in favor of the `nuclide-hyperclick` package. You can delete the `nuclide-click-to-symbol` package.

**Comment by ssorallen** [comment]
Going to close this one since nuclide-click-to-symbol has been replaced. @iostalk, let us know if you still have problems in the nuclide-hyperclick package.

**Comment by lutherism** [comment]
@ssorallen I seem to be having this problem with `nuclid-hyperlink` but Atom pointed me to this issue.
`Uncaught TypeError: undefined is not a function`
`/Users/<user>/.atom/packages/nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:94`
