### ISSUE TITLE
Nuclide Quick Open has no search results

### ISSUE THREAD

**Issue by pwillcode** [facebook/nuclide#188]
When I use the quick search (Ctrl+t or any other tab of that particular tool) I get no results.
Here is what it looks like when I press Ctrl+t after opening a remote project.
![all-results1](https://cloud.githubusercontent.com/assets/6126513/9839847/9ec1cb5e-5a39-11e5-9126-22ba85d31348.png)
Any open files show at first, however if I enter anything into the search box...
![all-results2](https://cloud.githubusercontent.com/assets/6126513/9839854/bb23416a-5a39-11e5-8d9a-53c7e02949a8.png)
Even the open files no longer show in the results.
At the moment when I first begin typing into the search box, the following error is printed to the javascript console.
```
[2015-09-11T20:13:40.253Z] [ERROR] nuclide -  TypeError: Cannot read property 'getSearchProviders' of null {stack: (...), message: "Cannot read property 'getSearchProviders' of null"}
```
The stack trace is as follows:
```
TypeError: Cannot read property 'getSearchProviders' of null
  at OmniSearchResultProvider.<anonymous> (/home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:103:35)
  at GeneratorFunctionPrototype.next (native)
  at step (/home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:13:273)
  at /home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:13:443
  at OmniSearchResultProvider.<anonymous> (/home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:13:99)
  at /home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:67:24
  at GeneratorFunctionPrototype.next (native)
  at step (/home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:13:273)
  at /home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:13:443
  at /home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:13:99
  at Array.map (native)
  at OmniSearchResultProvider.<anonymous> (/home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:66:53)
  at GeneratorFunctionPrototype.next (native)
  at step (/home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:13:273)
  at /home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:13:443
  at OmniSearchResultProvider.<anonymous> (/home/paulw/.atom/packages/nuclide-quick-open/lib/OmniSearchResultProvider.js:13:99)
  at QuickSelectionComponent.setQuery (/home/paulw/.atom/packages/nuclide-quick-open/lib/QuickSelectionComponent.js:451:31)
  at QuickSelectionComponent.<anonymous> (/home/paulw/.atom/packages/nuclide-quick-open/lib/QuickSelectionComponent.js:197:23)
  at later (/home/paulw/.atom/packages/hyperclick/node_modules/nuclide-commons/lib/debounce.js:26:23)
```
I poked around in the debugger and found that in the call to RemoteConnection.getByHostnameAndPath, the _connections variable is an empty array, and so no object gets returned (leading to the attempted call of getSearchProviders on null.)
As far as I can tell, _connections never gets populated when I connect to a remote repository.
I have been unable to resolve this so far. (I tried uninstalling all Nuclide packages and then re-installing via nulcide-installer.)

**Comment by jgebhardt** [comment]
@pwillcode does this still repro for you?

**Comment by pwillcode** [comment]
Sorry, I won't have access to that work environment for about a week, so I can't check right now. It was still happening last time I tried it earlier this week. I'll try again when I get the chance.

**Comment by pwillcode** [comment]
On Atom 1.0.19 and Nuclide 0.0.32, the problem no longer reproduces. Quick search appears to work for me now.

**Comment by mostafaeweda** [comment]
This went through major changes and now the experience should be much better with the UP release, see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
