### ISSUE TITLE
nuclide-debugger-node not working under macosx

### ISSUE THREAD

**Issue by despairblue** [facebook/nuclide#193]
Atom shows this in the console:

```
Failed to require the main module of 'nuclide-debugger-node' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.
```

Issuing apm rebuild yields:

```
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.22.0
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/kietsy/git/nuclide/pkg/nuclide/debugger/node/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/kietsy/git/nuclide/pkg/nuclide/debugger/node/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/Users/kietsy/git/nuclide/pkg/nuclide/debugger/node/node_modules/v8-debug/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/kietsy/git/nuclide/pkg/nuclide/debugger/node/node_modules/v8-debug/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/kietsy/git/nuclide/pkg/nuclide/debugger/node/node_modules/v8-debug/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/kietsy/git/nuclide/pkg/nuclide/debugger/node/node_modules/v8-debug/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:434:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:452:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/usr/local/bin/iojs" "/Users/kietsy/git/nuclide/pkg/nuclide/debugger/node/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/kietsy/git/nuclide/pkg/nuclide/debugger/node/node_modules/v8-debug
node-pre-gyp ERR! node -v v4.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.10
node-pre-gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/kietsy/.atom/.apm/.apmrc" "--userconfig" "/Users/kietsy/.atom/.apmrc" "rebuild" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! v8-debug@0.5.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.5.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kietsy/git/nuclide/pkg/nuclide/debugger/node/npm-debug.log
```
## Versions
- **Atom:**       1.0.11
- **Atom-Shell:** 0.22.3
- **OS:**         Mac OS X 10.10.5
- **Misc**
  - Could not determine apm version information

**Comment by despairblue** [comment]
Nuclide is version 0.31.0

**Comment by pinny87** [comment]
:+1:  Also getting this issue. Identical setup.

**Comment by bolinfest** [comment]
I'm going to exclude `nuclide-debugger-node` from `nuclide-installer` until we can get this fixed: https://github.com/facebook/nuclide/commit/e14160d26ebe532753384cd4ac6b6b3678a8515d. I'm in the process of pushing v0.0.32 of Nuclide now.

**Comment by pkerschbaum** [comment]
I've got the same problem on windows 10, atom 1.0.15, this time with "unsupported target version 0.30.6".
A few days ago i also got "unsupported target version 0.22.0".

**Comment by mostafaeweda** [comment]
The newly integrated Node debugger should now be working.
