### ISSUE TITLE
Failed to activate the nuclide-debugger-atom package

### ISSUE THREAD

**Issue by andreqi** [facebook/nuclide#194]
[Enter steps to reproduce below:]

1. open nuclide

**Atom Version**: 1.0.14955173
**System**: Mac OS X 10.10.3
**Thrown From**: [nuclide-debugger-atom](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to activate the nuclide-debugger-atom package

```
At Tried to create a gutter with a name that is already in use.

Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.module.exports.GutterContainer.addGutter (/Applications/Nuclide.app/Contents/Resources/app/src/gutter-container.js:36:15)
    at TextEditor.module.exports.TextEditor.addGutter (/Applications/Nuclide.app/Contents/Resources/app/src/text-editor.js:2629:35)
    at new BreakpointDisplayController (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-debugger-atom/lib/BreakpointDisplayController.js:52:25)
    at BreakpointManager._handleTextEditor (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-debugger-atom/lib/BreakpointManager.js:54:24)
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Nuclide.app/Contents/Resources/app/src/workspace.js:276:9)
    at new BreakpointManager (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-debugger-atom/lib/BreakpointManager.js:28:42)
    at new DebuggerModel (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-debugger-atom/lib/DebuggerModel.js:40:31)
    at new Activation (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-debugger-atom/lib/main.js:83:19)
    at Object.activate (/Applications/Nuclide.app/Contents/Resources/app/node_modules/nuclide-debugger-atom/lib/main.js:174:20)
    at Package.module.exports.Package.activateNow (/Applications/Nuclide.app/Contents/Resources/app/src/package.js:243:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "deprecation-cop",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
arcanist, v0.0.0
autocomplete-haskell, v0.5.1
autocomplete-plus-clang, v0.0.0
buck, v0.0.0
debugger-hhvm, v0.0.0
debugger-lldb, v0.0.0
docblockr, v0.7.3
fb-analytics-client, v0.0.0
fb-diffs-and-tasks, v0.0.0
fb-file-a-bug, v0.0.0
fb-handle-url, v0.0.0
fb-nuclide-installer, v0.1.6
fb-package-manager, v0.0.0
fb-phabricator-comments, v0.0.0
graphql, v0.0.0
haskell-ghc-mod, v0.9.0
haskell-grammar, v0.3.0
hyperclick, v0.0.0
ide-haskell, v0.7.1
language-haskell, v1.4.1
language-ocaml, v1.1.1
linter, v1.0.4
nuclide-blame-ui, v0.0.0
nuclide-code-format, v0.0.0
nuclide-debugger, v0.0.0
nuclide-debugger-node, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-file-creation, v0.0.0
nuclide-file-creation-ios, v0.0.0
nuclide-file-tree, v0.0.0
nuclide-file-watcher, v0.0.0
nuclide-flow, v0.0.0
nuclide-hack, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-installer, v0.0.0
nuclide-language-hack, v0.0.0
nuclide-log-viewer, v0.0.0
nuclide-logging-helper, v0.0.0
nuclide-objc, v0.0.0
nuclide-quick-open, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-tabs-per-branch, v0.0.0
nuclide-toolbar, v0.0.0
nuclide-type-hint, v0.0.0
nuclide-ui-atom-text-editor, v0.0.0
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by morenoh149** [comment]
I think many people are seeing this on osx. Similar https://github.com/facebook/nuclide/issues/193

**Comment by frostyandy2k** [comment]
+1 
Atom also goes crazy with the CPU usage ~100%
OSX 10.9
Atom 1.2.4

**Comment by mostafaeweda** [comment]
The install process have improved a lot with our UP release, see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/ - feel free to reopen if still applies.
