### ISSUE TITLE
Failed to activate the nuclide-flow package

### ISSUE THREAD

**Issue by yvan-sraka** [facebook/nuclide#195]
Hello,

I just clicked on `Update All` packages in atom, and restarted my computer while the process was not completed I think.

**Atom Version**: 1.0.11
**System**: Debian GNU/Linux
**Thrown From**: [nuclide-flow](https://github.com/facebooknuclideapm/nuclide-flow) package, v0.0.32

### Stack Trace

Failed to activate the nuclide-flow package

```
At Cannot find module './lib/virtual-types'

Error: Cannot find module './lib/virtual-types'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/traversal/path/index.js:16:24)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/traversal/context.js:16:13)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/traversal/index.js:13:16)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/plugin-pass.js:19:18)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/plugin.js:16:19)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/transformer.js:12:15)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/file/plugin-manager.js:20:20)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/pipeline.js:12:26)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/transformation/index.js:12:17)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/lib/api/node.js:25:23)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/babel-core/index.js:1:80)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/node_modules/nuclide-node-transpiler/lib/babel-cache.js:14:13)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/node_modules/nuclide-service-parser/lib/main.js:17:43)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/lib/service-manager.js:5:29)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/node_modules/nuclide-client/lib/main.js:10:16)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/ysr/.atom/packages/nuclide-flow/lib/FlowHyperclickProvider.js:23:22)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.getHyperclickProvider (/home/ysr/.atom/packages/nuclide-flow/lib/main.js:84:34)
  at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:414:69)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:246:16)
  at /usr/share/atom/resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:486:21)
  at /usr/share/atom/resources/app.asar/src/package-manager.js:469:29
  at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:324:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:464:19)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:445:46)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom.js:670:21)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.6.9
hyperclick, v0.0.32
linter, v1.5.1
minimap, v4.13.3
nuclide-arcanist, v0.0.32
nuclide-code-format, v0.0.30
nuclide-diagnostics-store, v0.0.30
nuclide-diagnostics-ui, v0.0.32
nuclide-diff-view, v0.0.30
nuclide-file-tree, v0.0.32
nuclide-file-watcher, v0.0.30
nuclide-find-references, v0.0.32
nuclide-flow, v0.0.32
nuclide-hack, v0.0.30
nuclide-hg-repository, v0.0.30
nuclide-installer, v0.0.32
nuclide-language-hack, v0.0.30
nuclide-ocaml, v0.0.30
nuclide-quick-open, v0.0.30
nuclide-remote-projects, v0.0.30
nuclide-type-hint, v0.0.32
pigments, v0.15.0

# Dev
No dev packages
```

**Comment by yvan-sraka** [comment]
If I run again atom, I still get the error.

**Comment by nmote** [comment]
Thanks for reporting. We are looking into this.

**Comment by scv119** [comment]
@yvan-sraka  does remove the flow package and reinstall it helps?

**Comment by yvan-sraka** [comment]
No, I just tried, it does not solve the issue.

**Comment by mostafaeweda** [comment]
The UP release should have fixed this, see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
