### ISSUE TITLE
Failed to activate the nuclide-hack package

### ISSUE THREAD

**Issue by alvarezsantiago** [facebook/nuclide#197]
Cannot read property 'onDidRemoveProjectPath' of undefined
### Stack Trace
TypeError: Cannot read property 'onDidRemoveProjectPath' of undefined
  at Object.activate (/home/saalvare/.atom/packages/nuclide-hack/lib/main.js:35:31)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:243:19)
  at /usr/share/atom/resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:486:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:313:60
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

`Create issue on the nuclide-hack page` button results in an HTTP 404 error from github.com.  Similar issue with nuclide-flow package.

**Comment by mostafaeweda** [comment]
this is probably an install issue, because the new package versions should have `nuclide-atom-helpers` as dependency, having `projects.js` which exports as you see in: https://github.com/facebook/nuclide/blob/master/pkg/nuclide/atom-helpers/lib/projects.js#L90 - try re-installing or installing from source.
