### ISSUE TITLE
Throw Uncaught SyntaxError: Unexpected end of input, when I open AppDelegate.m

### ISSUE THREAD

**Issue by fomalhaut** [facebook/nuclide#205]
events.js:141

SyntaxError: Unexpected end of input
  at parse (native)
  at emit (/Users/Alex/.atom/packages/nuclide-clang-atom/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/nuclide-clang/node_modules/split/index.js:27:17)
  at Stream.<anonymous> (/Users/Alex/.atom/packages/nuclide-clang-atom/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/nuclide-clang/node_modules/split/index.js:59:7)
  at _end (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/through/index.js:65:9)
  at Stream.stream.end (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/through/index.js:74:5)
  at Socket.onend (_stream_readable.js:486:10)
  at Socket.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at Socket.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:889:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

**Comment by ta2gch** [comment]
I was also happened with .cpp file with `nuclide-clang-atom`.
