### ISSUE TITLE
Flow result parse error

### ISSUE THREAD

**Issue by LegNeato** [facebook/nuclide#206]
[2015-09-23T19:12:28.519Z] [ERROR] nuclide -  SyntaxError: Unexpected end of input
      at Object.parse (native)
      at LocalFlowService.<anonymous> (/Users/legnitto/.atom/packages/nuclide-flow/node_modules/nuclide-flow-base/lib/LocalFlowService.js:210:21)
      at GeneratorFunctionPrototype.next (native)
      at step (/Users/legnitto/.atom/packages/nuclide-flow/node_modules/nuclide-flow-base/lib/LocalFlowService.js:13:273)

    consoleAppender.js:37 [2015-09-23T19:12:31.292Z] [ERROR] nuclide - invalid JSON from flow type-at-pos: SyntaxError: Unexpected token l`

Note I have the latest flow from Homebrew:

    $ brew upgrade flow
    Error: flow 0.14.0 already installed

**Comment by bolinfest** [comment]
Hmm, we should make sure to update our `brew` recipe since we're on Flow 0.16.0 and there are some pretty important improvements:

https://github.com/facebook/flow/blob/master/Changelog.md#v0150
https://github.com/facebook/flow/blob/master/Changelog.md#v0160

**Comment by ssorallen** [comment]
Looks like it's already updated in Homebrew: https://github.com/Homebrew/homebrew/commit/ee072f95fd8d68e54db822c8973cc92ee4f74b35#diff-03d9e472713dea7839b461716dca58c4

Try running `brew update` and then `brew upgrade flow` again.

**Comment by bolinfest** [comment]
From the error, I'm guessing that Flow either wrote something to stdout that it should not have, or it segfaulted and the error was written to stdout, which was unsurprisingly not JSON.

Closing assuming this is a transient issue. Feel free to reopen if you can repro.
