### ISSUE TITLE
node module NaN does not compile

### ISSUE THREAD

**Issue by FlorianLudwig** [facebook/nuclide#207]
For nearly every nuclide package i get the following error:
```
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:74,
                 from ../src/bufferutil.cc:16:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
In file included from ../src/bufferutil.cc:7:0:
/home/f.ludwig/.atom/.node-gyp/.node-gyp/0.30.7/deps/v8/include/v8.h:4515:27: note: candidate: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/f.ludwig/.atom/.node-gyp/.node-gyp/0.30.7/deps/v8/include/v8.h:4515:27: note:   candidate expects 2 arguments, 4 provided
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
```

Any pointers how I get it working again?

Thanks

**Comment by bolinfest** [comment]
If you are on OS X, I think you need to upgrade Xcode to get the new version of Command Line Tools.

**Comment by FlorianLudwig** [comment]
I am on Fedora Linux - what exactly are you referencing to with "command line tools"?  Is a newer version of npm needed?

**Comment by hasssan** [comment]
```
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:74,
                 from ../src/bufferutil.cc:16:
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: error: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
../node_modules/nan/nan_implementation_12_inl.h:181:76: note: candidate is:
In file included from ../src/bufferutil.cc:7:0:
/home/hassan/.atom/.node-gyp/.node-gyp/0.30.7/deps/v8/include/v8.h:4515:27: note: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/hassan/.atom/.node-gyp/.node-gyp/0.30.7/deps/v8/include/v8.h:4515:27: note:   candidate expects 2 arguments, 4 provided
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-49-generic
gyp ERR! command "node" "/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hassan/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

npm ERR! Linux 3.16.0-49-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/hassan/.atom/.apm/.apmrc" "--userconfig" "/home/hassan/.atom/.apmrc" "rebuild" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hassan/.atom/packages/nuclide-quick-open/npm-debug.log
```

Same here, Ubuntu Linux.

**Comment by FlorianLudwig** [comment]
I solved it by reinstalling all nuclide packages.

```
cd  ~/.atom/packages
ls | grep ^nuclide | xargs -I{} sh -c "apm rm {}; apm install {}"
```
