### ISSUE TITLE
Uncaught Error: Remote connection has been closed.

### ISSUE THREAD

**Issue by simar7** [facebook/nuclide#209]
I think this is an edge that could be better handled.

[Enter steps to reproduce below:]
1. Close the debugger palate (don't disconnect)
2. Close the connection with the remote server
3. Shutdown the nuclide instance running on the remote server.
4. Re-open the debugger palate again.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [debugger-hhvm](https://github.com/facebook/nuclide) package, v0.0.0
### Stack Trace

Uncaught Error: Remote connection has been closed.

```
At /Users/simar/.nuclide/11908834/Tools/Nuclide/pkg/nuclide/analytics/fb/analytics.js:110

Error: Remote connection has been closed.
  at RemoteConnection.getClient (/Users/simar/.nuclide/11908834/Tools/Nuclide/pkg/nuclide/remote-connection/lib/RemoteConnection.js:351:15)
  at RemoteConnection.makeRpc (/Users/simar/.nuclide/11908834/Tools/Nuclide/pkg/nuclide/remote-connection/lib/RemoteConnection.js:387:19)
  at RemoteHhvmDebuggerProxyService.sendCommand (/Users/simar/.nuclide/11908834/Tools/Nuclide/pkg/nuclide/service-transformer/gen/HhvmDebuggerProxyService.js:62:31)
  at RemoteHhvmDebuggerProxyService.descriptor.value (/Users/simar/.nuclide/11908834/Tools/Nuclide/pkg/nuclide/analytics/fb/analytics.js:92:34)
  at DebuggerProcess._onSocketMessage (/Users/simar/.nuclide/11908834/Tools/Arsenal/pkg/debugger-hhvm/lib/DebuggerProcess.js:140:21)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:172:7)
  at Receiver.ontext (/Users/simar/.nuclide/11908834/Tools/Arsenal/pkg/debugger-hhvm/node_modules/ws/lib/WebSocket.js:798:10)
  at /Users/simar/.nuclide/11908834/Tools/Arsenal/pkg/debugger-hhvm/node_modules/ws/lib/Receiver.js:473:18
  at /Users/simar/.nuclide/11908834/Tools/Arsenal/pkg/debugger-hhvm/node_modules/ws/lib/Receiver.js:357:7
  at /Users/simar/.nuclide/11908834/Tools/Arsenal/pkg/debugger-hhvm/node_modules/ws/lib/PerMessageDeflate.js:217:5
  at afterWrite (_stream_writable.js:345:3)
  at onwrite (_stream_writable.js:336:7)
  at WritableState.onwrite (_stream_writable.js:88:5)
  at afterTransform (_stream_transform.js:79:5)
  at TransformState.afterTransform (_stream_transform.js:54:12)
  at Zlib.callback (zlib.js:614:5)

```
### Commands

```
     -2:24.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:24.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:24.3.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -2:23.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:23.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:22.1.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -2:19.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:19.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:19.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:19.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:18.6.0 nuclide-quick-open:toggle-omni-search (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -0:41.7.0 find-and-replace:show (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -0:39.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:39.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:26 core:save (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
     -0:05.2.0 nuclide-debugger:toggle (atom-text-editor.editor.enable-nuclide-find-references.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "deprecation-cop",
      "fuzzy-finder",
      "incompatible-packages",
      "metrics",
      "styleguide",
      "timecop",
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Termrk, v0.1.26
autocomplete-python, v0.5.4
debugger-hhvm, v0.0.0
fb-analytics-client, v0.0.0
fb-analytics-reporter-settings, v0.0.0
fb-biggrep-provider, v0.0.0
fb-codegraph-providers, v0.0.0
fb-diffs-and-tasks, v0.0.0
fb-error-reporting, v0.0.0
fb-file-a-bug, v0.0.0
fb-handle-url, v0.0.0
fb-health, v0.0.0
fb-hg-smartlog, v0.0.0
fb-nuclide-installer, v0.1.8
fb-package-manager, v0.0.0
fb-phabricator-comments-client, v0.0.0
fb-rating, v0.0.0
fb-test-runner-t-client, v0.0.0
graphql, v0.0.0
haskell-grammar, v0.3.0
hyperclick, v0.0.0
language-ocaml, v1.1.1
linter-python-pep8, v0.2.0
nuclide-arcanist, v0.0.0
nuclide-blame, v0.0.0
nuclide-blame-provider-hg, v0.0.0
nuclide-blame-ui, v0.0.0
nuclide-buck-files, v0.0.0
nuclide-clang-atom, v0.0.0
nuclide-code-format, v0.0.0
nuclide-debugger-atom, v0.0.0
nuclide-debugger-lldb, v0.0.0
nuclide-debugger-node, v0.0.0
nuclide-diagnostics-store, v0.0.0
nuclide-diagnostics-ui, v0.0.0
nuclide-diff-view, v0.0.0
nuclide-file-creation, v0.0.0
nuclide-file-creation-ios, v0.0.0
nuclide-file-tree, v0.0.0
nuclide-file-tree-deux, v0.0.0
nuclide-file-watcher, v0.0.0
nuclide-find-references, v0.0.0
nuclide-flow, v0.0.0
nuclide-fuzzy-filename-provider, v0.0.0
nuclide-hack, v0.0.0
nuclide-hack-symbol-provider, v0.0.0
nuclide-hg-repository, v0.0.0
nuclide-language-hack, v0.0.0
nuclide-log-viewer, v0.0.0
nuclide-logging-helper, v0.0.0
nuclide-objc, v0.0.0
nuclide-ocaml, v0.0.0
nuclide-open-filenames-provider, v0.0.0
nuclide-quick-open, v0.0.0
nuclide-remote-projects, v0.0.0
nuclide-tabs-per-branch, v0.0.0
nuclide-test-runner, v0.0.0
nuclide-toolbar, v0.0.0
nuclide-type-hint, v0.0.0

# Dev
No dev packages
```

**Comment by mostafaeweda** [comment]
A new HHVM debugger has been ported to Nuclide since then -- please update to the latest and see if things are fixed.
