### ISSUE TITLE
Failed to load the nuclide-hack package

### ISSUE THREAD

**Issue by urzds** [facebook/nuclide#224]
[Enter steps to reproduce below:]

1. I start Atom
2. I am greeted with two error messages. This and #226 (was: atom/atom#9306).

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [nuclide-hack](https://github.com/facebooknuclideapm/nuclide-hack) package, v0.0.32

### Stack Trace

Failed to load the nuclide-hack package

```
At Cannot find module 'nuclide-hack-common/lib/constants'

Error: Cannot find module 'nuclide-hack-common/lib/constants'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (${HOME}/.atom/packages/nuclide-hack/lib/main.js:14:17)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.32
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.0
latexer, v0.2.7
linter, v1.9.1
linter-csslint, v1.1.0
linter-gcc, v0.3.8
linter-htmlhint, v0.2.1
linter-lua, v1.0.0
linter-lua-findglobals, v1.0.0
linter-luacheck, v1.1.3
linter-php, v1.0.5
linter-rust, v0.2.10
linter-tidy, v1.0.1
minimap, v4.15.0
nuclide-arcanist, v0.0.32
nuclide-blame, v0.0.32
nuclide-blame-provider-hg, v0.0.32
nuclide-blame-ui, v0.0.32
nuclide-buck-files, v0.0.32
nuclide-clang-atom, v0.0.32
nuclide-code-format, v0.0.32
nuclide-debugger-atom, v0.0.32
nuclide-debugger-hhvm, v0.0.32
nuclide-debugger-lldb, v0.0.32
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-diff-view, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.32
nuclide-find-references, v0.0.32
nuclide-flow, v0.0.32
nuclide-fuzzy-filename-provider, v0.0.32
nuclide-hack, v0.0.32
nuclide-hack-symbol-provider, v0.0.32
nuclide-hg-repository, v0.0.32
nuclide-installer, v0.0.32
nuclide-language-hack, v0.0.32
nuclide-objc, v0.0.32
nuclide-ocaml, v0.0.32
nuclide-open-filenames-provider, v0.0.32
nuclide-quick-open, v0.0.32
nuclide-remote-projects, v0.0.32
nuclide-test-runner, v0.0.32
nuclide-toolbar, v0.0.32
nuclide-type-hint, v0.0.32
pdf-view, v0.34.0

# Dev
No dev packages
```

Maybe related: I am also experiencing #225 and #226.

**Comment by urzds** [comment]
I am also experiencing facebook/nuclide#225.

**Comment by urzds** [comment]
Still happens with Atom 1.2:

**Atom Version**: 1.2.0
**System**: Ubuntu 14.04.3
**Thrown From**: [nuclide-hack](https://github.com/facebooknuclideapm/nuclide-hack) package, v0.0.32


### Stack Trace

Failed to load the nuclide-hack package

```
At Cannot find module 'nuclide-hack-common/lib/constants'

Error: Cannot find module 'nuclide-hack-common/lib/constants'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/AD/tf128/.atom/packages/nuclide-hack/lib/main.js:14:17)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.32
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.2
latexer, v0.2.7
linter, v1.10.0
linter-csslint, v1.1.0
linter-gcc, v0.3.9
linter-htmlhint, v0.2.1
linter-lua, v1.0.0
linter-lua-findglobals, v1.0.0
linter-luacheck, v1.1.3
linter-rust, v0.2.10
linter-tidy, v1.0.1
minimap, v4.16.0
nuclide-arcanist, v0.0.32
nuclide-blame, v0.0.32
nuclide-blame-provider-hg, v0.0.32
nuclide-blame-ui, v0.0.32
nuclide-buck-files, v0.0.32
nuclide-clang-atom, v0.0.32
nuclide-code-format, v0.0.32
nuclide-debugger-atom, v0.0.32
nuclide-debugger-hhvm, v0.0.32
nuclide-debugger-lldb, v0.0.32
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-diff-view, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.32
nuclide-find-references, v0.0.32
nuclide-flow, v0.0.32
nuclide-fuzzy-filename-provider, v0.0.32
nuclide-hack, v0.0.32
nuclide-hack-symbol-provider, v0.0.32
nuclide-hg-repository, v0.0.32
nuclide-installer, v0.0.32
nuclide-language-hack, v0.0.32
nuclide-objc, v0.0.32
nuclide-ocaml, v0.0.32
nuclide-open-filenames-provider, v0.0.32
nuclide-quick-open, v0.0.32
nuclide-remote-projects, v0.0.32
nuclide-test-runner, v0.0.32
nuclide-toolbar, v0.0.32
nuclide-type-hint, v0.0.32
pdf-view, v0.34.0

# Dev
No dev packages
```

**Comment by mostafaeweda** [comment]
All installation issues should have been fixed with out UP release, see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
