### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by urzds** [facebook/nuclide#225]
[Enter steps to reproduce below:]

1. I open a file in Atom
2. I see this error message and also:

```
Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:266:12)
  at LocalClangService.<anonymous> (${HOME}/.atom/packages/nuclide-buck-files/node_modules/nuclide-buck-commons/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/nuclide-clang/lib/LocalClangService.js:153:28)
  at GeneratorFunctionPrototype.next (native)
  at step (${HOME}/.atom/packages/nuclide-buck-files/node_modules/nuclide-buck-commons/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/nuclide-clang/lib/LocalClangService.js:15:273)
```

**Atom Version**: 1.0.19
**System**: Ubuntu 14.04.3
**Thrown From**: [nuclide-buck-files](https://github.com/facebooknuclideapm/nuclide-buck-files) package, v0.0.32

### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At events.js:141

SyntaxError: Unexpected end of input
  at parse (native)
  at emit (${HOME}/.atom/packages/nuclide-buck-files/node_modules/nuclide-buck-commons/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/nuclide-clang/node_modules/split/index.js:27:17)
  at Stream.<anonymous> (${HOME}/.atom/packages/nuclide-buck-files/node_modules/nuclide-buck-commons/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/nuclide-clang/node_modules/split/index.js:59:7)
  at _end (/usr/share/atom/resources/app.asar/node_modules/through/index.js:65:9)
  at Stream.stream.end (/usr/share/atom/resources/app.asar/node_modules/through/index.js:74:5)
  at Socket.onend (_stream_readable.js:486:10)
  at Socket.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at Socket.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:889:12)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.32
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.0
latexer, v0.2.7
linter, v1.9.1
linter-csslint, v1.1.0
linter-gcc, v0.3.8
linter-htmlhint, v0.2.1
linter-lua, v1.0.0
linter-lua-findglobals, v1.0.0
linter-luacheck, v1.1.3
linter-php, v1.0.5
linter-rust, v0.2.10
linter-tidy, v1.0.1
minimap, v4.15.0
nuclide-arcanist, v0.0.32
nuclide-blame, v0.0.32
nuclide-blame-provider-hg, v0.0.32
nuclide-blame-ui, v0.0.32
nuclide-buck-files, v0.0.32
nuclide-clang-atom, v0.0.32
nuclide-code-format, v0.0.32
nuclide-debugger-atom, v0.0.32
nuclide-debugger-hhvm, v0.0.32
nuclide-debugger-lldb, v0.0.32
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-diff-view, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.32
nuclide-find-references, v0.0.32
nuclide-flow, v0.0.32
nuclide-fuzzy-filename-provider, v0.0.32
nuclide-hack, v0.0.32
nuclide-hack-symbol-provider, v0.0.32
nuclide-hg-repository, v0.0.32
nuclide-installer, v0.0.32
nuclide-language-hack, v0.0.32
nuclide-objc, v0.0.32
nuclide-ocaml, v0.0.32
nuclide-open-filenames-provider, v0.0.32
nuclide-quick-open, v0.0.32
nuclide-remote-projects, v0.0.32
nuclide-test-runner, v0.0.32
nuclide-toolbar, v0.0.32
nuclide-type-hint, v0.0.32
pdf-view, v0.34.0

# Dev
No dev packages
```

Maybe related: I am also experiencing #224, #226 (was: atom/atom#9306).

**Comment by urzds** [comment]
I am also experiencing #224 and atom/atom#9306.

**Comment by mostafaeweda** [comment]
this should have been fixed with the UP release, see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/ - feel free to reopen if still applies.
