### ISSUE TITLE
Uncaught TypeError: Cannot read property 'row' of undefined

### ISSUE THREAD

**Issue by jefflindholm** [facebook/nuclide#227]
[Enter steps to reproduce below:]

1.just opened a directory
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [nuclide-diagnostics-ui](https://github.com/facebooknuclideapm/nuclide-diagnostics-ui) package, v0.0.32

### Stack Trace

Uncaught TypeError: Cannot read property 'row' of undefined

```
At C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-ui\lib\DiagnosticsPane.js:39

TypeError: Cannot read property 'row' of undefined
  at locationColumnCellDataGetter (C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-ui\lib\DiagnosticsPane.js:39:62)
  at [object Object]._renderCell (C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-ui\node_modules\fixed-data-table-for-atom\internal\FixedDataTableCellGroup.react.js:121:35)
  at [object Object].render (C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-ui\node_modules\fixed-data-table-for-atom\internal\FixedDataTableCellGroup.react.js:75:25)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:775:34)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:801:14)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:235:30)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactReconciler.js:38:35)
  at mountComponentIntoNode (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMount.js:248:32)
  at ReactReconcileTransaction.Mixin.perform (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\Transaction.js:134:20)
  at batchedMountComponentIntoNode (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMount.js:269:15)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDefaultBatchingStrategy.js:64:7)
  at Object.batchedUpdates (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactUpdates.js:110:20)
  at Object.ReactMount._renderNewRootComponent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMount.js:404:18)
  at Object.ReactMount.render (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactMount.js:493:32)
  at render (C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-ui\lib\createPanel.js:72:30)
  at C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-ui\lib\createPanel.js:87:5
  at DiagnosticStore.onAllMessagesDidUpdate (C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-store\node_modules\nuclide-diagnostics-base\lib\DiagnosticStore.js:253:9)
  at Object.createDiagnosticsPanel (C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-ui\lib\createPanel.js:84:57)
  at createPanel (C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-ui\lib\main.js:36:66)
  at atom-workspace.<anonymous> (C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-ui\lib\main.js:155:9)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\jeff.lindholm\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (C:\Users\jeff.lindholm\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\jeff.lindholm\AppData\Local\atom\app-1.0.19\resources\app.asar\src\command-registry.js:145:19)
  at StatusBarTileComponent._onClick (C:\Users\jeff.lindholm\.atom\packages\nuclide-diagnostics-ui\lib\StatusBarTile.js:166:21)
  at Object.executeDispatch (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\EventPluginUtils.js:110:21)
  at SimpleEventPlugin.executeDispatch (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\SimpleEventPlugin.js:305:40)
  at forEachEventDispatch (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\EventPluginUtils.js:98:5)
  at Object.executeDispatchesInOrder (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\EventPluginUtils.js:119:3)
  at executeDispatchesAndRelease (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\EventPluginHub.js:46:22)
  at Array.forEach (native)
  at forEachAccumulated (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\forEachAccumulated.js:23:9)
  at Object.EventPluginHub.processEventQueue (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\EventPluginHub.js:253:5)
  at runEventQueueInBatch (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactEventEmitterMixin.js:44:5)
  at handleTopLevelImpl (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactEventListener.js:80:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\Transaction.js:134:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactDefaultBatchingStrategy.js:66:19)
  at Object.batchedUpdates (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactUpdates.js:110:20)
  at ReactEventListener.dispatchEvent (C:\Users\jeff.lindholm\.atom\packages\hyperclick\node_modules\react-for-atom\node_modules\react\lib\ReactEventListener.js:174:20)

```

### Commands

```
  5x -0:12.5.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:04.5.0 nuclide-diagnostics-ui:toggle-table (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jsfmt",
      "node-debugger",
      "tree-view"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.32
language-javascript-better, v1.5.0
language-javascript-jsx, v0.3.7
linter, v1.9.1
linter-eslint, v3.2.0
nuclide-arcanist, v0.0.32
nuclide-blame, v0.0.32
nuclide-blame-provider-hg, v0.0.32
nuclide-blame-ui, v0.0.32
nuclide-buck-files, v0.0.32
nuclide-clang-atom, v0.0.32
nuclide-code-format, v0.0.32
nuclide-debugger-atom, v0.0.32
nuclide-debugger-hhvm, v0.0.32
nuclide-debugger-lldb, v0.0.32
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-diff-view, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.32
nuclide-find-references, v0.0.32
nuclide-flow, v0.0.32
nuclide-fuzzy-filename-provider, v0.0.32
nuclide-hack, v0.0.32
nuclide-hack-symbol-provider, v0.0.32
nuclide-hg-repository, v0.0.32
nuclide-installer, v0.0.32
nuclide-language-hack, v0.0.32
nuclide-objc, v0.0.32
nuclide-ocaml, v0.0.32
nuclide-open-filenames-provider, v0.0.32
nuclide-quick-open, v0.0.32
nuclide-remote-projects, v0.0.32
nuclide-test-runner, v0.0.32
nuclide-toolbar, v0.0.32
nuclide-type-hint, v0.0.32
react, v0.12.10

# Dev
No dev packages
```

**Comment by mostafaeweda** [comment]
closing, duplicate issue
