### ISSUE TITLE
Setup script for builiding nuclide is not working on mac (El capitan)

### ISSUE THREAD

**Issue by latamautos** [facebook/nuclide#228]
Setup script for builiding nuclide is not working on mac (El capitan)

```
MacBook-Pro:nuclide xavier$ sudo ./scripts/dev/setup
Password:
Running pre-development setup scripts...
Nothing needed to be run.
Pre-development setup scripts executed.
START INSTALL: 2015-10-28 17:00:42.138254
Installing dependencies for Node package nuclide-inline-imports...
Dependencies for nuclide-inline-imports already installed
Installing dependencies for Node package nuclide-debugger-interfaces...
Installing dependencies for Node package nuclide-external-interfaces...
Dependencies for nuclide-debugger-interfaces already installed
Installing dependencies for Node package nuclide-home-interfaces...
Dependencies for nuclide-external-interfaces already installed
Dependencies for nuclide-home-interfaces already installed
Installing dependencies for Node package nuclide-node-transpiler...
Dependencies for nuclide-node-transpiler already installed
Installing dependencies for Node package hyperclick-interfaces...
Installing dependencies for Node package nuclide-keytar-wrapper...
Installing dependencies for Node package nuclide-service-hub-plus...
Dependencies for hyperclick-interfaces already installed
Dependencies for nuclide-keytar-wrapper already installed
Installing dependencies for Node package nuclide-blame-base...
Dependencies for nuclide-service-hub-plus already installed
Installing dependencies for Node package nuclide-process-output-store...
Dependencies for nuclide-blame-base already installed
Installing dependencies for Node package nuclide-process-output-handler...
Dependencies for nuclide-process-output-store already installed
Installing dependencies for Atom package nuclide-code-format...
Dependencies for nuclide-process-output-handler already installed
Installing dependencies for Atom package nuclide-language-hack...
Dependencies for nuclide-code-format already installed
Running `apm link /Users/xavier/latamautos/nuclide/pkg/nuclide/code-format`...
Installing dependencies for Node package nuclide-atom-test-helpers...
Dependencies for nuclide-language-hack already installed
Running `apm link /Users/xavier/latamautos/nuclide/pkg/nuclide/language-hack`...
Installing dependencies for Node package nuclide-jasmine...
Dependencies for nuclide-atom-test-helpers already installed
Dependencies for nuclide-jasmine already installed
Installing dependencies for Node package nuclide-test-helpers...
Installing dependencies for Node package nuclide-busy-signal-interfaces...
Installing dependencies for Node package nuclide-version...
Installing dependencies for Node package nuclide-hack-common...
Dependencies for nuclide-test-helpers already installed
Dependencies for nuclide-busy-signal-interfaces already installed
Installing dependencies for Node package nuclide-debugger-utils...
Dependencies for nuclide-version already installed
Installing dependencies for Node package nuclide-quick-open-interfaces...
Dependencies for nuclide-hack-common already installed
Installing dependencies for Node package nuclide-ui-pane-item...
Dependencies for nuclide-debugger-utils already installed
Dependencies for nuclide-quick-open-interfaces already installed
Installing dependencies for Node package nuclide-commons...
Installing dependencies for Node package nuclide-task...
Dependencies for nuclide-ui-pane-item already installed
Installing dependencies for Atom package nuclide-busy-signal...
Dependencies for nuclide-commons already installed
Installing dependencies for Atom package nuclide-recent-files-provider...
Installing dependencies for Atom package nuclide-open-filenames-provider...
Dependencies for nuclide-busy-signal already installed
Running `apm link /Users/xavier/latamautos/nuclide/pkg/nuclide/busy-signal`...
Dependencies for nuclide-task already installed
Dependencies for nuclide-recent-files-provider already installed
Running `apm link /Users/xavier/latamautos/nuclide/pkg/nuclide/recent-files-provider`...
Installing dependencies for Node package nuclide-atom-npm...
Dependencies for nuclide-open-filenames-provider already installed
Running `apm link /Users/xavier/latamautos/nuclide/pkg/nuclide/open-filenames-provider`...
Installing dependencies for Node package nuclide-remote-uri...
Dependencies for nuclide-atom-npm already installed
Installing dependencies for Node package nuclide-logging...
Dependencies for nuclide-remote-uri already installed
Installing dependencies for Node package nuclide-keystroke-label...
Dependencies for nuclide-logging already installed
Dependencies for nuclide-keystroke-label already installed
Installing dependencies for Node package nuclide-busy-signal-provider-base...
Installing dependencies for Node package nuclide-text-event-dispatcher...
Dependencies for nuclide-busy-signal-provider-base already installed
Installing dependencies for Node package nuclide-source-control-helpers...
Dependencies for nuclide-text-event-dispatcher already installed
Uninstall unused dependency async for /Users/xavier/latamautos/nuclide/pkg/nuclide/source-control-helpers
Installing dependencies for Node package nuclide-installer-base...
Installing dependencies for Atom package nuclide-debugger-lldb...
Dependencies for nuclide-installer-base already installed
Dependencies for nuclide-debugger-lldb already installed
Running `apm link /Users/xavier/latamautos/nuclide/pkg/nuclide/debugger/lldb`...
Installing dependencies for Atom package nuclide-home...
Dependencies for nuclide-home already installed
Running `apm link /Users/xavier/latamautos/nuclide/pkg/nuclide/home`...
Done linking nuclide-language-hack
Done linking nuclide-code-format
Installing dependencies for Node package nuclide-ui-tabs...
Done linking nuclide-home
Installing dependencies for Node package nuclide-ui-dropdown...
Dependencies for nuclide-ui-tabs already installed
Dependencies for nuclide-ui-dropdown already installed
Installing dependencies for Node package nuclide-ui-atom-input...
Done linking nuclide-busy-signal
Dependencies for nuclide-ui-atom-input already installed
Installing dependencies for Node package nuclide-ui-panel...
Installing dependencies for Node package nuclide-ui-radiogroup...
Dependencies for nuclide-ui-panel already installed
Done linking nuclide-debugger-lldb
Installing dependencies for Node package nuclide-ui-mutable-list-selector...
Dependencies for nuclide-ui-radiogroup already installed
Done linking nuclide-open-filenames-provider
Dependencies for nuclide-ui-mutable-list-selector already installed
Installing dependencies for Node package nuclide-ui-tree...
Installing dependencies for Node package nuclide-ui-checkbox...
Done linking nuclide-recent-files-provider
Installing dependencies for Node package nuclide-atom-helpers...
Dependencies for nuclide-ui-tree already installed
Installing dependencies for Node package nuclide-diagnostics-base...
Dependencies for nuclide-ui-checkbox already installed
Installing dependencies for Node package nuclide-format-js-base...
Dependencies for nuclide-atom-helpers already installed
Dependencies for nuclide-diagnostics-base already installed
Installing dependencies for Node package nuclide-analytics...
Installing dependencies for Node package nuclide-flow-base...
Installing dependencies for Node package nuclide-arcanist-base...
Uninstall unused dependency ansi-regex for /Users/xavier/latamautos/nuclide/pkg/nuclide/format-js-base
Installing dependencies for Node package nuclide-buck-base...
Installing dependencies for Node package nuclide-watchman-helpers...
Dependencies for nuclide-analytics already installed
Installing dependencies for Node package nuclide-debugger-hhvm-proxy...
Dependencies for nuclide-flow-base already installed
Uninstall unused dependency async for /Users/xavier/latamautos/nuclide/pkg/nuclide/arcanist-base
Dependencies for nuclide-buck-base already installed
Uninstall unused dependency node-int64 for /Users/xavier/latamautos/nuclide/pkg/nuclide/watchman-helpers
Installing dependencies for Node package nuclide-ocaml-base...
Dependencies for nuclide-debugger-hhvm-proxy already installed
Installing dependencies for Node package nuclide-remote-search...
Installing dependencies for Node package nuclide-hack-base...
Dependencies for nuclide-ocaml-base already installed
Dependencies for nuclide-hack-base already installed
Installing dependencies for Atom package nuclide-installer...
Dependencies for nuclide-installer already installed
Running `apm link /Users/xavier/latamautos/nuclide/pkg/nuclide/installer`...
Installing dependencies for Node package nuclide-hhvm-toolbar...
Installing dependencies for Node package nuclide-ui-atom-combo-box...
Error running ['npm', 'uninstall', 'async'] in /Users/xavier/latamautos/nuclide/pkg/nuclide/source-control-helpers
Process Process-34:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/dev/../lib/topological_installer.py", line 159, in install_dependencies
    npm.install(src_path, local_packages=package_config['localDependencies'], include_dev_dependencies=True)
  File "./scripts/dev/../lib/npm.py", line 60, in install
    self._clean_unused_dependencies(package_root);
  File "./scripts/dev/../lib/npm.py", line 115, in _clean_unused_dependencies
    self._execute(['npm', 'uninstall', folder], package_root)
  File "./scripts/dev/../lib/npm.py", line 123, in _execute
    output = fs.cross_platform_check_output(cmd_args, cwd=cwd, stderr=devnull)
  File "./scripts/dev/../lib/fs.py", line 89, in cross_platform_check_output
    raise subprocess.CalledProcessError(returncode, cmd_args, output=stdout)
CalledProcessError: Command '['npm', 'uninstall', 'async']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./scripts/dev/setup", line 50, in <module>
    exclude_windows_incompatible_packages=is_windows())
  File "./scripts/dev/../lib/package_manager.py", line 34, in install_dependencies
    installer.install()
  File "./scripts/dev/../lib/topological_installer.py", line 53, in install
    self._do_multiprocess_install()
  File "./scripts/dev/../lib/topological_installer.py", line 100, in _do_multiprocess_install
    (config['name'], exitcode))
Exception: Installing package nuclide-source-control-helpers failed with exit code 1
Done linking nuclide-installer
Error running ['npm', 'uninstall', 'async'] in /Users/xavier/latamautos/nuclide/pkg/nuclide/arcanist-base
Process Process-51:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/dev/../lib/topological_installer.py", line 159, in install_dependencies
    npm.install(src_path, local_packages=package_config['localDependencies'], include_dev_dependencies=True)
  File "./scripts/dev/../lib/npm.py", line 60, in install
    self._clean_unused_dependencies(package_root);
  File "./scripts/dev/../lib/npm.py", line 115, in _clean_unused_dependencies
    self._execute(['npm', 'uninstall', folder], package_root)
  File "./scripts/dev/../lib/npm.py", line 123, in _execute
    output = fs.cross_platform_check_output(cmd_args, cwd=cwd, stderr=devnull)
  File "./scripts/dev/../lib/fs.py", line 89, in cross_platform_check_output
    raise subprocess.CalledProcessError(returncode, cmd_args, output=stdout)
CalledProcessError: Command '['npm', 'uninstall', 'async']' returned non-zero exit status 1
Error running ['npm', 'uninstall', 'node-int64'] in /Users/xavier/latamautos/nuclide/pkg/nuclide/watchman-helpers
Process Process-53:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/dev/../lib/topological_installer.py", line 159, in install_dependencies
    npm.install(src_path, local_packages=package_config['localDependencies'], include_dev_dependencies=True)
  File "./scripts/dev/../lib/npm.py", line 60, in install
    self._clean_unused_dependencies(package_root);
  File "./scripts/dev/../lib/npm.py", line 115, in _clean_unused_dependencies
    self._execute(['npm', 'uninstall', folder], package_root)
  File "./scripts/dev/../lib/npm.py", line 123, in _execute
    output = fs.cross_platform_check_output(cmd_args, cwd=cwd, stderr=devnull)
  File "./scripts/dev/../lib/fs.py", line 89, in cross_platform_check_output
    raise subprocess.CalledProcessError(returncode, cmd_args, output=stdout)
CalledProcessError: Command '['npm', 'uninstall', 'node-int64']' returned non-zero exit status 1
Error running ['npm', 'uninstall', 'ansi-regex'] in /Users/xavier/latamautos/nuclide/pkg/nuclide/format-js-base
Process Process-48:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/dev/../lib/topological_installer.py", line 159, in install_dependencies
    npm.install(src_path, local_packages=package_config['localDependencies'], include_dev_dependencies=True)
  File "./scripts/dev/../lib/npm.py", line 60, in install
    self._clean_unused_dependencies(package_root);
  File "./scripts/dev/../lib/npm.py", line 115, in _clean_unused_dependencies
    self._execute(['npm', 'uninstall', folder], package_root)
  File "./scripts/dev/../lib/npm.py", line 123, in _execute
    output = fs.cross_platform_check_output(cmd_args, cwd=cwd, stderr=devnull)
  File "./scripts/dev/../lib/fs.py", line 89, in cross_platform_check_output
    raise subprocess.CalledProcessError(returncode, cmd_args, output=stdout)
CalledProcessError: Command '['npm', 'uninstall', 'ansi-regex']' returned non-zero exit status 1
Done installing dependencies for nuclide-ui-atom-combo-box
Done installing dependencies for nuclide-hhvm-toolbar
Done installing dependencies for nuclide-remote-search
```

I want to use nuclide-remote-projects but versions are distinct, please help

**Comment by guswelter** [comment]
Running the commands that are failing manually will give you more information. For example, for the first command that's failing, do:

    cd /Users/xavier/latamautos/nuclide/pkg/nuclide/source-control-helpers
    sudo npm uninstall async

**Comment by keyanzhang** [comment]
You probably don't need `sudo`. Is there a reason behind using it?

**Comment by guswelter** [comment]
Because he ran the script with sudo, and we're trying to capture the npm output as it would have occurred for the script.

**Comment by omarstreak** [comment]
When I run the first command that is failing, this is the relevant error message I get:
```
1295 error Darwin 15.0.0
1296 error argv "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/bin/npm" "install" "--no-optional"
1297 error node v4.2.0
1298 error npm  v3.3.10
1299 error path /Users/oismail/development/nuclide/pkg/nuclide/reprint-js/node_modules/defs/node_modules/esprima-fb/bin/esparse.js
1300 error code ENOENT
1301 error errno -2
1302 error syscall chmod
1303 error enoent ENOENT: no such file or directory, chmod '/Users/oismail/development/nuclide/pkg/nuclide/reprint-js/node_modules/defs/node_modules/esprima-fb/bin/esparse.js'
1303 error enoent This is most likely not a problem with npm itself
1303 error enoent and is related to npm not being able to find a file.
1304 verbose exit [ -2, true ]
```
this happens if I run the command with sudo or not.

**Comment by nmote** [comment]
This is a strange error. I've occasionally seen my repository get into a weird state that breaks the setup script (usually in some npm call like this), and cleaning out the repository does the trick.

Assuming you don't have any uncommitted work in the Nuclide repository that you care about, run `git clean -xfd` and see if that clears up the issue. Since you ran the setup script with `sudo`, you may have to run this command with `sudo`. After that, don't use `sudo` for the setup script -- it's not necessary.

**Comment by etcinit** [comment]
I'm currently having the same issue while attempting to install Nuclide on OS X 10.11. I attempted to run `git clean -xfd` and also did a fresh clone (from `master`) but neither worked. It looks like npm is failing to install some packages, which causes `scripts/dev/setup` to fail.

```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install" "--no-optional"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! path /Users/etcinit/projects/github.com/facebook/nuclide/pkg/nuclide/reprint-js/node_modules/nuclide-jasmine/bin/jasmine-node-transpiled
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/etcinit/projects/github.com/facebook/nuclide/pkg/nuclide/reprint-js/node_modules/nuclide-jasmine/bin/jasmine-node-transpiled'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

```

**Comment by guswelter** [comment]
May be related to System Integrity Protection in El Capitan: https://support.apple.com/en-us/HT204899

To disable: http://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-os-x-10-11

Don't forget to re-enable afterwards with `csrutil enable`.

**Comment by etcinit** [comment]
Hm. I don't think this issue is related to permissions.

After a while, I managed to get (most of) it working, but it was very tedious. I had to go through each package in nuclide, and manually run `npm install` or `npm install <missing dependency>` while reloading Atom in the background looking for errors on missing modules.

I think npm may be skipping installing some packages because it sees that the directories are linked (I get many messages about skipped actions while running `npm install` manually on a nuclide package).

**Comment by omarstreak** [comment]
The frustrating part of this is that installing Nuclide using Atom's
package manager sucks performance wise, and so Nuclide recommends
installing from source. But then installing from source is broken (for
some/many people).

**Comment by torifat** [comment]
Try using `npm 2.x`, `./scripts/dev/setup` doesn't work with `npm 3.x` for me. I get similar error using 3.

**Comment by omarstreak** [comment]
@torifat thanks for the advice, that worked for me.

Specifically I:
- installed npm 2.x (sudo npm install -g npm@2.14.10)
- rm -rf ~/.atom/
- sudo git clean -xfd
- sudo ./scripts/dev/setup

and now it's working! Flow autocomplete is sweet.

**Comment by nhz-io** [comment]
upgrade your npm and it will go away

**Comment by omarstreak** [comment]
I tried with the latest npm before trying 2.X and it failed with the latest
npm *shrug*.

**Comment by nhz-io** [comment]
well, installing this myself now, the mentioned issue went away with upgrade to npm 3.4, but suddenly arcanist-base deps failed to install, had to go and manually npm install it by hand from arcanist-base dir. This is weird.

**Comment by nmote** [comment]
I just tried with npm 3.3 and 3.4, and neither worked. I downgraded npm to 2.0.2 (with node still on v5.0.0), and the script worked.

We will settle on canonical versions and make sure that they are clearly documented. In the mean time, try using the versions above when setting up Nuclide.

**Comment by torifat** [comment]
Yeah, `3.x` doesn't work. I believe it has something to do with this-

```
$ apm --version
apm  1.4.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.6.3
```

**Comment by bolchisbolchis** [comment]
What worked for me was manually removing the problematic folders. E.g.:

```
[...]
Installing dependencies for Node package nuclide-reprint-js...
Uninstall unused dependency mkdirp for /Users/bogdanb/Developer/react-native/nuclide/pkg/nuclide/reprint-js
Error running ['npm', 'uninstall', 'mkdirp'] in /Users/bogdanb/Developer/react-native/nuclide/pkg/nuclide/reprint-js
Process Process-37:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
[...]
```
I removed reprint-js, then ran ./scripts/dev/setup again, repeating the process if needed.

**Comment by torifat** [comment]
I just pulled and checked. `npm` `v3` is working now.

**Comment by viatsko** [comment]
This helped me. Considering this is a very temporary solution
https://github.com/viatsko/nuclide/commit/bbcaa47ef42b5e4883eb2c10bd17c2441cd7fde8

**Comment by ssorallen** [comment]
The setup script has been removed as of yesterday's release, v0.111.0 of 'nuclide'. Building from source now only requires cloning, `npm install`, and `apm link`.

http://nuclide.io/docs/setup/#building-from-source
