### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by chadhietala** [facebook/nuclide#234]
This occurs in quick-open.

```
Uncaught (in promise) TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
  at /Users/chietala/.atom/packages/nuclide-quick-open/lib/SearchResultManager.js:319:68
  at Array.forEach (native)
  at SearchResultManager.<anonymous> (/Users/chietala/.atom/packages/nuclide-quick-open/lib/SearchResultManager.js:317:25)
  at GeneratorFunctionPrototype.next (native)
  at step (/Users/chietala/.atom/packages/nuclide-quick-open/lib/SearchResultManager.js:17:273)
  at /Users/chietala/.atom/packages/nuclide-quick-open/lib/SearchResultManager.js:17:443
  at SearchResultManager.<anonymous> (/Users/chietala/.atom/packages/nuclide-quick-open/lib/SearchResultManager.js:17:99)
  at Object.ID_1 (/Users/chietala/.atom/packages/nuclide-quick-open/lib/SearchResultManager.js:118:20)
  at Dispatcher.$Dispatcher_invokeCallback (/Users/chietala/.atom/packages/nuclide-quick-open/node_modules/flux/lib/Dispatcher.js:220:35)
  at Dispatcher.dispatch (/Users/chietala/.atom/packages/nuclide-quick-open/node_modules/flux/lib/Dispatcher.js:195:14)
  at Object.query (/Users/chietala/.atom/packages/nuclide-quick-open/lib/QuickSelectionActions.js:16:44)
  at QuickSelectionComponent.setQuery (/Users/chietala/.atom/packages/nuclide-quick-open/lib/QuickSelectionComponent.js:479:42)
  at Immediate._onImmediate (/Users/chietala/.atom/packages/nuclide-quick-open/lib/QuickSelectionComponent.js:117:29)
  at processImmediate [as _immediateCallback] (timers.js:371:17)
```

**Comment by kevinsimper** [comment]
I also have that problem, which results in a empty search bar 

atom: 1.1.0
nuclide-quick-open: v0.0.32

![image](https://cloud.githubusercontent.com/assets/1126497/10945060/7bbbc888-831c-11e5-8de7-c446ff0e606c.png)
