### ISSUE TITLE
Uncaught TypeError: Cannot read property 'row' of undefined

### ISSUE THREAD

**Issue by urzds** [facebook/nuclide#235]
[Enter steps to reproduce below:]
1. Happens sometimes during regular use.

Possibly related to issue #227.

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: [nuclide-diagnostics-ui](https://github.com/facebooknuclideapm/nuclide-diagnostics-ui) package, v0.0.32
### Stack Trace

Uncaught TypeError: Cannot read property 'row' of undefined

```
At ${HOME}/.atom/packages/nuclide-diagnostics-ui/lib/paneUtils.js:34

TypeError: Cannot read property 'row' of undefined
  at compareMessagesByFile (${HOME}/.atom/packages/nuclide-diagnostics-ui/lib/paneUtils.js:34:31)
  at Array.sort (native)
  at render (${HOME}/.atom/packages/nuclide-diagnostics-ui/lib/createPanel.js:68:53)
  at ${HOME}/.atom/packages/nuclide-diagnostics-ui/lib/createPanel.js:87:5
  at DiagnosticStore.onAllMessagesDidUpdate (${HOME}/.atom/packages/nuclide-diagnostics-store/node_modules/nuclide-diagnostics-base/lib/DiagnosticStore.js:253:9)
  at Object.createDiagnosticsPanel (${HOME}/.atom/packages/nuclide-diagnostics-ui/lib/createPanel.js:84:57)
  at createPanel (${HOME}/.atom/packages/nuclide-diagnostics-ui/lib/main.js:36:66)
  at atom-workspace.<anonymous> (${HOME}/.atom/packages/nuclide-diagnostics-ui/lib/main.js:155:9)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:143:19)
  at StatusBarTileComponent._onClick (${HOME}/.atom/packages/nuclide-diagnostics-ui/lib/StatusBarTile.js:166:21)
  at Object.executeDispatch (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/EventPluginUtils.js:110:21)
  at SimpleEventPlugin.executeDispatch (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/SimpleEventPlugin.js:305:40)
  at forEachEventDispatch (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/EventPluginUtils.js:98:5)
  at Object.executeDispatchesInOrder (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/EventPluginUtils.js:119:3)
  at executeDispatchesAndRelease (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:46:22)
  at Array.forEach (native)
  at forEachAccumulated (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/forEachAccumulated.js:23:9)
  at Object.EventPluginHub.processEventQueue (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/EventPluginHub.js:253:5)
  at runEventQueueInBatch (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/ReactEventEmitterMixin.js:44:5)
  at handleTopLevelImpl (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/ReactEventListener.js:80:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/Transaction.js:134:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.batchedUpdates (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/ReactUpdates.js:110:20)
  at ReactEventListener.dispatchEvent (${HOME}/.atom/packages/hyperclick/node_modules/react-for-atom/node_modules/react/lib/ReactEventListener.js:174:20)

```
### Commands

```
     -1:27.9.0 core:copy (atom-text-editor.editor.editor-objc.is-focused)
  2x -1:24.5.0 core:backspace (atom-text-editor.editor.editor-objc.is-focused)
     -1:24.1.0 core:paste (atom-text-editor.editor.editor-objc.is-focused)
     -1:23.3.0 nuclide-click-to-symbol:activate (atom-text-editor.editor.editor-objc.is-focused)
  2x -1:10.8.0 core:backspace (atom-text-editor.editor.editor-objc.is-focused)
     -1:09.1.0 core:move-left (atom-text-editor.editor.editor-objc.is-focused)
     -1:06.3.0 core:save (atom-text-editor.editor.editor-objc.is-focused)
     -1:01.7.0 core:delete (atom-text-editor.editor.editor-objc.is-focused)
     -1:00.8.0 editor:newline (atom-text-editor.editor.editor-objc.is-focused)
     -0:49.3.0 core:save (atom-text-editor.editor.editor-objc.is-focused)
     -0:43.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.editor-objc.is-focused)
  3x -0:41.8.0 editor:move-to-end-of-word (atom-text-editor.editor.editor-objc.is-focused)
  2x -0:41.1.0 core:move-right (atom-text-editor.editor.editor-objc.is-focused)
  7x -0:40.5.0 core:delete (atom-text-editor.editor.editor-objc.is-focused)
     -0:38.8.0 core:save (atom-text-editor.editor.editor-objc.is-focused)
     -0:32.1.0 nuclide-diagnostics-ui:toggle-table (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
hyperclick, v0.0.32
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.0
latexer, v0.2.7
linter, v1.10.0
linter-csslint, v1.1.0
linter-gcc, v0.3.9
linter-htmlhint, v0.2.1
linter-lua, v1.0.0
linter-lua-findglobals, v1.0.0
linter-luacheck, v1.1.3
linter-php, v1.0.5
linter-rust, v0.2.10
linter-tidy, v1.0.1
minimap, v4.16.0
nuclide-arcanist, v0.0.32
nuclide-blame, v0.0.32
nuclide-blame-provider-hg, v0.0.32
nuclide-blame-ui, v0.0.32
nuclide-buck-files, v0.0.32
nuclide-clang-atom, v0.0.32
nuclide-click-to-symbol, v0.0.22
nuclide-code-format, v0.0.32
nuclide-debugger-atom, v0.0.32
nuclide-debugger-hhvm, v0.0.32
nuclide-debugger-lldb, v0.0.32
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-diff-view, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.32
nuclide-find-references, v0.0.32
nuclide-flow, v0.0.32
nuclide-fuzzy-filename-provider, v0.0.32
nuclide-hack, v0.0.32
nuclide-hack-symbol-provider, v0.0.32
nuclide-hg-repository, v0.0.32
nuclide-installer, v0.0.32
nuclide-language-hack, v0.0.32
nuclide-objc, v0.0.32
nuclide-ocaml, v0.0.32
nuclide-open-filenames-provider, v0.0.32
nuclide-quick-open, v0.0.32
nuclide-remote-projects, v0.0.32
nuclide-test-runner, v0.0.32
nuclide-toolbar, v0.0.32
nuclide-type-hint, v0.0.32
pdf-view, v0.34.0

# Dev
No dev packages
```

**Comment by LegNeato** [comment]
I am seeing this when using rust-linter, there are multiple errors, and mousing over the first / topmost error in the gutter. The further down errors work correctly and show the gutter tooltip.

**Comment by mostafaeweda** [comment]
@nmote could you look into that?

**Comment by LegNeato** [comment]
Still seeing this.

**Comment by Nashenas88** [comment]
This is happening for me when working in rust and hovering over the rightward facing triangle in the gutter, i.e. on a row, but not part of the code row.

Here's another stack trace in case it helps:

```js
TypeError: Cannot read property 'row' of undefined
  at exports.DiagnosticsTraceItem.props (/Users/paul/.atom/packages/nuclide/pkg/nuclide-ui/DiagnosticsTraceItem.js:28:41)
  at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:310:27)
  at ReactCompositeComponentWrapper._constructComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:283:19)
  at ReactCompositeComponentWrapper.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:190:21)
  at Object.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:47:35)
  at ReactDOMComponent.mountChildren (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:240:44)
  at ReactDOMComponent._createInitialChildren (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:698:32)
  at ReactDOMComponent.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:523:12)
  at Object.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:47:35)
  at ReactCompositeComponentWrapper.performInitialMount (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:385:34)
  at ReactCompositeComponentWrapper.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:260:21)
  at Object.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:47:35)
  at ReactDOMComponent.mountChildren (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:240:44)
  at ReactDOMComponent._createInitialChildren (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:698:32)
  at ReactDOMComponent.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:523:12)
  at Object.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:47:35)
  at ReactDOMComponent.mountChildren (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:240:44)
  at ReactDOMComponent._createInitialChildren (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:698:32)
  at ReactDOMComponent.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:523:12)
  at Object.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:47:35)
  at ReactCompositeComponentWrapper.performInitialMount (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:385:34)
  at ReactCompositeComponentWrapper.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:260:21)
  at Object.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:47:35)
  at ReactCompositeComponentWrapper.performInitialMount (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:385:34)
  at ReactCompositeComponentWrapper.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:260:21)
  at Object.mountComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:47:35)
  at mountComponentIntoNode (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:105:32)
  at ReactReconcileTransaction.perform (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:138:20)
  at batchedMountComponentIntoNode (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:127:15)
  at ReactDefaultBatchingStrategyTransaction.perform (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:138:20)
  at Object.batchedUpdates (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:98:20)
  at Object._renderNewRootComponent (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:321:18)
  at Object._renderSubtreeIntoContainer (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:402:32)
  at Object.render (/Users/paul/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:423:23)
  at showPopupFor (/Users/paul/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/gutter.js:280:21)
  at HTMLAnchorElement.item.addEventListener.event (/Users/paul/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/gutter.js:241:20)
```

**Comment by griff** [comment]
If also happens when clicking the Full description checkbox in the Diagnostics pane where all the errors and warnings are from rust-linter.

```
TypeError: Cannot read property 'row' of undefined
  at exports.DiagnosticsTraceItem.props (/Users/bro/.atom/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-diagnostics-ui/lib/DiagnosticsTraceItem.js:28:41)
  at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:310:27)
  at ReactCompositeComponentWrapper._constructComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:283:19)
  at ReactCompositeComponentWrapper.mountComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:190:21)
  at Object.mountComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:47:35)
  at ReactDOMComponent.mountChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:240:44)
  at ReactDOMComponent._createInitialChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:698:32)
  at ReactDOMComponent.mountComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:523:12)
  at Object.mountComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:47:35)
  at ReactCompositeComponentWrapper._updateRenderedComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:776:40)
  at ReactCompositeComponentWrapper._performComponentUpdate (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:739:10)
  at ReactCompositeComponentWrapper.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:658:12)
  at ReactCompositeComponentWrapper.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:552:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at Object.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:110:25)
  at ReactDOMComponent._reconcilerUpdateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:215:28)
  at ReactDOMComponent._updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:314:31)
  at ReactDOMComponent.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:301:12)
  at ReactDOMComponent._updateDOMChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:941:12)
  at ReactDOMComponent.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:759:10)
  at ReactDOMComponent.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:717:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at Object.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:110:25)
  at ReactDOMComponent._reconcilerUpdateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:215:28)
  at ReactDOMComponent._updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:314:31)
  at ReactDOMComponent.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:301:12)
  at ReactDOMComponent._updateDOMChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:941:12)
  at ReactDOMComponent.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:759:10)
  at ReactDOMComponent.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:717:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at Object.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:110:25)
  at ReactDOMComponent._reconcilerUpdateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:215:28)
  at ReactDOMComponent._updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:314:31)
  at ReactDOMComponent.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:301:12)
  at ReactDOMComponent._updateDOMChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:941:12)
  at ReactDOMComponent.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:759:10)
  at ReactDOMComponent.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:717:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at Object.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:110:25)
  at ReactDOMComponent._reconcilerUpdateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:215:28)
  at ReactDOMComponent._updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:314:31)
  at ReactDOMComponent.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:301:12)
  at ReactDOMComponent._updateDOMChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:941:12)
  at ReactDOMComponent.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:759:10)
  at ReactDOMComponent.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:717:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at Object.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:110:25)
  at ReactDOMComponent._reconcilerUpdateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:215:28)
  at ReactDOMComponent._updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:314:31)
  at ReactDOMComponent.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:301:12)
  at ReactDOMComponent._updateDOMChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:941:12)
  at ReactDOMComponent.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:759:10)
  at ReactDOMComponent.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:717:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at ReactCompositeComponentWrapper._updateRenderedComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:761:23)
  at ReactCompositeComponentWrapper._performComponentUpdate (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:739:10)
  at ReactCompositeComponentWrapper.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:658:12)
  at ReactCompositeComponentWrapper.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:552:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at Object.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:110:25)
  at ReactDOMComponent._reconcilerUpdateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:215:28)
  at ReactDOMComponent._updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:314:31)
  at ReactDOMComponent.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:301:12)
  at ReactDOMComponent._updateDOMChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:941:12)
  at ReactDOMComponent.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:759:10)
  at ReactDOMComponent.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:717:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at ReactCompositeComponentWrapper._updateRenderedComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:761:23)
  at ReactCompositeComponentWrapper._performComponentUpdate (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:739:10)
  at ReactCompositeComponentWrapper.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:658:12)
  at ReactCompositeComponentWrapper.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:552:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at Object.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:110:25)
  at ReactDOMComponent._reconcilerUpdateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:215:28)
  at ReactDOMComponent._updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:314:31)
  at ReactDOMComponent.updateChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:301:12)
  at ReactDOMComponent._updateDOMChildren (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:941:12)
  at ReactDOMComponent.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:759:10)
  at ReactDOMComponent.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:717:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at ReactCompositeComponentWrapper._updateRenderedComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:761:23)
  at ReactCompositeComponentWrapper._performComponentUpdate (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:739:10)
  at ReactCompositeComponentWrapper.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:658:12)
  at ReactCompositeComponentWrapper.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:552:10)
  at Object.receiveComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:126:22)
  at ReactCompositeComponentWrapper._updateRenderedComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:761:23)
  at ReactCompositeComponentWrapper._performComponentUpdate (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:739:10)
  at ReactCompositeComponentWrapper.updateComponent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:658:12)
  at ReactCompositeComponentWrapper.performUpdateIfNecessary (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:566:12)
  at Object.performUpdateIfNecessary (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:158:22)
  at runBatchedUpdates (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:151:21)
  at ReactReconcileTransaction.perform (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:138:20)
  at ReactUpdatesFlushTransaction.perform (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:138:20)
  at ReactUpdatesFlushTransaction.perform (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:90:38)
  at Object.flushBatchedUpdates (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:173:19)
  at ReactDefaultBatchingStrategyTransaction.closeAll (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:204:25)
  at ReactDefaultBatchingStrategyTransaction.perform (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:151:16)
  at Object.batchedUpdates (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:98:20)
  at dispatchEvent (/Users/bro/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:150:20)
```

**Comment by griff** [comment]
I did some tracking and it seems to be the problem is in linterMessageToDiagnosticMessage 

/code
