### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPathOfUri' of undefined

### ISSUE THREAD

**Issue by markmiro** [facebook/nuclide#238]
I'm running Atom 1.0.7-0a6da38 with Nuclide 0.0.32 on a 2015 retina macbook pro with El Capitan.

I get this error on key press after opening a remote file and starting to type anything. I keep seeing more instances of the notification that shows the error as I keep typing.

```
TypeError: Cannot read property 'getPathOfUri' of undefined
  at RemoteFlowService.getAutocompleteSuggestions (/Users/mmiro/.atom/packages/nuclide-arcanist/node_modules/nuclide-arcanist-client/node_modules/nuclide-client/node_modules/nuclide-service-transformer/gen/FlowService.js:106:30)
  at FlowAutocompleteProvider.getSuggestions (/Users/mmiro/.atom/packages/nuclide-flow/lib/FlowAutocompleteProvider.js:43:26)
  at /Users/mmiro/Documents/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/mmiro/Documents/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Users/mmiro/Documents/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/mmiro/Documents/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
  at /Users/mmiro/Documents/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

**Comment by markmiro** [comment]
I thought it might have been due to me using a self-built version of Atom (which was stuck at an older version), but it still fails with a standard install with version 1.1.0

**Comment by nmote** [comment]
@markmiro Does this happen on any remote file, or just JavaScript?

@scv119 this looks like an error in the generated service framework code. Any ideas?

**Comment by 1N50MN14** [comment]
@nmote Experiencing the same error here, fresh install of both Atom and Nuclide. 

The error is being thrown from the nuclide-flow package, FlowService.js line 79. It seems to happen on Javascript code only.

**Comment by 1N50MN14** [comment]
@nmote Disabling the package fixed the issue. Disabled 70% of the `nuclide-*` packages while at it and that dramatically increased the performance, things are smooth all the sudden. Those should not install by default, imho.

**Comment by markmiro** [comment]
@nmote I uninstalled nuclide since it was causing a lot of lag while typing even on local files, but I don't remember the errors popping up on anything except JavaScript.
