### ISSUE TITLE
Failed to activate the nuclide-toolbar package

### ISSUE THREAD

**Issue by urzds** [facebook/nuclide#243]
[Enter steps to reproduce below:]

1. Open a new Atom window
2. See error message

**Atom Version**: 1.2.0
**System**: Ubuntu 14.04.3
**Thrown From**: [nuclide-toolbar](https://github.com/facebooknuclideapm/nuclide-toolbar) package, v0.0.32

### Stack Trace

Failed to activate the nuclide-toolbar package

```
At deprecationSite.getFileName is not a function

TypeError: deprecationSite.getFileName is not a function
    at Object.global.__grim__.deprecate (/usr/share/atom/resources/app.asar/node_modules/grim/lib/grim.js:56:36)
    at Object.defineProperty.get [as TextEditor] (/usr/share/atom/resources/app.asar/exports/atom.js:38:14)
    at Object.<anonymous> (${HOME}/.atom/packages/nuclide-toolbar/node_modules/nuclide-buck-toolbar/lib/BuckToolbar.js:37:27)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.load (${HOME}/.atom/packages/nuclide-toolbar/node_modules/nuclide-buck-toolbar/node_modules/nuclide-atom-npm/lib/main.js:68:31)
```

### Commands

```
     -0:00.2.0 nuclide-click-to-symbol:activate (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.32
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.2
latexer, v0.2.7
linter, v1.10.0
linter-csslint, v1.1.0
linter-gcc, v0.3.9
linter-htmlhint, v0.2.1
linter-lua, v1.0.0
linter-lua-findglobals, v1.0.0
linter-luacheck, v1.1.3
linter-rust, v0.2.10
linter-tidy, v1.0.1
minimap, v4.16.0
nuclide-arcanist, v0.0.32
nuclide-blame, v0.0.32
nuclide-blame-provider-hg, v0.0.32
nuclide-blame-ui, v0.0.32
nuclide-buck-files, v0.0.32
nuclide-clang-atom, v0.0.32
nuclide-click-to-symbol, v0.0.22
nuclide-code-format, v0.0.32
nuclide-debugger-atom, v0.0.32
nuclide-debugger-hhvm, v0.0.32
nuclide-debugger-lldb, v0.0.32
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-diff-view, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.32
nuclide-find-references, v0.0.32
nuclide-flow, v0.0.32
nuclide-fuzzy-filename-provider, v0.0.32
nuclide-hack, v0.0.32
nuclide-hack-symbol-provider, v0.0.32
nuclide-hg-repository, v0.0.32
nuclide-installer, v0.0.32
nuclide-language-hack, v0.0.32
nuclide-objc, v0.0.32
nuclide-ocaml, v0.0.32
nuclide-open-filenames-provider, v0.0.32
nuclide-quick-open, v0.0.32
nuclide-remote-projects, v0.0.32
nuclide-test-runner, v0.0.32
nuclide-toolbar, v0.0.32
nuclide-type-hint, v0.0.32
pdf-view, v0.34.0

# Dev
No dev packages
```

**Comment by urzds** [comment]
See-Also: atom/atom#9350

**Comment by ssorallen** [comment]
Thanks for bringing all of these up, @urzds. I am going to consolidate these into #243 because they all have the same root cause in the `TextEditor`.
