### ISSUE TITLE
Failed to activate the nuclide-blame-provider-hg package

### ISSUE THREAD

**Issue by urzds** [facebook/nuclide#256]
[Enter steps to reproduce below:]

1. Start Atom with Nuclide
2. Observe this error message

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [nuclide-blame-provider-hg](https://github.com/facebooknuclideapm/nuclide-blame-provider-hg) package, v0.0.35

### Stack Trace

Failed to activate the nuclide-blame-provider-hg package

```
At Cannot find module 'nuclide-commons'

Error: Cannot find module 'nuclide-commons'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (${HOME}/.atom/packages/nuclide-blame-provider-hg/node_modules/nuclide-hg-git-bridge/lib/repositoryForPath.js:1:102)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.get [as repositoryForPath] (${HOME}/.atom/packages/nuclide-blame-provider-hg/node_modules/nuclide-hg-git-bridge/lib/main.js:20:14)
    at Object.<anonymous> (${HOME}/.atom/packages/nuclide-blame-provider-hg/lib/common.js:16:33)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (${HOME}/.atom/packages/nuclide-blame-provider-hg/lib/HgBlameProvider.js:40:15)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.provideHgBlameProvider (${HOME}/.atom/packages/nuclide-blame-provider-hg/lib/main.js:20:23)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:327:69)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:512:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:490:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:474:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:671:21)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:38:8)
    at Object.<anonymous> (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:49:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:79:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.35
language-cuda, v0.1.0
language-glsl, v2.0.1
language-hlsl, v1.2.0
language-latex, v0.6.1
language-lua, v0.9.4
language-opencl, v0.1.1
language-rust, v0.4.5
language-tmux, v0.4.0
latex, v0.28.2
latexer, v0.2.7
linter, v1.11.2
linter-csslint, v1.1.0
linter-gcc, v0.5.0
linter-htmlhint, v0.2.1
linter-lua, v1.0.0
linter-luacheck, v1.1.3
linter-rust, v0.2.10
linter-tidy, v1.0.1
minimap, v4.16.2
nuclide-arcanist, v0.0.35
nuclide-blame, v0.0.35
nuclide-blame-provider-hg, v0.0.35
nuclide-blame-ui, v0.0.35
nuclide-buck-files, v0.0.35
nuclide-busy-signal, v0.0.35
nuclide-clang-atom, v0.0.35
nuclide-code-format, v0.0.35
nuclide-code-highlight, v0.0.35
nuclide-debugger-atom, v0.0.35
nuclide-debugger-hhvm, v0.0.35
nuclide-debugger-lldb, v0.0.35
nuclide-diagnostics-store, v0.0.35
nuclide-diagnostics-ui, v0.0.35
nuclide-diff-view, v0.0.35
nuclide-file-tree, v0.0.35
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.35
nuclide-find-references, v0.0.35
nuclide-flow, v0.0.35
nuclide-fuzzy-filename-provider, v0.0.35
nuclide-hack, v0.0.35
nuclide-hack-symbol-provider, v0.0.35
nuclide-health, v0.0.35
nuclide-hg-repository, v0.0.35
nuclide-home, v0.0.35
nuclide-installer, v0.0.35
nuclide-language-hack, v0.0.35
nuclide-objc, v0.0.35
nuclide-ocaml, v0.0.35
nuclide-open-filenames-provider, v0.0.35
nuclide-quick-open, v0.0.35
nuclide-recent-files-provider, v0.0.35
nuclide-recent-files-service, v0.0.35
nuclide-remote-projects, v0.0.35
nuclide-test-runner, v0.0.35
nuclide-toolbar, v0.0.35
nuclide-type-hint, v0.0.35
nuclide-url-hyperclick, v0.0.35
pdf-view, v0.37.0
project-manager, v2.6.5
tool-bar, v0.1.9

# Dev
No dev packages
```

**Comment by urzds** [comment]
I uninstalled nuclide-file-tree-deux@v0.0.32 and nuclide-click-to-symbol@v0.0.22, but that did not change anything.

**Comment by urzds** [comment]
The Diff View has a similar problem, but does not generate a proper error report or stacktrace.

**Comment by ssorallen** [comment]
Looks like the same cause as #253. Merging this one there.

**Comment by hankyum** [comment]
same issue happen on Mac OS X EI and it is very slow..

**Comment by udoyen** [comment]
Cannot find module 'nuclide-commons'

Hide Stack Trace

``` Error: Cannot find module 'nuclide-commons'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/george/.atom/packages/nuclide-blame-provider-hg/node_modules/nuclide-hg-git-bridge/lib/repositoryForPath.js:1:102)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.get [as repositoryForPath] (/home/george/.atom/packages/nuclide-blame-provider-hg/node_modules/nuclide-hg-git-bridge/lib/main.js:20:14)
    at Object.<anonymous> (/home/george/.atom/packages/nuclide-blame-provider-hg/lib/common.js:16:33)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/home/george/.atom/packages/nuclide-blame-provider-hg/lib/HgBlameProvider.js:40:15)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.provideHgBlameProvider (/home/george/.atom/packages/nuclide-blame-provider-hg/lib/main.js:20:23)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app.asar/src/package.js:327:69)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16) ```

This happened on Ubuntu LTS 14.04

**Comment by the-invisible-man** [comment]
This is still happening on OS X El Capitan on the most recent version version.

`Error: Cannot find module 'nuclide-commons'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/cgranados/.atom/packages/nuclide-blame-provider-hg/node_modules/nuclide-hg-git-bridge/lib/repositoryForPath.js:1:102)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.get [as repositoryForPath] (/Users/cgranados/.atom/packages/nuclide-blame-provider-hg/node_modules/nuclide-hg-git-bridge/lib/main.js:20:14)
    at Object.<anonymous> (/Users/cgranados/.atom/packages/nuclide-blame-provider-hg/lib/common.js:16:33)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/cgranados/.atom/packages/nuclide-blame-provider-hg/lib/HgBlameProvider.js:40:15)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.provideHgBlameProvider (/Users/cgranados/.atom/packages/nuclide-blame-provider-hg/lib/main.js:20:23)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:349:69)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:16)`
