### ISSUE TITLE
Error: Missing "providerName" property for hyperclick provider.

### ISSUE THREAD

**Issue by capaj** [facebook/nuclide#257]
Using latest Atom I get thrown this error on startup. I am using js-hyperclick as a provider.
```
Error: Missing "providerName" property for hyperclick provider.
    at Object.consumeProvider (/home/capaj/.atom/packages/hyperclick/lib/main.js:32:13)
    at Provider.module.exports.Provider.provide (/usr/share/atom-beta/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom-beta/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)`
```

**Comment by AsaAyers** [comment]
It's a bug produced by the fact that hyperclick isn't bothering to version your provider API. You shipped a breaking change without changing from `hyperclick.provider` `0.0.0` to anything else or supporting a 2nd version of that provider that requires a `providerName` that `js-hyperclick` could opt into.

**Comment by PointedEars** [comment]
**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [hyperclick](https://github.com/facebooknuclideapm/hyperclick) package, v0.0.35


### Stack Trace

Uncaught Error: Missing "providerName" property for hyperclick provider.

```
At /Users/tholah/.atom/packages/hyperclick/lib/main.js:32

Error: Missing "providerName" property for hyperclick provider.
    at Object.consumeProvider (/Users/tholah/.atom/packages/hyperclick/lib/main.js:32:13)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-shellcheck",
      "ctrl-last-tab"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-qunit-snippets, v1.1.0
atom-ternjs, v0.13.2
atomatigit, v1.5.5
auto-detect-indentation, v0.4.2
autoclose-html, v0.20.0
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autoupdate-packages, v1.3.1
break-time, v0.2.0
browser-plus, v0.0.54
character-table, v0.4.3
clipboard-plus, v0.5.1
color-picker, v2.1.1
column-select, v0.2.0
compare-files, v0.6.2
css-snippets, v0.9.0
css-specificity, v0.2.2
docblockr, v0.7.3
docs-snippets, v0.8.0
file-icons, v1.6.14
filesize, v0.4.2
fold-comments, v0.5.0
git-go, v1.0.1
git-hide, v0.1.2
git-log, v0.4.1
git-tabs, v0.3.0
highlight-selected, v0.11.2
hyperclick, v0.0.35
jade-snippets, v0.5.0
javascript-snippets, v1.2.0
js-refactor, v0.6.0
keyboard-localization, v1.4.14
keyboard-scroll, v0.4.0
language-diff, v0.4.0
language-jade, v0.6.3
line-count-status, v0.0.3
linter, v1.11.3
linter-csslint, v1.2.0
linter-htmlhint, v1.0.2
linter-jade, v0.3.2
linter-jshint, v1.3.0
linter-less, v2.4.0
local-history, v3.2.3
markdown-scroll-sync, vundefined
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
nav-panel, v0.0.11
navigate, v0.1.13
nodejs-snippets, v2.0.0
open-recent, v5.0.0
pigments, v0.23.1
preview-plus, v1.2.6
project-view, v0.5.0
recent-projects, v0.9.5
refactor, v0.6.0
remember-file-positions, v0.2.1
restore-windows, v0.4.1
revert-buffer, v0.5.0
save-session, v0.16.0
smart-tab-name, v1.0.5
snippets-jade, v0.1.1
source-preview-jade, v0.1.1
stash-tabs, v0.1.0
symbols-tree-view, v0.11.0
task-list, v0.7.0
text-manipulation, v0.6.0
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
up2date, v0.1.2
vim-mode-clipboard-plus, v0.2.0
vim-mode-plus, v0.19.1
xkcd-comics, v0.3.0

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
@PointedEars Hyperclick is now part of the ['nuclide' package](https://atom.io/packages/nuclide). You can install Nuclide and disable all of the features but Hyperclick if that is the feature you are looking to use. 'hyperclick' v0.0.35 still has the bug you are seeing, but it is fixed in the current release of 'nuclide'.
