### ISSUE TITLE
Install nuclide-debugger-node

### ISSUE THREAD

**Issue by tamascsaba** [facebook/nuclide#262]
Attached the trace:

[trace.txt](https://github.com/facebook/nuclide/files/50654/trace.txt)

**Comment by ssorallen** [comment]
It looks like the same error as https://github.com/electronjs/electron-rebuild/issues/31 and related to https://github.com/mapbox/node-pre-gyp/pull/175.

What command were you trying to run?

Here are relevant snippets from trace.txt for anyone else who looks at this issue:

```
> v8-debug@0.5.4 install /tmp/apm-install-dir-115113-4607-12dc9ur/node_modules/nuclide-debugger-node/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.34.0

> v8-profiler@5.3.2 install /tmp/apm-install-dir-115113-4607-12dc9ur/node_modules/nuclide-debugger-node/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.34.0
```

```
npm WARN deprecated babel-core@5.8.21: Babel 5 is no longer being maintained. Upgrade to Babel 6.
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.34.0
node-pre-gyp ERR! stack     at get_runtime_abi (/tmp/apm-install-dir-115113-4607-12dc9ur/node_modules/nuclide-debugger-node/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/versioning.js:156:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/tmp/apm-install-dir-115113-4607-12dc9ur/node_modules/nuclide-debugger-node/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/versioning.js:265:19)
node-pre-gyp ERR! stack     at install (/tmp/apm-install-dir-115113-4607-12dc9ur/node_modules/nuclide-debugger-node/node_modules/v8-debug/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/tmp/apm-install-dir-115113-4607-12dc9ur/node_modules/nuclide-debugger-node/node_modules/v8-debug/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/tmp/apm-install-dir-115113-4607-12dc9ur/node_modules/nuclide-debugger-node/node_modules/v8-debug/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/tmp/apm-install-dir-115113-4607-12dc9ur/node_modules/nuclide-debugger-node/node_modules/v8-debug/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:456:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:474:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:312:12)
```

**Comment by tamascsaba** [comment]
Thanks @ssorallen :)
 I trying to run: ```apm install nuclide-debugger-node```

**Comment by ssorallen** [comment]
All of the 'nuclide-*' packages have been replaced by the single 'nuclide' package as of yesterday's release of v0.111.0. Can you try installing that package, and re-open this issue if you still have problems?

http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
