### ISSUE TITLE
Failed to load the nuclide package

### ISSUE THREAD

**Issue by burakoner** [facebook/nuclide#271]
[Enter steps to reproduce below:]

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.1
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to load the nuclide package

```
At Cannot find module 'react-for-atom'

Error: Cannot find module 'react-for-atom'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/Users/burakoner/GitHub/nuclide/pkg/nuclide/health/lib/HealthPackage.js:37:20)
    at Module._compile (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Object.<anonymous> (/Users/burakoner/GitHub/nuclide/pkg/nuclide/health/lib/deserializePaneItem.js:11:22)
    at Module._compile (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at /Users/burakoner/GitHub/nuclide/lib/main.js:150:28
    at Array.forEach (native)
    at /Users/burakoner/GitHub/nuclide/lib/main.js:147:44
    at Array.forEach (native)
    at Object.<anonymous> (/Users/burakoner/GitHub/nuclide/lib/main.js:144:23)
    at Module._compile (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .js] (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/burakoner/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
nuclide, v0.0.0

# Dev
No dev packages
```

**Comment by nmote** [comment]
Can you provide some information on how you installed Nuclide? We haven't done a release with the single package yet so you must have cloned from GitHub, right? Did you follow the instructions at the [README](https://github.com/facebook/nuclide/blob/master/README.md) and run `npm install`?

**Comment by burakoner** [comment]
yes i did and it's run successfully.Thank you for your answer

**Comment by giautm** [comment]
Atom Version: 1.12.5
System: Mac OS X 10.12.1
Thrown From: nuclide package, v0.184.0

**Stack Trace**

Failed to load the nuclide package
```
Cannot find module '../pkg/nuclide-remote-connection/lib/service-manager'
Hide Stack Trace
Error: Cannot find module '../pkg/nuclide-remote-connection/lib/service-manager'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at _load_serviceManager (/Users/admin/.atom/packages/nuclide/lib/main.js:42:28)
    at Object.<anonymous> (/Users/admin/.atom/packages/nuclide/lib/main.js:110:25)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:741:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:118:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:466:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:410:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:405:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:772:28
```

**Comment by javymarmol** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.209.0


### Stack Trace

Failed to load the nuclide package

```
At Problem reading log4js config { appenders: [ { type: 'stdout' } ], replaceConsole: false }. Error was "Cannot find module 'stdout'" (Error: Cannot find module 'stdout'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\hmarm\AppData\Local\atom\app-1.15.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\hmarm\AppData\Local\atom\app-1.15.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\hmarm\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at requireAppender (C:\Users\hmarm\.atom\packages\nuclide\node_modules\log4js\lib\log4js.js:419:22)
    at loadAppender (C:\Users\hmarm\.atom\packages\nuclide\node_modules\log4js\lib\log4js.js:435:38)
    at C:\Users\hmarm\.atom\packages\nuclide\node_modules\log4js\lib\log4js.js:255:7
    at Array.forEach (native)
    at configureAppenders (C:\Users\hmarm\.atom\packages\nuclide\node_modules\log4js\lib\log4js.js:254:18)
    at configureOnceOff (C:\Users\hmarm\.atom\packages\nuclide\node_modules\log4js\lib\log4js.js:315:7)
    at configure (C:\Users\hmarm\.atom\packages\nuclide\node_modules\log4js\lib\log4js.js:376:3)
    at Object.<anonymous> (C:\Users\hmarm\.atom\packages\nuclide\node_modules\log4js\lib\log4js.js:514:1)
    at Module._compile (C:\Users\hmarm\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\hmarm\AppData\Local\atom\app-1.15.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\hmarm\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\hmarm\.atom\packages\nuclide\lib\preload-dependencies.js:26:1)
    at Module._compile (C:\Users\hmarm\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\hmarm\AppData\Local\atom\app-1.15.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\hmarm\AppData\Local\atom\app-1.15.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\hmarm\.atom\packages\nuclide\lib\main.js:11:1))

Error: Problem reading log4js config { appenders: [ { type: 'stdout' } ], replaceConsole: false }. Error was "Cannot find module 'stdout'" (Error: Cannot find module 'stdout'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at requireAppender (/packages/nuclide/node_modules/log4js/lib/log4js.js:419:22)
    at loadAppender (/packages/nuclide/node_modules/log4js/lib/log4js.js:435:38)
    at /packages/nuclide/node_modules/log4js/lib/log4js.js:255:7
    at Array.forEach (native)
    at configureAppenders (/packages/nuclide/node_modules/log4js/lib/log4js.js:254:18)
    at configureOnceOff (/packages/nuclide/node_modules/log4js/lib/log4js.js:315:7)
    at configure (/packages/nuclide/node_modules/log4js/lib/log4js.js:376:3)
    at /packages/nuclide/node_modules/log4js/lib/log4js.js:514:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/nuclide/lib/preload-dependencies.js:26:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/nuclide/lib/main.js:11:1))
    at configureOnceOff (/packages/nuclide/node_modules/log4js/lib/log4js.js:321:13)
    at configure (/packages/nuclide/node_modules/log4js/lib/log4js.js:376:3)
    at /packages/nuclide/node_modules/log4js/lib/log4js.js:514:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/nuclide/lib/preload-dependencies.js:26:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/nuclide/lib/main.js:11:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/nuclide/lib/main-entry.js:29:18)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
```

### Commands

```
```

### Non-Core Packages

```
nuclide 0.209.0 
```
