### ISSUE TITLE
Failed to activate the nuclide-hg-repository package

### ISSUE THREAD

**Issue by prasannamuley** [facebook/nuclide#274]
[Enter steps to reproduce below:]

1. Followed Nuclide under a single package doc
2. After starting Atom first time, have this issue.

**Atom Version**: 1.3.1
**System**: Microsoft Windows 10 Home
**Thrown From**: [nuclide-hg-repository](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to activate the nuclide-hg-repository package

```
At Invalid regular expression: /\/: \ at end of pattern

SyntaxError: Invalid regular expression: /\/: \ at end of pattern
  at new RegExp (native)
  at Object.<anonymous> (E:\Projects\nuclide\pkg\nuclide\hg-repository-client\lib\utils.js:18:22)
  at Module._compile (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:92:30)
  at Object.defineProperty.value [as .js] (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
  at Object.<anonymous> (E:\Projects\nuclide\pkg\nuclide\hg-repository-client\lib\HgRepositoryClient.js:29:14)
  at Module._compile (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:92:30)
  at Object.defineProperty.value [as .js] (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
  at Object.<anonymous> (E:\Projects\nuclide\pkg\nuclide\hg-repository-client\lib\main.js:11:27)
  at Module._compile (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:92:30)
  at Object.defineProperty.value [as .js] (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
  at Object.<anonymous> (E:\Projects\nuclide\pkg\nuclide\hg-repository\lib\HgRepositoryProvider.js:27:17)
  at Module._compile (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:92:30)
  at Object.defineProperty.value [as .js] (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\compile-cache.js:208:21)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\native-compile-cache.js:41:21)
  at Object.createHgRepositoryProvider (E:\Projects\nuclide\pkg\nuclide\hg-repository\lib\main.js:18:20)
  at Package.module.exports.Package.activateServices (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:327:69)
  at Package.module.exports.Package.activateNow (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:173:16)
  at C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:150:32
  at Package.module.exports.Package.measure (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:92:15)
  at C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:143:26
  at Package.module.exports.Package.activate (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\package.js:140:34)
  at E:\Projects\nuclide\lib\main.js:189:33
  at C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\config.js:624:20
  at Emitter.module.exports.Emitter.emit (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at Config.module.exports.Config.emitChangeEvent (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\config.js:809:29)
  at Config.module.exports.Config.setRawValue (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\config.js:601:19)
  at Config.module.exports.Config.set (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\src\config.js:227:14)
  at SettingsPanel.module.exports.SettingsPanel.set (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:196:28)
  at setNewValue (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:138:28)
  at HTMLInputElement.<anonymous> (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\settings-view\lib\settings-panel.js:144:22)
  at HTMLInputElement.jQuery.event.dispatch (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLInputElement.elemData.handle (C:\Users\prasa\AppData\Local\atom\app-1.3.1\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.0.0

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
`path.sep` in Windows is '\', which must be escaped to be a literal backslash in a regular expression. Thanks for the bug report.

**Comment by huafu** [comment]
same on `xubuntu 14.04 32bit`, tried with the webup8 PPA and from source to install atom (fresh install, cleaned .atom each try)

**Comment by wendkont** [comment]
How to fix this error

**Comment by mostafaeweda** [comment]
Proper windows support, refer to #321
