### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by jacob-israel-turner** [facebook/nuclide#279]
I just installed from Master yesterday.  On load, and when trying to launch the fuzzy finder (⌘+T), I get this error.  Following is the error report Atom generated.

**Atom Version**: 1.3.1
**System**: Mac OS X 10.11.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Uncaught SyntaxError: Unexpected identifier

```
At /Users/jacob/Applications/nuclide/pkg/nuclide/quick-open/lib/QuickSelectionActions.js:24

SyntaxError: Unexpected identifier
  at Activation.toggleOmniSearchProvider (/Users/jacob/Applications/nuclide/pkg/nuclide/quick-open/lib/main.js:196:42)
  at atom-workspace.nuclideQuickOpenFindAnythingViaOmniSearch (/Users/jacob/Applications/nuclide/pkg/nuclide/quick-open/lib/main.js:291:25)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -5:54.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:53.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:51.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:00.5.0 core:close (atom-text-editor.editor.is-focused)
     -1:28.7.0 settings-view:open (div.nuclide-file-tree.focusable-panel.tree-view)
     -1:18.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:07.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:06.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.5.0 project-manager:list-projects (ul.list-inline.tab-bar.inset-panel)
     -0:16.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:16.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:13.8.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:09.5.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
     -0:09.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:09.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:06.8.0 nuclide-quick-open:find-anything-via-omni-search (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "remoteProjectsConfig": [],
    "nuclide-home": {
      "showHome": false
    }
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.0
linter, v1.11.3
linter-eslint, v5.2.6
nuclide, v0.0.0
project-manager, v2.6.5

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
`hyperclick` is bundled with the 'nuclide' package. Can you try uninstalling that? It seems unrelated, but you have it installed as well.

**Comment by jacob-israel-turner** [comment]
Huh, that seemed to fix it.

I never manually installed `hyperclick`.  I installed `nuclide` a while ago when it was still broken into a bunch of packages.  I uninstalled all `nuclide` packages yesterday and installed from master yesterday, according to the README.  Would `hyperclick` have been residual from my first install?

**Comment by ssorallen** [comment]
@jacob-israel-turner Yes, `nuclide-installer`, the previous way of installing the Nuclide suite of features, installed the 'hyperclick' package for you. The Hyperclick functionality is now bundled in the 'nuclide' package.

**Comment by mostafaeweda** [comment]
Now we can close this with our latest UP release, see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
