### ISSUE TITLE
Uncaught TypeError: inst.render is not a function

### ISSUE THREAD

**Issue by eklavya** [facebook/nuclide#289]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Uncaught TypeError: inst.render is not a function

```
At /Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:775

TypeError: inst.render is not a function
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:775:34)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:801:14)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:235:30)
  at Object.ReactReconciler.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactReconciler.js:38:35)
  at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactMultiChild.js:192:44)
  at ReactDOMComponent.Mixin._createContentMarkup (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactDOMComponent.js:287:32)
  at ReactDOMComponent.Mixin.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactDOMComponent.js:197:12)
  at Object.ReactReconciler.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactReconciler.js:38:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactCompositeComponent.js:245:34)
  at Object.ReactReconciler.mountComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactReconciler.js:38:35)
  at mountComponentIntoNode (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactMount.js:248:32)
  at ReactReconcileTransaction.Mixin.perform (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/Transaction.js:134:20)
  at batchedMountComponentIntoNode (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactMount.js:269:15)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/Transaction.js:134:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
  at Object.batchedUpdates (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactUpdates.js:110:20)
  at Object.ReactMount._renderNewRootComponent (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactMount.js:404:18)
  at Object.ReactMount.render (/Users/eklavya/Documents/nuclide/pkg/nuclide/health/node_modules/react-for-atom/node_modules/react/lib/ReactMount.js:493:32)
  at createComponentItem (/Users/eklavya/Documents/nuclide/pkg/nuclide/gadgets/lib/createComponentItem.js:34:52)
  at Commands.createPaneItem (/Users/eklavya/Documents/nuclide/pkg/nuclide/gadgets/lib/Commands.js:157:55)
  at Commands.showGadget (/Users/eklavya/Documents/nuclide/pkg/nuclide/gadgets/lib/Commands.js:339:28)
  at GadgetsService.showGadget (/Users/eklavya/Documents/nuclide/pkg/nuclide/gadgets/lib/GadgetsService.js:42:22)
  at considerDisplayingHome (/Users/eklavya/Documents/nuclide/pkg/nuclide/home/lib/main.js:45:16)
  at Object.consumeGadgetsService (/Users/eklavya/Documents/nuclide/pkg/nuclide/home/lib/main.js:63:3)
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
  at doNTCallback0 (node.js:419:9)
  at process._tickDomainCallback (node.js:389:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": false,
    "disabledPackages": [
      "ide-flow",
      "tree-view"
    ]
  },
  "nuclide": {}
}
```

### Installed Packages

```coffee
# User
linter, v1.11.3
linter-flow-plus, v3.1.0
nuclide, v0.0.0

# Dev
No dev packages
```

**Comment by matthewwithanm** [comment]
Hi @eklavya! Sorry I missed this. /:

Are you still experiencing this issue? Also what were you doing when you saw it? Is it reproducible? Thanks!

**Comment by eklavya** [comment]
I am on the released version now, and it doesn't occur anymore, thanks :)

**Comment by matthewwithanm** [comment]
Thanks for getting back to me so quick 😊
