### ISSUE TITLE
Failed to activate the nuclide-blame-provider-hg package

### ISSUE THREAD

**Issue by jfkz** [facebook/nuclide#293]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [nuclide-blame-provider-hg](https://github.com/facebooknuclideapm/nuclide-blame-provider-hg) package, v0.0.35

### Stack Trace

Failed to activate the nuclide-blame-provider-hg package

```
At Cannot find module 'nuclide-commons'

Error: Cannot find module 'nuclide-commons'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Mike\.atom\packages\nuclide-blame-provider-hg\node_modules\nuclide-hg-git-bridge\lib\repositoryForPath.js:1:102)
    at Module._compile (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.get [as repositoryForPath] (C:\Users\Mike\.atom\packages\nuclide-blame-provider-hg\node_modules\nuclide-hg-git-bridge\lib\main.js:20:14)
    at Object.<anonymous> (C:\Users\Mike\.atom\packages\nuclide-blame-provider-hg\lib\common.js:16:33)
    at Module._compile (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Mike\.atom\packages\nuclide-blame-provider-hg\lib\HgBlameProvider.js:40:15)
    at Module._compile (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.provideHgBlameProvider (C:\Users\Mike\.atom\packages\nuclide-blame-provider-hg\lib\main.js:20:23)
    at Package.module.exports.Package.activateServices (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:327:69)
    at Package.module.exports.Package.activateNow (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:173:16)
    at C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:517:21)
    at C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\atom-environment.js:686:21)
    at module.exports (C:\Users\Mike\AppData\Local\atom\app-1.3.2\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/Mike/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/Mike/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-yii2, v0.4.0
hyperclick, v0.0.35
nuclide-arcanist, v0.0.35
nuclide-blame, v0.0.35
nuclide-blame-provider-hg, v0.0.35
nuclide-blame-ui, v0.0.35
nuclide-buck-files, v0.0.35
nuclide-busy-signal, v0.0.35
nuclide-clang-atom, v0.0.35
nuclide-code-format, v0.0.35
nuclide-code-highlight, v0.0.35
nuclide-debugger-atom, v0.0.35
nuclide-debugger-hhvm, v0.0.35
nuclide-debugger-lldb, v0.0.35
nuclide-diagnostics-store, v0.0.35
nuclide-diagnostics-ui, v0.0.35
nuclide-diff-view, v0.0.35
nuclide-file-tree, v0.0.35
nuclide-file-watcher, v0.0.35
nuclide-find-references, v0.0.35
nuclide-flow, v0.0.35
nuclide-fuzzy-filename-provider, v0.0.35
nuclide-hack, v0.0.35
nuclide-hack-symbol-provider, v0.0.35
nuclide-health, v0.0.35
nuclide-hg-repository, v0.0.35
nuclide-home, v0.0.35
nuclide-installer, v0.0.35
nuclide-language-hack, v0.0.35
nuclide-objc, v0.0.35
nuclide-ocaml, v0.0.35
nuclide-open-filenames-provider, v0.0.35
nuclide-quick-open, v0.0.35
nuclide-recent-files-provider, v0.0.35
nuclide-recent-files-service, v0.0.35
nuclide-remote-projects, v0.0.35
nuclide-test-runner, v0.0.35
nuclide-toolbar, v0.0.35
nuclide-type-hint, v0.0.35
nuclide-url-hyperclick, v0.0.35
remote-sync, v3.5.0
tidy-markdown, v1.0.0
tool-bar, v0.1.9

# Dev
No dev packages
```

**Comment by jfkz** [comment]
Same with #274

**Comment by Kesarr** [comment]
It's same with #253, not #274

**Comment by mostafaeweda** [comment]
All installation issues should have been fixed with our UP release see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
