### ISSUE TITLE
Remote server error  "EACESS"

### ISSUE THREAD

**Issue by GlobalHelp** [facebook/nuclide#300]
Hi.
I'm on ubuntu 14.04 TLS,EC2.
My node version is v0.12.9.
I installed nodejs like this : (Recommendation from [Remote sever does not start](https://github.com/facebook/nuclide/issues/99) )
> curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
> sudo apt-get install -y nodejs

When i run **$ nuclide-start-server** i got this error in my log file:
```
Error: EACCES, permission denied '/usr/lib/node_modules/nuclide-server/node_modules/nuclide-node-transpiler/babel-cache/ca1aec9364c151717eef0c412c10b0b0497bdebc/d8590274f613cb975ceb059534b5034005fdce6c'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at createOrFetchFromCache (/usr/lib/node_modules/nuclide-server/node_modules/nuclide-node-transpiler/lib/babel-cache.js:79:15)
    at Object.loadFile [as .js] (/usr/lib/node_modules/nuclide-server/node_modules/nuclide-node-transpiler/lib/transpile.js:30:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/lib/node_modules/nuclide-server/lib/serviceframework/ServerComponent.js:70:27
```

And this in my terminal : 
```
{"workspace": null, "ca": "-----BEGIN CERTIFICATE-----BLABLA-----END CERTIFICATE-----\n", "hostname": "HOSTNAME", "pid": "8212", "cert": "-----BEGIN CERTIFICATE-----BLABLA-----END CERTIFICATE-----\n", "version": "104", "key": "-----BEGIN RSA PRIVATE KEY-----BLABLA-----END RSA PRIVATE KEY-----\n", "port": 9090}
The log file can be found at /tmp/nuclide-ubuntu-logs/server-start/nuclide.nohup.out.
```

**Comment by get-trucked** [comment]
I suspect its npm permissions as root usually owns this dir on Ubuntu at least, and im assuming that root is not starting the nuclide server.

See, https://github.com/facebook/nuclide/issues/433#issuecomment-222418574

And depending which step you choose to fix your permissions this may be useful. https://github.com/facebook/nuclide/issues/522
