### ISSUE TITLE
Failed to activate the nuclide package

### ISSUE THREAD

**Issue by ppzhou1984** [facebook/nuclide#307]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Mac OS X 10.11.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to activate the nuclide package

```
At Nuclide features emitter has been disposed

Error: Nuclide features emitter has been disposed
  at Object.didLoadInitialFeatures (/Users/cen/Documents/working/nuclide/lib/nuclideFeatures.js:29:13)
  at Object.activate (/Users/cen/Documents/working/nuclide/lib/main.js:202:21)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:333:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:624:20
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:809:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:601:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:379:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:162:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  2x -1:24.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -1:18.7.0 core:undo (atom-text-editor.editor.is-focused)
  2x -1:17.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:05.8.0 core:cut (atom-text-editor.editor.is-focused)
  2x -1:04.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:56.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:52.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:48.4.0 core:undo (atom-text-editor.editor.is-focused)
  3x -0:47.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:44.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:41.4.0 editor:newline (atom-text-editor.editor.is-focused)
 39x -0:39 core:undo (atom-text-editor.editor.is-focused)
     -0:32.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:28.5.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:13.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:12.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view",
      "language-javascript"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-arcanist": {},
    "nuclide-buck-files": {},
    "nuclide-debugger-hhvm": {},
    "nuclide-flow": {
      "diagnosticsOnFly": true,
      "enableStructuredTypeHints": true
    },
    "nuclide-format-js": {
      "reprint": true
    },
    "nuclide-health": {},
    "nuclide-ocaml": {},
    "nuclide-file-tree": {
      "revealFileOnSwitch": true
    }
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.0.0

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
When did you see this exception?

Were you working from Nuclide source or from the 'nuclide' package?

**Comment by nmote** [comment]
Only one report, no repro steps, and happened quite a while ago. Closing.
