### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

### ISSUE THREAD

**Issue by eklavya** [facebook/nuclide#324]
[Enter steps to reproduce below:]
1. Try to create a new file in the sidebar.

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.111.0
### Stack Trace

Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:259

TypeError: Cannot read property 'hiddenInputComponent' of null
  at atom-text-editor.TextEditorElement.blurred (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:259:51)
  at TextEditorComponent.module.exports.TextEditorComponent.focused (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:424:55)
  at atom-text-editor.TextEditorElement.focused (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:253:55)
  at AtomInput.focus (/Users/eklavya/.atom/packages/nuclide/pkg/nuclide/ui/atom-input/lib/AtomInput.js:168:36)
  at FileDialogComponent.componentDidMount (/Users/eklavya/.atom/packages/nuclide/pkg/nuclide/file-tree/components/FileDialogComponent.js:61:13)
  at r.a.notifyAll (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:7127)
  at r.f.close (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:15:4173)
  at r.o.closeAll (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:2085)
  at r.o.perform (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:1531)
  at m (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:22538)
  at r.o.perform (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:1448)
  at Object.d.batchedUpdates (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:8520)
  at Object.a [as batchedUpdates] (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:15:14032)
  at Object.X._renderNewRootComponent (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:23933)
  at Object.X._renderSubtreeIntoContainer (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:24480)
  at Object.X.render (/Users/eklavya/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:24696)
  at Object._openDialog (/Users/eklavya/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileSystemActions.js:258:49)
  at Object._openAddDialog (/Users/eklavya/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileSystemActions.js:238:10)
  at Object.openAddFileDialog (/Users/eklavya/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileSystemActions.js:87:10)
  at HTMLDivElement.nuclideFileTreeAddFile (/Users/eklavya/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeController.js:127:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:172:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```
### Commands

```
     -0:01.5.0 nuclide-file-tree:add-file (div.nuclide-file-tree.focusable-panel.tree-view)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tree-view",
      "linter"
    ],
    "followSymlinks": false,
    "themes": [
      "spacegray-dark-ui",
      "base16-ocean-dark-spacegray"
    ]
  },
  "nuclide": {
    "nuclide-arcanist": {},
    "nuclide-buck-files": {},
    "nuclide-debugger-hhvm": {},
    "nuclide-diagnostics-ui": {
      "enableAutofix": true
    },
    "nuclide-file-tree": {
      "revealFileOnSwitch": true
    },
    "nuclide-flow": {
      "diagnosticsOnFly": true,
      "enableStructuredTypeHints": true,
      "pathToFlow": "/usr/local/bin/flow"
    },
    "nuclide-format-js": {
      "reprint": true
    },
    "nuclide-health": {
      "showCpu": true,
      "showHeap": true,
      "showMemory": true,
      "viewTimeout": 5
    },
    "nuclide-ocaml": {}
  }
}
```
### Installed Packages

``` coffee
# User
base16-ocean-dark-spacegray, v0.12.0
nuclide, v0.111.0
spacegray-dark-ui, v0.12.0

# Dev
No dev packages
```

**Comment by johnislarry** [comment]
Hey, currently we only officially support Atom 1.1.0 with Nuclide, can you try on that version and see if it works?  That said, maybe the fix for this is simple.  Assigning to @ssorallen -- the file tree master

**Comment by mostafaeweda** [comment]
Please upgrade to the latest Nuclide and see if that's fixed
