### ISSUE TITLE
Uncaught TypeError: this.stopTests is not a function

### ISSUE THREAD

**Issue by shafiq702** [facebook/nuclide#327]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.111.0

### Stack Trace

Uncaught TypeError: this.stopTests is not a function

```
At /Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14

TypeError: this.stopTests is not a function
  at hidePanel (/Users/Shafiq/.atom/packages/nuclide/pkg/nuclide/test-runner/lib/TestRunnerController.js:107:12)
  at Object.r (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:14204)
  at i (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:21753)
  at Object.u [as executeDispatchesInOrder] (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:21964)
  at p (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:18317)
  at f (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:18443)
  at Array.forEach (native)
  at r (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:4464)
  at Object.v.processEventQueue (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:19563)
  at r (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:14468)
  at Object.a.handleTopLevel [as _handleTopLevel] (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:14573)
  at i (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:15035)
  at a (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:14849)
  at r.o.perform (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:1448)
  at Object.d.batchedUpdates (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:8520)
  at Object.a [as batchedUpdates] (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:15:14032)
  at g.dispatchEvent (/Users/Shafiq/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:15926)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.12.2
nuclide, v0.111.0
seti-icons, v0.4.5

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
Can you give more info about how this happened? I haven't been able to reproduce this.

**Comment by rricard** [comment]
I got it too:

## Context

- No registered test runner (Followup question: where do I get something to test jest/mocha btw ?)

## How to reproduce

- Open the test runner (wherever you want)
- Close the Atom window after closing each tab
- Reopen the window
- Try to close the test runner
- => TypeError

**Comment by jeduan** [comment]
+1 Having this problem too, and can't find how to run mocha tests, either

**Comment by matthewwithanm** [comment]
I can't repro, but I think I know what might be causing it…fix coming!
