### ISSUE TITLE
Remote Development: "nuclide_server_manager.py: error: no such option: --common-name"

### ISSUE THREAD

**Issue by dhermanson** [facebook/nuclide#334]
Hi,

My host machine is a Mac running El Capitan. I'm trying to do remote development using a Ubuntu 14.04 Laravel/Homestead vagrant virtual machine. When I try to add a remote project folder I get an error.

```
[2016-01-26T04:13:53.755Z] [ERROR] nuclide - SshHandshake failed: UNKNOWN, Remote shell execution failed Error: Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-25-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Tue Jan 26 04:10:52 2016 from 192.168.10.1

nuclide-start-server --workspace=/home/vagrant/myriad-dashboard --common-name=192.168.10.10 --json-output-file=/tmp/nuclide-sshhandshake-0.64688112703152 -t 60
exit
exit
vagrant@myriad-dashboard:~$ nuclide-start-server --workspace=/home/vagrant/my
< nuclide-start-server --workspace=/home/vagrant/myr                         iad-dashboard --common-na

<rkspace=/home/vagrant/myriad-dashboard --common-nam                         e=192.168.10.10 --json-ou

<ad-dashboard --common-name=192.168.10.10 --json-out                         put-file=/tmp/nuclide-ssh

<=192.168.10.10 --json-output-file=/tmp/nuclide-sshh                         andshake-0.64688112703152

<ut-file=/tmp/nuclide-sshhandshake-0.64688112703152                          -t 60
Usage: nuclide_server_manager.py [options]

nuclide_server_manager.py: error: no such option: --common-name
vagrant@myriad-dashboard:~$ exit
logout



  at Channel.<anonymous> (/Users/derick/.repositories/github/facebook/nuclide/pkg/nuclide/remote-connection/lib/SshHandshake.js:322:93)
  at emitOne (events.js:77:13)
  at Channel.emit (events.js:169:7)
  at SSH2Stream.<anonymous> (/Users/derick/.repositories/github/facebook/nuclide/node_modules/ssh2/lib/Channel.js:126:14)
  at SSH2Stream.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at SSH2Stream.emit (events.js:166:7)
  at parsePacket (/Users/derick/.repositories/github/facebook/nuclide/node_modules/ssh2-streams/lib/ssh.js:3435:10)
  at SSH2Stream._transform (/Users/derick/.repositories/github/facebook/nuclide/node_modules/ssh2-streams/lib/ssh.js:552:13)
  at SSH2Stream.Transform._read (_stream_transform.js:167:10)
  at SSH2Stream._read (/Users/derick/.repositories/github/facebook/nuclide/node_modules/ssh2-streams/lib/ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:292:12)
  at writeOrBuffer (_stream_writable.js:278:5)
  at SSH2Stream.Writable.write (_stream_writable.js:207:11)
  at Socket.ondata (_stream_readable.js:525:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
```

**Comment by N3X15** [comment]
Why was this closed?  How did you fix it?

**Comment by jamesbeedy** [comment]
I'm hitting this same thing.

**Comment by jamesbeedy** [comment]
How did you fix??

**Comment by N3X15** [comment]
I ended up fixing this by compiling nodejs from source and removing Debian's version, since Debian's repo has higher priority than the nodesource repo.

**Comment by 1N50MN14** [comment]
Hey guys, I have an open issue about this #344 - I eventually managed to get this working by manually cloning the repo and installing the server and client separately. In other words, follow this https://github.com/facebook/nuclide/tree/master/pkg/nuclide/server to install the server.
