### ISSUE TITLE
Failed to activate the nuclide-installer package

### ISSUE THREAD

**Issue by jameliu** [facebook/nuclide#336]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.2
**Thrown From**: [nuclide-installer](https://github.com/facebook/nuclide) package, v1.0.0
### Stack Trace

Failed to activate the nuclide-installer package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.activate (/Users/liusihai/.atom/packages/nuclide-installer/index.js:3:5)
    at Package.module.exports.Package.activateNow (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Users/liusihai/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
highlight-selected, v0.11.1
nuclide-installer, v1.0.0

# Dev
No dev packages
```

**Comment by zertosh** [comment]
That package is deprecated, and the error likely happened because github was down earlier. Please remove `nuclide-installer` and use [nuclide](https://atom.io/packages/nuclide) instead.
