### ISSUE TITLE
Uncaught Error: Repository has been destroyed

### ISSUE THREAD

**Issue by antihate** [facebook/nuclide#337]
Opening Atom throw this error, doesn't occur if I disable the nuclide package.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.11.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.114.0

### Stack Trace

Uncaught Error: Repository has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:358

Error: Repository has been destroyed
    at GitRepository.module.exports.GitRepository.getRepo (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:358:15)
    at GitRepository.module.exports.GitRepository.getWorkingDirectory (/Applications/Atom.app/Contents/Resources/app.asar/src/git-repository.js:148:19)
    at repositoryContainsPath (/Users/antihate/.atom/packages/nuclide/pkg/nuclide/hg-git-bridge/lib/repositoryContainsPath.js:24:41)
    at /Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:756:56
    at /Users/antihate/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:4342:23
    at /Users/antihate/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:3675:58
    at /Users/antihate/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:1940:16
    at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (/Users/antihate/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:2289:11)
    at src_Map__Map.__iterate (/Users/antihate/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:1938:32)
    at src_Set__Set.__iterate (/Users/antihate/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:3675:24)
    at src_Set__Set.mixin.findEntry (/Users/antihate/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:4341:12)
    at src_Set__Set.mixin.find (/Users/antihate/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:4335:24)
    at FileTreeStore._repositoryForPath (/Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:755:37)
    at FileTreeStore.memoized [as _repositoryForPath] (/Users/antihate/.atom/packages/nuclide/node_modules/lodash.memoize/index.js:150:23)
    at FileTreeStore._shouldHidePath (/Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:1034:64)
    at /Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:1020:25
    at Array.filter (native)
    at FileTreeStore._omitHiddenPaths (/Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:1019:23)
    at FileTreeStore.getChildKeys (/Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:432:19)
    at FileTreeNode.getChildNodes (/Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeNode.js:76:35)
    at RootNodeComponent._renderNode (/Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/components/RootNodeComponent.js:75:14)
    at RootNodeComponent.render (/Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/components/RootNodeComponent.js:40:14)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:587:34)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:607:32)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:560:36)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
    at Object.ReactReconciler.receiveComponent (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
    at Object.ReactChildReconciler.updateChildren (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
    at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
    at ReactDOMComponent.Mixin._updateDOMChildren (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
    at ReactDOMComponent.Mixin.updateComponent (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
    at ReactDOMComponent.Mixin.receiveComponent (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
    at Object.ReactReconciler.receiveComponent (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
    at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
    at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
    at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
    at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:421:12)
    at Object.ReactReconciler.performUpdateIfNecessary (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:102:22)
    at runBatchedUpdates (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:129:21)
    at ReactReconcileTransaction.Mixin.perform (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
    at ReactUpdatesFlushTransaction.assign.perform (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:86:38)
    at Object.flushBatchedUpdates (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:147:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:202:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:149:16)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.enqueueUpdate (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:176:22)
    at enqueueUpdate (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactUpdateQueue.js:24:16)
    at Object.ReactUpdateQueue.enqueueForceUpdate (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactUpdateQueue.js:143:5)
    at FileTree.ReactComponent.forceUpdate (/Users/antihate/.atom/packages/nuclide/node_modules/react/lib/ReactComponent.js:86:16)
    at /Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/components/FileTree.js:97:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Immediate._onImmediate (/Users/antihate/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:290:29)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.Object.defineProperty.get [as loadSettings] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:160:27)
    at Object.windowState (/Applications/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:17:39)
    at Object.stringify (native)
    at exports.setWindowLoadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/window-load-settings-helpers.js:27:52)
    at ApplicationDelegate.module.exports.ApplicationDelegate.setRepresentedDirectoryPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:172:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:844:44
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.setPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:217:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/project.js:356:19
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:351:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:500:19)
    at Object.activate (/Users/antihate/.atom/packages/nuclide/lib/main.js:215:31)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:336:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:623:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:808:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:600:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:165:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.jQuery.event.add.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "/Users/antihate/planespy"
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-arcanist": {},
    "nuclide-buck-files": {},
    "nuclide-debugger-hhvm": {},
    "nuclide-flow": {},
    "nuclide-format-js": {},
    "nuclide-health": {},
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-ocaml": {},
    "nuclide-output": {}
  }
}
```

### Installed Packages

```coffee
# User
haskell-grammar, v0.4.0
highlight-selected, v0.11.1
language-babel, v2.14.1
language-ini, v1.14.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
nuclide, v0.114.0
tool-bar, v0.1.11

# Dev
No dev packages
```

**Comment by ermik** [comment]
Moved repos and then tried removing project folders from sidebar — got me here.
