### ISSUE TITLE
can't intall aws is blocked

### ISSUE THREAD

**Issue by bunnyblue** [facebook/nuclide#338]
```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp http GET http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.5/node-v0.34.5.tar.gz
gyp http 200 http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.5/node-v0.34.5.tar.gz
gyp http GET http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v0.34.5/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at TCP.onread (net.js:559:19)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.34.5" "--dist-url=http://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/user/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

**Comment by zertosh** [comment]
Next weeks release won't have any more binary dependencies so this won't be an issue.

**Comment by bunnyblue** [comment]
great
