### ISSUE TITLE
Failed to save remote file

### ISSUE THREAD

**Issue by nmalcolm** [facebook/nuclide#341]
Upon hitting `CTRL` + `S`, Atom throws the following error notification:

```
Failed to save remote file: ENOENT: no such file or directory, lstat '/home/nathan/nuclide:'
```

```
[2016-01-30T18:50:49.191Z] [FATAL] nuclide - Failed to save remote file. Error: ENOENT: no such file or directory, lstat '/home/nathan/nuclide:'
  at Error (native)
  at fs.lstatSync (fs.js:844:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
  at Object.realpathSync (fs.js:1454:21)
  at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
  at /home/nathan/.atom/packages/remote-sync/index.coffee:105:26
  at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at NuclideTextBuffer.<anonymous> (/home/nathan/.atom/packages/nuclide/pkg/nuclide/remote-projects/lib/NuclideTextBuffer.js:91:22)
  at [object Generator].next (native)
  at step (/home/nathan/.atom/packages/nuclide/pkg/nuclide/remote-projects/lib/NuclideTextBuffer.js:15:273)
```

OS: Debian 8
Atom: 1.4.0
Nuclide: 0.114.0

Interestingly, the file is uploaded successfully anyway. However it is incredibly annoying. :-)

**Comment by shushz** [comment]
It seems the exception is raised by the `remote-sync` package, not Nuclide. Could you try disabling it?

**Comment by nmalcolm** [comment]
Aha! Didn't think to check the stacktrace as I could've sworn I already uninstalled it... Thanks!
