### ISSUE TITLE
Uncaught TypeError: Invalid Point: (30, NaN)

### ISSUE THREAD

**Issue by noomz** [facebook/nuclide#347]
[Enter steps to reproduce below:]
1. Restart for updating Atom
2. Try to close a tab, some tab clash, some doesn't.

**Atom Version**: 1.4.2
**System**: Mac OS X 10.11.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.114.0
### Stack Trace

Uncaught TypeError: Invalid Point: (30, NaN)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:37

TypeError: Invalid Point: (30, NaN)
  at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1015:13)
  at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1003:20)
  at MarkerLayer.module.exports.MarkerLayer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:46)
  at TextEditorMarkerLayer.module.exports.TextEditorMarkerLayer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker-layer.js:78:52)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1100:38)
  at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1339:59)
  at applyUpdateToEditor (/Users/siriwat/.atom/packages/nuclide/pkg/nuclide/diagnostics/ui/lib/gutter.js:115:32)
  at callback (/Users/siriwat/.atom/packages/nuclide/pkg/nuclide/diagnostics/ui/lib/main.js:137:9)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at DiagnosticStore._emitFileMessages (/Users/siriwat/.atom/packages/nuclide/pkg/nuclide/diagnostics/base/lib/DiagnosticStore.js:420:33)
  at DiagnosticStore._invalidateFileMessagesForProvider (/Users/siriwat/.atom/packages/nuclide/pkg/nuclide/diagnostics/base/lib/DiagnosticStore.js:170:14)
  at DiagnosticStore.invalidateMessages (/Users/siriwat/.atom/packages/nuclide/pkg/nuclide/diagnostics/base/lib/DiagnosticStore.js:143:14)
  at /Users/siriwat/.atom/packages/nuclide/pkg/nuclide/diagnostics/store/lib/main.js:127:13
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at DiagnosticsProviderBase.publishMessageInvalidation (/Users/siriwat/.atom/packages/nuclide/pkg/nuclide/diagnostics/provider-base/lib/DiagnosticsProviderBase.js:104:21)
  at /Users/siriwat/.atom/packages/nuclide/pkg/nuclide/arcanist/lib/ArcanistDiagnosticsProvider.js:71:31
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at PaneContainer.module.exports.PaneContainer.willDestroyPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:285:27)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:446:17)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:433:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:651:35)
  at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:690:21)
  at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:170:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```
### Commands

```
 18x -0:54.2.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "atom-ctags",
      "language-javascript-jsx",
      "ide-flow",
      "linter-flow",
      "linter-eslint",
      "vim-mode",
      "js-hyperclick",
      "minimap",
      "hyperclick",
      "tree-view",
      "linter"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "nuclide": {
    "nuclide-arcanist": {},
    "nuclide-buck-files": {},
    "nuclide-debugger-hhvm": {},
    "nuclide-flow": {},
    "nuclide-format-js": {},
    "nuclide-health": {},
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-ocaml": {}
  }
}
```
### Installed Packages

``` coffee
# User
atom-json-editor, v0.4.1
atom-ternjs, v0.13.2
atom-typescript, vundefined
autocomplete-ctags, v0.4.0
color-picker, v2.1.1
cursor-history, v0.5.9
json-schema, v0.1.15
language-babel, v2.15.2
language-javascript-better, v1.7.1
language-x86asm, v0.7.1
linter-jshint, v1.3.0
linter-jsxhint, v0.1.2
markdown-preview-plus, v2.2.2
multi-wrap-guide, v0.23.5
nuclide, v0.114.0
react, v0.14.1

# Dev
No dev packages
```

**Comment by mostafaeweda** [comment]
Please upgrade to the latest
