### ISSUE TITLE
Failed to activate the nuclide-buck-toolbar package

### ISSUE THREAD

**Issue by ryanpcmcquen** [facebook/nuclide#349]
[Enter steps to reproduce below:]

1. Upgrade `nuclide` to 0.115.0

This issue was not present on 0.114.0.

**Atom Version**: 1.4.2
**System**: Debian GNU/Linux
**Thrown From**: [nuclide-buck-toolbar](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to activate the nuclide-buck-toolbar package

```
At Cannot find module './BuckIcon'

Error: Cannot find module './BuckIcon'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/ry/.atom/packages/nuclide/pkg/nuclide/buck/toolbar/lib/Activation.js:17:17)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/home/ry/.atom/packages/nuclide/pkg/nuclide/buck/toolbar/lib/main.js:27:20)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:500:19)
    at Object.activate (/home/ry/.atom/packages/nuclide/lib/main.js:215:31)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:505:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter-jslint, v10.2.0
nuclide, v0.115.0

# Dev
No dev packages
```

**Comment by googlaev** [comment]
Error: Cannot find module './BuckIcon'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/hi/.atom/packages/nuclide/pkg/nuclide/buck/toolbar/lib/Activation.js:17:17)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)

**Comment by matthewwithanm** [comment]
Sorry, this is an issue on case-sensitive filesystems. A fix is coming!

cc @ssorallen

**Comment by ryanpcmcquen** [comment]
Thanks!

**Comment by ssorallen** [comment]
Shoot, nice catch. It's annoying this worked fine locally with no warnings, which is why I overlooked it.

**Comment by Warchant** [comment]
Same issue. Just installed atom and nuclide. 

Ubuntu 14.04.
Stack trace:

```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Ubuntu 14.04.3
**Thrown From**: [nuclide-buck-toolbar](https://github.com/facebook/nuclide) package, v0.0.0


### Stack Trace

Failed to activate the nuclide-buck-toolbar package
```
```
At Cannot find module './BuckIcon'

Error: Cannot find module './BuckIcon'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/vm/.atom/packages/nuclide/pkg/nuclide/buck/toolbar/lib/Activation.js:17:17)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.activate (/home/vm/.atom/packages/nuclide/pkg/nuclide/buck/toolbar/lib/main.js:27:20)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:500:19)
    at Object.activate (/home/vm/.atom/packages/nuclide/lib/main.js:215:31)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:505:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.115.0

# Dev
No dev packages
```

**Comment by googlaev** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: "Manjaro Linux"
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.115.0


### Stack Trace

Failed to activate the nuclide-buck-toolbar package

```
At Cannot find module './BuckIcon'

Error: Cannot find module './BuckIcon'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/hi/.atom/packages/nuclide/pkg/nuclide/buck/toolbar/lib/Activation.js:17:17)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "nuclide-arcanist": {},
    "nuclide-health": {},
    "nuclide-buck-files": {},
    "nuclide-debugger-hhvm": {},
    "nuclide-format-js": {},
    "nuclide-output": {},
    "nuclide-hack": {},
    "nuclide-ocaml": {},
    "nuclide-flow": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
emmet, v2.4.1
file-icons, v1.6.14
highlight-selected, v0.11.2
linter, v1.11.3
minimap, v4.19.0
minimap-highlight-selected, v4.3.1
nuclide, v0.115.0
script-runner, v1.8.4

# Dev
No dev packages
```

**Comment by matthewwithanm** [comment]
@googlaev We fixed the issue this afternoon. Please update to 0.115.1!
