### ISSUE TITLE
Failed to activate the nuclide-file-tree package

### ISSUE THREAD

**Issue by AdamSkaidon** [facebook/nuclide#354]
[Enter steps to reproduce below:]

1. Clicked install.
2. Left computer for thirty minutes.
3. Saw this error.

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [nuclide-file-tree](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to activate the nuclide-file-tree package

```
At Tried to unload active package 'tree-view'

Error: Tried to unload active package 'tree-view'
    at PackageManager.module.exports.PackageManager.unloadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:466:15)
    at Object.activate (/Users/Adam/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/main.js:166:21)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:500:19)
    at Object.activate (/Users/Adam/.atom/packages/nuclide/lib/main.js:215:31)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -2:17.3.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:16.8.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:15.1.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:11 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:10.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "linter-scss-lint",
      "linter-bootlint",
      "tree-view"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.7
antialiased, v0.1.0
atom-beautify, v0.28.21
atom-material-syntax, v0.3.2
atom-material-ui, v0.8.1
atom-ternjs, v0.13.2
autoclose-html, v0.20.0
autocomplete-paths, v1.0.2
caniuse, v0.9.0
codekit-commands, v1.3.2
dash, v1.6.0
emmet, v2.4.1
es-identifier-highlight, v0.2.9
file-icons, v1.6.14
imdone-atom, v1.3.25
js-hyperclick, v1.4.1
language-javascript-better, v1.7.1
language-javascript-jsx, v0.3.7
language-svg, v0.9.0
linter, v1.11.3
linter-jshint, v1.3.0
minimap, v4.19.0
minimap-pigments, v0.1.7
nav-panel, v0.0.11
neon-cursor, v1.4.0
nuclide, v0.115.1
open-in-browsers, v0.0.7
pigments, v0.23.0
svg-preview, v0.7.3
tool-bar-main, v0.0.8
wakatime, v5.0.2

# Dev
No dev packages
```

**Comment by lu-ko** [comment]
The same problem on Windows 10 Home x64. Atom version: 1.4.3

**Comment by mlapierre** [comment]
I had this problem until I upgraded Atom to 1.5.0. Now I just have a tree view that doesn't display anything.

**Comment by mlapierre** [comment]
Scratch that, it still is an issue with Atom 1.5.0:

**Atom Version**: 1.5.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [nuclide-file-tree](https://github.com/facebook/nuclide) package, v0.0.0


### Stack Trace

Failed to activate the nuclide-file-tree package

```
At Tried to unload active package 'tree-view'

Error: Tried to unload active package 'tree-view'
    at PackageManager.module.exports.PackageManager.unloadPackage (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package-manager.js:468:15)
    at Object.activate (C:\Users\mlapierre.OIT\.atom\packages\nuclide\pkg\nuclide\file-tree\lib\main.js:166:21)
    at Package.module.exports.Package.activateNow (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package-manager.js:526:21)
    at C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package-manager.js:502:19)
    at Object.activate (C:\Users\mlapierre.OIT\.atom\packages\nuclide\lib\main.js:215:31)
    at Package.module.exports.Package.activateNow (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\package-manager.js:526:21)
    at C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\buffered-process.js:213:47)
    at C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\buffered-process.js:227:18
    at Socket.<anonymous> (C:\Users\mlapierre.OIT\AppData\Local\atom\app-1.5.0\resources\app.asar\src\buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
  3x -8:03.6.0 tree-view:toggle (div.package-detail.panels-item)
     -6:09.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:08.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:45 window:toggle-dev-tools (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.13.2
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.15.3
language-ini, v1.14.0
language-ocaml, v1.1.2
language-powershell, v2.1.0
language-thrift, v1.0.2
minimap, v4.19.0
nuclide, v0.115.1
tool-bar, v0.2.0

# Dev
No dev packages
```
