### ISSUE TITLE
Failed to activate the nuclide-file-tree package

### ISSUE THREAD

**Issue by rittbys** [facebook/nuclide#361]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.2
**System**: Ubuntu 15.10
**Thrown From**: [nuclide-file-tree](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to activate the nuclide-file-tree package

```
At Tried to unload active package 'tree-view'

Error: Tried to unload active package 'tree-view'
    at PackageManager.module.exports.PackageManager.unloadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:468:15)
    at Object.activate (/home/rittbys/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/main.js:166:21)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:181:20)
    at /usr/share/atom/resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:502:19)
    at Object.activate (/home/rittbys/.atom/packages/nuclide/lib/main.js:215:31)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:181:20)
    at /usr/share/atom/resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:526:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
 15x -3:55.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:40.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 22x -2:21.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:36.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -1:09.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:07.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.116.0

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
Thanks for the report. This is addressed in #354 (see attached commit that closed it) and will be out in the next release (v0.117.0).
