### ISSUE TITLE
Uncaught TypeError: this.refs.editor.getElement is not a function

### ISSUE THREAD

**Issue by tychota** [facebook/nuclide#363]
1. ... click on open in diff view in nuclide toolbar
2. ... BAM

**Atom Version**: 1.4.0
**System**: "Sabayon Linux
**Thrown From**: [nuclide-diff-view](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Uncaught TypeError: this.refs.editor.getElement is not a function

```
At /home/tychota/.atom/packages/nuclide/pkg/nuclide/diff-view/lib/DiffViewEditorPane.js:246

TypeError: this.refs.editor.getElement is not a function
  at DiffViewEditorPane.getEditorDomElement (/home/tychota/.atom/packages/nuclide/pkg/nuclide/diff-view/lib/DiffViewEditorPane.js:246:34)
  at DiffViewEditorPane._setupDiffEditor (/home/tychota/.atom/packages/nuclide/pkg/nuclide/diff-view/lib/DiffViewEditorPane.js:75:67)
  at DiffViewEditorPane.componentDidMount (/home/tychota/.atom/packages/nuclide/pkg/nuclide/diff-view/lib/DiffViewEditorPane.js:65:12)
  at CallbackQueue.assign.notifyAll (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/CallbackQueue.js:65:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
  at ReactReconcileTransaction.Mixin.closeAll (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:202:25)
  at ReactReconcileTransaction.Mixin.perform (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:149:16)
  at batchedMountComponentIntoNode (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:282:15)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:60:7)
  at Object.batchedUpdates (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:94:20)
  at Object.ReactMount._renderNewRootComponent (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:476:18)
  at Object.ReactMount._renderSubtreeIntoContainer (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:550:32)
  at Object.ReactMount.render (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:570:23)
  at DiffViewComponent._renderEditors (/home/tychota/.atom/packages/nuclide/pkg/nuclide/diff-view/lib/DiffViewComponent.js:177:57)
  at DiffViewComponent._renderDiffView (/home/tychota/.atom/packages/nuclide/pkg/nuclide/diff-view/lib/DiffViewComponent.js:149:12)
  at DiffViewComponent.componentDidMount (/home/tychota/.atom/packages/nuclide/pkg/nuclide/diff-view/lib/DiffViewComponent.js:121:12)
  at CallbackQueue.assign.notifyAll (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/CallbackQueue.js:65:22)
  at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
  at ReactReconcileTransaction.Mixin.closeAll (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:202:25)
  at ReactReconcileTransaction.Mixin.perform (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:149:16)
  at batchedMountComponentIntoNode (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:282:15)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
  at Object.batchedUpdates (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:94:20)
  at Object.ReactMount._renderNewRootComponent (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:476:18)
  at Object.ReactMount._renderSubtreeIntoContainer (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:550:32)
  at Object.ReactMount.render (/home/tychota/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:570:23)
  at createView (/home/tychota/.atom/packages/nuclide/pkg/nuclide/diff-view/lib/main.js:55:28)
  at /home/tychota/.atom/packages/nuclide/pkg/nuclide/diff-view/lib/main.js:195:16
  at Workspace.module.exports.Workspace.openURIInPane (/usr/share/atom/resources/app.asar/src/workspace.js:460:22)
  at Workspace.module.exports.Workspace.open (/usr/share/atom/resources/app.asar/src/workspace.js:399:19)
  at atom-workspace.<anonymous> (/home/tychota/.atom/packages/nuclide/pkg/nuclide/diff-view/lib/main.js:151:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
  at module.exports._executeCallback (/home/tychota/.atom/packages/tool-bar/lib/tool-bar-button-view.coffee:69:23)
  at space-pen-button.<anonymous> (/home/tychota/.atom/packages/tool-bar/lib/tool-bar-button-view.coffee:29:7)
  at space-pen-button.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-button.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -0:02.1.0 nuclide-diff-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "tree-view"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.3.3
atom-material-ui, v0.8.1
color-picker, v2.1.1
file-icons, v1.6.14
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.15.4
language-fortran, v2.0.9
language-ini, v1.14.0
language-ocaml, v1.1.2
language-openmp, v0.2.0
language-thrift, v1.0.2
minimap, v4.19.0
nuclide, v0.116.0
pigments, v0.23.1
tool-bar, v0.2.0

# Dev
No dev packages
```

**Comment by shushz** [comment]
Can't reproduce it. Is it a local or remote development? What kind of repository? Are you using atom-material theme?
