### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by grouma** [facebook/nuclide#364]
I'm using Atom version 1.5.3 and Nuclide version 0.166.0 on Mac OS X 10.10.5. I receive the following exception when attempting to add a remote folder:

/Users/grouma/.atom/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:53

RangeError: Maximum call stack size exceeded
  at Object.isDirKey (/Users/grouma/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeHelpers.js:32:14)
  at /Users/grouma/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:709:44
  at Array.forEach (native)
  at FileTreeStore._collapseNode (/Users/grouma/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:697:19)
  at /Users/grouma/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:712:22
  at Array.forEach (native)
  at FileTreeStore._collapseNode (/Users/grouma/.atom/packages/nuclide/pkg/nuclide/file-tree/lib/FileTreeStore.js:697:19)
...

**Comment by shushz** [comment]
Can't reproduce it.
What is the remote machine OS?
Does it happen with every remote folder you're trying to mount? Are there any sym/hard links?

**Comment by grouma** [comment]
The remote machine is running Ubuntu 14.04. I haven't tried with other folders but I will shortly and report back.

**Comment by darrenkenny** [comment]
I'm also seeing this on a Solaris server with a large code-base running nuclide 1.5.4 - and a slightly modified server-side process_info.py to make it work correctly - but otherwise unmodified.

**Comment by nnquy** [comment]
Same here

**Comment by ajostergaard** [comment]
I'm seeing this error from the iOS simulator on a Mac running locally - no server or remoting at all (not even git). I guess it's unrelated but you never know unless you know. :)

Atom: 1.14.1, Nuclide: 0.205.0, MacOS: 10.11.6, Simulator: 9.3, React Native: 0.41.1.

**Comment by joncursi** [comment]
Same error here trying to debug react native:

![screen shot 2017-02-24 at 1 28 00 am](https://cloud.githubusercontent.com/assets/4974609/23292898/ce427cdc-fa30-11e6-82aa-8a12bd163395.png)
