### ISSUE TITLE
Uncaught AssertionError: Nuclide URIs must contain paths, 'null' found.

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/nuclide#367]
[Enter steps to reproduce below:]

1. Opened a project folder

**Atom Version**: 1.5.3
**System**: Ubuntu 15.10
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.116.0

### Stack Trace

Uncaught AssertionError: Nuclide URIs must contain paths, 'null' found.

```
At assert.js:89

AssertionError: Nuclide URIs must contain paths, 'null' found.
    at Object.parse (/home/ryan/.atom/packages/nuclide/pkg/nuclide/remote-uri/lib/main.js:63:27)
    at Function.getForUri (/home/ryan/.atom/packages/nuclide/pkg/nuclide/remote-connection/lib/RemoteConnection.js:619:41)
    at getKeyOfUri (/home/ryan/.atom/packages/nuclide/pkg/nuclide/hack/lib/hack.js:268:61)
    at getCachedHackLanguageForUri (/home/ryan/.atom/packages/nuclide/pkg/nuclide/hack/lib/hack.js:273:13)
    at /home/ryan/.atom/packages/nuclide/pkg/nuclide/hack/lib/main.js:39:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at ProjectManager._updateProjectPaths (/home/ryan/.atom/packages/nuclide/pkg/nuclide/atom-helpers/lib/projects.js:59:25)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Project.module.exports.Project.addPath (/usr/share/atom/resources/app.asar/src/project.js:255:29)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:869:41
    at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/application-delegate.js:30:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```

### Commands

```
  2x -1:01.2.0 window:toggle-menu-bar (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:43.6.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:28.1.0 tree-view:remove-project-folder (div.header.list-item)
     -0:09.3.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-an-old-hope-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-dark-ui",
      "an-old-hope-syntax"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```

### Installed Packages

```coffee
# User
an-old-hope-syntax, v0.5.0
color-picker, v2.1.1
minimap, v4.19.0
nuclide, v0.116.0
pigments, v0.24.1

# Dev
No dev packages
```

**Comment by RyanMitchellWilson** [comment]
Just needed a good restart I guess. Works fine now.

**Comment by furdei** [comment]
Restart didn't help me:

```
assert.js:89
Hide Stack Trace
AssertionError: Nuclide URIs must contain paths, 'null' found.
  at Object.parse (/opt/facebook/nuclide/0.130.27569066/nuclide/pkg/nuclide-remote-uri/lib/main.js:67:27)
  at Object.getParentKey (/opt/facebook/nuclide/0.130.27569066/nuclide/pkg/nuclide-file-tree/lib/FileTreeHelpers.js:63:46)
  at ensurePresentParents (/opt/facebook/nuclide/0.130.27569066/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:607:50)
  at /opt/facebook/nuclide/0.130.27569066/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:620:11
  at Array.forEach (native)
  at FileTreeStore._setVcsStatuses (/opt/facebook/nuclide/0.130.27569066/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:617:32)
  at FileTreeStore._onDispatch (/opt/facebook/nuclide/0.130.27569066/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:321:16)
  at Object.ID_6 (/opt/facebook/nuclide/0.130.27569066/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:112:20)
  at FileTreeDispatcher.Dispatcher.$Dispatcher_invokeCallback (/opt/facebook/nuclide/0.130.27569066/nuclide/node_modules/flux/lib/Dispatcher.js:220:35)
  at FileTreeDispatcher.Dispatcher.dispatch (/opt/facebook/nuclide/0.130.27569066/nuclide/node_modules/flux/lib/Dispatcher.js:195:14)
  at FileTreeActions.setVcsStatuses (/opt/facebook/nuclide/0.130.27569066/nuclide/pkg/nuclide-file-tree/lib/FileTreeActions.js:250:24)
  at FileTreeActions._onDidChangeStatusesForRepository (/opt/facebook/nuclide/0.130.27569066/nuclide/pkg/nuclide-file-tree/lib/FileTreeActions.js:470:14)
  at later (/opt/facebook/nuclide/0.130.27569066/nuclide/pkg/nuclide-commons/lib/debounce.js:35:23)
```

**Comment by shushz** [comment]
@furdei - this seems to be a different issue. This time the stack trace suggests failing to parse some of the paths after a VCS status update.

**Comment by furdei** [comment]
Submitted as a new issue #455
Thanks @shushz
