### ISSUE TITLE
Uncaught AssertionError: null == true when using move-panes

### ISSUE THREAD

**Issue by Daniel15** [facebook/nuclide#370]
I installed [move-panes](https://atom.io/packages/move-panes) and attempted to move a pane to the right (cmd-ctrl-shift-right), which resulted in this error:

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.118.23098490

### Stack Trace

Uncaught AssertionError: null == true

```
At assert.js:89

AssertionError: null == true
  at getLinesDomNode (/opt/facebook/nuclide/0.118.23098490/nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:93:33)
  at addMouseDownListener (/opt/facebook/nuclide/0.118.23098490/nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:104:9)
  at HyperclickForTextEditor._setupMouseDownListener (/opt/facebook/nuclide/0.118.23098490/nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:109:7)
  at new HyperclickForTextEditor (/opt/facebook/nuclide/0.118.23098490/nuclide/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js:68:10)
  at Hyperclick.observeTextEditor (/opt/facebook/nuclide/0.118.23098490/nuclide/pkg/nuclide/hyperclick/lib/Hyperclick.js:82:37)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:295:16
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:360:18
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:375:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:359:28
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:355:20)
  at Object.module.exports.swapEditor (/Users/danlo/.atom/packages/move-panes/lib/move-panes.coffee:40:12)
  at Object.module.exports.move (/Users/danlo/.atom/packages/move-panes/lib/move-panes.coffee:35:8)
  at Object.module.exports.moveRight (/Users/danlo/.atom/packages/move-panes/lib/move-panes.coffee:11:18)
  at atom-workspace.atom.commands.add.move-panes:move-right (/Users/danlo/.atom/packages/move-panes/lib/move-panes.coffee:4:70)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -0:44.7.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
  2x -0:44.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:44.1.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:32.9.0 nuclide-quick-open:find-anything-via-omni-search (atom-text-editor.editor.is-focused)
     -0:31.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:31.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:27.9.0 nuclide-quick-open:find-anything-via-omni-search (atom-text-editor.editor.is-focused)
     -0:27.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:27.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:26.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:26.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:26.4.0 nuclide-quick-open:find-anything-via-omni-search (atom-text-editor.editor.is-focused)
     -0:25.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:25.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  4x -0:24.2.0 key-binding-resolver:toggle (atom-text-editor.editor.is-focused)
     -0:12.5.0 move-panes:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "TARGETS",
        "cconf",
        "cinc",
        "mcconf",
        "tw",
        "BUCK"
      ]
    },
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "deprecation-cop",
      "fuzzy-finder",
      "metrics",
      "styleguide",
      "timecop",
      "linter",
      "language-javascript-jsx",
      "tree-view",
      "minimap"
    ],
    "themes": [
      "one-dark-ui",
      "visual-studio-dark-syntax"
    ]
  },
  "nuclide": {
    "connectionProfiles": [
      {
        "displayTitle": "www2",
        "params": {
          "username": "danlo",
          "server": "our.danlo.sb.facebook.com",
          "cwd": "/home/danlo/www2",
          "sshPort": "22",
          "authMethod": "PRIVATE_KEY",
          "pathToPrivateKey": "/Users/danlo/.ssh/fb_id_rsa",
          "remoteServerCommand": ""
        }
      }
    ],
    "fb-health": {},
    "installRecommendedPackages": true,
    "lastConnectionDetails": {
       ...
    },
    "nuclide-arcanist": {
      "blacklistedLinters": [
        "FBHACK"
      ]
    },
    "nuclide-connection": {
      ...
    },
    "nuclide-file-tree-deux": {
      "enabled": true,
      "revealFileOnSwitch": true
    },
    "nuclide-format-js": {},
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-remote-projects": {
      "shutdownServerAfterDisconnection": false
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-yeoman, v0.3.15
editorconfig, v1.2.4
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
json-schema, v0.1.15
language-babel, v2.15.4
language-ini, v1.14.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
minimap-find-and-replace, v4.4.0
minimap-selection, v4.3.1
move-panes, v0.2.0
nuclide, v0.118.23098490
omnisharp-atom, v0.26.11
tool-bar, v0.2.0
visual-studio-dark-syntax, v0.1.0

# Dev
No dev packages
```

**Comment by Daniel15** [comment]
For what it's worth, this plugin is similar, but actually works with Nuclide: https://atom.io/packages/pane-move-plus

**Comment by nmote** [comment]
I tried to repro and ran into https://github.com/santip/move-panes/issues/2. That plugin doesn't appear to be maintained (last commit was 8 months ago) so I don't think it's worth any effort to maintain compatibility.

**Comment by Daniel15** [comment]
Good catch, thanks. :+1:

**Comment by ssorallen** [comment]
@Daniel15 @nmote Atom core is getting pane move commands in v1.6: https://github.com/atom/atom/commit/500afb0f206c23c9b1a844e2ad07a2f286e36453 You will be able to bind them in your own keybindings once we move to 1.6.

**Comment by vjpr** [comment]
The native bindings weren't showing up in `Settings > Keybindings`. Here they are:

```
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-alt-]': 'window:move-active-item-to-pane-on-right'
  'ctrl-alt-[': 'window:move-active-item-to-pane-on-left'
```
