### ISSUE TITLE
Uncaught Error: Missing "providerName" property for hyperclick provider.

### ISSUE THREAD

**Issue by matthieuheitz** [facebook/nuclide#383]
[Enter steps to reproduce below:]

1. Install the hyperclick package

**Atom Version**: 1.5.4
**System**: Ubuntu 14.04.4
**Thrown From**: [hyperclick](https://github.com/facebooknuclideapm/hyperclick) package, v0.0.35

### Stack Trace

Uncaught Error: Missing "providerName" property for hyperclick provider.

```
At /home/matthieu/.atom/packages/hyperclick/lib/main.js:32

Error: Missing "providerName" property for hyperclick provider.
    at Object.consumeProvider (/home/matthieu/.atom/packages/hyperclick/lib/main.js:32:13)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -5:36.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:24.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -4:26.6.0 code-links:tmp-show-links (atom-text-editor.editor.is-focused)
     -1:31.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:21.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:20.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 10x -0:20.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "line-ending-selector",
      "autocomplete-cmake",
      "linter-clang",
      "linter-gcc",
      "linter",
      "symbol-gen",
      "goto",
      "symbols-view"
    ],
    "ignoredNames": [
      ".git",
      ".idea"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.9
file-icons, v1.6.17
hyperclick, v0.0.35
language-cmake, v0.1.4
markdown-writer, v2.3.1
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
symbols-tree-view, v0.11.0

# Dev
No dev packages
```

**Comment by matthieuheitz** [comment]
Duplicate of #229
