### ISSUE TITLE
nuclide-start-server failes

### ISSUE THREAD

**Issue by fuxiocteract** [facebook/nuclide#394]
I was trying to start a nuclide server via remote ssh to aws, then got this error:

/usr/local/lib/node_modules/nuclide/pkg/nuclide/server/lib/main.js:4
var main = _asyncToGenerator(function* (args) {
                                     ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.loadFile [as .js] (/usr/local/lib/node_modules/nuclide/pkg/nuclide/node-transpiler/lib/transpile.js:33:17)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nuclide/pkg/nuclide/server/lib/nuclide-main.js:17:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Remote Server Command is:
nuclide-start-server -k

**Comment by shushz** [comment]
What version of Node are you running on the aws instance? It seems to lack the support for generators.

**Comment by adnnn** [comment]
I'm having the same issue and I use node 10.42

**Comment by shushz** [comment]
Node 0.10.42 is not supported (and is ancient!). Why do you think `n stable` installed 0.10.42? I'd expect it to install current stable - v5.8.0
