### ISSUE TITLE
Uncaught Reference Error (CMake + Remote)

### ISSUE THREAD

**Issue by fcrisciani** [facebook/nuclide#429]
### Issue and Steps to Reproduce
Just opening any file on a remote directory

### Actual Behavior
Exception thrown

### Versions
* Atom: 1.6.0
* Nuclide: 0.125
* Client OS: 10.11.4
* Server OS (optional): Linux Ubuntu 12.04

### Additional Details
* Installed packages (`apm ls --installed`):
apm ls --installed
/Users/flavioc/.atom/packages (9)
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.16.0
├── language-ini@1.14.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── nuclide@0.125.0
├── sort-lines@0.14.0
└── tool-bar@0.4.0

Debugger (step by step):
http://s10.postimg.org/fnuut0n0p/Issue.png

File:
.atom/packages/nuclide/pkg/nuclide-datatip/lib/DatatipManager.js:formatted:59 Uncaught (in promise) Unknown Error: [object Object]

> JSON.stringify(error)
`VM2123:1 Uncaught ReferenceError: error is not defined
  at eval (<anonymous>:1:16)
  at Object.InjectedScript._evaluateOn (<anonymous>:904:55)
  at Object.InjectedScript._evaluateAndWrap (<anonymous>:837:34)
  at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:963:21)
  at step (/Users/flavioc/.atom/packages/nuclide/pkg/nuclide-datatip/lib/DatatipManager.js:17:280)
  at /Users/flavioc/.atom/packages/nuclide/pkg/nuclide-datatip/lib/DatatipManager.js:17:443
  at DatatipManager.<anonymous> (/Users/flavioc/.atom/packages/nuclide/pkg/nuclide-datatip/lib/DatatipManager.js:17:99)
  at DatatipManager._datatipForMouseEvent (/Users/flavioc/.atom/packages/nuclide/pkg/nuclide-datatip/lib/DatatipManager.js:172:12)
  at DatatipManager.<anonymous> (/Users/flavioc/.atom/packages/nuclide/pkg/nuclide-datatip/lib/DatatipManager.js:102:16)
  at later (/Users/flavioc/.atom/packages/nuclide/pkg/nuclide-commons/lib/debounce.js:35:23)`

**Comment by fcrisciani** [comment]
@hansonw here you are :) Any eta on the support of cmake on remote?
