### ISSUE TITLE
Uncaught Error: repositoryContainsPath: Received an unrecognized repository type. Expected git or hg.

### ISSUE THREAD

**Issue by rawon** [facebook/nuclide#434]
[Enter steps to reproduce below:]

1. Open atom

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.127.0

### Stack Trace

Uncaught Error: repositoryContainsPath: Received an unrecognized repository type. Expected git or hg.

```
At /Users/adityaw/.atom/packages/nuclide/pkg/nuclide-hg-git-bridge/lib/repositoryContainsPath.js:36

Error: repositoryContainsPath: Received an unrecognized repository type. Expected git or hg.
  at repositoryContainsPath (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-hg-git-bridge/lib/repositoryContainsPath.js:36:9)
  at /Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:874:63
  at /Users/adityaw/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:4360:23
  at /Users/adityaw/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:3883:58
  at /Users/adityaw/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:1365:16
  at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate] (/Users/adityaw/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:1714:11)
  at Map.__iterate (/Users/adityaw/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:1363:32)
  at Set.__iterate (/Users/adityaw/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:3883:24)
  at Set.mixin.findEntry (/Users/adityaw/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:4359:12)
  at Set.mixin.find (/Users/adityaw/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:4353:24)
  at FileTreeStore._repositoryForPath (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:873:37)
  at FileTreeStore.memoized [as _repositoryForPath] (/Users/adityaw/.atom/packages/nuclide/node_modules/lodash.memoize/index.js:150:23)
  at FileTreeStore._isIgnoredPath (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:1247:64)
  at FileTreeStore._shouldHidePath (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:1228:32)
  at /Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:1222:25
  at Array.filter (native)
  at FileTreeStore._omitHiddenPaths (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:1221:23)
  at FileTreeStore.getChildKeys (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:501:19)
  at FileTreeNode.getChildNodes (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeNode.js:82:35)
  at RootNodeComponent._renderNode (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/components/RootNodeComponent.js:96:14)
  at RootNodeComponent.render (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/components/RootNodeComponent.js:45:27)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:587:34)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:607:32)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:560:36)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.receiveComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:405:10)
  at Object.ReactReconciler.receiveComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at Object.ReactChildReconciler.updateChildren (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactChildReconciler.js:84:25)
  at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:220:35)
  at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:351:31)
  at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactMultiChild.js:326:14)
  at ReactDOMComponent.Mixin._updateDOMChildren (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:871:12)
  at ReactDOMComponent.Mixin.updateComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:700:10)
  at ReactDOMComponent.Mixin.receiveComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactDOMComponent.js:645:10)
  at Object.ReactReconciler.receiveComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:87:22)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:562:23)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:544:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:473:12)
  at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:421:12)
  at Object.ReactReconciler.performUpdateIfNecessary (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:102:22)
  at runBatchedUpdates (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:129:21)
  at ReactReconcileTransaction.Mixin.perform (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at ReactUpdatesFlushTransaction.assign.perform (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:86:38)
  at Object.flushBatchedUpdates (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:147:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:202:25)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:149:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
  at Object.enqueueUpdate (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:176:22)
  at enqueueUpdate (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactUpdateQueue.js:24:16)
  at Object.ReactUpdateQueue.enqueueForceUpdate (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactUpdateQueue.js:143:5)
  at FileTreeSidebarComponent.ReactComponent.forceUpdate (/Users/adityaw/.atom/packages/nuclide/node_modules/react/lib/ReactComponent.js:86:16)
  at FileTreeSidebarComponent._processExternalUpdate (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:99:14)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at Immediate.<anonymous> (/Users/adityaw/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:334:29)
  at processImmediate [as _immediateCallback] (timers.js:374:17)

```

### Commands

```
     -1:19.5.0 nuclide-quick-open:find-anything-via-omni-search (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -1:11 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:11 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:07.5.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
     -0:24.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "hyperclick",
      "nuclide-arcanist",
      "nuclide-code-format",
      "nuclide-diagnostics-store",
      "nuclide-diagnostics-ui",
      "nuclide-diff-view",
      "nuclide-file-tree",
      "nuclide-file-watcher",
      "nuclide-find-references",
      "nuclide-flow",
      "nuclide-hack",
      "nuclide-hg-repository",
      "nuclide-installer",
      "nuclide-language-hack",
      "nuclide-ocaml",
      "nuclide-quick-open",
      "nuclide-remote-projects",
      "nuclide-type-hint",
      "tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "nuclide": {
    "nuclide-flow": {}
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.127.0
svn, v0.0.8

# Dev
No dev packages
```

**Comment by matthewwithanm** [comment]
Sorry about this @rawon. 😞

Did this just start with 0.127?

cc @ssorallen @shushz
