### ISSUE TITLE
Uncaught Error: Diff view only supports `Mercurial` repositories, but found `git` at path: `/User...

### ISSUE THREAD

**Issue by aichijia** [facebook/nuclide#436]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.127.0

### Stack Trace

Uncaught Error: Diff view only supports `Mercurial` repositories, but found `git` at path: `/Users/zhanglei/.atom`

```
At /Users/zhanglei/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:136

Error: Diff view only supports `Mercurial` repositories, but found `git` at path: `/Users/zhanglei/.atom`
  at hgRepositoryForPath (/Users/zhanglei/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:133:11)
  at DiffViewModel._getRepositoryStackForPath (/Users/zhanglei/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:619:26)
  at DiffViewModel._findFilePathToDiffInDirectory (/Users/zhanglei/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:419:34)
  at DiffViewModel.diffEntity (/Users/zhanglei/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:443:25)
  at activateDiffPath (/Users/zhanglei/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:127:19)
  at createView (/Users/zhanglei/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:60:5)
  at /Users/zhanglei/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:231:16
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:484:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:419:19)
  at atom-text-editor.<anonymous> (/Users/zhanglei/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:184:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at module.exports._executeCallback (/Users/zhanglei/.atom/packages/tool-bar/lib/tool-bar-button-view.coffee:71:23)
  at space-pen-button.<anonymous> (/Users/zhanglei/.atom/packages/tool-bar/lib/tool-bar-button-view.coffee:30:7)
  at space-pen-button.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-button.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -2:49.1.0 nuclide-health:toggle (atom-text-editor.editor)
     -2:26.9.0 nuclide-home:show-settings (atom-text-editor.editor)
     -2:24.1.0 nuclide-health:toggle (div.package-detail.panels-item)
  2x -2:22.8.0 nuclide-home:show-settings (div.package-detail.panels-item)
  2x -2:20.7.0 nuclide-health:toggle (div.package-detail.panels-item)
     -2:18.5.0 nuclide-home:show-settings (div.package-detail.panels-item)
  3x -0:55.7.0 nuclide-outline-view:toggle (atom-text-editor.editor)
     -0:34.5.0 nuclide-outline-view:hide (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:31.9.0 nuclide-diagnostics-ui:toggle-table (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:30.3.0 nuclide-diff-view:open (atom-text-editor.editor.is-focused)
  2x -0:27.8.0 nuclide-diagnostics-ui:toggle-table (atom-text-editor.editor.is-focused)
     -0:01.0 nuclide-diff-view:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-arcanist": {},
    "nuclide-buck-files": {},
    "nuclide-clang-atom": {},
    "nuclide-console": {},
    "nuclide-datatip": {},
    "nuclide-debugger-hhvm": {},
    "nuclide-flow": {},
    "nuclide-format-js": {},
    "nuclide-hack": {},
    "nuclide-health": {},
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-ios-simulator-logs": {},
    "nuclide-ocaml": {},
    "nuclide-react-native": {},
    "nuclide-working-sets": {}
  }
}
```

### Installed Packages

```coffee
# User
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.16.0
language-ini, v1.15.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
nuclide, v0.127.0
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by mostafaeweda** [comment]
As the message says, the Diff View doesn't yet support git - that may change when we use Atom 1.7 and build on the `GitRepositoryAsync`

**Comment by mikaoelitiana** [comment]
Hello, is git supported now? (I have Atom 1.8)

**Comment by mostafaeweda** [comment]
Not yet, unfortunately

**Comment by alukos** [comment]
Hello, do you plan to support for git?

**Comment by mostafaeweda** [comment]
That's not coming soon, however I'm open to contributions enabling it though.
