### ISSUE TITLE
Nuclide hg repository support doesn't work with the atom 1.7.0-beta1 async features

### ISSUE THREAD

**Issue by inkytonik** [facebook/nuclide#439]
1. Open Atom 1.7.0-beta1 in a project that uses Mercural with Nuclide 0.127.0 installed
2. Get crash in status-bar (see trace below)

**Atom Version**: 1.7.0-beta1
**System**: Mac OS X 10.11.4
**Thrown From**: [status-bar](https://github.com/atom/status-bar) package, v1.1.2

### Stack Trace

Failed to activate the status-bar package

```
At Cannot read property 'onDidChangeStatus' of undefined

TypeError: Cannot read property 'onDidChangeStatus' of undefined
    at status-bar-git.GitView.subscribeToRepositories (/Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:99:52)
    at status-bar-git.GitView.initialize (/Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/node_modules/status-bar/lib/git-view.js:34:12)
    at Object.module.exports.activate (/Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/node_modules/status-bar/lib/main.js:67:16)
    at Package.module.exports.Package.activateNow (/Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/package-manager.js:535:21)
    at /Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/package-manager.js:516:29
    at Config.module.exports.Config.transactAsync (/Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/package-manager.js:511:19)
    at PackageManager.module.exports.PackageManager.activate (/Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/package-manager.js:494:46)
    at /Users/asloane/Applications/AtomBeta.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "symbols-view"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      ".ensime",
      ".ensime_cache",
      ".hgcheck",
      ".hgignore",
      ".hgtags",
      "target",
      "tags",
      ".tags",
      ".tags1"
    ],
    "projectHome": "/Users/asloane/Projects",
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "status-bar": {}
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-ctags, v4.5.2
build, v0.58.0
file-icons, v1.6.19
floobits, v0.31.1
language-fish-shell, v1.0.3
language-latex, v0.6.1
language-moama, v0.1.0
language-scala, v1.1.6
language-scalatex, v0.1.0
language-syntax, v0.1.0
last-cursor-position, v0.9.0
linter, v1.11.4
linter-coffeelint, v1.1.2
monto, v0.0.0
nuclide, v0.127.0
open-recent, v5.0.0
pdf-view, v0.50.0
terminal-plus, v0.14.5
toggle-gutter, v0.2.2

# Dev
No dev packages
```

**Comment by inkytonik** [comment]
After a brief investigation, it seems that this issue is the same one that is affecting the atom-svn package: [atom-svn/issues/20](https://github.com/andischerer/atom-svn/issues/20).

**Comment by ssorallen** [comment]
Thanks for the report. I began a fix for this yesterday and would like to get it into the next release. I'll reference this issue in the commit so you know when it lands.

**Comment by ssorallen** [comment]
@inkytonik This landed in master and will be in next week's release.

**Comment by inkytonik** [comment]
Thanks. I'll report back here if there are any issues.

**Comment by inkytonik** [comment]
I've installed Nuclide 0.128.0 which contains this fix. The hg repo support seems to be working fine in that I get the expected status bar information and gutter annotations.

However, Atom's CPU usage seems be quite a bit higher now when I have the hg repository support enabled. When using the Nuclide hg repository support Atom sits at 25-30% CPU constantly which on my Macbook Pro means the fans are on most of the time. This CPU usage happens even when Atom is running but I am using another application, or when I am using Atom but just navigating around and not making changes to files.

When the hg repo feature is turned off Atom idles at a much lower and "normal" CPU usage.

Is it possible that this async support is doing a lot more work than it needs to?
