### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by dudeinthemirror** [facebook/nuclide#448]
[Enter steps to reproduce below:]

1. It happens sometimes upon starting Atom from the command line as: `atom .`  (in the root dir of a react-native project)
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.127.0

### Stack Trace

Uncaught TypeError: Cannot read property 'slice' of undefined

```
At /Users/dudeinthemirror/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeHelpers.js:44

TypeError: Cannot read property 'slice' of undefined
  at Object.isDirKey (/Users/dudeinthemirror/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeHelpers.js:44:13)
  at FileTreeController._findLowermostDescendantKey (/Users/dudeinthemirror/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeController.js:674:42)
  at FileTreeController._moveUp (/Users/dudeinthemirror/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeController.js:629:50)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```

### Commands

```
     -0:01.7.0 nuclide-side-bar:toggle-focus (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
  2x -0:01.7.0 blur (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
  2x -0:01.0 core:move-up (div.nuclide-file-tree.focusable-panel.tree-view)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "nerd-treeview"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".*"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-react-native-autocomplete, v0.0.7
autocomplete-swift, v1.0.2
language-babel, v2.16.0
language-javascript-jsx, v0.3.7
language-swift, v0.4.0
nuclide, v0.127.0
pigments, v0.26.0
tool-bar, v0.4.0
vim-mode-plus, v0.29.0

# Dev
No dev packages
```

**Comment by shushz** [comment]
The code in this stack trace has changed a lot in the upcoming version v0.129.0
Let's see whether this issue will still be reproducible in it

**Comment by dudeinthemirror** [comment]
Sounds good. Thanks
