### ISSUE TITLE
Failed to activate the nuclide-quick-open package

### ISSUE THREAD

**Issue by montogeek** [facebook/nuclide#469]
Hi! I just updated to 0.132.0 and this error happened:
1. Update to 0.132.0

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide-quick-open](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to activate the nuclide-quick-open package

```
At Provider FuzzyFileNameProvider is not registered with quick-open.

AssertionError: Provider FuzzyFileNameProvider is not registered with quick-open.
  at SearchResultManager._getProviderByName (/Users/montogeek/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:441:31)
  at SearchResultManager.getProviderByName (/Users/montogeek/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:505:38)
  at new QuickSelectionComponent (/Users/montogeek/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:100:38)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:153:16)
  at Object.ReactReconciler.mountComponent (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:37:35)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:225:34)
  at Object.ReactReconciler.mountComponent (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:37:35)
  at mountComponentIntoNode (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:266:32)
  at ReactReconcileTransaction.Mixin.perform (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at batchedMountComponentIntoNode (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:282:15)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
  at Object.batchedUpdates (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:94:20)
  at Object.ReactMount._renderNewRootComponent (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:476:18)
  at Object.ReactMount._renderSubtreeIntoContainer (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:550:32)
  at Object.ReactMount.render (/Users/montogeek/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:570:23)
  at Activation._render (/Users/montogeek/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/main.js:177:37)
  at Activation._updateScrollableHeight (/Users/montogeek/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/main.js:172:36)
  at new Activation (/Users/montogeek/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/main.js:98:10)
  at getActivation (/Users/montogeek/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/main.js:276:18)
  at Object.activate (/Users/montogeek/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/main.js:290:3)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
  at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
  at Object.activate (/Users/montogeek/.atom/packages/nuclide/lib/main.js:252:29)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:389:60
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:237:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

### Commands

```
  5x -9:50.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-genesis-ui)
     -9:36.1.0 pane:reopen-closed-item (atom-text-editor.editor.is-focused.hyperclick)
     -9:35.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-genesis-ui)
     -9:10.3.0 core:close (atom-text-editor.editor.is-focused)
  2x -9:10.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-genesis-ui)
     -2:31.7.0 core:save (atom-text-editor.editor.is-focused.hyperclick)
  2x -2:23 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -2:22.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:20.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:20.1.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-genesis-ui)
     -2:09.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-genesis-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tabs-to-spaces",
      "Stylus",
      "editorconfig",
      "linter",
      "atom-ternjs",
      "color-picker",
      "intentions",
      "intentions-colorpicker",
      "language-ejs",
      "merge-conflicts",
      "react",
      "tree-view",
      "git-time-machine",
      "haskell-grammar",
      "language-ocaml",
      "language-thrift",
      "tool-bar"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "genesis-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-chai-snippets, v0.3.0
docblockr, v0.7.3
emmet, v2.4.3
enzyme-snippets, v0.1.0
file-icons, v1.7.6
genesis-ui, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.17.3
language-ini, v1.16.0
linter-eslint, v7.2.1
nuclide, v0.132.0
pigments, v0.26.0
project-manager, v2.9.7
synced-sidebar, v0.4.3
wakatime, v5.0.8

# Dev
No dev packages
```

**Comment by johnislarry** [comment]
Strange, I can't repro.  Does this happen every time you load Nuclide?

**Comment by johnislarry** [comment]
I believe this is fixed now, please try v134 and re-open if it's not
