### ISSUE TITLE
File tree not sync with file system change

### ISSUE THREAD

**Issue by Spy-Seth** [facebook/nuclide#472]
### Issue and Steps to Reproduce
My tree file do not keep sync (git colors outdated) with my local files and I have this error in the Atom console:

```
[2016-04-25T11:31:32.480Z] [ERROR] nuclide - Cannot subscribe to directory "/Users/spy-seth/workspace/my_project/frontend/property_onboarding/src/PropertyOnboarding/" Error: Unable to watch path
  at Error (native)
  at HandleWatcher.start (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/main.js:179:12)
  at Directory.module.exports.Directory.subscribeToNativeChangeEvents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:336:109)
  at Directory.module.exports.Directory.willAddSubscription (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:93:14)
  at Directory.willAddSubscription (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:3:61)
  at Directory.module.exports.Directory.onDidChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:87:12)
  at FileTreeStore._makeSubscription (/Users/spy-seth/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:883:26)
  at /Users/spy-seth/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:846:37
  at /Users/spy-seth/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:421:39
  at /Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:3004:46
  at /Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:2687:43
  at List.__iterate (/Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:2194:13)
  at OrderedMap.__iterate (/Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:2686:25)
  at KeyedIterable.mappedSequence.__iterateUncached (/Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:3003:23)
  at seqIterate (/Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:606:16)
  at KeyedIterable.Seq.__iterate (/Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:276:14)
  at KeyedIterable.mixin.forEach (/Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:4374:19)
  at /Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:2639:16
  at OrderedMap.Map.withMutations (/Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:1341:7)
  at new OrderedMap (/Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:2636:27)
  at reify (/Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:3554:37)
  at OrderedMap.mixin.map (/Users/spy-seth/.atom/packages/nuclide/node_modules/immutable/dist/immutable.js:4394:14)
  at FileTreeStore._updateNodeAtAllRoots (/Users/spy-seth/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:415:30)
  at /Users/spy-seth/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:820:16
```

### Expected Behavior
I expect the file tree color to be sync with the actual git state

### Actual Behavior
The file tree color do not update when changing file in the git repository from the project.

### Versions
* Atom: 1.7.2
* Nuclide: 1.32.0
* Client OS: OSX 10.11.4

**Comment by mostafaeweda** [comment]
The error is not directly related to the git tree highlighting, but is coming from Atom's core `pathwatcher` module -- in a code path intended to update the contents of a directory when it changes on the filesystem.
The error indicates that it can't watch that directory --> could that be a permissions issue?
If the node module `pathwatcher` can't watch the directory -- then, probably the `GitRepository` can't as well, hence, missing status updates causing the file tree color to go out of sync.
Does that work with Atom's file tree?

**Comment by Spy-Seth** [comment]
It works in the default Atom tree view.
