### ISSUE TITLE
Failed to activate the nuclide-toolbar package

### ISSUE THREAD

**Issue by excelbrium** [facebook/nuclide#474]
Happening after opening atom.
Fresh install, used apm to install nuclide with "apm install nuclide"

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide-toolbar](https://github.com/facebooknuclideapm/nuclide-toolbar) package, v0.0.32

### Stack Trace

Failed to activate the nuclide-toolbar package

```
At Cannot read property 'bool' of undefined

TypeError: Cannot read property 'bool' of undefined
    at Object.<anonymous> (/Users/oliver/.atom/packages/nuclide-toolbar/node_modules/nuclide-buck-toolbar/node_modules/nuclide-ui-atom-combo-box/node_modules/nuclide-ui-atom-input/lib/AtomInput.js:25:24)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.load (/Users/oliver/.atom/packages/nuclide-toolbar/node_modules/nuclide-buck-toolbar/node_modules/nuclide-atom-npm/lib/main.js:68:31)
    at Object.<anonymous> (/Users/oliver/.atom/packages/nuclide-toolbar/node_modules/nuclide-buck-toolbar/node_modules/nuclide-ui-atom-combo-box/node_modules/nuclide-ui-atom-input/lib/main.js:10:46)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/oliver/.atom/packages/nuclide-toolbar/node_modules/nuclide-buck-toolbar/node_modules/nuclide-ui-atom-combo-box/lib/AtomComboBox.js:14:17)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.load (/Users/oliver/.atom/packages/nuclide-toolbar/node_modules/nuclide-buck-toolbar/node_modules/nuclide-atom-npm/lib/main.js:68:31)
    at Object.<anonymous> (/Users/oliver/.atom/packages/nuclide-toolbar/node_modules/nuclide-buck-toolbar/node_modules/nuclide-ui-atom-combo-box/lib/main.js:10:46)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
hyperclick, v0.0.36
nuclide, v0.132.0
nuclide-arcanist, v0.0.32
nuclide-blame, v0.0.32
nuclide-blame-provider-hg, v0.0.32
nuclide-blame-ui, v0.0.32
nuclide-buck-files, v0.0.32
nuclide-clang-atom, v0.0.32
nuclide-code-format, v0.0.32
nuclide-debugger-atom, v0.0.32
nuclide-debugger-hhvm, v0.0.32
nuclide-debugger-lldb, v0.0.32
nuclide-diagnostics-store, v0.0.32
nuclide-diagnostics-ui, v0.0.32
nuclide-diff-view, v0.0.32
nuclide-file-tree, v0.0.32
nuclide-file-tree-deux, v0.0.32
nuclide-file-watcher, v0.0.32
nuclide-find-references, v0.0.32
nuclide-flow, v0.0.32
nuclide-fuzzy-filename-provider, v0.0.32
nuclide-hack, v0.0.32
nuclide-hack-symbol-provider, v0.0.32
nuclide-hg-repository, v0.0.32
nuclide-installer, v0.0.32
nuclide-language-hack, v0.0.32
nuclide-objc, v0.0.32
nuclide-ocaml, v0.0.32
nuclide-open-filenames-provider, v0.0.32
nuclide-quick-open, v0.0.32
nuclide-remote-projects, v0.0.32
nuclide-test-runner, v0.0.32
nuclide-toolbar, v0.0.32
nuclide-type-hint, v0.0.32

# Dev
No dev packages
```

**Comment by excelbrium** [comment]
After some further trying I deleted atom again, cleared ~/.atom and did another reinstall. Now it works.

**Comment by nmote** [comment]
You had all of the old `nuclide-*` packages from before we unified Nuclide into a single `nuclide` package, as well as the new `nuclide` package. It should have printed a warning explaining the issue, but in any case deleting those packages was the right thing to do and you should be all set now.
