### ISSUE TITLE
Uncaught AssertionError: The file that is about to be closed should still be open.

### ISSUE THREAD

**Issue by mpkuth** [facebook/nuclide#475]
[Enter steps to reproduce below:]

1. Editor window open to file
2. Delete file
-- I got an uncaught excpeption from the minimap package here
3. Attempt to close file or change tabs
-- File that was deleted will not close
-- Error pops up every time I switch tabs
4. Restart atom to resolve

**Atom Version**: 1.7.2
**System**: Mac OS X 10.9.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.132.0

### Stack Trace

Uncaught AssertionError: The file that is about to be closed should still be open.

```
At assert.js:89

AssertionError: The file that is about to be closed should still be open.
  at /Users/mpkuth/.atom/packages/nuclide/pkg/nuclide-atom-helpers/lib/on-will-destroy-text-buffer.js:30:29
  at Function.module.exports.Emitter.simpleDispatch (/Users/mpkuth/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Users/mpkuth/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at PaneContainer.module.exports.PaneContainer.willDestroyPaneItem (/Users/mpkuth/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-container.js:298:27)
  at Pane.module.exports.Pane.destroyItem (/Users/mpkuth/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:630:17)
  at atom-tabs.TabBarView.onClick (/Users/mpkuth/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:658:17)

```

### Commands

```
     -9:51.1.0 core:copy (atom-text-editor.editor.is-focused.hyperclick)
     -9:49.5.0 core:paste (atom-text-editor.editor.is-focused)
     -9:47.6.0 core:save (atom-text-editor.editor.is-focused)
     -9:42.3.0 find-and-replace:show (atom-text-editor.editor.is-focused.hyperclick)
     -9:35.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -9:35.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:43 tree-view:remove (span.name.icon.icon-file-text)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ]
    },
    "disabledPackages": [
      "nuclide-flow",
      "exception-reporting",
      "metrics",
      "linter",
      "language-toml",
      "minimap-hide",
      "minimap-autohide",
      "vim-mode"
    ],
    "ignoredNames": [
      ".git",
      ".DSStore",
      "*.pyc"
    ],
    "projectHome": "/Users/erydo/Preo",
    "themes": [
      "zenburn-ui",
      "zenburn-syntax"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-arcanist": {},
    "nuclide-buck-files": {},
    "nuclide-clang-atom": {},
    "nuclide-datatip": {},
    "nuclide-debugger-hhvm": {},
    "nuclide-file-tree": {
      "revealFileOnSwitch": true
    },
    "nuclide-flow": {
      "enableStructuredTypeHints": true
    },
    "nuclide-format-js": {},
    "nuclide-fuzzy-filename-provider": {
      "useRxMode": true
    },
    "nuclide-hack": {},
    "nuclide-health": {},
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-ios-simulator-logs": {},
    "nuclide-ocaml": {},
    "nuclide-output": {},
    "nuclide-remote-ctags": {
      "disableWithHack": false
    },
    "nuclide-remote-projects": {
      "shutdownServerAfterDisconnection": false
    },
    "nuclide-working-sets": {},
    "use": {
      "nuclide-blame-provider-hg": false,
      "nuclide-buck-files": false,
      "nuclide-buck-toolbar": false,
      "nuclide-debugger-hhvm": false,
      "nuclide-file-tree": false,
      "nuclide-hack": false,
      "nuclide-hack-symbol-provider": false,
      "nuclide-hg-repository": false,
      "nuclide-hhvm-toolbar": false,
      "nuclide-language-hack": false
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
autocomplete-python, v1.7.2
autocomplete-sass, v0.1.0
color-picker, v2.1.1
file-icons, v1.7.7
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.18.2
language-cython, v0.3.0
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
linter-annotations, v1.0.1
linter-eslint, v7.2.1
linter-flake8, v1.13.0
linter-python-pep257, v0.0.1
linter-sass-lint, v1.4.2
merge-conflicts, v1.4.2
minimap, v4.23.1
minimap-bookmarks, v0.3.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-selection, v4.4.0
nuclide, v0.132.0
pigments, v0.26.0
project-manager, v2.9.7
python-indent, v0.4.3
python-tools, v0.6.7
tool-bar, v0.4.0
zenburn-syntax, v3.1.2
zenburn-ui, v0.1.2

# Dev
No dev packages
```

**Comment by hansonw** [comment]
I suspect the exception from minimap is the root cause here, throwing off Atom's built-in buffer destroy behaviour. Perhaps we can handle this better, but have you reported this to the minimap package yet?

**Comment by mpkuth** [comment]
The exception had already been reported to the minimap package. You can see it here:
https://github.com/atom-minimap/minimap/issues/477
