### ISSUE TITLE
Uncaught TypeError: repository.getProjectDirectory is not a function

### ISSUE THREAD

**Issue by gnotari** [facebook/nuclide#482]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.134.0
### Stack Trace

Uncaught TypeError: repository.getProjectDirectory is not a function

```
At /Users/guido/.atom/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:52

TypeError: repository.getProjectDirectory is not a function
  at new RepositoryStack (/Users/guido/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/RepositoryStack.js:78:40)
  at DiffViewModel._createRepositoryStack (/Users/guido/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:265:29)
  at DiffViewModel._updateRepositories (/Users/guido/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:249:14)
  at new DiffViewModel (/Users/guido/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/DiffViewModel.js:197:10)
  at getDiffViewModel (/Users/guido/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:109:21)
  at createView (/Users/guido/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:75:19)
  at /Users/guido/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:299:16
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:489:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:424:19)
  at diffActivePath (/Users/guido/.atom/packages/nuclide/pkg/nuclide-diff-view/lib/main.js:166:20)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
  at React.createElement.React.createElement.React.createElement.onClick (/Users/guido/.atom/packages/nuclide/pkg/nuclide-home/lib/HomeFeatureComponent.js:53:38)
  at Object.invokeGuardedCallback (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:26:12)
  at executeDispatch (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:87:21)
  at Object.executeDispatchesInOrder (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:110:5)
  at executeDispatchesAndRelease (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:42:22)
  at executeDispatchesAndReleaseTopLevel (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:53:10)
  at Array.forEach (native)
  at forEachAccumulated (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/forEachAccumulated.js:24:9)
  at Object.EventPluginHub.processEventQueue (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:215:7)
  at runEventQueueInBatch (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
  at handleTopLevelImpl (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:73:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:97:20)
  at ReactEventListener.dispatchEvent (/Users/guido/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:150:20)

```
### Commands

```
     -1:05.3.0 nuclide-outline-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-atom-light-ui)
     -0:00.9.0 nuclide-diff-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-atom-light-ui)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "metrics",
      "spell-check",
      "tree-view"
    ],
    "packagesWithKeymapsDisabled": [
      "emacs-plus"
    ],
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-hg, v2.0.4
emacs-plus, v0.11.0
language-docker, v1.1.6
nuclide, v0.134.0

# Dev
No dev packages
```

**Comment by hansonw** [comment]
Hi - I think this is due to an incompatibility with the `atom-hg` package. You shouldn't use both `atom-hg` and Nuclide, as Nuclide's hg implementation is not compatible (and it looks like we provide a superset of the features that `atom-hg` does, including diff view). Could you try disabling `atom-hg`?

Are there any features in `atom-hg` that are missing from Nuclide?
