### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScrollBottom' of null

### ISSUE THREAD

**Issue by tychota** [facebook/nuclide#483]
Sorry it just appears. I thus don't have reproduction steps.
I don't mind if you close this as unreproductible.

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.134.0

### Stack Trace

Uncaught TypeError: Cannot read property 'setScrollBottom' of null

```
At /Users/tychotatitscheff/.atom/packages/nuclide/node_modules/rxjs/Subscriber.js:229

TypeError: Cannot read property 'setScrollBottom' of null
  at atom-text-editor.TextEditorElement.setScrollBottom (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:376:28)
  at atom-text-editor.TextEditorElement.scrollToBottom (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:384:19)
  at TextEditor.module.exports.TextEditor.scrollToBottom (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2789:46)
  at ProcessOutputView._handleBufferChange (/Users/tychotatitscheff/.atom/packages/nuclide/pkg/nuclide-process-output/lib/ProcessOutputView.js:74:17)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at TextBuffer.module.exports.TextBuffer.applyChange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:692:27)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:602:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:576:26
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:828:18)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:574:21)
  at TextBuffer.module.exports.TextBuffer.insert (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:607:19)
  at TextBuffer.module.exports.TextBuffer.append (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:611:19)
  at update (/Users/tychotatitscheff/.atom/packages/nuclide/pkg/nuclide-process-output/lib/createBoundTextBuffer.js:33:14)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at ProcessOutputStore._receiveStdout (/Users/tychotatitscheff/.atom/packages/nuclide/pkg/nuclide-process-output-store/lib/ProcessOutputStore.js:119:21)
  at stdout (/Users/tychotatitscheff/.atom/packages/nuclide/pkg/nuclide-process-output-store/lib/ProcessOutputStore.js:55:24)
  at SafeSubscriber.onNext [as _next] (/Users/tychotatitscheff/.atom/packages/nuclide/pkg/nuclide-react-native/lib/packager/ReactNativeServerManager.js:135:13)
  at SafeSubscriber.__tryOrUnsub (/Users/tychotatitscheff/.atom/packages/nuclide/node_modules/rxjs/Subscriber.js:225:16)
  at SafeSubscriber.next (/Users/tychotatitscheff/.atom/packages/nuclide/node_modules/rxjs/Subscriber.js:174:22)
  at Subscriber._next (/Users/tychotatitscheff/.atom/packages/nuclide/node_modules/rxjs/Subscriber.js:124:26)
  at Subscriber.next (/Users/tychotatitscheff/.atom/packages/nuclide/node_modules/rxjs/Subscriber.js:88:18)
  at Socket.<anonymous> (/Users/tychotatitscheff/.atom/packages/nuclide/pkg/nuclide-commons/lib/process.js:239:18)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:523:20)

```

### Commands

```
     -5:21.8.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-fizzy.theme-one-light-ui)
     -5:21.8.0 nuclide-console:show (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-fizzy.theme-one-light-ui)
     -5:21.7.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-fizzy.theme-one-light-ui)
     -5:04.8.0 nuclide-react-native:start-packager (atom-pane.pane.active)
  4x -4:55.4.0 nuclide-diagnostics-ui:toggle-table (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-fizzy.theme-one-light-ui)
     -3:22.7.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -3:22.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:20.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:20.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:19.8.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -3:19.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:18.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:35.8.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-fizzy.theme-one-light-ui)
     -2:16.5.0 nuclide-diagnostics-ui:toggle-table (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-fizzy.theme-one-light-ui)
     -0:20 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:16.1.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "linter"
    ],
    "themes": [
      "one-light-ui",
      "fizzy"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.7.8
fizzy, v0.16.0
linter-eslint, v7.2.1
minimap, v4.23.2
nuclide, v0.134.0

# Dev
No dev packages
```

**Comment by matthewwithanm** [comment]
Thanks for the report, @tychota! This should be fixed by a4ff2e70b1eb2cb7414ebc60d04acc423cc49603, which'll be in next week's release.
