### ISSUE TITLE
ImportError: No module named lldb

### ISSUE THREAD

**Issue by cortopy** [facebook/nuclide#485]
When trying to attach nuclide to a process I get a stack trace in the console:

```
Traceback (most recent call last):
  File "/home/me/.atom/packages/nuclide/pkg/nuclide-debugger-lldb-server/scripts/main.py", line 14, in <module>
    from find_lldb import lldb
  File "/home/me/.atom/packages/nuclide/pkg/nuclide-debugger-lldb-server/scripts/find_lldb.py", line 54, in <module>
    lldb = find_lldb()
  File "/home/me/.atom/packages/nuclide/pkg/nuclide-debugger-lldb-server/scripts/find_lldb.py", line 50, in find_lldb
    import lldb
ImportError: No module named lldb
```

### Versions
* Atom: 1.7.3
* Nuclide: 0.135
* Client OS: Fedora 23

**Comment by bottledwalter** [comment]
Looks like you need to make sure Python can find the LLDB bindings. 

Here's a SO thread that should help: http://stackoverflow.com/questions/30869945/how-to-import-lldb-in-a-python-script

**Comment by janosimas** [comment]
@bottledwalter this link worked for me but...

After attaching I get another error:
```
Inferior should be stopped after attach or linux launch
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/jsimas/.atom/packages/nuclide/pkg/nuclide-debugger-lldb-server/scripts/event_thread.py", line 206, in run
    if lldb.SBTarget.EventIsTargetEvent(event):
AttributeError: type object 'SBTarget' has no attribute 'EventIsTargetEvent'
```

Any ideas?

**Comment by janosimas** [comment]
Looks like the EventIsTargetEvent exists in the C++ API but not in the python binding.

https://llvm.org/svn/llvm-project/lldb/trunk/include/lldb/API/SBTarget.h
http://lldb.llvm.org/python_reference/

**Comment by amon-ra** [comment]
I have fixed the two errors downloading lldb 3.9 from the page:
```
echo "deb http://apt.llvm.org/jessie/ llvm-toolchain-jessie-3.9 main " >  /etc/apt/sources.list.d/lldb.list
apt-get update 
apt-get install -y lldb-3.9
```
Now debugging is working ok

**Comment by deeprest** [comment]
workaround for Debian, with llvm-3.8 and python2.7:
* Atom: 1.20.0
* Nuclide: 0.252.0
* Client OS: Debian 9 (stretch)

**Partially taken from bottledwalter's SO link above:**
`PYTHON=2.7`
`LLVM=3.8`
`LLVM_PATCH=1`
`pushd /usr/lib/llvm-$LLVM/lib/python$PYTHON/site-packages/lldb`
`sudo rm _lldb.so libLLVM-$LLVM.0.so.1 libLLVM-$LLVM.so.1`
`sudo ln -s ../../../liblldb.so.1 _lldb.so`
`sudo ln -s ../../../libLLVM-$LLVM.$LLVM_PATCH.so.1 libLLVM-$LLVM.0.so.1`
`sudo ln -s ../../../libLLVM-$LLVM.$LLVM_PATCH.so.1 libLLVM-$LLVM.so.1`
`popd`

**This was necessary for the Atom.io Nuclide debugger to find module _lldb**
`sudo ln -s /usr/lib/llvm-$LLVM/lib/liblldb.so /usr/lib/python$PYTHON/dist-packages/_lldb.so`

**Check that python can import lldb without exporting the path first**
`python`
`>>> import lldb`
If that works then hopefully the Nuclide debugger works too
