### ISSUE TITLE
Cannot find module '../pkg/nuclide-feature-config'

### ISSUE THREAD

**Issue by sicum** [facebook/nuclide#486]
### Issue and Steps to Reproduce
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.135.0

### Stack Trace

Failed to activate the nuclide package

```
At Cannot find module '../pkg/nuclide-feature-config'

Error: Cannot find module '../pkg/nuclide-feature-config'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/erickgaillard/.atom/packages/nuclide/lib/main.js:18:32)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-adb-logcat": {},
    "nuclide-blame-provider-hg": {
      "showVerboseBlame": false
    },
    "nuclide-home": {
      "showHome": true
    }
  }
}
```

### Installed Packages

```coffee
# User
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.19.4
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
nuclide, v0.135.0
tool-bar, v0.4.0

# Dev
No dev packages
```

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom:
* Nuclide:
* Client OS:
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by zertosh** [comment]
@sicum I can't repro. Have you tried restarting Atom?

**Comment by zertosh** [comment]
Closing due to lack of activity.
