### ISSUE TITLE
"Failed to activate the hyperclick package"

### ISSUE THREAD

**Issue by itinance** [facebook/nuclide#497]
### Issue and Steps to Reproduce
When opening Atom-IDE, this message box appears:

"Failed to activate the hyperclick package"
"Cannot read property 'Component' of undefined"

```
TypeError: Cannot read property 'Component' of undefined
    at Object.<anonymous> (/Users/hagen/.atom/packages/hyperclick/lib/SuggestionListElement.js:255:23)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/hagen/.atom/packages/hyperclick/lib/Hyperclick.js:50:30)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/hagen/.atom/packages/hyperclick/lib/main.js:22:19)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)

```
### Expected Behavior
No error message at launch of IDE

### Actual Behavior
Error message after each launch of IDE:

> "Failed to activate the hyperclick package"
> "Cannot read property 'Component' of undefined"
> 

### Versions
* Atom: 1.7.4
* Nuclide: 0.0.35 (i guess)
* Client OS: OSX El Capitan 10.11.4 (15E65)
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

Community Packages (45)
├── hyperclick@0.0.36
├── nuclide-arcanist@0.0.35
├── nuclide-blame@0.0.35
├── nuclide-blame-provider-hg@0.0.35
├── nuclide-blame-ui@0.0.35
├── nuclide-buck-files@0.0.35
├── nuclide-busy-signal@0.0.35
├── nuclide-clang-atom@0.0.35
├── nuclide-clipboard-path@0.0.35
├── nuclide-code-format@0.0.35
├── nuclide-code-highlight@0.0.35
├── nuclide-debugger-atom@0.0.35
├── nuclide-debugger-hhvm@0.0.35
├── nuclide-debugger-lldb@0.0.35
├── nuclide-diagnostics-store@0.0.35
├── nuclide-diagnostics-ui@0.0.35
├── nuclide-diff-view@0.0.35
├── nuclide-file-tree@0.0.35
├── nuclide-file-watcher@0.0.35
├── nuclide-find-references@0.0.35
├── nuclide-flow@0.0.35
├── nuclide-format-js@0.0.35
├── nuclide-fuzzy-filename-provider@0.0.35
├── nuclide-hack@0.0.35
├── nuclide-hack-symbol-provider@0.0.35
├── nuclide-health@0.0.35
├── nuclide-hg-repository@0.0.35
├── nuclide-home@0.0.35
├── nuclide-installer@0.0.35
├── nuclide-language-hack@0.0.35
├── nuclide-move-pane@0.0.35
├── nuclide-objc@0.0.35
├── nuclide-ocaml@0.0.35
├── nuclide-open-filenames-provider@0.0.35
├── nuclide-quick-open@0.0.35
├── nuclide-react-native-inspector@0.0.35
├── nuclide-recent-files-provider@0.0.35
├── nuclide-recent-files-service@0.0.35
├── nuclide-remote-projects@0.0.35
├── nuclide-service-monitor@0.0.35
├── nuclide-test-runner@0.0.35
├── nuclide-toolbar@0.0.35
├── nuclide-type-hint@0.0.35
├── nuclide-url-hyperclick@0.0.35
└── tool-bar@0.4.0

### Config
```
"*":
  core:
    disabledPackages: [
      "tree-view"
    ]
  editor:
    fontSize: 12
    invisibles: {}
    showIndentGuide: true
    tabLength: 4
    tabType: "hard"
  "exception-reporting":
    userId: "7af243c2-4b2f-3ad6-e0a3-28391c4bb54b"
  "file-watcher":
    promptWhenFileHasChangedOnDisk: false
  nuclide:
    remoteProjectsConfig: []
  "nuclide-home": {}
  welcome:
    showOnStartup: false

```

**Comment by nmote** [comment]
You're on a very old version of Nuclide from back when we distributed it as many different packages. Please remove the `nuclide-*` packages and `hyperclick` and install the `nuclide` package.

Alternatively, if you just install the `nuclide` package it should instruct you on how to remove the old packages on startup.

**Comment by ssorallen** [comment]
You can follow the following instructions to uninstall the old versions of Nuclide packages: http://nuclide.io/docs/help/troubleshooting/#uninstalling-older-versions-of-nuclide
