### ISSUE TITLE
Uncaught TypeError: Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by juanmirocks** [facebook/nuclide#501]
[Enter steps to reproduce below:]

1. Just opening Atom after installing nuclide. Many other errors like that. `Component` is Undefined

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.136.0

### Stack Trace

Uncaught TypeError: Cannot read property 'render' of undefined

```
At /Users/jmcejuela/.atom/packages/nuclide/pkg/nuclide-side-bar/lib/main.js:170

TypeError: Cannot read property 'render' of undefined
    at renderPanelSync (/Users/jmcejuela/.atom/packages/nuclide/pkg/nuclide-side-bar/lib/main.js:170:63)
    at setState (/Users/jmcejuela/.atom/packages/nuclide/pkg/nuclide-side-bar/lib/main.js:112:5)
    at Object.registerView (/Users/jmcejuela/.atom/packages/nuclide/pkg/nuclide-side-bar/lib/main.js:264:5)
    at Object.consumeNuclideSideBar (/Users/jmcejuela/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/main.js:341:11)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "scala-worksheet",
      "linter-pylint",
      "tree-view"
    ],
    "projectHome": "/Users/jmcejuela/Work/hck/"
  },
  "nuclide": {
    "installRecommendedPackages": true
  }
}
```

### Installed Packages

```coffee
# User
Ensime, v0.38.1
browser-plus, v0.0.54
color-picker, v2.1.1
file-icons, v1.6.19
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
hyperclick, v0.0.35
intentions, v1.0.5
java-importer, v1.4.1
jshint, v1.8.5
language-babel, v2.20.10
language-docker, v1.1.6
language-generic-config, v1.0.0
language-gitignore, v0.2.0
language-ini, v1.16.0
language-ocaml, v1.1.2
language-scala, v1.1.6
language-thrift, v1.0.2
last-cursor-position, v0.9.0
linter, v1.11.4
linter-docker, v0.1.2
linter-flake8, v1.13.0
linter-htmlhint, v1.1.0
linter-javac, v1.8.1
linter-xmllint, v1.3.4
minimap, v4.21.0
nuclide, v0.136.0
pigments, v0.26.0
project-manager, v2.7.6
react, v0.14.2
remote-edit, v1.8.24
remote-sync, v3.5.0
tabular, v0.1.0
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by shushz** [comment]
Nuclide has recently changed its module loading logic to make it load faster. Unfortunately it doesn't always play nicely with Atom's cache. Could you please reload Atom and see whether this persists?

**Comment by shushz** [comment]
@juanmirocks  I think you confirmed in https://github.com/facebook/nuclide/issues/500 that after a restart it works for you. Closing the issue.
