### ISSUE TITLE
Uncaught Error: Cannot find module '../../nuclide-commons'

### ISSUE THREAD

**Issue by aarmand** [facebook/nuclide#514]
UPDATE: Upon restarting Atom AppDelegate opens. It might be that the Nuclide update that was just prompted and processed needed Atom to restart. I am now getting a 

### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).Uncaught Error: Cannot find module '../../nuclide-commons' a clang error: Diagnostics are disabledd due to lack of compilation flag.

### Additional Details
* Installed packages (`apm ls --installed`): true

1. This happened after open the React-Native project created with a react-native init 'project-name' command.
2. Running react-native run-ios get following error in Xcode simulator. Could not connect to development server. I then went to apply the troubleshooting recommendation found http://facebook.github.io/react-native/docs/troubleshooting.html#content. 
3. I open the project in Atom, run command shift F to find AppDelagate.m file to make the recommended changes. Once the file is found I try to open it by clicking on the Project Find Results item. Once I click, Nuclide throws that error and I am unable to open the file to make the changes recommended.

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [nuclide-busy-signal](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Uncaught Error: Cannot find module '../../nuclide-commons'

```
At /Users/klik/.atom/packages/nuclide/pkg/nuclide-busy-signal/lib/BusySignalProviderBase.js:136

Error: Cannot find module '../../nuclide-commons'
  at Module._resolveFilename (module.js:338:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:289:25)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at _nuclideCommons (/Users/klik/.atom/packages/nuclide/pkg/nuclide-busy-signal/lib/BusySignalProviderBase.js:40:29)
  at DedupedBusySignalProviderBase.reportBusy (/Users/klik/.atom/packages/nuclide/pkg/nuclide-busy-signal/lib/BusySignalProviderBase.js:131:67)
  at ArcanistDiagnosticsProvider._runLintWithBusyMessage (/Users/klik/.atom/packages/nuclide/pkg/nuclide-arcanist/lib/ArcanistDiagnosticsProvider.js:108:39)
  at /Users/klik/.atom/packages/nuclide/pkg/nuclide-commons/lib/debounce.js:59:21
  at TextEventDispatcher._dispatchEvents (/Users/klik/.atom/packages/nuclide/pkg/nuclide-text-event-dispatcher/lib/TextEventDispatcher.js:268:11)
  at /Users/klik/.atom/packages/nuclide/pkg/nuclide-text-event-dispatcher/lib/TextEventDispatcher.js:233:22
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:431:21)
  at atom-tabs.TabBarView.onMouseDown (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:658:19)

```

### Commands

```
     -1:27.2.0 core:move-right (div.nuclide-file-tree.focusable-panel.tree-view)
     -1:21.1.0 project-find:show (atom-text-editor.editor.is-focused)
     -1:04.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "linter-flow",
      "linter"
    ],
    "projectHome": "/Users/klik/projects"
  }
}
```

### Installed Packages

```coffee
# User
flow, v0.5.3
language-babel, v2.23.0
nuclide, v0.139.0

# Dev
No dev packages
```

**Comment by nmote** [comment]
Try restarting. This looks like an issue with Atom's module cache being out of date across a Nuclide upgrade.

By the way, the `flow` package you have installed is not related to Facebook's Flow project.

**Comment by aarmand** [comment]
Restarting worked. Thanks for the flow tip. I uninstalled it. other problem is solved following [this issue](https://github.com/facebook/react-native/issues/5747) to this [http://stackoverflow.com/questions/35563025/new-react-native-app-has-typeerror-babelhelpers-typeof-is-not-a-function-ios](url)

**Comment by aarmand** [comment]
Restarting worked. Thanks for the flow tip. I uninstalled it. other problem is solved following [this issue](https://github.com/facebook/react-native/issues/5747) to this [http://stackoverflow.com/questions/35563025/new-react-native-app-has-typeerror-babelhelpers-typeof-is-not-a-function-ios](url)
