### ISSUE TITLE
Uncaught Error: Cannot find module '../../nuclide-atom-helpers'

### ISSUE THREAD

**Issue by irvinebroque** [facebook/nuclide#518]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.139.0

### Stack Trace

Uncaught Error: Cannot find module '../../nuclide-atom-helpers'

```
At /Users/brendan/.atom/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:52

Error: Cannot find module '../../nuclide-atom-helpers'
  at Module._resolveFilename (module.js:338:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:289:25)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at _nuclideAtomHelpers (/Users/brendan/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/DiagnosticsPane.js:28:33)
  at onRowClick (/Users/brendan/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/DiagnosticsPane.js:144:32)
  at diagnosticCells.push.React.createElement.onClick (/Users/brendan/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/DiagnosticsPane.js:249:15)
  at Object.invokeGuardedCallback (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:26:12)
  at executeDispatch (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:87:21)
  at Object.executeDispatchesInOrder (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:110:5)
  at executeDispatchesAndRelease (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:42:22)
  at executeDispatchesAndReleaseTopLevel (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:53:10)
  at Array.forEach (native)
  at forEachAccumulated (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/forEachAccumulated.js:24:9)
  at Object.EventPluginHub.processEventQueue (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:215:7)
  at runEventQueueInBatch (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
  at handleTopLevelImpl (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:73:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:97:20)
  at ReactEventListener.dispatchEvent (/Users/brendan/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:150:20)

```

### Commands

```
     -0:45.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.7.0 nuclide-file-tree:reveal-text-editor (atom-text-editor.editor.is-focused)
     -0:35.7.0 nuclide-file-tree:toggle (atom-workspace.workspace.theme-one-dark-syntax.theme-one-dark-ui.scrollbars-visible-always.find-visible)
     -0:20.7.0 nuclide-file-tree:rename-selection (span.)
     -0:17.3.0 core:confirm (atom-text-editor.mini.is-focused)
  2x -0:13.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
 20x -0:09.6.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:08.2.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:08.0 core:copy (atom-text-editor.editor.is-focused)
     -0:07.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:07.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:07.3.0 core:move-left (atom-text-editor.editor.is-focused)
 18x -0:07.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:05.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "linter",
      "language-javascript-jsx",
      "tool-bar-almighty",
      "tool-bar"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-arcanist": {},
    "nuclide-buck-files": {},
    "nuclide-debugger-hhvm": {},
    "nuclide-file-tree": {
      "revealFileOnSwitch": true
    },
    "nuclide-flow": {
      "enableStructuredTypeHints": true
    },
    "nuclide-format-js": {},
    "nuclide-health": {},
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-ocaml": {},
    "nuclide-output": {},
    "nuclide-working-sets": {}
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.139.0
sort-lines, v0.14.0

# Dev
No dev packages
```

**Comment by shushz** [comment]
This seems to be related to Atom's module cache. Restarting Atom should solve that.

**Comment by nmote** [comment]
@zertosh wrote something that will make Nuclide refuse to start after an upgrade until Atom is restarted. That should solve all these module cache issues.

**Comment by zertosh** [comment]
It was f60e755db8c1d1d7c1050fd9876349b544ebf4ae
