### ISSUE TITLE
Uncaught Error: Cannot find module './relativeDate'

### ISSUE THREAD

**Issue by ttkzee** [facebook/nuclide#520]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.139.0

### Stack Trace

Uncaught Error: Cannot find module './relativeDate'

```
At module.js:340

Error: Cannot find module './relativeDate'
  at Module._resolveFilename (module.js:338:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:289:25)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at requireFromCache (/Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-commons/lib/main.js:18:24)
  at Object.get [as relativeDate] (/Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-commons/lib/main.js:205:14)
  at getComponentForItem (/Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-recent-files-provider/lib/RecentFilesProvider.js:170:88)
  at QuickSelectionComponent.componentForItem (/Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:518:69)
  at /Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:733:22
  at Array.map (native)
  at /Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:718:60
  at Array.map (native)
  at /Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:684:52
  at Array.map (native)
  at QuickSelectionComponent.render (/Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:679:35)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:687:34)
  at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:707:32)
  at [object Object].ReactCompositeComponentMixin._updateRenderedComponent (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:659:36)
  at [object Object].ReactCompositeComponentMixin._performComponentUpdate (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:643:10)
  at [object Object].ReactCompositeComponentMixin.updateComponent (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:572:12)
  at [object Object].ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:511:12)
  at Object.ReactReconciler.performUpdateIfNecessary (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:122:22)
  at runBatchedUpdates (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:143:21)
  at ReactReconcileTransaction.Mixin.perform (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at ReactUpdatesFlushTransaction.Mixin.perform (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at ReactUpdatesFlushTransaction._assign.perform (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:89:38)
  at Object.flushBatchedUpdates (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:165:19)
  at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:202:25)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:149:16)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.enqueueUpdate (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:194:22)
  at enqueueUpdate (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactUpdateQueue.js:22:16)
  at Object.ReactUpdateQueue.enqueueSetState (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactUpdateQueue.js:201:5)
  at QuickSelectionComponent.ReactComponent.setState (/Users/tsogtook/.atom/packages/nuclide/node_modules/react/lib/ReactComponent.js:67:16)
  at QuickSelectionComponent._updateResults (/Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:303:12)
  at QuickSelectionComponent.handleResultsChange (/Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:288:12)
  at later (/Users/tsogtook/.atom/packages/nuclide/pkg/nuclide-commons/lib/debounce.js:41:23)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.139.0

# Dev
No dev packages
```

**Comment by nmote** [comment]
Looks like a dup of #518. I know the title isn't the same but I believe it's the same root cause.
