### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by guinunez** [facebook/nuclide#523]
[Enter steps to reproduce below:]

1. Just installed this package on my atom installation and I get this error several times whenever I open a file

**Atom Version**: 0.165.0
**System**: linux 4.4.0-22-generic
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.139.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/guille/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:600

TypeError: undefined is not a function
  at SearchResultManager.getRenderableProviders (/home/guille/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:600:46)
  at new QuickSelectionComponent (/home/guille/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:140:48)
  at [object Object].ReactCompositeComponentMixin._constructComponentWithoutOwner (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:248:14)
  at [object Object].ReactCompositeComponentMixin._constructComponent (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:241:19)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:159:21)
  at Object.ReactReconciler.mountComponent (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:39:35)
  at [object Object].ReactCompositeComponentMixin.performInitialMount (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:297:34)
  at [object Object].ReactCompositeComponentMixin.mountComponent (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactCompositeComponent.js:222:21)
  at Object.ReactReconciler.mountComponent (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactReconciler.js:39:35)
  at mountComponentIntoNode (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:103:32)
  at ReactReconcileTransaction.Mixin.perform (/home/guille/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at batchedMountComponentIntoNode (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:124:15)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/guille/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:97:20)
  at Object.ReactMount._renderNewRootComponent (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:277:18)
  at Object.ReactMount._renderSubtreeIntoContainer (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:354:32)
  at Object.ReactMount.render (/home/guille/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:374:23)
  at Activation._render (/home/guille/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/main.js:205:68)
  at Activation._updateScrollableHeight (/home/guille/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/main.js:200:36)
  at later (/home/guille/.atom/packages/nuclide/pkg/commons-node/debounce.js:41:23)

```

### Commands

```
```

### Config

```
{
  "core": {
    "customFileTypes": {
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ],
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source": {}
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emmet, v2.4.3
nuclide, v0.139.0
php-twig, v4.0.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by nmote** [comment]
You have an unbelievably ancient version of Atom. Please upgrade. Specifically I suspect this error stems from the use of `Array.from` which did not exist in Atom's version of Node until 1.3 or so.
