### ISSUE TITLE
Uncaught SyntaxError: Unexpected token }

### ISSUE THREAD

**Issue by nskpaun** [facebook/nuclide#525]
Start react packager from command pallet
1. cmd-shift-p
2. type start packager
3. press return

**Atom Version**: 1.7.4
**System**: Mac OS X 10.10.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.139.30535848
### Stack Trace

Uncaught SyntaxError: Unexpected token }

```
At /opt/facebook/nuclide/0.139.30535848/nuclide/node_modules/rxjs/observable/PromiseObservable.js:78

SyntaxError: Unexpected token }
  at Object.parse (native)
  at /opt/facebook/nuclide/0.139.30535848/nuclide/pkg/nuclide-react-native/lib/packager/getCommandInfo.js:82:21
  at [object Generator].next (native)
  at step (/opt/facebook/nuclide/0.139.30535848/nuclide/pkg/nuclide-react-native/lib/packager/getCommandInfo.js:128:273)

```
### Commands

```
     -2:43.4.0 nuclide-quick-open:find-anything-via-omni-search (atom-text-editor.editor.is-focused)
     -2:40.1.0 core:confirm (atom-text-editor.mini.is-focused)
     -2:40 tabs:keep-preview-tab (atom-text-editor.editor)
     -2:35.6.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  3x -2:32.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  5x -2:30.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:17.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
 13x -2:17.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:04.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.3.0 nuclide-react-native:start-packager (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "TARGETS",
        "cconf",
        "cinc",
        "mcconf",
        "tw",
        "BUCK"
      ]
    },
    "disabledPackages": [
      "fb-nuclide-installer",
      "tree-view",
      "fuzzy-finder",
      "metrics"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-arcanist": {
      "blacklistedLinters": [
        "FBHACK"
      ]
    },
    "nuclide-diff-view": {
      "toolbarVisible": true
    },
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-remote-projects": {
      "shutdownServerAfterDisconnection": false
    }
  }
}
```
### Installed Packages

``` coffee
# User
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.23.2
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
nuclide, v0.139.30535848
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by mostafaeweda** [comment]
cc @matthewwithanm for the `react-native` stuff

**Comment by matthewwithanm** [comment]
Oh interesting. Do you have an invalid package.json?

**Comment by nskpaun** [comment]
I don't think I've made any changes to package.json. I get this every time I try to use the packager on my macbook and my mac pro

**Comment by mostafaeweda** [comment]
cc @zertosh

**Comment by mostafaeweda** [comment]
Please upgrade to the latest Atom & Nuclide and this should be fixed
