### ISSUE TITLE
Nuclide@0.141.0 server fails to start on node v4.4.5

### ISSUE THREAD

**Issue by avaly** [facebook/nuclide#532]
### Issue and Steps to Reproduce
Upgrading `nuclide` to version `0.141.0` in order to match the latest Nuclide client version, the server fails to start.

```
$ cat nuclide-2016-06-06T10\:17\:46.nohup.out 
/Users/avaly/.nvm/versions/node/v4.4.5/lib/node_modules/nuclide/pkg/nuclide-node-transpiler/lib/NodeTranspiler.js:29
const PREFIX_LENGTH = Math.max(...PREFIXES.map(x => x.length));
                               ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/avaly/.nvm/versions/node/v4.4.5/lib/node_modules/nuclide/pkg/nuclide-node-transpiler/lib/main.js:21:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

### Expected Behavior

`nuclide-start-server` should start.

### Actual Behavior

`nuclide-start-server` fails to start.

### Versions
* Atom: `1.7.4`
* Nuclide: server: `0.141.0` / client: `0.141.31158982`
* Client OS: Ubuntu 16.04
* Server OS (optional): Mac OS X 10.11.6
* nvm: `0.31.1`
* node: `4.4.5`

### Additional Details

Upgraded from `nuclide@0.138.0` which worked on the same setup.

**Comment by avaly** [comment]
This is related to f0557268dd1d5263bb3821e6a07c34a0a15101f7.

The docs only mention a minimum node version of 0.12, not 5.

**Comment by zertosh** [comment]
Docs are incorrect, sorry. We target the same Node version that is bundled with the Atom version we support. Currently it's Atom 1.7.4 and Node 5.1.1, https://github.com/facebook/nuclide/blob/2813c84/package.json#L106-L109.
