### ISSUE TITLE
Uncaught TypeError: validateDOMNesting.updatedAncestorInfo is not a function

### ISSUE THREAD

**Issue by RTsGIT** [facebook/nuclide#547]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.141.0
### Stack Trace

Uncaught TypeError: validateDOMNesting.updatedAncestorInfo is not a function

```
At /Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/ReactDOMContainerInfo.js:28

TypeError: validateDOMNesting.updatedAncestorInfo is not a function
  at ReactDOMContainerInfo (/Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/ReactDOMContainerInfo.js:28:52)
  at mountComponentIntoNode (/Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:103:83)
  at ReactReconcileTransaction.Mixin.perform (/Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at batchedMountComponentIntoNode (/Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:124:15)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:97:20)
  at Object.ReactMount._renderNewRootComponent (/Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:277:18)
  at Object.ReactMount._renderSubtreeIntoContainer (/Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:354:32)
  at Object.ReactMount.render (/Users/rpanidepu/.atom/packages/nuclide/node_modules/react/lib/ReactMount.js:374:23)
  at RemoteProjectsController._renderStatusBar (/Users/rpanidepu/.atom/packages/nuclide/pkg/nuclide-remote-projects/lib/RemoteProjectsController.js:161:68)
  at RemoteProjectsController._updateConnectionStatus (/Users/rpanidepu/.atom/packages/nuclide/pkg/nuclide-remote-projects/lib/RemoteProjectsController.js:92:14)
  at later (/Users/rpanidepu/.atom/packages/nuclide/pkg/commons-node/debounce.js:41:23)

```
### Commands

```
     -3:22.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
undefined -3:21.9.0 blur (a.btn-issue.btn.btn-error)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```
### Installed Packages

``` coffee
# User
nuclide, v0.141.0
terminal-plus, v0.14.5
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by jgebhardt** [comment]
Are you able to reproduce this consistently? If so, would you mind sharing repro steps? Are you running Atom in dev mode? Thanks!

**Comment by ssorallen** [comment]
Did this happen after an automatic update to Nuclide? Please restart Atom and see if the problem persists.

**Comment by RTsGIT** [comment]
I had the issue when ever I have opened .js file from command line and there is already project opened in Atom.. @jgebhardt  No I am using straight forward atom.

**Comment by ssorallen** [comment]
This sounds related to https://github.com/facebook/nuclide/issues/463 and https://github.com/jgebhardt/react-for-atom/issues/13 given that this is from Atom v1.8.0.

**Comment by jgebhardt** [comment]
Please upgrade Atom and Nuclide and file another issue if you still experience this.
