### ISSUE TITLE
Uncaught TypeError: validateEventDispatches is not a function

### ISSUE THREAD

**Issue by liang37038** [facebook/nuclide#548]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.141.0

### Stack Trace

Uncaught TypeError: validateEventDispatches is not a function

```
At /Users/lwj/.atom/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:99

TypeError: validateEventDispatches is not a function
  at Object.executeDispatchesInOrder (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:99:5)
  at executeDispatchesAndRelease (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:42:22)
  at executeDispatchesAndReleaseTopLevel (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:53:10)
  at Array.forEach (native)
  at forEachAccumulated (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/forEachAccumulated.js:24:9)
  at Object.EventPluginHub.processEventQueue (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:215:7)
  at runEventQueueInBatch (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
  at handleTopLevelImpl (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:73:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:97:20)
  at ReactEventListener.dispatchEvent (/Users/lwj/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:150:20)

```

### Commands

```
  2x -2:21.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:20.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:15.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:14.8.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:14.5.0 editor:cut-to-end-of-line (atom-text-editor.editor.is-focused)
     -2:13.6.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -2:13.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:12.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:12.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:09.6.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
     -2:09.0 core:save (atom-text-editor.editor.is-focused)
  5x -0:58.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:56.9.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
  3x -0:56.6.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:56 core:backspace (atom-text-editor.editor.is-focused)
     -0:55.1.0 core:save (atom-text-editor.editor.is-focused.hyperclick)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.11.0
docblockr, v0.7.3
js-hyperclick, v1.4.2
nuclide, v0.141.0
pigments, v0.29.2

# Dev
No dev packages
```

**Comment by courthead** [comment]
This happens to me regularly when using `atom filename` from the Terminal to open a file in Atom.

**Comment by jgebhardt** [comment]
This is due to another package using a second instance of React. Most likely the culprit is atom-typescript, which uses react@0.13 rather than `react-for-atom`: https://github.com/TypeStrong/atom-typescript/blob/master/package.json
