### ISSUE TITLE
Uncaught TypeError: Cannot read property 'close' of null

### ISSUE THREAD

**Issue by zimpower** [facebook/nuclide#562]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.147.0
### Stack Trace

Uncaught TypeError: Cannot read property 'close' of null

```
At zlib.js:465

TypeError: Cannot read property 'close' of null
  at InflateRaw.Zlib.close (zlib.js:465:15)
  at PerMessageDeflate.cleanup (/Users/simonhards/Dropbox/.atom/packages/nuclide/node_modules/ws/lib/PerMessageDeflate.js:82:46)
  at WebSocket.cleanupWebsocketResources (/Users/simonhards/Dropbox/.atom/packages/nuclide/node_modules/ws/lib/WebSocket.js:957:54)
  at emitNone (events.js:72:20)
  at Socket.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:905:12)
  at doNTCallback2 (node.js:465:9)
  at process._tickDomainCallback (node.js:420:17)

```
### Commands

```
  4x -3:11.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:01.1.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -3:00.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:59.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -2:59.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:59.1.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:32.9.0 editor:move-line-up (atom-text-editor.editor.is-focused)
     -1:31.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:30.6.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:29.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:29 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:29 snippets:expand (atom-text-editor.editor.is-focused)
     -1:29 editor:indent (atom-text-editor.editor.is-focused)
     -1:28.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:28.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:28.6.0 editor:indent (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "language-gfm",
      "tree-view"
    ],
    "themes": [
      "one-dark-ui",
      "spacegray-atom-dark-syntax"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
color-picker, v2.1.1
highlight-selected, v0.11.2
language-jade, v0.7.1
language-latex, v0.6.1
language-markdown, v0.14.1
linter, v1.11.14
linter-jsxhint, v0.1.2
markdown-preview-plus, v2.4.0
minimap, v4.24.6
nuclide, v0.147.0
pdf-view, v0.50.0
pigments, v0.29.2
react, v0.15.0
spacegray-atom-dark-syntax, v1.1.1

# Dev
No dev packages
```

**Comment by yinghuitan** [comment]
@zimpower, the callstack is not enough for us to figure out what's going on. Can you add detailed reproduce steps?

**Comment by zimpower** [comment]
I was running the react native debugger and packager. Atom window was actually in the background when this happened... So not sure exactly what caused it. 

Happy to leave and let you know if it happens again.

**Comment by shanecav** [comment]
I'm having the same issue while using the React Native Debugger. While I'm using the debugger, it will sporadically show a notification that it's been "Datached from the target", at which point I get the same Uncaught TypeError as above. I have to restart the debugger and refresh the simulator in order to get back to debugging. I haven't noticed a trend as to what's causing this yet - I'll reply here if I do.

**Comment by danfairs** [comment]
I'm also seeing this - unfortunately, it's hard to repro deterministically. However, I'm using a fresh install of just Atom 1.8.0 and Nuclide 0.161.0, nothing else installed.

**Comment by mostafaeweda** [comment]
The newly integrated RN debugger should have this fixed already
