### ISSUE TITLE
Clicking "Uncommitted Changes" in side-bar for Git repo throws

### ISSUE THREAD

**Issue by ssorallen** [facebook/nuclide#569]
### Issue and Steps to Reproduce
* Open a Git repo in Nuclide
* Open the source control side bar
* Click the "Uncommitted Changes" line

### Expected Behavior
No exception

### Actual Behavior

```
/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14
Hide Stack Trace
AssertionError: false == true
  at RepositorySectionComponent._handleUncommittedChangesClick (/Users/joep/.atom/packages/nuclide/pkg/nuclide-source-control-side-bar/lib/RepositorySectionComponent.js:81:43)
  at Object.r (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:21971)
  at a (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:23434)
  at Object.s [as executeDispatchesInOrder] (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:23649)
  at p (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:20137)
  at f (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:20263)
  at Array.forEach (native)
  at r (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:12963)
  at Object.h.processEventQueue (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:21217)
  at r (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:22235)
  at Object.i.handleTopLevel [as _handleTopLevel] (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:22336)
  at i (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:22783)
  at r.o.perform (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at Object.d.batchedUpdates (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:17100)
  at Object.i [as batchedUpdates] (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:15:16775)
  at v.dispatchEvent (/Users/joep/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:23665)
```

Stack trace copied from https://github.com/facebook/nuclide/issues/513#issuecomment-228079434

**Comment by fdalsotto** [comment]
this might be a dumb question, but how can I install this fix in atom? Thanks
