### ISSUE TITLE
Uncaught TypeError: getActions(...).setFocusedNode is not a function

### ISSUE THREAD

**Issue by markslight** [facebook/nuclide#572]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.148.0

### Stack Trace

Uncaught TypeError: getActions(...).setFocusedNode is not a function

```
At /Users/mark/.atom/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:52

TypeError: getActions(...).setFocusedNode is not a function
  at FileTreeEntryComponent._onClick (/Users/mark/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeEntryComponent.js:281:22)
  at Object.invokeGuardedCallback (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/ReactErrorUtils.js:26:12)
  at executeDispatch (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:87:21)
  at Object.executeDispatchesInOrder (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/EventPluginUtils.js:110:5)
  at executeDispatchesAndRelease (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:42:22)
  at executeDispatchesAndReleaseTopLevel (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:53:10)
  at Array.forEach (native)
  at forEachAccumulated (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/forEachAccumulated.js:24:9)
  at Object.EventPluginHub.processEventQueue (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/EventPluginHub.js:215:7)
  at runEventQueueInBatch (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
  at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
  at handleTopLevelImpl (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:73:24)
  at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/Transaction.js:136:20)
  at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
  at Object.batchedUpdates (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/ReactUpdates.js:97:20)
  at ReactEventListener.dispatchEvent (/Users/mark/.atom/packages/nuclide/node_modules/react/lib/ReactEventListener.js:150:20)

```

### Commands

```
     -0:33.9.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-working-sets": {
      "workingSets": [
        {
          "name": "app",
          "active": true,
          "uris": [
            "/Users/mark/projects/MyFaceHub/react/MyFaceHub/App.js",
            "/Users/mark/projects/MyFaceHub/react/MyFaceHub/components",
            "/Users/mark/projects/MyFaceHub/react/MyFaceHub/index.android.js",
            "/Users/mark/projects/MyFaceHub/react/MyFaceHub/index.ios.js",
            "/Users/mark/projects/MyFaceHub/react/MyFaceHub/package.json",
            "/Users/mark/projects/MyFaceHub/react/MyFaceHub/screens",
            "/Users/mark/projects/MyFaceHub/react/MyFaceHub/style"
          ]
        }
      ]
    }
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.148.0

# Dev
No dev packages
```

**Comment by shushz** [comment]
Please try restarting Atom, it seems like a source caching issue.
