### ISSUE TITLE
Failed to active the nuclide-quick-open

### ISSUE THREAD

**Issue by lenage** [facebook/nuclide#607]
Hi there, 
Thank you for creating a such great tools, 
I just install on Mac and can't quick-open files, 
here are steps to reproduce:

1. Open Atom
2. Press `command + T`

## information

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [nuclide-quick-open](https://github.com/facebooknuclideapm/nuclide-quick-open) package, v0.0.21

### Stack Trace

Failed to activate the nuclide-quick-open package

```
At Cannot read property 'bool' of undefined

TypeError: Cannot read property 'bool' of undefined
    at Object.<anonymous> (/Users/lenage/.atom/packages/nuclide-quick-open/node_modules/nuclide-ui-atom-input/lib/AtomInput.js:26:30)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.load (/Users/lenage/.atom/packages/nuclide-file-tree/node_modules/nuclide-ui-tree/node_modules/nuclide-atom-npm/lib/main.js:41:36)
    at Object.<anonymous> (/Users/lenage/.atom/packages/nuclide-quick-open/node_modules/nuclide-ui-atom-input/lib/main.js:12:46)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/lenage/.atom/packages/nuclide-quick-open/lib/QuickSelectionComponent.js:17:17)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at getQuickSelectionComponentLazily (/Users/lenage/.atom/packages/nuclide-quick-open/lib/main.js:54:32)
    at Activation._render (/Users/lenage/.atom/packages/nuclide-quick-open/lib/main.js:165:35)
    at new Activation (/Users/lenage/.atom/packages/nuclide-quick-open/lib/main.js:88:34)
    at Object.activate (/Users/lenage/.atom/packages/nuclide-quick-open/lib/main.js:249:20)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:02.1.0 nuclide-quick-open:toggle-omni-search (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "sidebar",
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
emacs-plus, v0.11.0
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
language-babel, v2.31.0
language-ini, v1.16.0
language-ocaml, v1.1.2
language-thrift, v1.0.2
merge-conflicts, v1.4.4
nuclide, v0.150.0
nuclide-code-format, v0.0.21
nuclide-diff-view, v0.0.21
nuclide-file-tree, v0.0.21
nuclide-file-watcher, v0.0.21
nuclide-flow, v0.0.21
nuclide-hack, v0.0.21
nuclide-hg-repository, v0.0.21
nuclide-installer, v0.0.21
nuclide-language-hack, v0.0.21
nuclide-quick-open, v0.0.21
nuclide-remote-projects, v0.0.21
nuclide-type-hint, v0.0.21
react-snippets, v0.4.2
tool-bar, v1.0.0

# Dev
No dev packages
```

any idea to fix ?

**Comment by lenage** [comment]
seems duplicated with #469 ?

**Comment by johnislarry** [comment]
@lenage the function that caused this error in the stacktrace was removed over seven months ago:

https://github.com/facebook/nuclide/commit/49517d10f522100d6bd4e74a372bea963ef2bef4#diff-b825fd5d04802d4d33044727f93d6d25L61

Somehow you're running the wrong code.  Maybe try `rm -rf ~/.atom/packages/nuclide` and then re-installing via the atom package manager?  The issue is definitely that you're running old code though.
