### ISSUE TITLE
Merlin raises error when being used by Nuclide

### ISSUE THREAD

**Issue by benedictleejh** [facebook/nuclide#615]
### Issue and Steps to Reproduce
When opening an OCaml source file, Merlin starts up then immediately fails with `[ERROR] nuclide - Ocamlmerlin raised an error: ["failure","invalid arguments"]`. Then

```
Uncaught (in promise) Error: Ocamlmerlin returned an error
~/.atom/packages/nuclide/pkg/nuclide-ocaml-base/lib/MerlinProcess.js:263
  at Error (native)
  at Interface.<anonymous> (~/.atom/packages/nuclide/pkg/nuclide-ocaml-base/lib/MerlinProcess.js:263:20)
  at emitOne (events.js:77:13)
  at Interface.emit (events.js:169:7)
  at Interface._onLine (readline.js:210:10)
  at Interface.<anonymous> (readline.js:340:12)
  at Array.forEach (native)
  at Interface._normalWrite (readline.js:339:11)
  at Socket.ondata (readline.js:86:10)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:523:20)
```

Steps to reproduce:
1. Open an OCaml source file

### Expected Behavior
Nuclide should behave normally, and there should not be an error from Merlin

### Actual Behavior
Merlin crashes, and no longer responds; no completion, type hints, etc.

### Versions
* Atom: 1.6.2/1.8.0
* Nuclide: 0.136.0/0.155.0
* Client OS: Linux 64-bit
* Server OS (optional):
* Merlin: 2.5.0
* OCaml: 4.02.3

### Additional Details
* Installed packages (`apm ls --installed`):

Atom 1.6.2
```
~/.atom/packages (46)
├── Stylus@3.0.0
├── asciidoc-preview@2.5.2
├── atom-beautify@0.29.9
├── atom-jade@0.3.0
├── atom-material-ui@1.2.13
├── autocomplete-haskell@0.6.5
├── build@0.65.0
├── build-gulp@0.11.0
├── build-make@0.10.0
├── build-rake@0.1.1
├── busy@0.5.0
├── file-icons@1.7.17
├── gitignore-snippets@0.2.5
├── gl-light-syntax@2.2.0
├── haskell-ghc-mod@1.16.0
├── haskell-pointfree@0.1.3
├── highlight-selected@0.11.2
├── ide-haskell@1.6.5
├── ide-haskell-repl@0.0.23
├── ide-haskell-stack@0.0.3
├── jade-beautify@0.1.5
├── language-asciidoc@1.5.1
├── language-dots@0.0.4
├── language-elm@1.5.0
├── language-gradle@0.0.3
├── language-groovy@0.6.0
├── language-haskell@1.7.17
├── language-latex@0.6.1
├── language-lisp@0.2.0
├── language-ocaml@1.1.2
├── language-pfm@0.82.0
├── language-slim@0.5.0
├── latextools@0.8.1
├── linter@1.11.14
├── linter-elm-make@0.12.2
├── markdown-preview-plus@2.4.0
├── minimap@4.24.7
├── minimap-highlight-selected@4.4.0
├── nuclide@0.136.0
├── open-recent@5.0.0
├── pdf-view@0.50.0
├── pigments@0.31.1
├── terminal-fusion@2.2.3
├── terminal-plus@0.14.5
├── tool-bar@1.0.0
└── tool-bar-main@0.0.9
```

Atom 1.8.0
```
Community Packages (55) ~/.atom/packages
├── Stylus@3.0.0
├── atom-beautify@0.29.9
├── atom-jade@0.3.0
├── atom-material-syntax-light@0.4.5
├── atom-material-ui@1.2.13
├── autocomplete-clang@0.9.4
├── autocomplete-haskell@0.6.5
├── autocomplete-sass@0.1.0
├── build@0.65.0
├── build-cargo@0.15.0
├── build-gulp@0.11.0
├── build-make@0.10.0
├── build-rake@0.1.1
├── busy@0.5.0
├── close-tags@0.6.0
├── elm-snippets@0.1.0
├── file-icons@1.7.17
├── gitignore-snippets@0.2.5
├── gl-light-syntax@2.2.0
├── goto@1.7.1
├── haskell-ghc-mod@1.16.0
├── haskell-pointfree@0.1.3
├── highlight-selected@0.11.2
├── ide-haskell@1.6.5
├── ide-haskell-cabal@1.4.1
├── ide-haskell-hasktags@0.0.4
├── ide-haskell-repl@0.0.23
├── language-coq@0.1.0
├── language-elm@1.5.0
├── language-fish-shell@1.0.4
├── language-gitignore@0.2.0
├── language-haskell@1.7.18
├── language-idris@0.4.5
├── language-lisp@0.2.0
├── language-ocaml@1.1.2
├── language-rust@0.4.6
├── language-scheme@1.4.0
├── language-slim@0.5.0
├── linter@1.11.14
├── linter-elm-make@0.12.2
├── linter-hlint@0.4.3
├── linter-rust@0.4.6
├── lisp-paredit@0.5.3
├── markdown-pdf@1.5.0
├── markdown-preview-plus@2.4.0
├── minimap@4.24.7
├── nuclide@0.155.0
├── open-recent@5.0.0
├── pdf-view@0.50.0
├── pigments@0.31.1
├── racer@0.20.0
├── rustfmt@0.1.2
├── terminal-fusion@2.3.1
├── tool-bar@1.0.0
└── tool-bar-main@0.0.9
```

Using Merlin in emacs produces no error, and behaves as expected.

Tested in a folder with a single OCaml source file.

.merlin file:
```
S .
B .
```

**Comment by johnislarry** [comment]
It could be an incompatible version of merlin.  @peterhal may know more

**Comment by peterhal** [comment]
Merlin 2.5 support was only checked in in the last couple of days. It will be available in the release after 155. 

In the mean time, Nuclide's Merlin support works with Merlin 2.3.1.

**Comment by freebroccolo** [comment]
Any update on this? I'm seeing the exact same error with merlin `2.3.1` on both the release version of nuclide and with the build from `master`.
