### ISSUE TITLE
Uncaught Error: Packager exited with non-zero exit code (8)

### ISSUE THREAD

**Issue by manicakes** [facebook/nuclide#617]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.155.0
### Stack Trace

Uncaught Error: Packager exited with non-zero exit code (8)

```
At /Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:50

Error: Packager exited with non-zero exit code (8)
  at c.project (/Users/mani/.atom/packages/nuclide/pkg/nuclide-react-native/lib/packager/PackagerActivation.js:177:89)
  at c._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:325:140)
  at c.e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.notifyNext (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:326:282)
  at b._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.notifyNext (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:275:183)
  at b._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.notifyNext (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:275:183)
  at b._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.e._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:401)
  at c.e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at e._next (/Users/mani/.atom/packages/nuclide/pkg/commons-node/stream.js:322:16)
  at e.__tryOrUnsub (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:50:141)
  at e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:49:63)
  at e._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:401)
  at e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.b.notifyNext (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:16:355)
  at b._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.b.notifyNext (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:16:355)
  at b._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:323)
  at b.e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at c.b.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:40:408)
  at c.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:18:170)
  at c.e._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:401)
  at c.e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at d._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:265:293)
  at d.e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at b._next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:331:161)
  at b.e.next (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:64)
  at ChildProcess.<anonymous> (/Users/mani/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:123:196)
  at emitTwo (events.js:92:20)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```
### Commands

```
  2x -1:48.6.0 nuclide-build:toggle-toolbar-visibility (atom-text-editor.editor.is-focused)
     -1:27.2.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:06.4.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:06.4.0 nuclide-console:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:06.3.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:47.1.0 nuclide-console:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:05.4.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:00.6.0 nuclide-console:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
nuclide, v0.155.0

# Dev
No dev packages
```

**Comment by shushz** [comment]
Seems more like a problem with an external tool rather than Nuclide itself.
But still /CC @matthewwithanm

**Comment by justingosan** [comment]
Bumping this.

Happened to me on fresh Atom install + Nuclide and importing an existing react-native project which runs fine using the react-native cli

**Comment by shushz** [comment]
Yeah, sorry - I completely lost track of this. I suspect that this is no longer an issue as this package has been updated quite a lot since. Please reopen if you see it persists.
