### ISSUE TITLE
Failed to activate the nuclide package

### ISSUE THREAD

**Issue by niaofei2008** [facebook/nuclide#618]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).
Error: "nuclide-blame-provider-hg" exported a "config"
    at /Users/sipengfei/.atom/packages/nuclide/lib/main.js:278:15
    at Array.map (native)
    at Object.activate (/Users/sipengfei/.atom/packages/nuclide/lib/main.js:266:38)
    at Package.module.exports.Package.activateNow (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:342:19
    at /Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:169:14)
    at /Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:693:36
    at /Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:458:15
    at exit (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Users/sipengfei/Downloads/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom:
* Nuclide:
* Client OS:
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by nmote** [comment]
Please include the requested information. Specifically, the versions and the installed packages.

**Comment by shushz** [comment]
Also, it seems like a code caching problem. Please restart Atom and see whether the issue persists.

**Comment by nmote** [comment]
My suspicion is that a pre-UP version of `nuclide-blame-provider-hg` is installed and it's conflicting with the post-UP version. I'd be surprised if a code caching problem could cause that, since it's been quite a long time since we moved all config into `package.json` files. Unfortunately I can't confirm that without the requested information.

**Comment by niaofei2008** [comment]
Thank you, I download the Atom before, haven't delete some files.After finish delete, no error

**Comment by shushz** [comment]
Cool, glad it worked for you :-)

**Comment by niaofei2008** [comment]
nuclide can run app on device?

**Comment by niaofei2008** [comment]
I just can run app on Simulator with nuclide now.

**Comment by PointedEars** [comment]
I had this problem when for some reason Nuclide was not properly installed, as I could not “Uninstall” it because the error message said “not found” (there might be a general problem with packages after upgrading Atom; this happened to me with other packages as well). I could also not install it via the UI since the “Install” button was missing.

After `apm install nuclide` and restarting Atom, the problem did not occur again. (This solved such problems for some, not all, other packages, too.)

Atom 1.8.0 on Mac OS X, 10.11.6

**Comment by nmote** [comment]
You can always remove packages manually by deleting them from `~/.atom/packages` if it comes to that.

**Comment by VinayMtdmcc** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.282.0


### Stack Trace

Failed to activate the nuclide package

```
At Invariant violation: "rootPackage != null"

Error: Invariant violation: "rootPackage != null"
    at FeatureLoader.activate (/Users/vinay/node_modules/nuclide-commons-atom/FeatureLoader.js:176:13)
    at /packages/nuclide/lib/main.js:261:17)
    at Package.module.exports.Package.activateNow (/Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/package.js:255:25)
    at /Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at /Users/vinay/Desktop/Atom.app/Contents/Resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
nuclide 0.282.0 
tool-bar 1.1.5 
```
Kindly help me out of this

**Comment by Bannerets** [comment]
@xlliang update atom to latest version
