### ISSUE TITLE
Uncaught TypeError: Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by zoeysiadevelopment** [facebook/nuclide#656]
[Enter steps to reproduce below:]

Open atom. this is one of dozens of errors upon launch. 

**Atom Version**: 1.9.2
**System**: Debian GNU/Linux
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.158.0

### Stack Trace

Uncaught TypeError: Cannot read property 'render' of undefined

```
At /home/zoey/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/main.js:204

TypeError: Cannot read property 'render' of undefined
  at Activation._render (/home/zoey/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/main.js:204:67)
  at Activation._updateScrollableHeight (/home/zoey/.atom/packages/nuclide/pkg/nuclide-quick-open/lib/main.js:199:36)
  at later (/home/zoey/.atom/packages/nuclide/pkg/commons-node/debounce.js:41:23)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```

### Installed Packages

```coffee
# User
crystal, v0.1.0 (active)
flow-ide, v1.1.4 (active)
git-grep-provider, v0.9.3 (active)
linter, v1.11.14 (active)
nuclide, v0.158.0 (active)
react-native-snippets, v0.3.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by yanivtal** [comment]
Is Nuclide still being supported? This is a big issue and hasn't received any response for 2 weeks.

**Comment by skreyen** [comment]
Our apologies for not responding earlier. Atom 1.9 is going to be supported in a release very soon. In the meantime, here are few workarounds you might try:

1) Upgrade to Nuclide 0.163.0 - many Atom 1.9 fixes have gone in already.
2) Downgrade Atom to 1.8.x - this version is fully supported.

Sorry again for the inconvenience. We will update this thread when 1.9 is fully supported.

**Comment by IanVS** [comment]
I assume this can be closed now, right?

**Comment by ZoeyCluff** [comment]
Yep
