### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by Andreyco** [facebook/nuclide#66]
I get error when building from source. Build process runs with sudo privileges.  
There seems to be error with *nuclide-server* package.

```bash
Installing dependencies for Node package nuclide-server...
Process Process-41:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/dev/../lib/package_manager.py", line 307, in install_dependencies
    symlink(src_dir, dest_dir, relative=True)
  File "./scripts/dev/../lib/fs.py", line 59, in symlink
    os.remove(dest)
OSError: [Errno 1] Operation not permitted: '/Users/andrejbadin/Code/nuclide/pkg/nuclide/server/node_modules/nuclide-clang'
Traceback (most recent call last):
  File "./scripts/dev/setup", line 44, in <module>
    package_manager.install_dependencies(npm, include_packages_that_depend_on_atom=include_apm)
  File "./scripts/dev/../lib/package_manager.py", line 46, in install_dependencies
    installer.install()
  File "./scripts/dev/../lib/package_manager.py", line 151, in install
    self._do_multiprocess_install()
  File "./scripts/dev/../lib/package_manager.py", line 198, in _do_multiprocess_install
    (config['name'], exitcode))
Exception: Installing package nuclide-server failed with exit code 1
`

**Comment by ssorallen** [comment]
Hi, @Andreyco. Since the codebase has changed significantly since you opened this issue, can you try pulling latest and rebuilding? I am going to close this since it happened a while ago, but please reopen if you have issues after pulling again.
