### ISSUE TITLE
Exceptions coming from Nuclide diagnostics UI

### ISSUE THREAD

**Issue by nathansobo** [facebook/nuclide#660]
I'm seeing some exceptions  like the following in Atom's internal bug tracker:

```
Error Cannot decorate a destroyed marker 
    src/decoration-manager.js:192:15 module.exports.DecorationManager.decorateMarker
    src/text-editor.js:1528:37 module.exports.TextEditor.decorateMarker
    /Users/taomeng/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/gutter.js:128:14 applyUpdateToEditor
    /Users/taomeng/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/main.js:161:7 callback
    node_modules/event-kit/lib/emitter.js:25:14 module.exports.Emitter.simpleDispatch
    node_modules/event-kit/lib/emitter.js:125:28 module.exports.Emitter.emit
    /Users/taomeng/.atom/packages/nuclide/pkg/nuclide-diagnostics-base/lib/DiagnosticStore.js:435:33 _emitFileMessages
    /Users/taomeng/.atom/packages/nuclide/pkg/nuclide-diagnostics-base/lib/DiagnosticStore.js:185:14 _invalidateFileMessagesForProvider
    /Users/taomeng/.atom/packages/nuclide/pkg/nuclide-diagnostics-base/lib/DiagnosticStore.js:158:14 invalidateMessages
    /Users/taomeng/.atom/packages/nuclide/pkg/nuclide-diagnostics-store/lib/main.js:162:18 _next
    /Users/taomeng/.atom/packages/nuclide/node_modules/rxjs/Subscriber.js:225:16 __tryOrUnsub
    /Users/taomeng/.atom/packages/nuclide/node_modules/rxjs/Subscriber.js:174:22 next
    /Users/taomeng/.atom/packages/nuclide/node_modules/rxjs/Subscriber.js:124:26 _next
    /Users/taomeng/.atom/packages/nuclide/node_modules/rxjs/Subscriber.js:88:18 next
    node_modules/event-kit/lib/emitter.js:25:14 module.exports.Emitter.simpleDispatch
    node_modules/event-kit/lib/emitter.js:125:28 module.exports.Emitter.emit
    /Users/taomeng/.atom/packages/nuclide/pkg/nuclide-diagnostics-provider-base/lib/DiagnosticsProviderBase.js:109:21 publishMessageInvalidation
    /Users/taomeng/.atom/packages/nuclide/pkg/nuclide-clang-atom/lib/ClangDiagnosticsProvider.js:225:28 invalidateBuffer
    /Users/taomeng/.atom/packages/nuclide/pkg/nuclide-clang-atom/lib/ClangDiagnosticsProvider.js:112:20 none
    node_modules/event-kit/lib/emitter.js:25:14 module.exports.Emitter.simpleDispatch
    node_modules/event-kit/lib/emitter.js:125:28 module.exports.Emitter.emit
    node_modules/text-buffer/lib/text-buffer.js:1258:29 module.exports.TextBuffer.destroy
    node_modules/text-buffer/lib/text-buffer.js:1282:14 module.exports.TextBuffer.release
    src/text-editor.js:389:19 module.exports.TextEditor.destroyed
    src/model.js:31:58 module.exports.Model.destroy
    src/pane.js:641:18 module.exports.Pane.destroyItem
    node_modules/tabs/lib/tab-bar-view.js:690:17 TabBarView.onClick
```

Looks like you're trying to decorate markers for a destroyed editor perhaps?

**Comment by nmote** [comment]
Weird, it does look like that. Can you provide repro steps and all the standard version info? Is this on Atom master? I've never seen this.

**Comment by nmote** [comment]
Oh sorry, I just realized that this did not happen to you personally. Still, do you have any version info sent back along with this? Thanks for reporting.

**Comment by crucialfelix** [comment]
I get this often. Just closing tabs.

I am guessing that it's because the Linter still lives and it's off in async world. But the document is now closed.
```
Error: Cannot decorate a destroyed marker
    at DecorationManager.module.exports.DecorationManager.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/decoration-manager.js:192:15)
    at TextEditor.module.exports.TextEditor.decorateMarker (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1540:37)
    at applyUpdateToEditor (/Users/crucial/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/gutter.js:136:14)
    at callback [as _next] (/Users/crucial/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/main.js:181:55)
    at c.__tryOrUnsub (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:50:307)
    at c.next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:49:217)
    at c._next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:48:48)
    at c.next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:222)
    at d.b.notifyNext (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:16:202)
    at b._next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:10:279)
    at b.c.next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:222)
    at e._next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:247:163)
    at e.c.next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:222)
    at b.next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:41:85)
    at DiagnosticStore._emitFileMessages (/Users/crucial/.atom/packages/nuclide/pkg/nuclide-diagnostics-common/lib/DiagnosticStore.js:411:25)
    at DiagnosticStore._invalidateFileMessagesForProvider (/Users/crucial/.atom/packages/nuclide/pkg/nuclide-diagnostics-common/lib/DiagnosticStore.js:180:14)
    at DiagnosticStore.invalidateMessages (/Users/crucial/.atom/packages/nuclide/pkg/nuclide-diagnostics-common/lib/DiagnosticStore.js:155:14)
    at c._next (/Users/crucial/.atom/packages/nuclide/pkg/nuclide-diagnostics-store/lib/main.js:202:18)
    at c.__tryOrUnsub (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:50:307)
    at c.next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:49:217)
    at c._next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:48:48)
    at c.next (/Users/crucial/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.umd.min.js:47:222)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at DiagnosticsProviderBase.publishMessageInvalidation (/Users/crucial/.atom/packages/nuclide/pkg/nuclide-diagnostics-provider-base/lib/DiagnosticsProviderBase.js:122:21)
    at LinterAdapter._invalidateBuffer (/Users/crucial/.atom/packages/nuclide/pkg/nuclide-diagnostics-store/lib/LinterAdapter.js:246:29)
    at /Users/crucial/.atom/packages/nuclide/pkg/nuclide-diagnostics-store/lib/LinterAdapter.js:173:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.destroy (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1288:29)
    at TextBuffer.module.exports.TextBuffer.release (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1312:14)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:401:19)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom.app/Contents/Resources/app.asar/src/model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:641:18)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:619:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:703:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:742:21)
    at atom-workspace.commandRegistry.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:217:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
```
