### ISSUE TITLE
At Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by tiptronic** [facebook/nuclide#692]
[Enter steps to reproduce below:]

1. Launch Atom in OSX 10.11.6
2. Click 'Uncommited Changes' in Source Control
3. It also throws: 'Uncaught AssertionError: false == true'

Seems to be similar as #513 (which is closed)

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [nuclide-file-tree](https://github.com/facebooknuclideapm/nuclide-file-tree) package, v0.0.35

### Stack Trace

Failed to activate the nuclide-file-tree package

```
At Super expression must either be null or a function, not undefined

TypeError: Super expression must either be null or a function, not undefined
    at _inherits (/Users/andy/.atom/packages/nuclide-file-tree/node_modules/nuclide-ui-atom-input/lib/AtomInput.js:16:113)
    at /Users/andy/.atom/packages/nuclide-file-tree/node_modules/nuclide-ui-atom-input/lib/AtomInput.js:31:3
    at Object.<anonymous> (/Users/andy/.atom/packages/nuclide-file-tree/node_modules/nuclide-ui-atom-input/lib/AtomInput.js:178:3)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.load (/Users/andy/.atom/packages/nuclide-file-tree/node_modules/nuclide-ui-atom-input/node_modules/nuclide-atom-npm/lib/main.js:68:31)
    at Object.<anonymous> (/Users/andy/.atom/packages/nuclide-file-tree/node_modules/nuclide-ui-atom-input/lib/main.js:10:46)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/andy/.atom/packages/nuclide-file-tree/components/FileDialogComponent.js:19:27)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/andy/.atom/packages/nuclide-file-tree/lib/FileSystemActions.js:21:38)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
     -0:01.4.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-native-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "themes": [
      "native-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.5 (inactive)
color-picker, v2.2.2 (inactive)
emmet, v2.4.3 (inactive)
git-plus, v5.16.2 (inactive)
git-status, v0.3.4 (inactive)
minimap, v4.25.0 (inactive)
monokai, v0.18.0 (inactive)
native-ui, v0.18.3 (inactive)
nuclide, v0.166.0 (inactive)
nuclide-file-tree, v0.0.35 (inactive)
nuclide-flow, v0.0.35 (inactive)
pigments, v0.34.0 (inactive)
remote-edit, v1.8.24 (inactive)
seti-icons, v1.3.3 (inactive)
sync-settings, v0.7.2 (inactive)
tabs-to-spaces, v1.0.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.2 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.65.0 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by nmote** [comment]
You have some ancient packages installed from when Nuclide was a collection of separate packages. Nuclide consists of only one package now: `nuclide`. Please remove all other `nuclide-*` packages.
