### ISSUE TITLE
cmd+p crashes

### ISSUE THREAD

**Issue by nskpaun** [facebook/nuclide#750]
### Issue and Steps to Reproduce
Open atom and press cmd+p

### Expected Behavior
I should be able to quickly open files

### Actual Behavior
Crash:

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.171.40040796

### Stack Trace

Uncaught AssertionError: Nuclide URIs must contain paths, null' found while parsing 'fb-login://show'

```
At assert.js:89

AssertionError: Nuclide URIs must contain paths, null' found while parsing 'fb-login://show'
  at parse (/opt/facebook/nuclide/0.171.40040796/nuclide/pkg/commons-node/nuclideUri.js:109:39)
  at getPath (/opt/facebook/nuclide/0.171.40040796/nuclide/pkg/commons-node/nuclideUri.js:166:10)
  at Object.basename (/opt/facebook/nuclide/0.171.40040796/nuclide/pkg/commons-node/nuclideUri.js:242:33)
  at getComponentForItem (/opt/facebook/nuclide/0.171.40040796/nuclide/pkg/fb-biggrep-provider/lib/BigGrepProvider.js:104:82)
  at QuickSelectionComponent.componentForItem (/opt/facebook/nuclide/0.171.40040796/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:536:69)
  at /opt/facebook/nuclide/0.171.40040796/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:769:22
  at Array.map (native)
  at /opt/facebook/nuclide/0.171.40040796/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:750:60
  at Array.map (native)
  at /opt/facebook/nuclide/0.171.40040796/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:716:52
  at Array.map (native)
  at QuickSelectionComponent.render (/opt/facebook/nuclide/0.171.40040796/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:711:35)
  at E._renderValidatedComponentWithoutOwnerOrContext (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:13:21363)
  at E._renderValidatedComponent (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:13:21499)
  at E._updateRenderedComponent (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:13:20799)
  at E._performComponentUpdate (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:13:20600)
  at E.updateComponent (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:13:19878)
  at E.performUpdateIfNecessary (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:13:19205)
  at Object.i.performUpdateIfNecessary (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:15:8021)
  at s (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:15:17268)
  at r.o.perform (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:16:10271)
  at o.perform (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:16:10271)
  at o.p.perform (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:15:18353)
  at Object.P [as flushBatchedUpdates] (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:15:18522)
  at r.o.closeAll (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:16:10910)
  at r.o.perform (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:16:10354)
  at Object.d.batchedUpdates (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:14:17213)
  at Object.u [as enqueueUpdate] (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:15:17550)
  at r (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:15:15308)
  at Object.l.enqueueSetState (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:15:16302)
  at QuickSelectionComponent.r.setState (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/react/dist/react-with-addons.min.js:13:13467)
  at QuickSelectionComponent._updateResults (/opt/facebook/nuclide/0.171.40040796/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:321:12)
  at QuickSelectionComponent.handleProvidersChange (/opt/facebook/nuclide/0.171.40040796/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:341:12)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
  at Object.ID_10 (/opt/facebook/nuclide/0.171.40040796/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:188:29)
  at Dispatcher.$Dispatcher_invokeCallback (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/flux/lib/Dispatcher.js:220:35)
  at Dispatcher.dispatch (/opt/facebook/nuclide/0.171.40040796/nuclide/node_modules/flux/lib/Dispatcher.js:195:14)
  at Immediate._onImmediate (/opt/facebook/nuclide/0.171.40040796/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionActions.js:28:89)
  at tryOnImmediate (timers.js:534:15)
  at processImmediate [as _immediateCallback] (timers.js:514:5)

```

### Commands

```
     -0:18.3.0 nuclide-quick-open:find-anything-via-omni-search (atom-pane.pane.active)
     -0:17.5.0 core:paste (atom-text-editor.omnisearch-pane.mini.is-focused)
     -0:16 editor:consolidate-selections (atom-text-editor.omnisearch-pane.mini.is-focused)
     -0:16 core:cancel (atom-text-editor.omnisearch-pane.mini.is-focused)
     -0:15 nuclide-quick-open:find-anything-via-omni-search (atom-pane.pane.active)
     -0:14.1.0 core:cancel (atom-pane.pane.active)
     -0:02.4.0 nuclide-quick-open:find-anything-via-omni-search (atom-pane.pane.active)
     -0:00.6.0 core:cancel (atom-pane.pane.active)
     -0:00.0 nuclide-quick-open:find-anything-via-omni-search (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "customFileTypes": {
      "source.cpp": [
        "h"
      ],
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "TARGETS",
        "cconf",
        "cinc",
        "mcconf",
        "tw",
        "BUCK",
        "ctw"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "fuzzy-finder",
      "metrics"
    ],
    "telemetryConsent": "no",
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-arcanist": {
      "blacklistedLinters": [
        "FBHACK",
        "PEP8",
        "FLAKE8",
        "FBFLOW",
        "FBRELAYFLOW"
      ]
    },
    "nuclide-bookshelf": {
      "changeActiveBookmarkBehavior": "Always Ignore"
    },
    "nuclide-diff-view": {
      "toolbarVisible": true
    },
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-remote-projects": {
      "connectionProfiles": [
        {
          "deletable": true,
          "displayTitle": "www",
          "params": {
            "authMethod": "PRIVATE_KEY",
            "cwd": "/home/nspaun/www",
            "pathToPrivateKey": "/Users/nspaun/.ssh/fb_id_rsa",
            "remoteServerCommand": "",
            "server": "our.nspaun.sb.facebook.com",
            "sshPort": "22",
            "username": "nspaun"
          },
          "saveable": true
        }
      ],
      "shutdownServerAfterDisconnection": false
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-macros, v0.5.2 (active)
auto-pth, v0.1.0 (inactive)
buddy-test-runner, v0.1.0 (active)
consolelog, v0.1.0 (inactive)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
language-babel, v2.15.3 (active)
language-ini, v1.14.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.4.0 (active)
language-thrift, v1.0.2 (active)
merge-conflicts, v1.4.4 (active)
nuclide, v0.171.40040796 (active)
sort-lines, v0.13.0 (inactive)
tool-bar, v0.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (active)
atom-light-ui, v0.44.0 (active)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (inactive)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by nmote** [comment]
We definitely need more information than this
