### ISSUE TITLE
Nuclide version >= 0.171.0 crashes on Windows 10 when opening react-native file

### ISSUE THREAD

**Issue by bosung90** [facebook/nuclide#767]
### Issue and Steps to Reproduce
Installing nuclide 0.171.0 or higher and opening react js file will cause exception to be thrown causing "expected uri, instead got 'my file path to react-native js file' "

### Expected Behavior
I should not get this error when I open react js files

### Actual Behavior
There is exception thrown. Also, restarting atom will break tree-view and uninstalling nuclide will not fix the issue. You can fix the issue by installing 0.170.0 nuclide by doing apm install nuclide@0.170.0

### Versions
* Atom: 1.10.2
* Nuclide: 0.171.0 ~ 0.174.0 (latest)
* Client OS: Windows 10

### Additional Details
* Installed packages (`apm ls --installed`):

language-babel@2.43.0
linter@1.11.18
nuclide@0.174.0
platformio-ide-terminal@2.2.0

**Comment by shushz** [comment]
Could you please provide a stack trace of the exception?

**Comment by bosung90** [comment]
```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.174.0


### Stack Trace

Uncaught Error: Expected remote uri. Got C:\Users\Eric\Documents\ConquerMobileWorkspace\goldcorp-stepup\src\App.js

```
At C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:14

Error: Expected remote uri. Got C:\Users\Eric\Documents\ConquerMobileWorkspace\goldcorp-stepup\src\App.js
  at parseRemoteUri (C:\Users\Eric\.atom\packages\nuclide\pkg\commons-node\nuclideUri.js:145:11)
  at Object.getHostname (C:\Users\Eric\.atom\packages\nuclide\pkg\commons-node\nuclideUri.js:171:10)
  at notifyDisconnectedRemoteFile (C:\Users\Eric\.atom\packages\nuclide\pkg\nuclide-remote-projects\lib\notification.js:41:134)
  at StatusBarTile._onStatusBarTileClicked (C:\Users\Eric\.atom\packages\nuclide\pkg\nuclide-remote-projects\lib\StatusBarTile.js:92:80)
  at Object.r (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:14:20205)
  at a (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:12:22682)
  at Object.s [as executeDispatchesInOrder] (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:12:22897)
  at p (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:12:19275)
  at f (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:12:19401)
  at Array.forEach (native)
  at r (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:16:14025)
  at Object.m.processEventQueue (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:12:20408)
  at r (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:14:20469)
  at Object.i.handleTopLevel [as _handleTopLevel] (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:14:20570)
  at i (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:14:21013)
  at r.o.perform (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:16:10271)
  at Object.d.batchedUpdates (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:14:17213)
  at Object.i [as batchedUpdates] (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:15:16832)
  at m.dispatchEvent (C:\Users\Eric\.atom\packages\nuclide\node_modules\react\dist\react-with-addons.min.js:14:21894)

```

### Commands

```
     -0:15.2.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-babel, v2.43.0 (active)
linter, v1.11.18 (active)
nuclide, v0.174.0 (active)
platformio-ide-terminal, v2.2.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by olegdizus** [comment]
Have same issue

**Comment by shushz** [comment]
The above stack trace happens when a file's connection status icon (monitor shaped) is clicked in the status bar. For some reason it is marked internally as a (disconnected) remote file rather than local, which results in this error being thrown. Thanks for reporting! We'll fix that.

This stack trace, however, doesn't seem to be caused by opening of the file, only to clicking on the mentioned status icon, so there may be more. If you could provide a trace that happens when you open the file that would be great too!

**Comment by bosung90** [comment]
@shushz Hi thanks for looking into the problem. The stack I get happens when I try to open App.js file, and it is exactly same stack as the one I posted. 
Thanks!

**Comment by wycats** [comment]
@shushz I also see it when I click the triangle, which happens after I make a file active.

**Comment by shushz** [comment]
OK. Thanks for confirming, guys!
