### ISSUE TITLE
Diagnostics-UI: Uncaught TypeError: Super expression must [...] not undefined

### ISSUE THREAD

**Issue by wabu** [facebook/nuclide#780]
**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: linux 4.8.0-gentoo
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.174.0
### Stack Trace

Uncaught TypeError: Super expression must either be null or a function, not undefined

```
At /home/wabu/.atom/packages/nuclide/pkg/nuclide-ui/Checkbox.js:11

TypeError: Super expression must either be null or a function, not undefined
  at _inherits (/home/wabu/.atom/packages/nuclide/pkg/nuclide-ui/Checkbox.js:11:113)
  at /home/wabu/.atom/packages/nuclide/pkg/nuclide-ui/Checkbox.js:41:3
  at Object.<anonymous> (/home/wabu/.atom/packages/nuclide/pkg/nuclide-ui/Checkbox.js:125:3)
  at Module._compile (/usr/lib64/atom/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/usr/lib64/atom/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:357:32)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (/usr/lib64/atom/app.asar/src/native-compile-cache.js:50:27)
  at _nuclideUiCheckbox (/home/wabu/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/DiagnosticsPanel.js:28:32)
  at DiagnosticsPanel.render (/home/wabu/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/DiagnosticsPanel.js:189:97)
  at E._renderValidatedComponentWithoutOwnerOrContext (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:21550)
  at E._renderValidatedComponent (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:21638)
  at E.performInitialMount (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:17578)
  at E.mountComponent (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:16637)
  at Object.i.mountComponent (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:8972)
  at E._updateRenderedComponent (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:21249)
  at E._performComponentUpdate (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:20799)
  at E.updateComponent (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:20077)
  at E.performUpdateIfNecessary (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:19582)
  at Object.i.performUpdateIfNecessary (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:9522)
  at s (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:17193)
  at r.o.perform (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at o.perform (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at o.c.perform (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:18210)
  at Object.P [as flushBatchedUpdates] (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:18379)
  at r.o.closeAll (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10699)
  at r.o.perform (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10145)
  at Object.d.batchedUpdates (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:14:17100)
  at Object.i [as batchedUpdates] (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:16775)
  at v.dispatchEvent (/home/wabu/.atom/packages/git-commit/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:14:23665)

```
### Commands

```
     -0:00.2.0 nuclide-diagnostics-ui:toggle-table (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "new-tab",
      "dvnk-icons",
      "test-status",
      "hide-tree",
      "symbols-view",
      "autocomplete-ctags",
      "activate-power-mode-delete",
      "nbviewer",
      "jupyter-notebook",
      "tree-view",
      "atom-python-test",
      "linter-python",
      "linter-python-pep257",
      "linter-python-pyflakes",
      "python-autopep8",
      "linter",
      "file-type-icons"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      "__pycache__",
      ".*.swp",
      ".*.swn",
      ".*.swo"
    ],
    "packagesWithKeymapsDisabled": [
      "linter-python-pep257",
      "atom-ctags",
      "term3",
      "java-generator"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-buck": {
      "compileErrorDiagnostics": false
    },
    "nuclide-file-tree": {
      "revealFileOnSwitch": true,
      "showOpenFiles": false
    },
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-python": {
      "includeOptionalArguments": true
    },
    "use": {
      "nuclide-adb-logcat": false,
      "nuclide-arcanist": false,
      "nuclide-buck": false,
      "nuclide-debugger-node": false,
      "nuclide-debugger-php": false,
      "nuclide-distraction-free-mode": false,
      "nuclide-flow": false,
      "nuclide-hack": false,
      "nuclide-hhvm": false,
      "nuclide-home": false,
      "nuclide-ios-simulator-logs": false,
      "nuclide-language-hack": false,
      "nuclide-objc": false,
      "nuclide-ocaml": false,
      "nuclide-react-native": false,
      "nuclide-react-native-inspector": false,
      "nuclide-swift": false,
      "nuclide-type-coverage": false
    }
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v1.0.2 (active)
activate-power-mode-delete, v0.6.1 (inactive)
adwaita-ui, v0.30.0 (inactive)
aligner-python, v1.0.1 (active)
atom-beautify, v0.29.13 (inactive)
atom-dark-ui-slim, v0.47.1 (inactive)
atom-light-ui-slim, v0.25.1 (inactive)
atom-python-debugger, v0.3.4 (active)
atom-python-package, v0.7.0 (inactive)
atom-python-test, v0.5.4 (inactive)
atom-slim-ui, v0.10.7 (inactive)
atom-square-light-ui, v0.1.2 (inactive)
atomic-ui, v1.5.2 (inactive)
autocomplete-awk, v0.1.2 (active)
autocomplete-bash-builtins, v0.3.4 (active)
autocomplete-ctags, v0.4.1 (inactive)
autocomplete-java, v1.2.5 (inactive)
autocomplete-python, v1.8.6 (active)
character-table, v0.4.3 (active)
clipboard-plus, v0.5.1 (active)
cold-ui, v1.4.0 (inactive)
commands, v0.0.1 (active)
ctags-status, v1.3.6 (active)
daylight-ui, v0.2.2 (inactive)
direct-flat-ui, v0.1.0 (inactive)
dvnk-icons, v1.8.2 (inactive)
ex-mode, v0.13.0 (inactive)
file-icon-supplement, v0.8.3 (active)
file-type-icons, v1.3.2 (inactive)
git-commit, v1.5.3 (active)
git-log, v0.4.1 (active)
git-time-machine, v1.5.3 (inactive)
haskell-grammar, v0.4.0 (active)
hide-tree, v0.0.20 (inactive)
highlight-selected, v0.11.2 (active)
Hydrogen, v0.14.0 (inactive)
java-generator, v2.2.0 (inactive)
java-importer, v1.4.1 (active)
jupyter-notebook, v0.0.9 (inactive)
language-babel, v2.44.1 (active)
language-ini, v1.16.0 (active)
language-ipynb, v1.3.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.4.0 (active)
language-thrift, v1.0.2 (active)
light-bint-ui, v1.0.4 (inactive)
linter, v1.11.18 (inactive)
linter-checkbashisms, v0.1.5 (active)
linter-checkstyle, v1.2.0 (active)
linter-javac, v1.9.4 (active)
linter-python, v3.0.5 (inactive)
linter-python-pep257, v0.0.1 (inactive)
linter-python-pyflakes, v0.1.0 (inactive)
luser-interface-ui, v0.2.1 (inactive)
MagicPython, v0.5.16 (active)
markdown-folder, v0.5.0 (inactive)
markdown-scroll-sync, v2.1.2 (active)
merge-conflicts, v1.4.4 (active)
min-ui, v0.0.1 (inactive)
minimap, v4.25.0 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-codeglance, v0.4.5 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-selection, v4.4.0 (active)
minimap-split-diff, v0.3.1 (active)
navigate-indent, v0.1.0 (active)
nbviewer, v1.0.2 (inactive)
nerd-treeview, v0.4.2 (active)
new-tab, v0.5.1 (inactive)
nuclide, v0.174.0 (active)
nuclide-test-runner-pytest, v0.1.1 (active)
numix-ui, v0.2.2 (inactive)
open-this, v0.2.0 (inactive)
pandoc, v0.2.2 (inactive)
paper-flat-ui, v1.3.4 (inactive)
pigments, v0.37.0 (active)
project-find-navigation, v0.2.0 (inactive)
pytest, v0.3.0 (active)
python-autopep8, v0.1.3 (inactive)
python-debugger, v0.1.0 (inactive)
python-indent, v2.0.0 (active)
python-iresolve, v0.0.3 (active)
python-isort, v0.0.7 (active)
python-jedi, v0.3.8 (active)
python-mrigor, v2.1.3 (inactive)
python-terminal, v0.2.0 (inactive)
python-tools, v0.6.8 (active)
release-notes, v0.53.0 (active)
scroll-percentage, v1.2.1 (active)
slack-ui, v0.7.0 (inactive)
slim-dark-ui, v0.12.0 (inactive)
sort-lines, v0.14.0 (inactive)
special-symbols, v0.1.0 (inactive)
symbols-tree-view, v0.13.2 (active)
tab-to-escape, v0.1.0 (active)
term3, v0.22.1 (active)
test, v0.1.2 (active)
test-jumper, v0.6.0 (inactive)
test-status, v1.0.0 (inactive)
tidy-markdown, v3.0.1 (active)
tool-bar, v1.0.1 (active)
two-light-ui, v1.1.2 (inactive)
unicorn-light-ui, v2.1.0 (inactive)
unicorn-ui, v1.2.0 (inactive)
vim-mode-plus, v0.60.0 (active)
vim-mode-plus-ex-mode, v0.5.0 (inactive)
vim-mode-plus-move-selected-text, v0.6.1 (active)
vim-mode-plus-move-to-symbols, v0.1.6 (active)
vim-mode-plus-project-find-from-search, v0.1.0 (inactive)
vim-mode-plus-replace-with-execution, v0.1.3 (active)
vim-mode-plus-subword-movement, v0.2.2 (active)
vim-mode-visual-block, v0.2.15 (active)
vim-modeline, v0.4.2 (active)
vim-shift-movers, v0.1.3 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by nmote** [comment]
It looks like your install or the require cache got corrupted. Could you try restarting Atom, and if that doesn't work, try removing and re-installing the `nuclide` package? Let us know whether that works.

**Comment by wabu** [comment]
I already did both before opening the ticket ... could also try to remove .atom/compile-cache directory (only obvious cache I was able to find) after backing up .atom, but only after I got some sleep. Thanks for having a look at this.

**Comment by nmote** [comment]
That seems worth a try. Honestly this is a pretty weird error and I'm not really sure what to make of it.

**Comment by wabu** [comment]
clearing compile-cache and reinstalling nuclide did not help, so I renamed my .atom and reinstalled all plugings, which did the trick. But I don't know of an easy solution that does not require manual migration of config files.
