### ISSUE TITLE
Uncaught TypeError: Super expression must either be null or a function, not undefined

### ISSUE THREAD

**Issue by snavien** [facebook/nuclide#787]
[Enter steps to reproduce below:]

1. Just opened an angular project, nothing else was really done.
Sidenote: opening this page was done manually, the link given to open the issue gave me a 414 URI too long error.

**Atom Version**: 1.11.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.175.0

### Stack Trace

Uncaught TypeError: Super expression must either be null or a function, not undefined

```
At /Users/svien/.atom/packages/nuclide/pkg/nuclide-file-tree/components/OpenFilesListComponent.js:19

TypeError: Super expression must either be null or a function, not undefined
    at _inherits (/Users/svien/.atom/packages/nuclide/pkg/nuclide-file-tree/components/OpenFilesListComponent.js:19:113)
    at /Users/svien/.atom/packages/nuclide/pkg/nuclide-file-tree/components/OpenFilesListComponent.js:54:3
    at Object.<anonymous> (/Users/svien/.atom/packages/nuclide/pkg/nuclide-file-tree/components/OpenFilesListComponent.js:165:3)
    at Module._compile (/Users/svien/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Users/svien/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Users/svien/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at _load_OpenFilesListComponent (/Users/svien/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:60:36)
    at FileTreeSidebarComponent.render (/Users/svien/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:258:115)
    at E._renderValidatedComponentWithoutOwnerOrContext (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:21550)
    at E._renderValidatedComponent (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:21638)
    at E._updateRenderedComponent (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:20998)
    at E._performComponentUpdate (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:20799)
    at E.updateComponent (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:20077)
    at E.performUpdateIfNecessary (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:19582)
    at Object.i.performUpdateIfNecessary (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:9522)
    at s (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:17193)
    at r.o.perform (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10062)
    at o.perform (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10062)
    at o.c.perform (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:18210)
    at Object.P [as flushBatchedUpdates] (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:18379)
    at r.o.closeAll (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10699)
    at r.o.perform (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10145)
    at Object.d.batchedUpdates (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:14:17100)
    at Object.u [as enqueueUpdate] (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:17415)
    at r (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:15480)
    at Object.u.enqueueSetState (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:16284)
    at FileTreeSidebarComponent.r.setState (/Users/svien/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:13808)
    at FileTreeSidebarComponent._processExternalUpdate (/Users/svien/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:314:14)
    at Function.module.exports.Emitter.simpleDispatch (/Users/svien/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/svien/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Users/svien/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:640:25
```

### Commands

```
     -1:23.1.0 window:install-shell-commands (atom-text-editor.editor.is-focused)
  3x -1:15 nuclide-settings:toggle (atom-text-editor.editor)
     -0:05.9.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "logo-file-icons",
      "pdf-view",
      "tree-view"
    ],
    "telemetryConsent": "limited"
  },
  "nuclide": {
    "nuclide-code-format": {
      "formatOnSave": true
    },
    "nuclide-hg-repository": {
      "enableDiffStats": true
    },
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-working-sets": {
      "workingSets": [
        {
          "name": "yelp_website",
          "active": false,
          "uris": [
            "/Users/svien/Documents/Test_App"
          ]
        }
      ]
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-typescript, v10.1.8 (active)
atomic-chrome, v0.3.0 (active)
auto-detect-indentation, v1.2.0 (active)
auto-update-packages, v1.0.1 (active)
autocomplete-modules, v1.6.7 (active)
color-picker, v2.2.2 (active)
config-import-export, v0.3.1 (inactive)
docblockr, v0.8.7 (active)
emmet, v2.4.3 (active)
file-icons, v1.7.21 (active)
flow, v0.5.3 (active)
git-checkout, v0.3.2 (active)
git-plus, v5.18.0 (active)
git-time-machine, v1.5.3 (inactive)
github-atom-light-syntax, v0.2.0 (inactive)
hack, v0.0.2 (active)
highlight-selected, v0.11.2 (active)
language-babel, v2.44.1 (active)
language-ocaml, v1.1.2 (active)
language-scala, v1.1.6 (active)
linter, v1.11.18 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-find-and-replace, v4.5.1 (active)
nuclide, v0.175.0 (active)
open-recent, v5.0.0 (active)
pigments, v0.37.0 (active)
rest-client, v1.2.6 (active)
simple-drag-drop-text, v0.3.1 (active)
sort-lines, v0.14.0 (inactive)
todo-show, v1.7.0 (inactive)
tool-bar, v1.0.1 (active)
tree-view-git-branch, v0.1.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by shushz** [comment]
Seems similar to #780. Just as there, the missing super class is `React.PureComponent. It seems as if an old version of React was loaded.
If the issue persists after Atom restart, deleting the `~/.atom/compile_cache` seems like the next logical step to try.

**Comment by snavien** [comment]
Yeah, it's a duplicate: renaming ~/.atom worked but reinstalling the packages was an overhead.

**Comment by snavien** [comment]
Actually renaming didn't work specifically it looks at 
OpenFilesListComponent.js:19
node_modules/rxjs/bundles/Rx.min.js:50

any idea how to fix that?

**Comment by shushz** [comment]
@jgebhardt, do you have any idea why wouldn't `React.PureComponent` be available?

Also, @snavien, could you please open Developer Tools in Atom (Cmd-Alt-i), in the console type:
```
atom.__DO_NOT_ACCESS_React_Singleton.React.version
```
And tell what the result is?

**Comment by jgebhardt** [comment]
My only guess would be that one of the third-party package might be loading an older version of React. I'm also curious to see the values mentioned above.
