### ISSUE TITLE
Failed for load the nuclide package

### ISSUE THREAD

**Issue by kean-bs** [facebook/nuclide#812]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

Always that update the package Atom I have the following error. Somethings Nuclide it work.

-------------------------

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.175.0

### Stack Trace

Failed to load the nuclide package

```
At Cannot find module '../pkg/nuclide-remote-connection/lib/service-manager'

Error: Cannot find module '../pkg/nuclide-remote-connection/lib/service-manager'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at _load_pkgNuclideRemoteConnectionLibServiceManager (C:\Users\DaRK\.atom\packages\nuclide\lib\main.js:59:57)
    at Object.<anonymous> (C:\Users\DaRK\.atom\packages\nuclide\lib\main.js:129:54)
    at Module._compile (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:721:27)
    at C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package-manager.js:536:30)
    at C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:460:29
    at exit (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\buffered-process.js:215:47)
    at C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\buffered-process.js:222:18
    at Socket.<anonymous> (C:\Users\DaRK\AppData\Local\atom\app-1.11.1\resources\app.asar\src\buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
color-picker, v2.2.2 (active)
emmet, v2.4.3 (active)
linter, v1.11.18 (active)
linter-csslint, v1.3.3 (active)
linter-htmlhint, v1.3.0 (active)
linter-jshint, v3.0.0 (active)
minimap, v4.25.0 (active)
nuclide, v0.175.0 (inactive)
pigments, v0.37.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

----------------------------

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom: 1.11.1
* Nuclide: 0.175.0
* Client OS: Windows 7 
* Server OS (optional): Any

### Additional Details
* Installed packages (`apm ls --installed`):
![screenshot_2](https://cloud.githubusercontent.com/assets/12689339/19411806/a18fe59e-92de-11e6-923d-a08212756601.png)

**Comment by nmote** [comment]
This looks like either a mismatch between what's on disk and what's in memory or an issue with the require cache. Either way, restarting Atom should fix it. Let us know whether that works.

**Comment by KBuenoDev** [comment]
Thanks so much, Now work but sometimes this not work, I have re-install nuclide.
