### ISSUE TITLE
Uncaught Error: Remote Error: Connection Closed processing message {"protocol":"service_framework...

### ISSUE THREAD

**Issue by bjackson** [facebook/nuclide#828]
Enter steps to reproduce below:
1. Connect to a nuclide remote server

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12.1
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.176.0

### Stack Trace

Uncaught Error: Remote Error: Connection Closed processing message {"protocol":"service_framework3_rpc","type":"call-object","method":"isFileInProject","objectId":2,"id":18,"args":{"fileUri":"/home/pi/mp1"}}
"Error: Connection Closed\n    at /Users/brett/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:694:21\n    at Map.forEach (native)\n    at RpcConnection.dispose (/Users/brett/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:693:19)\n    at ServerConnection.close (/Users/brett/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/ServerConnection.js:298:22)\n    at ServerConnection.<anonymous> (/Users/brett/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/ServerConnection.js:374:14)\n    at undefined.next (native)\n    at step (/Users/brett/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/ServerConnection.js:17:273)\n    at process._tickCallback (internal/process/next_tick.js:103:7)"

```
At /Users/brett/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:445

Error: Connection Closed
    at /Users/brett/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:694:21
    at Map.forEach (native)
    at RpcConnection.dispose (/Users/brett/.atom/packages/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:693:19)
    at ServerConnection.close (/Users/brett/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/ServerConnection.js:298:22)
    at ServerConnection.<anonymous> (/Users/brett/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/ServerConnection.js:374:14)
    at undefined.next (native)
    at step (/Users/brett/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/ServerConnection.js:17:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Commands

```
     -9:52.7.0 nuclide-remote-projects:connect (span.)
     -9:48 core:confirm (atom-text-editor.atom-text-editor-unstyled.mini.is-focused)
  2x -9:35 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
  2x -6:08.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:03.8.0 core:save (atom-text-editor.editor.is-focused)
     -5:38.2.0 nuclide-remote-projects:connect (span.)
     -5:24.4.0 nuclide-file-tree:set-current-working-root (div.header.list-item)
     -5:18.8.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
     -3:19.4.0 nuclide-health:toggle (atom-text-editor.editor.is-focused)
     -3:08.7.0 nuclide-home:toggle (atom-text-editor.editor.is-focused)
     -3:00.7.0 nuclide-settings:toggle (atom-text-editor.editor.is-focused)
     -2:57.6.0 find-and-replace:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
     -2:54.6.0 core:cancel (atom-pane.pane.active)
  4x -2:35.7.0 core:backspace (atom-text-editor.atom-text-editor-lg.mini.is-focused)
     -0:10 nuclide-file-tree:remove-project-folder-selection (div.header.list-item)
     -0:06.3.0 nuclide-remote-projects:connect (span.icon.name.icon-briefcase)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "atom-ctags",
      "symbol-gen",
      "linter-jshint",
      "tree-view",
      "atom-yeoman",
      "autocomplete-clang",
      "autocomplete-elixir",
      "autocomplete-python",
      "dockerletion",
      "git-time-machine",
      "language-babel",
      "vim-mode",
      "linter",
      "linter-pep8",
      "linter-pylint"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "node_moudles"
    ],
    "telemetryConsent": "no"
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-python": {
      "lintOnFly": true
    },
    "nuclide-remote-projects": {
      "connectionProfiles": [
        {
          "deletable": true,
          "displayTitle": "pi",
          "params": {
            "displayTitle": "pi",
            "username": "pi",
            "server": "10.193.167.157",
            "cwd": "/home/pi/mp1",
            "sshPort": "22",
            "authMethod": "PRIVATE_KEY",
            "pathToPrivateKey": "/Users/brett/.ssh/id_rsa",
            "remoteServerCommand": "nuclide-start-server -k"
          },
          "saveable": true
        }
      ]
    }
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined (inactive)
advanced-open-file, v0.16.4 (inactive)
atom-beautify, v0.29.13 (active)
atom-ctags, v5.0.0 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-ternjs, v0.15.0 (active)
atom-typescript, v10.1.9 (active)
autoclose-html, v0.23.0 (active)
autocomplete-clang, v0.10.0 (inactive)
autocomplete-elixir, v1.5.14 (inactive)
autocomplete-modules, v1.6.7 (active)
autocomplete-python, v1.8.7 (inactive)
color-picker, v2.2.2 (active)
docblockr, v0.8.7 (active)
dockerletion, v0.2.0 (inactive)
ex-mode, v0.13.0 (inactive)
file-icons, v1.7.22 (active)
filesize, v1.0.0 (active)
git-time-machine, v1.5.3 (inactive)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
language-arm, v1.2.2 (active)
language-babel, v2.45.0 (inactive)
language-docker, v1.1.7 (active)
language-elixir, v0.16.0 (active)
language-fsharp, v0.8.4 (active)
language-ini, v1.16.0 (active)
language-jade, v0.7.2 (active)
language-ocaml, v1.1.2 (active)
language-rust, v0.4.8 (active)
language-swift, v0.4.0 (active)
language-thrift, v1.0.2 (active)
language-x86asm, v0.8.0 (active)
linter, v1.11.18 (inactive)
linter-clang, v3.4.4 (active)
linter-docker, v0.1.2 (active)
linter-eslint, v8.0.0 (active)
linter-jshint, v3.0.1 (inactive)
linter-pep8, v1.3.2 (inactive)
linter-pylint, v1.2.2 (inactive)
linter-rust, v0.6.0 (active)
merge-conflicts, v1.4.4 (active)
nuclide, v0.176.0 (active)
nuclide-format-js, v0.0.36 (inactive)
pigments, v0.37.0 (active)
qolor, v0.4.0 (active)
react, v0.16.1 (active)
remote-edit, v1.8.24 (active)
script, v3.10.1 (inactive)
solarized-dark-ui, v0.3.1 (inactive)
sort-lines, v0.14.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
symbol-gen, v1.3.1 (inactive)
todo-show, v1.7.0 (inactive)
tool-bar, v1.0.1 (active)
travis-ci-status, v1.3.0 (active)
vim-mode, v0.65.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by alfa07** [comment]
Did you try to kill nuclide server? (`$ pkill -9 nuclide`) Do you have:
`[ "$TERM" = "nuclide" ] && return;`
in your .bash_profile?

**Comment by szente** [comment]
Have the same issue with version 0.181.0

**Comment by szente** [comment]
The issue still exists. Version 0.183.0

**Comment by minikin** [comment]
I've received the same error.
