### ISSUE TITLE
Uncaught Error: Invariant violation: "this.props.repository != null"

### ISSUE THREAD

**Issue by phellipeandrade** [facebook/nuclide#849]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04.1
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.177.0
### Stack Trace

Uncaught Error: Invariant violation: "this.props.repository != null"

```
At /home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14

Error: Invariant violation: "this.props.repository != null"
  at RepositorySectionComponent._handleUncommittedChangesClick (/home/phellipe/.atom/packages/nuclide/pkg/nuclide-source-control-side-bar/lib/RepositorySectionComponent.js:77:13)
  at Object.r (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:20205)
  at a (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:22682)
  at Object.s [as executeDispatchesInOrder] (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:22897)
  at p (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:19275)
  at f (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:19401)
  at Array.forEach (native)
  at r (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:14025)
  at Object.m.processEventQueue (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:12:20408)
  at r (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:20469)
  at Object.i.handleTopLevel [as _handleTopLevel] (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:20570)
  at i (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:21013)
  at r.o.perform (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:16:10271)
  at Object.d.batchedUpdates (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:17213)
  at Object.i [as batchedUpdates] (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:15:16832)
  at m.dispatchEvent (/home/phellipe/.atom/packages/nuclide/node_modules/react/dist/react-with-addons.min.js:14:21894)

```
### Commands

```
     -0:11.8.0 application:add-project-folder (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "react"
    ],
    "telemetryConsent": "limited"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-ternjs, v0.15.0 (active)
dark-flat-ui, v1.2.4 (inactive)
emmet, v2.4.3 (active)
language-babel, v2.45.0 (active)
language-javascript-jsx, v0.3.7 (active)
minimap, v4.25.6 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-pigments, v0.2.1 (active)
minimap-selection, v4.4.0 (active)
nuclide, v0.177.0 (active)
pigments, v0.37.0 (active)
react, v0.16.1 (inactive)
react-es6-snippets, v0.3.0 (active)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by nmote** [comment]
Please include steps to reproduce.

@mostafaeweda, @aadisriram: Do you know what's going on here?

**Comment by phellipeandrade** [comment]
Hi, I Just tried to add a project folder, and nuclide throw this error. After restarting atom, everything went back to work.

**Comment by nmote** [comment]
Had you just updated `nuclide` or any other packages? Is there any other information you could add about what you were doing before you saw this error? Did you have other project folders open already, or was this the first one? Had you just opened Nuclide or had you already been working for a while?

**Comment by phellipeandrade** [comment]
I had one more project open,  when this happened. Nuclide was started about 30 min before that. the most recent package updated was language-babel. Sorry, but I haven't  anymore informations about it, thank you!

**Comment by mostafaeweda** [comment]
fix for this on the way
