### ISSUE TITLE
Assertion Error on Delete

### ISSUE THREAD

**Issue by rmurcek** [facebook/nuclide#851]
### Issue and Steps to Reproduce

Attempting to delete a line fails and prints an assertion error from text-buffer.js

![image](https://cloud.githubusercontent.com/assets/1427905/19840945/24d4223a-9ed8-11e6-8832-141a31f8166a.png)

Deleting the line a second time succeeds, but the same assertion error is presented:

![image](https://cloud.githubusercontent.com/assets/1427905/19840962/5a39afd0-9ed8-11e6-9567-3c166136f5ff.png)

Pressing undo after successfully deleting the line causes the same assertion error to be printed.

Restarting Atom solved the issue.
### Expected Behavior

The line should go away peacefully.
### Stack Trace

Uncaught AssertionError: false == true

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:871

AssertionError: false == true
  at BreakpointStore._deleteBreakpoint (/Users/rob.murcek/.atom/packages/nuclide/pkg/nuclide-debugger/lib/BreakpointStore.js:139:43)
  at BreakpointStore._handlePayload (/Users/rob.murcek/.atom/packages/nuclide/pkg/nuclide-debugger/lib/BreakpointStore.js:89:16)
  at Dispatcher.$Dispatcher_invokeCallback (/Users/rob.murcek/.atom/packages/nuclide/node_modules/flux/lib/Dispatcher.js:220:35)
  at Dispatcher.dispatch (/Users/rob.murcek/.atom/packages/nuclide/node_modules/flux/lib/Dispatcher.js:195:14)
  at DebuggerActions.deleteBreakpoint (/Users/rob.murcek/.atom/packages/nuclide/pkg/nuclide-debugger/lib/DebuggerActions.js:434:24)
  at BreakpointDisplayController._handleMarkerChange (/Users/rob.murcek/.atom/packages/nuclide/pkg/nuclide-debugger/lib/BreakpointDisplayController.js:177:31)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at DisplayMarker.module.exports.DisplayMarker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:245:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker.js:53:26
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:425:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:293:25
  at Set.forEach (native)
  at MarkerLayer.module.exports.MarkerLayer.emitChangeEvents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:290:39)
  at TextBuffer.module.exports.TextBuffer.emitMarkerChangeEvents (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1393:34)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:890:12)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1519:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1096:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2493:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2459:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1094:19)
  at TextEditor.module.exports.TextEditor.delete (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1079:19)
  at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.core:delete (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:423:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:661:34
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1519:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:660:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

```
### Commands

```
     -6:47.9.0 core:save (atom-text-editor.editor.is-focused)
     -6:26.1.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:25.6.0 core:save (atom-text-editor.editor.is-focused)
     -6:24.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -6:24.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:23.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -6:23.3.0 core:delete (atom-text-editor.editor.is-focused)
     -6:22.9.0 core:save (atom-text-editor.editor.is-focused)
     -5:35.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -5:35.6.0 core:paste (atom-text-editor.editor.is-focused)
     -5:35.2.0 core:save (atom-text-editor.editor.is-focused)
     -3:43.1.0 core:paste (atom-text-editor.editor.is-focused)
     -3:41.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:09.0 core:select-all (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -2:04.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:00.1.0 core:delete (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "linter",
      "activate-power-mode"
    ],
    "telemetryConsent": "limited"
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.9.0 (inactive)
atom-beautify, v0.29.13 (active)
atom-python-debugger, v0.2.2 (inactive)
atom-typescript, v10.1.7 (active)
autocomplete-plus-python-jedi, v0.2.6 (inactive)
autocomplete-python, v1.8.6 (active)
highlight-selected, v0.11.2 (active)
js-hyperclick, v1.6.0 (active)
keybinding-cheatsheet, v0.1.0 (inactive)
language-awk, v0.1.11 (active)
language-babel, v2.35.0 (active)
language-ocaml, v1.1.2 (active)
linter, v1.11.16 (inactive)
linter-python-pep8, v0.2.0 (active)
nuclide, v0.165.0 (active)
python-isort, v0.0.6 (inactive)
python-yapf, v0.4.0 (active)
sort-lines, v0.14.0 (inactive)
split-diff, v1.0.5 (inactive)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```
### Versions

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.10.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.165.0
### Additional Details
- Installed packages (`apm ls --installed`):

**Comment by nmote** [comment]
You have an outdated version of Nuclide. Please try updating Nuclide and re-open if the issue persists.
