### ISSUE TITLE
Failed to activate the hyperclick package

### ISSUE THREAD

**Issue by JustDevZero** [facebook/nuclide#852]
### Issue and Steps to Reproduce
Hyperclick package crashed just after installing.

### Expected Behavior
Normall install?

### Actual Behavior
*Thrown From**: [hyperclick] (https://github.com/facebooknuclide/hyperclick) package, Failed to execute 'registerElement' on 'Document': Registration failed for type 'hyperclick-suggestion-list'. A type with that name is already registered.
Hide Stack Trace
Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'hyperclick-suggestion-list'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (/home/dripoll/.atom/packages/hyperclick/lib/SuggestionListElement.js:265:31)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/dripoll/.atom/packages/hyperclick/lib/Hyperclick.js:49:30)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/dripoll/.atom/packages/hyperclick/lib/main.js:22:19)
    at Module._compile (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom-beta/resources/app.asar/src/package.js:741:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom-beta/resources/app.asar/src/package.js:174:16)
    at /usr/share/atom-beta/resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/usr/share/atom-beta/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom-beta/resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/usr/share/atom-beta/resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom-beta/resources/app.asar/src/package-manager.js:548:21)
    at /usr/share/atom-beta/resources/app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/usr/share/atom-beta/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:215:47)
    at ChildProcess.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/buffered-process.js:237:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

### Versions
* Atom:* 1.12.0-beta5
* Nuclide:* v0.177.0
* Client OS: * Fedora Release 25
* Electron Version*: 1.3.6

### Additional Details
* Installed packages (`apm ls --installed`):
nuclide
nuclide-format-js

### Enter steps to reproduce below:
1. Install hyperclick module from package list.
2. Wait 1 second, will popup alone.

**Comment by nmote** [comment]
We don't currently support the standalone `hyperclick` package. It is now bundled with Nuclide, so since you do have Nuclide installed the easiest thing to do is to just remove the standalone `hyperclick` package.

**Comment by surdu** [comment]
... then... why is it a separate package ??!

**Comment by yesnault** [comment]
Do you plan a fix for https://github.com/facebooknuclide/hyperclick/issues/4#issuecomment-309225606 ?

**Comment by danqing** [comment]
There are almost 180k users of the standalone hyperclick package, and other providers depend on it, so it isn't a terribly good idea to not support it (it's not created by a 3rd party in the first place).

If it really won't be supported, then pull it from atom so at least people know that it's not there.
