### ISSUE TITLE
Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by adithyan** [facebook/nuclide#856]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [nuclide-bookshelf](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to activate the nuclide-bookshelf package

```
At Cannot read property 'bind' of undefined

TypeError: Cannot read property 'bind' of undefined
    at watchProjectRepository (/Users/adithyan-1244/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/applyActionMiddleware.js:69:36)
    at c._rxjsBundlesRxMinJs.Observable.merge.getActionsOfType.flatMap.action [as project] (/Users/adithyan-1244/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/applyActionMiddleware.js:51:12)
    at c._tryNext (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:278:120)
    at c._next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:278:22)
    at c.d.next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:47:323)
    at e._next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:249:79)
    at e.d.next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:47:323)
    at b.next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:41:205)
    at Commands.Activation.action [as _dispatch] (/Users/adithyan-1244/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/main.js:111:15)
    at Commands.addProjectRepository (/Users/adithyan-1244/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/Commands.js:47:10)
    at d.Activation.addedRepoSubscription.subscribe.repository [as _next] (/Users/adithyan-1244/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/main.js:116:16)
    at d.__tryOrSetError (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:50:506)
    at d.next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:49:249)
    at d._next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:48:128)
    at d.next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:47:323)
    at c.notifyNext (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:279:25)
    at b._next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:10:279)
    at b.d.next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:47:323)
    at c._subscribe (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:139:254)
    at c.a.subscribe (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:14:78)
    at Object.f.subscribeToResult (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:445:184)
    at c._innerSub (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:278:261)
    at c._tryNext (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:278:194)
    at c._next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:278:22)
    at c.d.next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:47:323)
    at e._next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:249:79)
    at e.d.next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:47:323)
    at e._next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:269:131)
    at e.d.next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:47:323)
    at b._next (/Users/adithyan-1244/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:294:421)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-hg, v2.0.11 (inactive)
nuclide, v0.178.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by mostafaeweda** [comment]
Are you working on a mercurial repository?
I see the error is coming from this piece of code: https://github.com/facebook/nuclide/blob/cf7878ec6bb6e2f4fbaa42f22d2c3d525cd8a37a/pkg/nuclide-bookshelf/lib/applyActionMiddleware.js#L57-L104

while all the bound functions already exist in https://github.com/facebook/nuclide/blob/cf7878ec6bb6e2f4fbaa42f22d2c3d525cd8a37a/pkg/nuclide-hg-repository-client/lib/HgRepositoryClient.js

So, I suspect something is bad with your Nuclide setup.
Could you update to the latest version and let me know if it reproduces and how to reproduce it?

**Comment by adithyan** [comment]
I have updated the Nuclide, Still getting the same on Atom startup.

**Comment by acenicks** [comment]
Getting the same error:

> [Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Ubuntu 14.04.5
**Thrown From**: [nuclide-bookshelf](https://github.com/facebook/nuclide) package, v0.0.0


### Stack Trace

Failed to activate the nuclide-bookshelf package

```
At Cannot read property 'bind' of undefined

TypeError: Cannot read property 'bind' of undefined
    at watchProjectRepository (/home/acenicks/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/applyActionMiddleware.js:69:36)
    at a._rxjsBundlesRxMinJs.Observable.merge.getActionsOfType.flatMap.action [as project] (/home/acenicks/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/applyActionMiddleware.js:51:12)
    at a._tryNext (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:125:27)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:124:430)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:157:18)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:35:279)
    at Commands.dispatch [as _dispatch] (/home/acenicks/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/main.js:111:15)
    at Commands.addProjectRepository (/home/acenicks/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/Commands.js:47:10)
    at a.Activation.addedRepoSubscription.subscribe.repository [as _next] (/home/acenicks/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/main.js:116:16)
    at a.__tryOrSetError (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:31:56)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:29:315)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:28:238)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a.notifyNext (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:125:422)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:48:25)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a._subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:58:277)
    at a.b.subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:32:225)
    at p (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:12:317)
    at a._innerSub (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:125:166)
    at a._tryNext (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:125:101)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:124:430)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:157:18)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:93:172)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:190:95)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a.notifyNext (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:46:327)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:48:25)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:93:172)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a.notifyNext (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:46:327)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:48:25)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at p (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:12:282)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:51:305)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a._subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:46:163)
    at a.b.subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:32:225)
    at b._subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:175)
    at b.call (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:51:43)
    at b.subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:32:201)
    at b._subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:175)
    at b.call (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:92:354)
    at b.subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:32:201)
    at p (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:12:317)
    at a._next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:51:305)
    at a.next (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:27:414)
    at a._subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:46:163)
    at a.b.subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:32:225)
    at b._subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:175)
    at b.call (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:51:43)
    at b.subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:32:201)
    at b._subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:175)
    at b.call (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:189:433)
    at b.subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:32:201)
    at b._subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:175)
    at b.call (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:92:354)
    at b.subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:32:201)
    at b._subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:175)
    at b.call (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:156:187)
    at b.subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:32:201)
    at b._subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:33:175)
    at b.call (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:124:61)
    at b.subscribe (/home/acenicks/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:32:201)
    at new Activation (/home/acenicks/.atom/packages/nuclide/pkg/nuclide-bookshelf/lib/main.js:115:116)
    at Object.activate (/home/acenicks/.atom/packages/nuclide/pkg/commons-atom/createPackage.js:65:20)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:184:19)
    at /usr/share/atom/resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:548:21)
    at Object.keys.forEach.name (/home/acenicks/.atom/packages/nuclide/lib/main.js:283:21)
    at Array.forEach (native)
    at Object.activate (/home/acenicks/.atom/packages/nuclide/lib/main.js:280:25)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:184:19)
    at /usr/share/atom/resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:548:21)
    at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:215:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
```

### Commands

```
     -8:50.2.0 pane:show-next-recently-used-item (atom-text-editor.editor.is-focused)
     -8:50.1.0 pane:move-active-item-to-top-of-stack (div.pdf-view)
  2x -8:49.6.0 pane:show-next-recently-used-item (div.pdf-view)
     -8:49 pane:move-active-item-to-top-of-stack (div.panels-item)
  5x -8:47.3.0 core:move-down (div.panels-item)
  2x -8:39.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -4:53.9.0 core:backspace (div.package-detail.panels-item)
     -1:13.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:03.5.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-atom-material-syntax-dark.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "latex-plus",
      "atom-hg",
      "tree-view"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "atom-material-syntax-dark"
    ],
    "customFileTypes": {
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ],
      "source.ini": [
        ".buckconfig",
        ".hgrc"
      ]
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-hg, v2.0.11 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (active)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.6 (inactive)
autocomplete-bibtex, v0.7.0 (active)
language-latex, v1.0.0 (active)
latex, v0.40.0 (active)
latex-plus, v0.9.1 (inactive)
latexer, v0.3.0 (active)
linter, v1.11.18 (active)
linter-chktex, v1.3.0 (active)
minimap, v4.25.6 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-selection, v4.4.0 (active)
nuclide, v0.182.0 (inactive)
pdf-view, v0.53.0 (active)
pigments, v0.38.0 (active)
project-manager, v3.3.3 (active)
terminal-plus, v0.14.5 (active)
wordcount, v2.8.0 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

<

**Comment by acenicks** [comment]
Seems like I was running an old version of mercurial. Upgrading to the latest version (v4.0) solved this issue for me. You can check your mercurial version using:
`hg version`
I tried reinstalling mercurial using:
`sudo apt-get install mercurial`
which told me that I already had the latest version. Apparently to get the latest version you need to install it via pip:
`sudo add-apt-repository -y ppa:mercurial-ppa/releases
sudo apt-get update
sudo apt-get install -y mercurial`

**Comment by mostafaeweda** [comment]
@acenicks glad that's now fixed
