### ISSUE TITLE
Failed to activate the nuclide-debugger package

### ISSUE THREAD

**Issue by tigerZhang86** [facebook/nuclide#861]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12.1
**Thrown From**: [nuclide-debugger](https://github.com/facebook/nuclide) package, v0.0.0

### Stack Trace

Failed to activate the nuclide-debugger package

```
At subscription is not defined

ReferenceError: subscription is not defined
    at atom.packages.serviceHub.consume.provider (/Users/zhanghu/.atom/packages/nuclide/pkg/commons-atom/consumeFirstProvider.js:28:7)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:355:71)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:186:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at Object.keys.forEach.name (/Users/zhanghu/.atom/packages/nuclide/lib/main.js:309:21)
    at Array.forEach (native)
    at Object.activate (/Users/zhanghu/.atom/packages/nuclide/lib/main.js:306:25)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:342:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:827:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:343:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:18.1.0 nuclide-debugger:toggle (div.package-detail.panels-item)
     -4:13.2.0 nuclide-react-native:start-debugging (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:13.2.0 nuclide-debugger:stop-debugging (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:13.2.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:13.2.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:13.2.0 nuclide-debugger:toggle-launch-attach (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:13.1.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:13.1.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -4:13 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -3:08.8.0 core:copy (webview.native-key-bindings.nuclide-debugger-webview)
     -2:36.5.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "telemetryConsent": "no",
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v1.3.0 (active)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
js-hyperclick, v1.9.0 (active)
language-babel, v2.46.0 (active)
language-ini, v1.16.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.4.0 (active)
language-thrift, v1.0.2 (active)
markdown-preview-plus, v2.4.0 (active)
merge-conflicts, v1.4.4 (active)
nuclide, v0.179.0 (inactive)
nuclide-format-js, v0.0.36 (inactive)
sort-lines, v0.14.0 (inactive)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jgebhardt** [comment]
@tigerZhang86 please help us resolve this issue by providing all of the information requested in the issue template.

**Comment by tigerZhang86** [comment]
@jgebhardt  i have updated the issue.

**Comment by pierr** [comment]
Same problems 

## Stacktrace
```
Failed to start debugger process: name: TypeError, message: Cannot read property 'Subject' of undefined, stack: TypeError: Cannot read property 'Subject' of undefined
  at new NodeDebuggerHost (/Users/pierrebesson/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/lib/NodeDebuggerHost.js:58:51)
  at new NodeDebuggerService (/Users/pierrebesson/.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/lib/NodeDebuggerService.js:129:26)
  at NodeAttachProcessInfo._getRpcService (/Users/pierrebesson/.atom/packages/nuclide/pkg/nuclide-debugger-node/lib/NodeAttachProcessInfo.js:66:12)
  at /Users/pierrebesson/.atom/packages/nuclide/pkg/nuclide-debugger-node/lib/NodeAttachProcessInfo.js:50:32
```

## Packages 
```
Community Packages (16) /Users/pierrebesson/.atom/packages
├── autocomplete-emojis@2.5.0
├── docblockr@0.8.7
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.48.5
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@1.11.18
├── linter-js-standard@3.6.0
├── merge-conflicts@1.4.4
├── nuclide@0.184.0
├── nuclide-format-js@0.0.36
├── sort-lines@0.14.0
└── tool-bar@1.0.1

```

**Comment by danmademe** [comment]
I found the issue it's in NodeDebuggerHost.js , looks like its a Babel issue
https://github.com/facebook/nuclide/blob/master/pkg/nuclide-debugger-node-rpc/lib/NodeDebuggerHost.js

Inside you have the Constructor

```js
let NodeDebuggerHost = exports.NodeDebuggerHost = class NodeDebuggerHost {

  constructor() {
    this._subscriptions = new (_UniversalDisposable || _load_UniversalDisposable()).default();
    this._nodeSocketServer = new (_WebSocketServer || _load_WebSocketServer()).WebSocketServer();
    this._subscriptions.add(this._nodeSocketServer);
    this._close$ = new _rxjsBundlesRxMinJs.default.Subject();
    this._close$.first().subscribe(() => {
      this.dispose();
    });
  }
```

Line 58 is `this._close$ = new _rxjsBundlesRxMinJs.default.Subject();` all you need to do is remove the .default.

**Comment by tsenterd** [comment]
same problem here - anyone know of a solution?

**Comment by jgebhardt** [comment]
@pierr @danmademe @tsenterd what versions of Atom & Nuclide were you on while seeing this error?

**Comment by tsenterd** [comment]
@jgebhardt I am on atom 1.12.6 and nuclide 0.184.0

**Comment by danmademe** [comment]
I'm on the latest for both. Two different machines same problem. I go to the transpiled code and remove the default and it works perfectly. So yeah. There you go

**Comment by tsenterd** [comment]
@danmademe Can you paste the exact code? I tried doing what you suggested to no avail :(

**Comment by tsenterd** [comment]
Trace for reference:

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.11.6
**Thrown From**: [nuclide-debugger](https://github.com/facebook/nuclide) package, v0.0.0


### Stack Trace

Failed to activate the nuclide-debugger package

```
At subscription is not defined

ReferenceError: subscription is not defined
  at atom.packages.serviceHub.consume.provider (/Users/David/.atom/packages/nuclide/pkg/commons-atom/consumeFirstProvider.js:28:7)
  at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
  at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:30:20)
  at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:356:71)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:187:16)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
  at Object.keys.forEach.name (/Users/David/.atom/packages/nuclide/lib/main.js:283:21)
  at Array.forEach (native)
  at Object.activate (/Users/David/.atom/packages/nuclide/lib/main.js:280:25)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:350:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:635:20
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:826:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:171:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:358:27)
  at HTMLButtonElement.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -7:07.8.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:07.8.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:07.8.0 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:07.8.0 nuclide-console:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:07.8.0 nuclide-debugger:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -6:47 nuclide-debugger:hide (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -5:40.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:39 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -1:41.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:35.6.0 core:undo (atom-text-editor.editor.is-focused)
     -1:14.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:14.5.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:12.9.0 core:save (atom-text-editor.editor.is-focused)
 12x -0:52.1.0 core:undo (atom-text-editor.editor.is-focused)
     -0:41.5.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:06.9.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "telemetryConsent": "no",
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
george-atom, v1.2.0 (active)
language-babel, v2.48.5 (active)
linter, v1.11.18 (active)
linter-flow, v5.5.0 (active)
nuclide, v0.184.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by danmademe** [comment]
@tsenterd basically turn this on Line 58 of 
`.atom/packages/nuclide/pkg/nuclide-debugger-node-rpc/lib/NodeDebuggerHost.js`


```js 
let NodeDebuggerHost = exports.NodeDebuggerHost = class NodeDebuggerHost {

  constructor() {
    this._subscriptions = new (_UniversalDisposable || _load_UniversalDisposable()).default();
    this._nodeSocketServer = new (_WebSocketServer || _load_WebSocketServer()).WebSocketServer();
    this._subscriptions.add(this._nodeSocketServer);
    this._close$ = new _rxjsBundlesRxMinJs.default.Subject();
    this._close$.first().subscribe(() => {
      this.dispose();
    });
  }
```

Into
 
```js
let NodeDebuggerHost = exports.NodeDebuggerHost = class NodeDebuggerHost {

  constructor() {
    this._subscriptions = new (_UniversalDisposable || _load_UniversalDisposable()).default();
    this._nodeSocketServer = new (_WebSocketServer || _load_WebSocketServer()).WebSocketServer();
    this._subscriptions.add(this._nodeSocketServer);
    this._close$ = new _rxjsBundlesRxMinJs.Subject();
    this._close$.first().subscribe(() => {
      this.dispose();
    });
  }
```

But really maybe you should wait till they rebuild this.. your choice man

**Comment by tsenterd** [comment]
@danmademe This seems to fix the error! thanks :)

**Comment by danmademe** [comment]
It's a very hacky solution, the better way of doing it is to fix the problem with the compiler/transpiler

**Comment by tsenterd** [comment]
It seems like the debugger is still broken for some features. For example the react native debugger console will not log console.log statements and throws some weird errors. There's already another issue open about this #899 maybe it could be related.

**Comment by danmademe** [comment]
It's probably the reason

**Comment by johnislarry** [comment]
For the `subscription is not defined` errors in this thread, I believe this may be fixed by 4cbf50cd12d6d6eaf86a92b7019beb4aee1336b4
