### ISSUE TITLE
Tree View Error

### ISSUE THREAD

**Issue by alanzanattadev** [facebook/nuclide#878]
### Issue and Steps to Reproduce
Opening atom, scrolling in the treeview

**Atom Version**: 1.12.1
**Electron Version**: 1.3.6
**System**: Ubuntu 16.10
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.181.0

### Stack Trace

Uncaught TypeError: Class extends value undefined is not a function or null

```
At /home/main/.atom/packages/nuclide/pkg/nuclide-file-tree/components/OpenFilesListComponent.js:45

TypeError: Class extends value undefined is not a function or null
  at Object.<anonymous> (/home/main/.atom/packages/nuclide/pkg/nuclide-file-tree/components/OpenFilesListComponent.js:45:119)
  at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
  at _load_OpenFilesListComponent (/home/main/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:37:36)
  at FileTreeSidebarComponent.render (/home/main/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:220:87)
  at _renderValidatedComponentWithoutOwnerOrContext (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:21550)
  at _renderValidatedComponent (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:21638)
  at _updateRenderedComponent (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:20998)
  at _performComponentUpdate (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:20799)
  at updateComponent (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:20077)
  at performUpdateIfNecessary (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:13:19582)
  at Object.performUpdateIfNecessary (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:9522)
  at s (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:17193)
  at r.perform (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at o.perform (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at o.perform (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:18210)
  at Object.P [as flushBatchedUpdates] (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:18379)
  at r.closeAll (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10699)
  at r.perform (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:16:10145)
  at Object.batchedUpdates (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:14:17100)
  at Object.i [as batchedUpdates] (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:15:16775)
  at dispatchEvent (/home/main/.atom/packages/git-checkout/node_modules/react-for-atom/node_modules/react/dist/react-with-addons.min.js:14:23665)

```

### Commands

```
     -0:47.7.0 nuclide-file-tree:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-overwatch-dark-syntax.theme-one-dark-ui)
     -0:47.7.0 nuclide-file-tree:toggle (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-overwatch-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "react",
      "neon-cursor",
      "tree-view",
      "tree-view-autoresize",
      "api-docs",
      "atom-hot-package-loader",
      "bottom-dock",
      "docker",
      "gulp-manager",
      "molecule-webpack",
      "nuclide-test-runner-jest",
      "terminal-plus"
    ],
    "excludeVcsIgnoredPaths": false,
    "packagesWithKeymapsDisabled": [
      "api-docs"
    ],
    "projectHome": "/home/main/Documents",
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "overwatch-dark-syntax"
    ]
  },
  "nuclide": {
    "hyperclick": {
      "linuxTriggerKeys": "ctrlKey,altKey"
    },
    "installRecommendedPackages": true,
    "nuclide-diagnostics-store": {},
    "nuclide-file-tree": {
      "hideIgnoredNames": false,
      "revealFileOnSwitch": true
    },
    "nuclide-flow": {
      "enableStructuredTypeHints": true
    },
    "nuclide-health": {
      "toolbarJewel": "Memory"
    },
    "nuclide-home": {
      "showHome": false
    },
    "nuclide-objc": {
      "enableAutomaticSquareBracketInsertion": true
    },
    "nuclide-python": {},
    "nuclide-remote-projects": {
      "connectionProfiles": [
        {
          "deletable": true,
          "displayTitle": "Jeemix OSX",
          "params": {
            "username": "alanzanatta",
            "server": "10.42.0.45",
            "cwd": "/Users/alanzanatta/Documents/jeemix-server",
            "sshPort": "22",
            "authMethod": "PRIVATE_KEY",
            "pathToPrivateKey": "/home/main/.ssh/id_rsa",
            "remoteServerCommand": "/Users/alanzanatta/.nvm/versions/node/v4.4.0/bin/nuclide-start-server"
          }
        },
        {
          "deletable": true,
          "displayTitle": "Test Local",
          "params": {
            "username": "main",
            "server": "localhost",
            "cwd": "/home/main/Dirt",
            "sshPort": "22",
            "authMethod": "PRIVATE_KEY",
            "pathToPrivateKey": "/home/main/.ssh/id_rsa",
            "remoteServerCommand": ""
          }
        }
      ]
    },
    "nuclide-working-sets": {
      "workingSets": [
        {
          "name": "App",
          "active": false,
          "uris": [
            "nuclide://10.42.0.45/Users/alanzanatta/Documents/jeemix-server/apps/jeemix",
            "nuclide://10.42.0.45/Users/alanzanatta/Documents/jeemix-server/commons"
          ]
        },
        {
          "name": "API",
          "active": false,
          "uris": [
            "/home/main/Documents/jeemix-server/appfirewall.dockerfile",
            "/home/main/Documents/jeemix-server/authsystem.dockerfile",
            "/home/main/Documents/jeemix-server/build_servers.sh",
            "/home/main/Documents/jeemix-server/commons/package.json",
            "/home/main/Documents/jeemix-server/commons/servers",
            "/home/main/Documents/jeemix-server/contactmanager.dockerfile",
            "/home/main/Documents/jeemix-server/identitymanager.dockerfile",
            "/home/main/Documents/jeemix-server/jeemixwebsite.dockerfile",
            "/home/main/Documents/jeemix-server/messagemanager.dockerfile",
            "/home/main/Documents/jeemix-server/microservices",
            "/home/main/Documents/jeemix-server/musicmanager.dockerfile",
            "/home/main/Documents/jeemix-server/newsmanager.dockerfile",
            "/home/main/Documents/jeemix-server/proposalmanager.dockerfile",
            "/home/main/Documents/jeemix-server/providermanager.dockerfile",
            "/home/main/Documents/jeemix-server/push_servers.sh",
            "/home/main/Documents/jeemix-server/queuebot.dockerfile",
            "/home/main/Documents/jeemix-server/rolemanager.dockerfile"
          ]
        },
        {
          "name": "Website",
          "active": false,
          "uris": [
            "/home/main/Documents/jeemix-server/Dockerfile",
            "/home/main/Documents/jeemix-server/commons",
            "/home/main/Documents/jeemix-server/jeemixwebsite.dockerfile",
            "/home/main/Documents/jeemix-server/websites/jeemixwebsite"
          ]
        },
        {
          "name": "Cloud",
          "active": false,
          "uris": [
            "/home/main/Documents/jeemix-server/cloud",
            "/home/main/Documents/jeemix-server/tests/dev"
          ]
        },
        {
          "name": "Dev Environment",
          "active": false,
          "uris": [
            "/home/main/Documents/jeemix-server/tests/dev",
            "/home/main/Documents/jeemix-server/tests/qa-local"
          ]
        },
        {
          "name": "Batch",
          "active": false,
          "uris": [
            "/home/main/Documents/jeemix-server/add_admin_role.dockerfile",
            "/home/main/Documents/jeemix-server/batch"
          ]
        },
        {
          "name": "ProposalManager",
          "active": false,
          "uris": [
            "/home/main/Documents/jeemix-server/microservices/proposalmanager",
            "/home/main/Documents/jeemix-server/proposalmanager.dockerfile"
          ]
        },
        {
          "name": "Veyo Commons Presenters",
          "active": false,
          "uris": [
            "/home/main/Documents/veyo-frontend/commons/.storybook",
            "/home/main/Documents/veyo-frontend/commons/components/presenters"
          ]
        },
        {
          "name": "Veyopflege App",
          "active": false,
          "uris": [
            "/home/main/Documents/veyo-frontend/websites/veyopflege/app"
          ]
        },
        {
          "name": "Veyopflege Landing",
          "active": false,
          "uris": [
            "/home/main/Documents/veyo-frontend/websites/veyopflege/landing"
          ]
        },
        {
          "name": "Veyocare",
          "active": false,
          "uris": [
            "/home/main/Documents/veyo-frontend/websites/veyocare"
          ]
        },
        {
          "name": "Veyo Commons",
          "active": false,
          "uris": [
            "/home/main/Documents/veyo-frontend/commons"
          ]
        },
        {
          "name": "Veyo ops",
          "active": false,
          "uris": [
            "/home/main/Documents/veyo-frontend/ops"
          ]
        },
        {
          "name": "DocumentUpload",
          "active": false,
          "uris": [
            "/home/main/Documents/veyo-frontend/commons/components/containers/ConnectedDocumentUploadForm.js",
            "/home/main/Documents/veyo-frontend/commons/components/presenters/documents",
            "/home/main/Documents/veyo-frontend/commons/components/presenters/forms/FileInputField.js",
            "/home/main/Documents/veyo-frontend/commons/components/presenters/forms/StatePart.js",
            "/home/main/Documents/veyo-frontend/commons/consts",
            "/home/main/Documents/veyo-frontend/commons/model/api/endpoints/leads",
            "/home/main/Documents/veyo-frontend/commons/redux/actions/leads",
            "/home/main/Documents/veyo-frontend/commons/redux/graphql",
            "/home/main/Documents/veyo-frontend/commons/redux/selectors",
            "/home/main/Documents/veyo-frontend/commons/types",
            "/home/main/Documents/veyo-frontend/websites/veyopflege/app/lib/pages/documentUpload",
            "/home/main/Documents/veyo-frontend/websites/veyopflege/app/tests"
          ]
        },
        {
          "name": "Caretaker Assessment",
          "active": false,
          "uris": [
            "/home/main/Documents/veyo-frontend/commons/components/containers/ConnectedCareAssessmentForm.js",
            "/home/main/Documents/veyo-frontend/commons/components/presenters/caretakerLead/CareAssessmentForm.js",
            "/home/main/Documents/veyo-frontend/commons/redux/actions/leads",
            "/home/main/Documents/veyo-frontend/commons/redux/graphql",
            "/home/main/Documents/veyo-frontend/commons/tests/OnBoardingSystemEpic/CareAssessmentFeature",
            "/home/main/Documents/veyo-frontend/commons/types",
            "/home/main/Documents/veyo-frontend/websites/veyopflege/app/lib/pages/caretakerAssessment",
            "/home/main/Documents/veyo-frontend/websites/veyopflege/app/lib/router/routes",
            "/home/main/Documents/veyo-frontend/websites/veyopflege/app/tests/e2e/PageObjects/acp.js",
            "/home/main/Documents/veyo-frontend/websites/veyopflege/app/tests/e2e/suites/admin"
          ]
        },
        {
          "name": "Veyo - Mobile Caregiver",
          "active": false,
          "uris": [
            "/home/main/Documents/veyo-frontend/commons/components",
            "/home/main/Documents/veyo-frontend/commons/consts",
            "/home/main/Documents/veyo-frontend/commons/model",
            "/home/main/Documents/veyo-frontend/commons/redux",
            "/home/main/Documents/veyo-frontend/commons/tests",
            "/home/main/Documents/veyo-frontend/commons/types",
            "/home/main/Documents/veyo-frontend/mobiles"
          ]
        }
      ]
    }
  }
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.6 (inactive)
atom-hot-package-loader, v0.5.1 (inactive)
atom-jinja2, v0.5.0 (active)
atom-material-ui, v1.3.6 (inactive)
atom-ternjs, v0.15.0 (active)
autoclose-html, v0.23.0 (active)
autocomplete-paths, v1.0.2 (active)
autohide-tree-view, v0.25.1 (active)
block-travel, v1.0.5 (active)
bottom-dock, v0.4.4 (inactive)
climate-ui, v4.5.0 (inactive)
code-peek, v1.4.14 (inactive)
color-picker, v2.2.2 (active)
docker, v0.7.0 (inactive)
duotone-dank-green-syntax, v0.0.0 (inactive)
duotone-dark-sea-syntax, v2.0.0 (inactive)
duotone-dark-syntax, v2.0.0 (inactive)
fast-import-js, v0.5.1 (active)
file-icons, v1.7.24 (active)
firewatch-hot-syntax, v1.3.0 (inactive)
genesis-ui, v0.5.0 (inactive)
git-checkout, v0.3.2 (active)
git-commit, v1.5.3 (active)
git-log, v0.4.1 (active)
git-time-machine, v1.5.3 (inactive)
glacier-dark-syntax, v0.5.0 (inactive)
glacier-dark-ui, v0.3.0 (inactive)
gulp-manager, v0.2.19 (inactive)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
js-hyperclick, v1.9.0 (active)
language-ansible, v0.1.11 (active)
language-babel, v2.48.1 (active)
language-docker, v1.1.7 (active)
language-hcl, v0.4.0 (active)
language-ini, v1.16.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.5.0 (active)
language-thrift, v1.0.2 (active)
livestyle-atom, v0.2.7 (active)
lunar-syntax, v0.1.3 (inactive)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.6 (active)
minimap-codeglance, v0.4.5 (active)
molecule-ubuntu, v0.2.0 (inactive)
molecule-webpack, v0.1.2 (inactive)
nice-index, v1.0.3 (active)
nuclide, v0.181.0 (active)
nuclide-format-js, v0.0.36 (inactive)
nuclide-test-runner-jest, v0.3.0 (inactive)
open-terminal-here, v2.1.4 (inactive)
overwatch-dark-syntax, v2.1.0 (active)
paraiso-dark, v1.3.1 (inactive)
parasol-syntax, v1.3.0 (inactive)
predawn-syntax, v1.0.2 (inactive)
predawn-ui, v1.0.2 (inactive)
pretty-json, v1.6.1 (active)
redux-devtools, v0.5.0 (inactive)
remove-whitespace, v0.2.1 (inactive)
seti-ui, v1.3.2 (inactive)
seti-ui-beta, v0.1.1 (inactive)
snytax, v0.1.2 (inactive)
sort-lines, v0.14.0 (inactive)
string-theory, v0.1.1 (inactive)
sync-settings, v0.7.2 (active)
terminal-plus, v0.14.5 (inactive)
tool-bar, v1.0.1 (active)
trendy-light-ui, v0.28.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

### Versions
* Atom: 1.12
* Nuclide: 0.181.0
* Client OS: Ubuntu 16.10

**Comment by johnislarry** [comment]
My guess here is that one of your installed non-Nuclide 3rd party atom packages is using a different version of React from the one Nuclide is using, and this is conflicting.  I'm not sure which one, but if you use atom with Nuclide as the only 3rd party package installed, then the problem shouldn't persist.  Please feel free to reopen this issue, and let us know if this isn't the case! :)
