### ISSUE TITLE
Uncaught TypeError: Class extends value undefined is not a function or null

### ISSUE THREAD

**Issue by SupremeTechnopriest** [facebook/nuclide#881]
[Enter steps to reproduce below:]

1. Open project
2. (optional) click on a file in sidebar

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.181.0

### Stack Trace

Uncaught TypeError: Class extends value undefined is not a function or null

```
At /Users/rl/.atom/packages/nuclide/pkg/nuclide-file-tree/components/OpenFilesListComponent.js:45

TypeError: Class extends value undefined is not a function or null
  at Object.<anonymous> (/Users/rl/.atom/packages/nuclide/pkg/nuclide-file-tree/components/OpenFilesListComponent.js:45:119)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at _load_OpenFilesListComponent (/Users/rl/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:37:36)
  at FileTreeSidebarComponent.render (/Users/rl/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:220:87)
  at _renderValidatedComponentWithoutOwnerOrContext (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:21550)
  at _renderValidatedComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:21638)
  at _updateRenderedComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:20998)
  at _performComponentUpdate (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:20799)
  at updateComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:20077)
  at performUpdateIfNecessary (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:19582)
  at Object.performUpdateIfNecessary (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:9522)
  at s (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:17193)
  at r.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at o.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at o.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:18210)
  at Object.P [as flushBatchedUpdates] (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:18379)
  at r.closeAll (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10699)
  at r.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10145)
  at Object.batchedUpdates (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:14:17100)
  at Object.u [as enqueueUpdate] (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:17415)
  at r (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:15480)
  at Object.enqueueSetState (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:16284)
  at FileTreeSidebarComponent.r.setState (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:13808)
  at FileTreeSidebarComponent._processExternalUpdate (/Users/rl/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:275:12)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at _animationFrameRequestId.window.requestAnimationFrame (/Users/rl/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/FileTreeStore.js:566:21)

```

### Commands

```
     -3:47.3.0 nuclide-debugger:toggle (atom-pane.pane.active)
     -3:44.8.0 nuclide-debugger:toggle-launch-attach (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-monokai-shade.theme-one-dark-ui)
  2x -3:41.6.0 nuclide-task-runner:toggle-toolbar-visibility (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-monokai-shade.theme-one-dark-ui)
  2x -3:34.5.0 nuclide-context-view:toggle (atom-pane.pane.active)
  2x -3:31.6.0 nuclide-outline-view:toggle (atom-pane.pane.active)
  2x -3:28 nuclide-diagnostics-ui:toggle-table (atom-pane.pane.active)
     -3:22.4.0 git-commit:commit (atom-pane.pane.active)
  4x -3:09.5.0 nuclide-distraction-free-mode:toggle (atom-pane.pane.active)
     -2:59.6.0 nuclide-health:toggle (atom-pane.pane.active)
  2x -2:50.2.0 nuclide-settings:toggle (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "monokai-shade"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-buck": {},
    "nuclide-code-format": {
      "formatOnSave": true
    }
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v1.2.0 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-ternjs, v0.16.1 (active)
color-picker, v2.2.3 (active)
dark-flat-ui, v1.2.4 (inactive)
docblockr, v0.8.7 (active)
docker, v0.7.0 (inactive)
file-icons, v1.7.25 (active)
filesize, v2.0.0 (active)
git-blame, v0.4.11 (inactive)
git-commit, v1.5.3 (active)
git-control, v0.8.2 (inactive)
git-log, v0.4.1 (active)
git-plus, v5.25.1 (active)
git-time-machine, v1.5.3 (inactive)
haskell-grammar, v0.4.0 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
jumpy, v3.1.3 (inactive)
language-babel, v2.48.3 (active)
language-docker, v1.1.7 (active)
language-ini, v1.16.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.5.0 (active)
language-thrift, v1.0.2 (active)
merge-conflicts, v1.4.4 (active)
monokai-shade, v0.3.5 (active)
nuclide, v0.181.0 (active)
nuclide-format-js, v0.0.36 (inactive)
pigments, v0.37.0 (active)
set-syntax, v0.3.2 (active)
sort-lines, v0.14.0 (inactive)
terminal-plus, v0.14.5 (active)
tool-bar, v1.0.1 (active)
wakatime, v6.0.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by SupremeTechnopriest** [comment]
Here is another related error

[Enter steps to reproduce below:]

1. Open project

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.181.0


### Stack Trace

Uncaught TypeError: Class extends value undefined is not a function or null

```
At /Users/rl/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:50

TypeError: Class extends value undefined is not a function or null
  at Object.<anonymous> (/Users/rl/.atom/packages/nuclide/pkg/nuclide-file-tree/components/OpenFilesListComponent.js:45:119)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at _load_OpenFilesListComponent (/Users/rl/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:37:36)
  at FileTreeSidebarComponent.render (/Users/rl/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:220:87)
  at _renderValidatedComponentWithoutOwnerOrContext (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:21550)
  at _renderValidatedComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:21638)
  at _updateRenderedComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:20998)
  at _performComponentUpdate (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:20799)
  at updateComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:20077)
  at performUpdateIfNecessary (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:19582)
  at Object.performUpdateIfNecessary (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:9522)
  at s (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:17193)
  at r.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at o.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at o.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:18210)
  at Object.P [as flushBatchedUpdates] (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:18379)
  at r.closeAll (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10699)
  at r.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10145)
  at Object.batchedUpdates (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:14:17100)
  at Object.u [as enqueueUpdate] (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:17415)
  at r (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:15480)
  at Object.enqueueSetState (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:16284)
  at FileTreeSidebarComponent.r.setState (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:13808)
  at b.default.subscribe.editor [as _next] (/Users/rl/.atom/packages/nuclide/pkg/nuclide-file-tree/components/FileTreeSidebarComponent.js:315:14)
  at b.__tryOrUnsub (/Users/rl/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:50:307)
  at b.next (/Users/rl/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:49:217)
  at b._next (/Users/rl/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:48:48)
  at b.next (/Users/rl/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:47:222)
  at c.notifyNext (/Users/rl/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:335:341)
  at d._next (/Users/rl/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:10:279)
  at d.b.next (/Users/rl/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:47:222)
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at stoppedChangingActivePaneItemCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:352:36)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "atom-ternjs",
      "tree-view"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "monokai-shade"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-buck": {},
    "nuclide-code-format": {
      "formatOnSave": true
    }
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v1.2.0 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-ternjs, v0.16.1 (inactive)
color-picker, v2.2.3 (active)
dark-flat-ui, v1.2.4 (inactive)
docblockr, v0.8.7 (active)
docker, v0.7.0 (inactive)
file-icons, v1.7.25 (active)
filesize, v2.0.0 (active)
git-blame, v0.4.11 (inactive)
git-commit, v1.5.3 (active)
git-control, v0.8.2 (inactive)
git-log, v0.4.1 (active)
git-plus, v5.25.1 (active)
git-time-machine, v1.5.3 (inactive)
haskell-grammar, v0.4.0 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
jumpy, v3.1.3 (inactive)
language-babel, v2.48.3 (active)
language-docker, v1.1.7 (active)
language-ini, v1.16.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.5.0 (active)
language-thrift, v1.0.2 (active)
merge-conflicts, v1.4.4 (active)
monokai-shade, v0.3.5 (active)
nuclide, v0.181.0 (active)
nuclide-format-js, v0.0.36 (inactive)
pigments, v0.37.0 (active)
set-syntax, v0.3.2 (active)
sort-lines, v0.14.0 (inactive)
terminal-plus, v0.14.5 (active)
tool-bar, v1.0.1 (active)
wakatime, v6.0.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by SupremeTechnopriest** [comment]
And another...
[Enter steps to reproduce below:]

1. Open project

**Atom Version**: 1.12.2
**Electron Version**: 1.3.6
**System**: Mac OS X 10.11.6
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.181.0


### Stack Trace

Uncaught TypeError: Class extends value undefined is not a function or null

```
At /Users/rl/.atom/packages/nuclide/pkg/nuclide-ui/Checkbox.js:33

TypeError: Class extends value undefined is not a function or null
  at Object.<anonymous> (/Users/rl/.atom/packages/nuclide/pkg/nuclide-ui/Checkbox.js:33:95)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at _load_Checkbox (/Users/rl/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/DiagnosticsPanel.js:21:22)
  at DiagnosticsPanel.render (/Users/rl/.atom/packages/nuclide/pkg/nuclide-diagnostics-ui/lib/DiagnosticsPanel.js:154:61)
  at _renderValidatedComponentWithoutOwnerOrContext (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:21550)
  at _renderValidatedComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:21638)
  at performInitialMount (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:17578)
  at mountComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:16637)
  at Object.mountComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:8972)
  at _updateRenderedComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:21249)
  at _performComponentUpdate (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:20799)
  at updateComponent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:20077)
  at performUpdateIfNecessary (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:13:19582)
  at Object.performUpdateIfNecessary (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:9522)
  at s (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:17193)
  at r.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at o.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10062)
  at o.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:18210)
  at Object.P [as flushBatchedUpdates] (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:18379)
  at r.closeAll (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10699)
  at r.perform (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:16:10145)
  at Object.batchedUpdates (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:14:17100)
  at Object.i [as batchedUpdates] (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:15:16775)
  at dispatchEvent (/Users/rl/.atom/packages/git-commit/node_modules/react/dist/react-with-addons.min.js:14:23665)

```

### Commands

```
     -0:59 nuclide-side-bar:toggle (button.btn.icon.enablement.icon-playback-pause)
  2x -0:47 nuclide-context-view:toggle (button.btn.icon.enablement.icon-playback-pause)
     -0:38.9.0 nuclide-console:toggle (atom-text-editor.editor.mini)
  2x -0:22.5.0 nuclide-task-runner:toggle-toolbar-visibility (atom-pane.pane.active)
     -0:00.0 nuclide-diagnostics-ui:toggle-table (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-monokai-shade.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "atom-ternjs"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "monokai-shade"
    ]
  },
  "nuclide": {
    "installRecommendedPackages": true,
    "nuclide-buck": {},
    "nuclide-code-format": {
      "formatOnSave": true
    }
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v1.2.0 (inactive)
atom-material-ui, v1.3.6 (inactive)
atom-ternjs, v0.16.1 (inactive)
color-picker, v2.2.3 (active)
dark-flat-ui, v1.2.4 (inactive)
docblockr, v0.8.7 (active)
docker, v0.7.0 (inactive)
file-icons, v1.7.25 (active)
filesize, v2.0.0 (active)
git-blame, v0.4.11 (inactive)
git-commit, v1.5.3 (active)
git-control, v0.8.2 (inactive)
git-log, v0.4.1 (active)
git-plus, v5.25.1 (active)
git-time-machine, v1.5.3 (inactive)
haskell-grammar, v0.4.0 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
jumpy, v3.1.3 (inactive)
language-babel, v2.48.3 (active)
language-docker, v1.1.7 (active)
language-ini, v1.16.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.5.0 (active)
language-thrift, v1.0.2 (active)
merge-conflicts, v1.4.4 (active)
monokai-shade, v0.3.5 (active)
nuclide, v0.181.0 (active)
nuclide-format-js, v0.0.36 (inactive)
pigments, v0.37.0 (active)
set-syntax, v0.3.2 (active)
sort-lines, v0.14.0 (inactive)
terminal-plus, v0.14.5 (active)
tool-bar, v1.0.1 (active)
wakatime, v6.0.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.1 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by SupremeTechnopriest** [comment]
Ive tried disabling all packages other than nuclide.  Same errors.

**Comment by johnislarry** [comment]
The issue is with conflicting React versions I believe.  @vjeux has this issue on his radar
