### ISSUE TITLE
Uncaught Error: Cannot find module './hyperclick-utils'

### ISSUE THREAD

**Issue by elvisblanco1993** [facebook/nuclide#896]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.13.0-beta4
**Electron Version**: 1.3.9
**System**: Ubuntu 16.10
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package, v0.183.0

### Stack Trace

Uncaught Error: Cannot find module './hyperclick-utils'

```
At /usr/share/atom-beta/resources/app.asar/src/module-cache.js:379

Error: Cannot find module './hyperclick-utils'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (/usr/share/atom-beta/resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.Module._resolveFilename (/usr/share/atom-beta/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:403:25)
  at Module.require (module.js:483:17)
  at require (/usr/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
  at _load_hyperclickUtils (/home/elvis/.atom/packages/nuclide/pkg/hyperclick/lib/HyperclickForTextEditor.js:26:29)
  at HyperclickForTextEditor._onMouseMove (/home/elvis/.atom/packages/nuclide/pkg/hyperclick/lib/HyperclickForTextEditor.js:198:57)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "nuclide": {
    "nuclide-home": {
      "showHome": false
    }
  }
}
```

### Installed Packages

```coffee
# User
nuclide, v0.183.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (active)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (active)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.46.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by nmote** [comment]
This looks like a corrupted install. Try removing and then re-installing the Nuclide package.

**Comment by elvisblanco1993** [comment]
Worked! Thanks a lot
