### ISSUE TITLE
Unexpected token while updating to 188.0 server

### ISSUE THREAD

**Issue by alexandreroche** [facebook/nuclide#925]
Hi there, when I try to connect from Atom to my server, I get an error in the server logs. What's going on?

Also, how do I prevent Nuclide from auto-updating (I always get the "server/client cert mismatch" error and am forced to  update -- which is very very annoying).

Thanks!

### Issue and Steps to Reproduce
Run the server

### Expected Behavior
The server should start up properly...

### Actual Behavior

> alexandre@ip-172-31-36-76:~/bottle-server$ cat /tmp/nuclide-alexandre-logs/server-start/nuclide-2016-12-12T19:01:20.nohup.out
> /home/alexandre/.npm_packages/lib/node_modules/nuclide/pkg/nuclide-server/lib/main.js:24
>       const { port } = args;
>             ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:387:25)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/alexandre/.npm_packages/lib/node_modules/nuclide/pkg/nuclide-server/lib/nuclide-main.js:23:1)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)

### Versions
* Atom: 1.12.7
* Nuclide: 188.0 with node v5.11.0
* Client OS: Mac 10.11.6
* Server OS (optional): Ubuntu

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by alexandreroche** [comment]
Nevermind I fixed it, had to update to node v6 LTS

**Comment by alexandreroche** [comment]
(This is why I dislike the forced updates)
