### ISSUE TITLE
Error in nuclide-file-tree

### ISSUE THREAD

**Issue by Keno** [facebook/nuclide#98]
I just tried installing nuclide and frequently, I get the following error (might have to do with the remote connection failing - will file a separate issue for that):

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [nuclide-file-tree](https://github.com/facebooknuclideapm/nuclide-file-tree) package, v0.0.21

### Stack Trace

Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

```
At /Users/kfischer/.atom/packages/nuclide-file-tree/node_modules/react-for-atom/node_modules/react/lib/invariant.js:49

Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at invariant (/Users/kfischer/.atom/packages/nuclide-file-tree/node_modules/react-for-atom/node_modules/react/lib/invariant.js:35:15)
  at findDOMNode (/Users/kfischer/.atom/packages/nuclide-file-tree/node_modules/react-for-atom/node_modules/react/lib/findDOMNode.js:60:7)
  at [object Object].ReactBrowserComponentMixin.getDOMNode (/Users/kfischer/.atom/packages/nuclide-file-tree/node_modules/react-for-atom/node_modules/react/lib/ReactBrowserComponentMixin.js:25:12)
  at [object Object].close (/Users/kfischer/.atom/packages/nuclide-remote-projects/node_modules/nuclide-ssh-dialog/lib/ConnectionDialog.js:476:39)
  at Object.onError (/Users/kfischer/.atom/packages/nuclide-remote-projects/node_modules/nuclide-ssh-dialog/lib/ConnectionDialog.js:377:16)
  at Client.<anonymous> (/Users/kfischer/.atom/packages/nuclide-remote-projects/node_modules/nuclide-remote-connection/lib/SshHandshake.js:65:30)
  at emitOne (events.js:77:13)
  at Client.emit (events.js:166:7)
  at Socket.<anonymous> (/Users/kfischer/.atom/packages/nuclide-remote-projects/node_modules/nuclide-remote-connection/node_modules/ssh2/lib/client.js:215:10)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at net.js:438:14
  at process._tickCallback (node.js:357:13)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-julia, v0.1.1
nuclide-code-format, v0.0.21
nuclide-diff-view, v0.0.21
nuclide-file-tree, v0.0.21
nuclide-file-watcher, v0.0.21
nuclide-flow, v0.0.21
nuclide-hack, v0.0.21
nuclide-hg-repository, v0.0.21
nuclide-installer, v0.0.21
nuclide-language-hack, v0.0.21
nuclide-remote-projects, v0.0.21
nuclide-tabs, v0.0.18
nuclide-type-hint, v0.0.21

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
Thanks for the detailed bug report. The stack trace might be enough for us to track this down until we are able to toggle between minified and un-minified React builds.

**Comment by ssorallen** [comment]
@jgebhardt This exception originates in the connection dialog. Can you take a look? Excerpt from above:

```
at [object Object].ReactBrowserComponentMixin.getDOMNode (/Users/kfischer/.atom/packages/nuclide-file-tree/node_modules/react-for-atom/node_modules/react/lib/ReactBrowserComponentMixin.js:25:12)
  at [object Object].close (/Users/kfischer/.atom/packages/nuclide-remote-projects/node_modules/nuclide-ssh-dialog/lib/ConnectionDialog.js:476:39)
  at Object.onError (/Users/kfischer/.atom/packages/nuclide-remote-projects/node_modules/nuclide-ssh-dialog/lib/ConnectionDialog.js:377:16)
```

**Comment by jgebhardt** [comment]
@Keno Can you point me to the separate issue for the connection dialog? Thanks.

**Comment by Keno** [comment]
It wasn't an issue with the connection dialog per se - more with the remote connection failing, I posted a few of those.

**Comment by ssorallen** [comment]
@jgebhardt this does look like an error in the ConnectionDialog's logic. It tries to unmount itself regardless of whether it is currently mounted: https://github.com/facebook/nuclide/blob/master/pkg/nuclide/ssh-dialog/lib/ConnectionDialog.js#L444

This looks like it could happen if the user closes the dialog and then the SshHandshake resolves after that and tries to close the modal again.

`close` could guard against this:

```javascript
  close() {
    ...

    var domNode = React.findDOMNode(this);
    if (domNode) {
      React.unmountComponentAtNode(domNode.parentNode);
    }
  },
```

**Comment by MerlinYu** [comment]
I don't know how to deal with this problem now.

**Comment by ssorallen** [comment]
@MerlinYu Are you having a similar issue? I'm going to lock this issue since it's quite old. Please open a new one, and we will take a look.
