### ISSUE TITLE
Remote sever does not start

### ISSUE THREAD

**Issue by Keno** [facebook/nuclide#99]
I get the following error when trying to use the remote server:
```
kfischer@julia:~$ nuclide-start-server
Cleaning up old files...
Starting Nuclide server...
Nuclide server failed to respond to version check on port 9090.
The log file can be found at ~/nuclide.nohup.out.
kfischer@julia:~$ cat ~/nuclide.nohup.out

/home/kfischer/.npm_packages/lib/node_modules/nuclide-server/lib/main.js:3
var main = _asyncToGenerator(function* (args) {
                                     ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.loadFile [as .js] (/home/kfischer/.npm_packages/lib/node_modules/nuclide-server/node_modules/nuclide-node-transpiler/lib/transpile.js:33:17)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/kfischer/.npm_packages/lib/node_modules/nuclide-server/lib/nuclide-main.js:17:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by ssorallen** [comment]
This transpilation error looks similar to #14. Can you see which version of Babel you are using via `cat pkg/nuclide/node-transpiler/node_modules/babel-core/package.json`?

**Comment by Keno** [comment]
```
kfischer@julia:~/.npm_packages$ cat ~/.npm_packages/lib/node_modules/nuclide-server/node_modules/nuclide-node-transpiler/node_modules/babel-core/package.json
{
  "name": "babel-core",
  "description": "A compiler for writing next generation JavaScript",
  "version": "5.5.4",
  "author": {
    "name": "Sebastian McKenzie",
    "email": "sebmck@gmail.com"
  },
  "homepage": "https://babeljs.io/",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/babel/babel.git"
  },
  "main": "lib/babel/api/node.js",
  "browser": {
    "./lib/babel/api/register/node.js": "./lib/babel/api/register/browser.js"
  },
  "keywords": [
    "harmony",
    "classes",
    "modules",
    "let",
    "const",
    "var",
    "es6",
    "transpile",
    "transpiler",
    "6to5",
    "babel"
  ],
  "scripts": {
    "bench": "make bench",
    "test": "make test"
  },
  "dependencies": {
    "acorn-jsx": "^1.0.0",
    "ast-types": "~0.7.0",
    "bluebird": "^2.9.25",
    "chalk": "^1.0.0",
    "convert-source-map": "^1.1.0",
    "core-js": "^0.9.0",
    "debug": "^2.1.1",
    "detect-indent": "^3.0.0",
    "esquery": "^0.4.0",
    "estraverse": "^4.0.0",
    "esutils": "^2.0.0",
    "fs-readdir-recursive": "^0.1.0",
    "globals": "^6.4.0",
    "home-or-tmp": "^1.0.0",
    "is-integer": "^1.0.4",
    "js-tokens": "1.0.0",
    "leven": "^1.0.1",
    "line-numbers": "0.2.0",
    "lodash": "^3.6.0",
    "minimatch": "^2.0.3",
    "output-file-sync": "^1.1.0",
    "path-is-absolute": "^1.0.0",
    "private": "^0.1.6",
    "regenerator": "0.8.28",
    "regexpu": "^1.1.2",
    "repeating": "^1.1.2",
    "resolve": "^1.1.6",
    "shebang-regex": "^1.0.0",
    "slash": "^1.0.0",
    "source-map": "^0.4.0",
    "source-map-support": "^0.2.10",
    "strip-json-comments": "^1.0.2",
    "to-fast-properties": "^1.0.0",
    "trim-right": "^1.0.0"
  },
  "devDependencies": {
    "babel": "5.3.1",
    "browserify": "^9.0.8",
    "chai": "^2.2.0",
    "eslint": "^0.21.2",
    "babel-eslint": "^3.1.9",
    "esvalid": "^1.1.0",
    "istanbul": "^0.3.5",
    "matcha": "^0.6.0",
    "mocha": "2.2.0",
    "rimraf": "^2.3.2",
    "uglify-js": "^2.4.16"
  },
  "gitHead": "d69b0973e1b600977665c55cd1bd6b5da086d495",
  "bugs": {
    "url": "https://github.com/babel/babel/issues"
  },
  "_id": "babel-core@5.5.4",
  "_shasum": "582277ef91cff21a7dd626beb68a0f92a59a3a87",
  "_from": "babel-core@5.5.4",
  "_npmVersion": "2.9.0",
  "_nodeVersion": "2.0.0",
  "_npmUser": {
    "name": "sebmck",
    "email": "sebmck@gmail.com"
  },
  "maintainers": [
    {
      "name": "sebmck",
      "email": "sebmck@gmail.com"
    }
  ],
  "dist": {
    "shasum": "582277ef91cff21a7dd626beb68a0f92a59a3a87",
    "tarball": "http://registry.npmjs.org/babel-core/-/babel-core-5.5.4.tgz"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/babel-core/-/babel-core-5.5.4.tgz",
  "readme": "ERROR: No README data found!"
}
```

**Comment by sophaskins** [comment]
I am seeing the same output as @Keno, with Babel 5.5.4, according to `~/.npm_packages/lib/node_modules/nuclide-server/node_modules/nuclide-node-transpiler/node_modules/babel-core/package.json`

**Comment by nickpanaiotov** [comment]
Same here, the worse is that noting log in nuclide.nohup.out

**Comment by kyleferguson** [comment]
I was able to resolve this by upgrading my version of node. Was on version `0.10` instead of `0.12`.

(for ubuntu 14.04)

```
$ curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
$ sudo apt-get install -y nodejs
```

**Comment by Keno** [comment]
I can confirm that upgrading to 0.12 does fix this error. May I recommend that a proper error message be given on 0.10?

**Comment by sophaskins** [comment]
Upgrading to 0.12 fixed it for me too - I think I thought that the docs said that 0.10 was OK? but upon checking them that seems to not be the case http://nuclide.io/docs/remote/

**Comment by ssorallen** [comment]
Thanks for the confirming Node v0.12.x solved your issue.

@Keno, I agree the error message could easily be better. I am going to close and track the error message improvement in #111.
